### ISSUE TITLE
mariadb설치 링크 관련

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#10]
설명 하신 링크는 로그인을 해야 하는 링크네요. (엔터프라이즈는 상용아닌가요?)

로그인 안해도 되는 링크 입니다.

리눅스 버전별 저장소 자동 생성 페이지
[Setting up MariaDB Repositories](https://downloads.mariadb.org/mariadb/repositories/)

**Comment by doortts** [comment]
@pokev25 님 이야기주신 내용이 맞는 것 같습니다. 
가이드도 더 확실하고 분류별로 볼 수 있어서 좋네요.
알려주신 링크로 수정해 놓아야 할 것 같습니다.

혹시 여유되신다면 pull request 보내주시면 어떠세요? ^^)
(contributor로!!!)

그리고 web download 라면 아래 링크도 있네요.
https://downloads.mariadb.org/mariadb/10.1.11/

**Comment by doortts** [comment]
@pokev25 고맙습니다.  보내주신 pull request는 #12 로 랜딩되었습니다.
