### ISSUE TITLE
Yona 1.0.4에서 1.1로 업그레이드 방법은 어떻게 해야하나요?

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#100]
현재 Yona 1.0.4에서 잘 쓰고 있습니다.
1.1로 업데이트를 하려고 하는데, 어떻게 해야하는지 궁금합니다.

전체를 백업했다가 재설치하고 다시 복원을 하는 형태인가요?
단순 파일만 교체를 해도 될지...
가급적이면 기존 프로젝트들에 영향을 주지 않고 업그레이드를 했으면 좋겠습니다.
(자동업데이트는 아닌 것 같더라구요~~)

**Comment by doortts** [comment]
@minishanell 
현재 사용하시는 버전이 MariaDB를 사용하시는 거라면 
[release](https://github.com/yona-projects/yona/releases/latest)에서 bin 파일을 새로 다운로드 받아서 압축을 푸시고 기존 폴더에서 repo, download, conf 세개의 폴더를 복사해 오시면 됩니다.

업그레이드 방법을 좀 더 단순화시키거나 설명을 잘 적어 놓겠습니다.
Docker 쓰시는 분들은 편하게 하시는것 같은데 제가 도커를 잘 몰라서.. ;;;

**Comment by minishanell** [comment]
감사합니다. ^^ 업데이트 완료했습니다.
혹시나... 저처럼 사용하시다 업데이트 힘드실까.. 제가 했던 로그를 올려봅니다.

//요나 정지 및 기존 요나 폴더명 변경
sudo killall java                         
sudo mv yona yona_104          

//요나 1.1.0 받아오고, 압축 해제 후, 폴더명을 yona로 변경
wget https://github.com/yona-projects/yona/releases/download/v1.1.0/yona-v1.1.0-bin.zip 
unzip yona-v1.1.0-bin.zip 
mv yona-1.1.0 yona 

//만일을 위한 기존 요나 압축 백업 실시(이후 이상없으면 삭제해도 무방)
cd yona_104
tar -cvzf yona104.tgz ./* 

//기존 요나 데이터 복사 실시
sudo mv ./conf ../yona/
sudo mv ./uploads ../yona/
sudo mv ./logs ../yona/

//요나 1.1.0 실행
cd ../yona/bin
sudo ./yona&

//이상 유무 확인 후 기존 요나 삭제하면 됩니다.

**Comment by doortts** [comment]
@minishanell 엇! 근데 repo 폴더가 빠진것 같은데요?

**Comment by minishanell** [comment]
앗~~ 그러네요 ^^ㅋ (입력한걸 복사해놨다가 로그로 남기는 거라... 큰일날 뻔 했네요..)
복사하실때 sudo mv ./repo ../yona/ 도 해주시면 됩니닷~~~
