### ISSUE TITLE
Application.context 설정이 적용되지 않는 링크가 존재합니다.

### ISSUE THREAD

**Issue by fracktal** [yona-projects/yona#102]
안녕하세요.

현재 application.conf 파일의 application.context 를 설정하여, 하위 경로를  yona root로 사용 중입니다.
 
이 경우, 프로젝트 페이지의 첫 페이지에서 Recent History탭의 commit 항목 링크가 Application.context가 
적용되지 않아서 링크가 깨지는 문제가 있습니다.

Yona 버전 : Yona v 1.1.0 (with mongodb)
OS : Ubuntu 16.04.1 LTS

**Comment by sjstyle** [comment]
자세히 확인하지는 못했지만, https://github.com/yona-projects/yona/blob/next/app/models/History.java#L138 에서 봤을때는 commit 항목 이외에 이슈, 게시판, 코드 주고받기 모두 발생할 것으로 보입니다. 

저기에 setUrl 하는 곳 맨 앞에 `/` 대신에 `Configuration.root().getString("application.context")` 을 붙이면 해결이 가능할 것 같긴 한데 조금 더 확인해봐야할 것 같네요.

**Comment by doortts** [comment]
@sjstyle Pull Request !!

**Comment by sjstyle** [comment]
@doortts 
집에서 쓰는 5년된 울트라북으로는 도저히 yona를 로드할 자신이 없어서 회사에서 시간이 남는대로 작업하겠습니다. 😱

**Comment by doortts** [comment]
@sjstyle 그럼 내가 작업할게요~
