### ISSUE TITLE
외부망 연결시 게스트 멤버 접근권한 관련. 

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#105]
공개 프로젝트도 로그인한 멤버만 볼 수 있으면 좋겠습니다.
멤버 가입시 승인절차 같은 것이 가능한가요?? 

내부망에서 사용할 때는 문제가 없었는데
외부망 연결 시 걱정이 되네요.
공개 프로젝트도 회사 내부 공유는 문제 될 것이 업지만
외부에 공개되는 것은...

Yona 잘 사용하고 있습니다.
감사 합니다.

**Comment by doortts** [comment]
application.conf 파일내에

application.allowsAnonymousAccess=false
signup.require.confirm = true

를 넣어주시면 로그인 하지 않으면 public 프로젝트도 보이지 않게 되고, 가입후 사이트 관리자의 승인이 있어야 이용할 수 있게 됩니다.

**Comment by rtboss** [comment]
@doortts 잘 동작 합니다. 
이제 맘 편히 어디에서나 사용할 수 있을 것 같습니다.
감사합니다.

**Comment by doortts** [comment]
추가로 설정파일 및 설명을 조금 변경했습니다. 6f7b0ca9

이슈는 닫습니다.
