### ISSUE TITLE
jandi 와 연동법 문의

### ISSUE THREAD

**Issue by jisoon** [yona-projects/yona#107]
si 하면서 이곳 저곳에 요나를 전파 하고 있는 개발자 입니다. 한고객이 잔디와 요나를 연동 할수는 없냐고 문의를 하셨는데 제가 실력이 미천해서 webhook 설정을 못하고 있습니다.

요나 이슈와 잔디 채널간 이슈 연동 방법은 아시는분의 도움이 절실 합니다.

읽어 주셔서 감사 합니다.

**Comment by doortts** [comment]
안녕하세요?

혹시 원하시는 연동 사용 케이스를 알 수 있을까요?

예를들면 이슈가 등록되면 잔디 메신저로 노티가 온다던가 그런걸 원하시는 걸까요?

**Comment by jisoon** [comment]
@doortts

네 맞습니다.

**Comment by doortts** [comment]
@jisoon 좀더 구체적인 워크플로우(work flow)에 대해서 알 수 있을까요? 있으면 좋은것 말고 없어서 불편한 상황 위주면 더 좋을 것 같구요.

**Comment by jisoon** [comment]
@doortts 고객(?) 이 원하는 점은 나에게 이슈가 할당 되면 잔디로 노티를 받고 싶어 합니다. 그리고 댓글이나 이슈가 클로즈 될때 이슈 알림을 받아 보고 싶어 합니다.

1. 김pm 이 이슈를 생성
2. 담당자를 홍길동으로 지정함
3. 홍길동은 잔디 1:1(private) 대화에 해당 이슈를 노티 받음
4. 홍길동은 이슈를 수정 하고 "검수 부탁합니다" 댓글을 추가함
5. 김pm 1:1 대화에 댓글 정보를 노티 받음
6. 김pm 은 해당 이슈를 검수 하고 close 함
7. 홍길동은 1:1 대화에 close noti 를 받음

이런 워크플로워가 이루어 진다면 이슈 트랙킹이 정말 잘될것 같다고 합니다.

**Comment by jisoon** [comment]
@doortts 작성하다보니 잔디와 요나 id가 일치 해야 될것 같네요.. 쩝...

**Comment by hongwonjun** [comment]
Private 하게 노티를 받는 것은 어려울 수 있지만,
Public 한 내용은 연동이 가능합니다.
 
Jandi 의 Webhook 관련 링크를 공유해주시면 일단 연결은 검토해보도록 하겠습니다.
