### ISSUE TITLE
yona 첨부파일 용량을 100메가 정도로 증설하고 싶은데 가능한가요?

### ISSUE THREAD

**Issue by jacobjune** [yona-projects/yona#108]
yona 첨부파일 용량을 100메가 정도로 증설하고 싶은데 가능한가요?

지금은 10메가도 안되네요;;?

방법이 없을까요 가이드 주시면 감사하겠습니다 ㅠㅠ

**Comment by doortts** [comment]
@jacobjune 해결하셨어요?

**Comment by jacobjune** [comment]
아니요 해결이 안되네요..도와 주실 수 있으신가요;;??

**Comment by doortts** [comment]
@jacobjune 글 첨부파일 기본이 최대치가 2G 일텐데 이상하네요. 몇 메가 정도 올라가나요?
