### ISSUE TITLE
1.0.0 버전에서 1.2.0 버전으로 업데이트

### ISSUE THREAD

**Issue by h0ngz** [yona-projects/yona#109]
기존 conf, repo, uploads 폴더 세개를 1.2.0 버전으로 옮기면 되는 문제인줄알았는데
알고보니 1.2.0은 폴더구조 자체가 다르던데

어떻게 업데이트해야하나요? 그냥 새로 설치해야하나요

**Comment by doortts** [comment]
안녕하세요? 현재 사용하시는 버전은 어떻게 되세요?

**Comment by h0ngz** [comment]
1.0.0 버전이요

**Comment by doortts** [comment]
@h0ngz 폴더구조 자체가 많이 다르진 않은데요 폴더가 어떻게 보이시는지 스크린샷 가능할까요?  그리고  https://github.com/yona-projects/yona/wiki/Yona-%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%93%9C 도 함께 봐주세요.

**Comment by h0ngz** [comment]
@doortts 
1. 1.0.0 버전 
![image](https://cloud.githubusercontent.com/assets/5969709/21449411/58fa1b96-c930-11e6-8b0f-011805b5d714.png)

2. 1.2.0 버전
![image](https://cloud.githubusercontent.com/assets/5969709/21449413/630f3814-c930-11e6-9fb5-413343367ec9.png)

**Comment by doortts** [comment]
@h0ngz binary 버전이 아니라 소스코드 버전을 내려 받으신것 같아요. 

![image](https://cloud.githubusercontent.com/assets/520523/21449460/d03e436c-c930-11e6-8fa8-843d654d5814.png)

https://github.com/yona-projects/yona/releases/tag/v1.2.0 에서 bin 버전으로 다운받아주세요
