### ISSUE TITLE
이슈 글을 쓸 때 단일 라벨 복구가 안되는 문제

### ISSUE THREAD

**Issue by sjstyle** [yona-projects/yona#112]
이미지로 첨부합니다. 😱 

![default](https://cloud.githubusercontent.com/assets/4811664/21490322/7ebe6b26-cc36-11e6-8d1d-522703775854.gif)

**Comment by khs711** [comment]
이 문제도 있네요. 좀더 확인하고 한번에 남길걸 그랬네요.

**Comment by doortts** [comment]
이 버그는 왠지 개발자가 빨리 해결 안할 것 같습니다...;;

**Comment by doortts** [comment]
v1.4에서 해결되었습니다.
