### ISSUE TITLE
요나 업데이트 후 메인 깨짐 현상

### ISSUE THREAD

**Issue by naninyang** [yona-projects/yona#113]
![image](https://cloud.githubusercontent.com/assets/6149100/21534992/9fe1a76e-cdb2-11e6-877e-506662e84cfa.png)

[환경]
MacOS 10.12.2
Google Chrome 55.0.2883.95
Yona 1.2.0 (Binary Version)

요나 업데이트 후 첨부한 이미지처럼 메인이 깨지는 현상이 발생합니다.

**Comment by pokev25** [comment]
강제 새로 고침해도 안되나요? 

http://codeigniter-kr.org/bbs/view/tip?idx=8332

**Comment by minishanell** [comment]
Leave a comment
