### ISSUE TITLE
알림 설정에 중복 항목

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#114]
멤버 등록 요청이 중복되어 있습니다.

![noti](https://cloud.githubusercontent.com/assets/4251972/21535804/c669dd10-cdbd-11e6-8436-221162cf11d3.png)

**Comment by sjstyle** [comment]
정확히 말하자면, 위의 멤버 등록 요청은 프로젝트에 멤버 등록 요청(notification.type.member.enroll)이고, 
하단의 멤버 등록 요청은 해당 organization의 멤버 등록 요청(notification.organization.type.member.enroll)입니다. ( https://github.com/yona-projects/yona/blob/next/app/models/enumeration/EventType.java )

하지만, message 파일에 둘다 '멤버 등록 요청'으로 입력되어 있어서 오해의 여지가 있을 것 같습니다.

**Comment by pokev25** [comment]
그렇다면 명칭 구분이 필요할 것 같습니다.

**Comment by doortts** [comment]
Fix 올렸습니다. @sjstyle 님이 알려주셔서 매우 빠르게 fix를 만들 수 있었습니다. 고맙습니다. : )
