### ISSUE TITLE
내가 단 덧글에 이메일 알림이 옵니다.

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#115]
요나 공개 프로젝트 게시물에 덧글을 달았더니 (지켜보는 프로젝트가 아닙니다.)

덧글이 달렸다고 메일이 옵니다. 

'나'는 제외 해야 하지 않을까요?

**Comment by doortts** [comment]
한 번 덧글을 남기면 그 때부터 해당 게시물을 구독(subscribe)하게 됩니다. 만약 이것이 의도하지 않은 상황이라 불편한 경우를 가정해 관련 링크 문구가 있긴 한데 좀 작죠? 

![image](https://cloud.githubusercontent.com/assets/520523/21543495/42b2014e-ce0a-11e6-9896-10c04e1ba675.png)

**Comment by pokev25** [comment]
수정을 하고싶어도 알림설정 항목에 해당 프로젝트는 존재 하지 않습니다.

**Comment by sjstyle** [comment]
지켜보기를 하지 않은 프로젝트의 경우에는 메일에서 '그만 지켜보기' 링크를 누르거나 해당 이슈/게시글의 '그만 지켜보기'를 눌러야 할 것 같습니다~

**Comment by doortts** [comment]
현재는 기준설정이 댓글을 달면 프로젝트 지켜보기를 하지 않더라도 해당 글 한정 지켜보기가 자동으로 켜집니다. 댓글을 남겼다는 뜻은 이후로 이어지는 댓글에 대해 답변이 달리거나 해당 글에 관심이 있다는 걸 기본으로 가정하고 시스템이 동작하게 되어 있습니다. 불편하면 위에 @sjstyle 님의 댓글처럼 그만지켜보기를 눌러서 중지하도록 하고 있고요. 

![image](https://cloud.githubusercontent.com/assets/520523/22745319/7cdff8ca-ee63-11e6-95c9-2bab68406d71.png)


여러가지 상황이 있고 기본동작에 대해 오랜기간 고민후에 정했음에도 모든 사람을 만족시키기는 조금 어려운 부분인 것 같습니다. 조금 불편하시더라도 이런 경우가 발생하면 글 그만지켜보기를 눌러서 처리해주세요.
