### ISSUE TITLE
로그에서 404 에러 뜨는 현상

### ISSUE THREAD

**Issue by naninyang** [yona-projects/yona#117]
콘솔로그에서

[error] application - Unexpected url call : /cache/global/img/gs.gif
[info] a.h.b.c.gif - 93.174.93.136 - - [30/Dec/2016:00:09:15 +0900] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 - - "Mozilla" 229ms

라는 에러가 보이네요. 바이두에서 이미지 파일을 끌어오게 설계되어 있는 부분이 있나요?
이 현상은 요나 업데이트하면 사라질 줄 알았는데 없어지지 않네요.
요나 실행에는 딱히 문제는 없지만 신경 쓰이네요.

**Comment by sjstyle** [comment]
소스에서는 해당 경로를 참조하는 로직이 없는데요... 어느 페이지/상황에서 발생하고 계신가요?

**Comment by doortts** [comment]
올려주신 로그에 대한 설명
---

``` 
GET        http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 - - "Mozilla
----       -------------------------------------------- ---------
Method     Rqeuest-URI                                 HTTP/Version
```
콘솔로그의 "GET /xxx~" 부분은 client가 Yona 서버로 요청한 내용입니다. 위 로그에 따르면 Mozilla 가 client 이고 Yona 서버로 요청한 URI은 http://www.baidu.com/cache/global/img/gs.gif  인 상황입니다. 
당연히 404 (Not Found)로 Yona 서버는 응답하게 되는 것이 정상입니다.

그럼 저건 어디서 누가 보낸거냐? 
---

ip: 93.174.93.136 에서 모질라 클라이언트가 요청한겁니다. 아마 뭔진 모르겠지만 

- http://www.baidu.com/cache/global/img/gs.gif 가 취약점으로 웹에 있거나
- http://www.baidu.com/cache/global/img/gs.gif 가 함정이라 로그를 본 누군가가 저걸 클릭하길 바라고 요청했거나

(참고로 전 괜히 클라이언트 ip를 남기는 상황이 될까봐 링크 클릭은 안했습니다.)

그럼 어떻게 하면 되나?
--
우선 저런 요청들은 네트워크등의 자원을 잡아먹긴 하지만 별다른 피해는 없습니다. 

사실 서버가 공용망이라 외부에서 접근가능하다면 벼라별 요청들이 다 들어옵니다. 그냥 상황자체는 받아들이셔야 합니다. 간단하게는 아파치를 이용해서 특정 아이피를 막거나 blacklist 를 관리하는 방법이 있습니다. 예를 들면 https://www.digitalocean.com/community/tutorials/how-to-protect-against-dos-and-ddos-with-mod_evasive-for-apache-on-centos-7

repo.yona.io에도 유사한 것들을 적용해 놓았습니다.

그리고 Yona 다음 버전쯤에는 유사한 기능을 넣으려고 조금씩 작업하고 있습니다.
