### ISSUE TITLE
[이슈] 입력 줄이 너무 깁니다. 명령 구문이 올바르지 않습니다

### ISSUE THREAD

**Issue by freepow** [yona-projects/yona#118]
C:\Users\Administrator\Downloads\yona-1.2.0\bin\yona.bat
입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다

아래와 같이 디렉토리 이동시켜서 하니까 실행이 잘 되네요.
C:\yona-1.2.0\bin\yona.bat

**Comment by doortts** [comment]
@freepow 팁 고맙습니다. 혹시 여유가 되신다면 HOME을 지정해서 실행하는 것이 경로를 바꾸지 않고도 해당 문제가 해결되는지 확인해 주실 수 있을까요?

https://github.com/yona-projects/yona#windows의-경우

**Comment by freepow** [comment]
기존 디렉토리로 변경해서 말씀하신 대로 YONA_HOME 지정해서 run.bat 만들어 실행해봐도 안되네요.


2017-01-05 22:32 GMT+09:00 Suwon Chae <notifications@github.com>:

**Comment by enchantor** [comment]
동일한 증상을 겪었는데, 제 경우 요나의 위치가 D:\xampp\htdocs\yona 이었습니다.

**Comment by doortts** [comment]
@enchantor 아직 완벽하진 않습니다만 v1.3에서 이부분 처리중에 있습니다. 1.3이전 버전의 경우에는 https://github.com/yona-projects/yona/issues/130 을 참고해서 처리해주시고 안되시면 다시 이슈 열어주세요.
