### ISSUE TITLE
아이패드에서 메인화면이 조금 간격이 맞지 않게 나옵니다.

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#120]
한가지 궁금증이 있어 여쭤봅니다.
버그..라기엔 그렇고.... 

아이패드(사파리 브라우저입니다)에서 요나를 볼때, 가로 화면에서는 이상없이 나오지만,
세로 화면에서 메인화면(로그인하기 전)의 화면이 간격이 맞지 않게 나옵니다.
위 아래는 제대로 나오지만, 아래 화면과 같이 중간에 그림과 Yona 시작하기 화면이 간격이 맞지 않게 나오네요. 별 건 아니고.. 사용에도 이상없지만.. 맞춰둔다면 더 좋을 것 같야요 ^^

![yonaback](https://cloud.githubusercontent.com/assets/13401664/21703265/2e0e8b32-d3f4-11e6-978b-d2b2265873e6.jpg)

**Comment by minishanell** [comment]
기종별로도 차이가 있나보네요..
iPad mini 4 입니다. 
해상도는 2048 x 1536 이라고 나오네요..

**Comment by doortts** [comment]
@minishanell 저런!! 테스트를 해봐야겠군요. 그럼 아이패드를 보내주세요. 경기도 용인시 죽전1...

**Comment by doortts** [comment]
@minishanell 테스트용 아이패드 미니가 안와서 100% 자신은 없지만 간단히 처리를 해 보았습니다. repo.yona.io 에 반영해 놓았는데 한 번 테스트 해 봐 주시겠어요?

**Comment by minishanell** [comment]
요나 1.3 버전에서 정상작동합니다. ^^
감사합니다.
