### ISSUE TITLE
프로젝트 정보의 라벨을 한글로 작성하면 삭제가 되지 않습니다.

### ISSUE THREAD

**Issue by enchantor** [yona-projects/yona#122]
요나를 이것 저것 적어보다가 분류에 라벨을 "한국어", "한글", "영어"와 같이 적어보았는데,
이것 중 "한글"을 제거하려니 제거가 안되서, 다른 것도 눌러보앗는데 마찮가지로 제거가 안되었어요.
혹시나 해서 같은 프로젝트에서 라벨을 영어로 "kor" 추가했다가 삭제를 눌러보는데 이것도 제거가 안되네요.
다만, 다른 프로젝트에서 사용 중인 언어 "jsp"를 등록했다가 삭제하면 그것만 정상 삭제가 됩니다.

삭제가 안되는 것들은 전부 콘솔창에서 자바스크립트 500 에러가 나타나고 있어요.

**Comment by enchantor** [comment]
특이하게도 다른 프로젝트에서 저 프로젝트에서 사용한 한글 라벨을 사용 하는데 문제가 없습니다.
추가/제거가 아주 잘 되요.

**Comment by doortts** [comment]
@enchantor 다음 버전(v1.3예정)에서는 프로젝트 라벨 기능 자체를 제거해 버릴 예정입니다. ;;;; 효용이 높지 않으면서도 버그 유발자라서 이번 기회에 떠나 보낼려고요..;;

**Comment by haare** [comment]
이슈 라벨 = 프로젝트 라벨은 아니지요??

**Comment by sjstyle** [comment]
네 프로젝트 라벨은 현재 프로젝트 메인페이지 우측에 `프로젝트 정보` 란을 말합니다.

**Comment by minishanell** [comment]
현재 1.3 버전에서 프로젝트 정보..가 삭제되었기에 이 이슈를 닫아봅니다.
