### ISSUE TITLE
그룹 프로젝트에서 첫 마일스톤을 작성하였는데요. 프로필 변경에 사용했던 이미지가 첨부되어 나옵니다.

### ISSUE THREAD

**Issue by enchantor** [yona-projects/yona#123]
내용이 없어서 작성이 안되던데, 아무 메시지가 안뜨떠서 계속 작성시도를 하고 있기도 했는데요,
내용을 넣고 첫 마일스톤을 작성했더니,
제가 이런 저런 프로필 이미지로 사용 하려고 적용하고 변경했던 이미지 파일 6개 모두 마일스톤의 내용에 첨부되어서 나타났습니다.
두번째 마일스톤도 동일하게 프로필에 사용했던 이미지 6개가 모두 첨부되어서 나오네요.

아래는 현재 요나 설치 후 실행 해본 것들입니다.
추가 계정 생성 (해당 계정으로 진행) -> 프로필 이미지 6회 변경 -> 개인프로젝트 생성 -> 한글 라벨 -> 그룹 생성 -> 그룹 프로젝트 생성 -> 그룹 프로젝트에서 내용 없는 마일스톤 생성시도 약 2~3회 -> 내용 작성 후 마일스톤 작성 완료 -> 그룹프로젝트에서 두번째 마일스톤 작성

**Comment by enchantor** [comment]
첫번째 마일스톤 내용에서 수정을 누르고, 첨부 파일을 제거하려하니 에러가 발생하고, 마일스톤은 수정 되지 않았습니다.
그런데 두번째 마일스톤의 내용에 첨부파일이 모두 사라졌습니다..?!

**Comment by doortts** [comment]
@enchantor v1.3에서 이부분은 처리했습니다. 혹시 다시 재현되신다면 편하게 이슈를 다시 열어주세요. : )
