### ISSUE TITLE
마크다운 문서의 이미지 링크 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#124]
https://github.com/pokev25/mdtest/blob/master/readme.md

https://repo.yona.io/postimg/mdtest/code/master/readme.md

똑같은 문서를 요나와 Github에 올렸습니다.

요나에서는 이미지가 보이지 않습니다.

**Comment by sjstyle** [comment]
이미지 경로를
```
![yonatitle](/assets/yonatitle.png)
```
에서 
```
![yonatitle](./assets/yonatitle.png)
```
으로 바꾸시면 아마 해결이 될 것이라고 생각됩니다.

근본적으로는 저 앞에 / 가 붙으면 해당 프로젝트의 루트로 치환해주어야할 것 같아보이네요.

**Comment by pokev25** [comment]
네 뭔가 처리가 필요해 보입니다.

문법이 틀린건 아니니 요나쪽에서 뭔가 손대야 할 것 같습니다.
https://guides.github.com/features/mastering-markdown/

```
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)
```

**Comment by sjstyle** [comment]
오늘 알게된 사실인데요. 원래는 처리를 하려고 계획했는데 장단점이 발견되어서 우선순위를 낮추려 합니다.
yona에서는 파일을 첨부하게 되면 `/files/{ID}` 형식으로 업로드하게 됩니다.
이 경우에, README.md 에서 이 `/files/{ID}`를 이미지 혹은 링크하면 링크가 걸리게 되는데요.
말씀하신 절대경로로 치환하게 되면 이 기능이 동작하지 않게 됩니다.

완벽하게 기존 기능을 유지하면서 치환하는 것은 구현이 어려워서, 어느 방법의 사용성이 더 높은지를 고려해서 반영해야 할 것 같습니다.

**Comment by doortts** [comment]
이 부분은 조금 고민이 되었던 부분이기도 한데요 어떤 글에서 링크를 /abc 식으로 링크를 걸었을때 그 의미가 yona 사이트 기준의 root 인 /abc 인지 아니면 해당 프로젝트 산출물 기준으로의 root 라고 가정하고 저장소 파일(repo.yona.io/gildong/bandit/code/readme.md 에서의 /abc가 실제로는  repo.yona.io/gildong/bandit/code/abc 인지를 구분하거나 정의해야 하기 때문입니다.

그런데 @pokev25 님의 의견도 충분히 합리적이라는 생각이 들었습니다.

**Comment by doortts** [comment]
@pokev25 님 코드를 만들어 보았는데요 repo.yona.io 에서 간단히 테스트 해 봐 주실수 있을까요?

**Comment by pokev25** [comment]
@doortts 잘 됩니다!!!
