### ISSUE TITLE
새이슈 작성시 메일이 전송되지 않습니다.

### ISSUE THREAD

**Issue by leesunghee1229** [yona-projects/yona#125]
안녕하세요.

새이슈 작성시 메일이 전송되지 않아요

관리자에서 메일 발송하면 전송은 되는데... 이슈는 등록해도 메일이 안오네요.

smtp.host = localhost
smtp.port = 25
smtp.ssl = false
smtp.user = dev
smtp.password = ""
smtp.domain = mydomain.com
smtp.mock = false

application.conf 파일은 위와 같이 수정하고 재부팅하였습니다.

무엇이 문제일까요?

**Comment by sjstyle** [comment]
관리자에서 메일이 발송되어 수신이 된다면 smtp 설정은 제대로 된 것 같습니다.

이슈 등록시에 원래 등록자에게는 알림이 오지 않는데, 다른 '지켜보기' 한 팀원 메일 주소로도 메일이 오지 않으신가요?

**Comment by leesunghee1229** [comment]
@sjstyle 
네 메일이 전혀오지 않네요 ㅠㅠ

**Comment by doortts** [comment]
@leesunghee1229 Yona가 설치되어 있는 폴더 하위 logs 폴더에 보면 mail.log 가 있습니다.
혹시 해당 부분에 오류나 기타 메시지는 없는지 확인해봐주시겠어요?

**Comment by leesunghee1229** [comment]
살펴 보니까 스팸으로 발송되고 있었네요
설정이 뭔가 잘못된건지 모르겠어요

그리고 보낸 사람이 무조건 dev 로 오네요.
smtp.user = dev  이 설정 때문인거 같긴 한데요.

작성한 사람의 이메일로 발송되지 않고 있어요.

**Comment by sjstyle** [comment]
말씀하신 부분은 smtp 서버 설정 문제입니다.
yobi 단에서 설정할 수 있는 것은 아니고, smtp 서버 설정을 고쳐야 하는데요..
smtp 서버가 어떤 것을 쓰느냐에 따라서 설정이 모두 달라서 공식 가이드를 만들기는 어려울 것 같습니다.
스팸으로 발송되지 않는 방법은 https://blog.asamaru.net/2015/12/16/how-can-i-prevent-mail-from-being-classified-as-spam/ 와 같은 스팸 방지 설정들이 있습니다. 
이 역시 메일을 수신하는 서버의 정책에 따라서 일부 위반은 스팸처리를 하지 않을수도 있고, 모든 정책을 위반하지 않아야 할 수도 있습니다.

**Comment by doortts** [comment]
만약 자체 메일 서버를 운영중이고 외부 dns에 공개적으로 등록된 서버가 아니라면 주요 메일 서비스 회사들이나 제품들에서는 spammer로 분류될 가능성이 높습니다. 사내망에서 사내망으로의 발송 경우라면 메일서비스 팀에게 제외 문의를 하셔야 할 것 같습니다. 만약 외부망으로 보내고 있다면 gmail이나 전문 메일 발송 서비스를 회사의 서비스를 이용하시는 것을 추천드립니다.

**Comment by leesunghee1229** [comment]
제 메일서버 문제인거 같으니 close 하도록 하겠습니다.
도움주셔서 감사합니다. :-)
