### ISSUE TITLE
git을 써보려는 사람입니다.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#127]
안녕하세요. 이제야 git을 이용해보려고 하고 있습니다.
내부 사정상 git server을 사내에 구축해서 써야하는데 찾아보던중 yona를 알게되었는데요

요나만 서버에 설치하면 깃서버도 함께 구성이 되는건가요??

설치가이드에는 깃설정 관련 내용은 못찾아서 문의글 남깁니다.

**Comment by doortts** [comment]
@junho103 네 git 서버는 내장되어 있습니다.

**Comment by doortts** [comment]
내용 확인하신걸로 간주하고 이슈 닫아도 되지요? : )
