### ISSUE TITLE
관리자 생성 페이지가 호출되지 않는 이슈.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#128]
안녕하세요.

OS: windows server 2008 r2 
JAVA: jre 1.8
MarialDB:  10.1
====================

위 환경에서 yona를 설치 진행하였습니다. 
그런데 맨처음 접속하더라도 관리자 생성페이지가 호출되지 않는데 어떤 부분을 참고해보면 좋을까요?

**Comment by sjstyle** [comment]
서버 로그에는 어떤 내용이 나오고 있나요?

**Comment by junho103** [comment]
yona 실행 후 http://127.0.0.1:9000/ 접속하였을때 올라온 로그입니다.
--------------------------
**application.log**

2017-01-23 17:15:44,331 - [INFO] - from play in main 
database [default] connected at jdbc:mysql://localhost:3306/yona

2017-01-23 17:15:46,328 - [INFO] - from play in main 
Starting application default Akka system.

2017-01-23 17:15:46,375 - [INFO] - from play in main 
Application started (Prod)

2017-01-23 17:15:46,390 - [INFO] - from application in application-akka.actor.default-dispatcher-3 
User uploaded temporary files are cleaned up...(0 of 0)

2017-01-23 17:15:46,484 - [INFO] - from play in main 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

------------------------------
**root.log**
2017-01-23 17:15:44,331 - [INFO] - from play in main 
database [default] connected at jdbc:mysql://localhost:3306/yona

2017-01-23 17:15:46,328 - [INFO] - from play in main 
Starting application default Akka system.

2017-01-23 17:15:46,375 - [INFO] - from play in main 
Application started (Prod)

2017-01-23 17:15:46,390 - [INFO] - from application in application-akka.actor.default-dispatcher-3 
User uploaded temporary files are cleaned up...(0 of 0)

2017-01-23 17:15:46,484 - [INFO] - from play in main 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2017-01-23 17:16:01,054 - [INFO] - from access./ in play-akka.actor.default-dispatcher-14 
127.0.0.1 - - [23/Jan/2017:17:16:01 +0900] "GET / HTTP/1.1" 200 - - "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" 265ms

2017-01-23 17:16:01,335 - [INFO] - from access./messages.js in play-akka.actor.default-dispatcher-10 
127.0.0.1 - - [23/Jan/2017:17:16:01 +0900] "GET /messages.js HTTP/1.1" 200 - "http://127.0.0.1:9000/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" 31ms

**Comment by junho103** [comment]
가장 먼저 접속했을때 관리자 생성 페이지가 나와야 한다고 본거 같아 더이상 진행하지 않고
왜그런지 이유를 찾아보고 있습니다.

조치해본 사항
[1] 디비 설치 및 생성 후 Admin 이라는 유저를 생성했다가 다시 삭제했습니다.

**Comment by sjstyle** [comment]
음 관리자 생성 페이지는 db를 만든 후에 단 한번만 나오는 페이지인걸로 알고 있는데요..
1번 조치에서 admin 유저는 어떻게 생성하신건가요?

**Comment by doortts** [comment]
@junho103 만약 admin 계정 설정과 비밀번호를 다시 리셋하고 싶으시면 application.conf 설정파일을 여신 다음 application.secret을 아래처럼 수정해 주신다음 다시 띄우시면 됩니다.

```
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
application.secret="VA2v:_I=h9>?FYOH:@ZhW]01P<mWZAKlQ>kk>Bo`mdCiA>pDw64FcBuZdDh<47Ew"
```

만약 Admin 계정을 새로 등록하실때는 우선 email은 다른 이메일로 지정하시는걸 권장드립니다.

**Comment by junho103** [comment]
관련 문제로 아래 순서로 다시 진행하였으나, 문제는 동일 합니다.

[1] MariaDB를 삭제 후 다시 설치 
[2] wiki 가이드 기준으로, 사용자 및 DB 생성
https://github.com/yona-projects/yona/wiki/MariaDB-%EC%84%A4%EC%B9%98-(Windows)


초기
마리아 디비 port 3307
yona 계정의 비밀번호를 yona123! 

이렇게 설정하고 진행하였을때 (application.conf 파일 내용 수정함.) 아래와 같이 접속이 불가하다는 오류가 발생하였습니다.
--------------------
2017-01-24 15:39:10,305 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in main 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES).Message:Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)

그래서 마리아디비 포트를 다시 3306으로 돌리고, yona 계정이 비밀번호 역시 yonadan 으로 설정 하니 
db에 접속이 되고 yona가 정상 구동 됩니다.

-------------------------
하지만...... 여전히 초기 관리자 생성페이지는 호출되지 않습니다. ㅠㅠ;

또한 알려주신 application.secret 의 내용은 위와 동일하게 되어있습니다.

**Comment by junho103** [comment]
@sjstyle db 상에서 admin 이라는 유저를 생성했던 부분인데 저부분은 관련이 없던것 같습니다....

**Comment by junho103** [comment]
application.conf 파일을 읽지 못하는게 아닌가 싶어 
application.conf 의 MariaDB  접속정보를 이상하게 수정 후 저장한뒤 
yona를 다시 종료 및 시작하여도 정상 동작합니다...... 

어떤 부분을 좀더 보면 좋을까요?

**Comment by junho103** [comment]
bin\start_yona.bat 파일을 만들어 실행 하고 있습니다. 

SET YONA_HOME=F:\yona\yona-1.2.0
SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml
SET JAVA_OPTS=-Xmx2048m -Xms2048m
SET JAVA_OPTS=-DapplyEvolutions.default=true
bin\yona.bat

**Comment by junho103** [comment]
bin\start_yona.bat 파일을 만들어 실행 하던 부분을

cmd 창에서 직접 입려하고 yona를 실행하니 설치폴더\conf\application.conf 파일을 제대로 읽었습니다.
더불어 관리자생성 페이지도 호출 되었습니다.

start bat 파일을 별도로 하였을때 JAVA_OPTS가 안먹힌 이유에 대해서는 찾아보아야 할것 같네요.

조언 주신분들 감사드립니다.

**Comment by junho103** [comment]
제가 많이 무지했군요...

bin\start_yona.bat 파일의 내용을 아래와 같이 수정 후 모두 정상동작 되는 것을 확인하였습니다.

--------------------
SET YONA_HOME=F:\yona\yona-1.2.0
SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml -Xmx2048m -Xms2048m -DapplyEvolutions.default=true
bin\yona.bat
