### ISSUE TITLE
메인페이지 깨짐

### ISSUE THREAD

**Issue by sjstyle** [yona-projects/yona#129]
아마 최근 배포가 원인으로 추정되는 메인 페이지 깨짐 현상이 있습니다.

Chrome 55.0.2883.87 / Windows 10 입니다.

![image](https://cloud.githubusercontent.com/assets/4811664/22207965/88979dfe-e1c4-11e6-9c41-3e7db76a7ac0.png)

**Comment by doortts** [comment]
4열이 나올 수 있는 해상도라니!!
해상도가 얼마인거죠?

**Comment by sjstyle** [comment]
1600 x 900 입니다......... (무려 12년 8월에 산 노트북입죠)

**Comment by doortts** [comment]
참고로 깨진거 아니에요.. (정신승리!)

**Comment by doortts** [comment]
내 노트북은 얼만가 봤더니 1440*900 이네요. 새 레이아웃에서 다시 확인 한번 부탁할게요! : )

**Comment by sjstyle** [comment]
강제새로고침후에 해결되었습니다~
