### ISSUE TITLE
설치시 오류 [1]입력 줄이 너무 깁니다.  [2]파일, YONA_config.txt을(를) 찾을 수 없 습니다.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#130]
경로를 다음과 같이 잡았을때 아래와 같은 오류가 발생합니다.

-------------------------------------
F:\Program Files\yona\yona-1.2.0\bin>yona.bat
파일 F:\Program Files\yona\yona-1.2.0\bin\\\..\YONA_config.txt을(를) 찾을 수 없
습니다.
입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다.
F:\Program Files\yona\yona-1.2.0\bin>

경로를 짧게 옮기면 되었으나, 경로를 옮길수 없는 상황입니다.

**Comment by junho103** [comment]
제어판→모든 제어판 항목→시스템→고급 시스템 설정 시스템변수 추가.

YONA_HOME 추가로 해결이 되는듯 하였으나 착각이였네요...

조금더 보고 다시 질문또는 해결된 방법 공유하겠습니다. ;;

**Comment by sjstyle** [comment]
중간에 java를 실행하는 부분이 너무 길어서 문제가 발생하는데.. 회사여서 도와드리기가 어렵네요 ㅠㅠ
명령줄을 한번 나눠보시면 도움이 될 것 같습니다;;;;;;;;;;

**Comment by doortts** [comment]
bin 폴더 하위의 yona.bat 파일을 여시고 150번째 줄이 굉장히 길텐데 아래처럼 줄여서한 번 실행해봐주시겠어요?

```
set "APP_CLASSPATH=%APP_LIB_DIR%\*.jar"
```

ps. 참고로 제가 윈도우 환경이 여의치 않아서 테스트는 못해봤습니다.. 죄송합니다..;;; 우선 이렇게 테스트 한 번 부탁드릴게요.

**Comment by doortts** [comment]
아 그리고 위에 명령어 대로라면

F:\Program Files\yona\yona-1.2.0 위치에서 

```
bin\yona.bat
```
으로 실행하셔야 할거에요.

https://github.com/yona-projects/yona#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0

**Comment by junho103** [comment]
명령줄을 나눠 보라고 얘기해주셔서...

set "APP_CLASSPATH=%APP_LIB_DIR%\yona.yona-1.2.0.j~~~~ 
부분을 


set "APP_CLASSPATH01=%APP_LIB_DIR%
set "APP_CLASSPATH02=%APP_LIB_DIR%
set "APP_CLASSPATH03=%APP_LIB_DIR%
...

식으로 나눠 진행해 보았는데 제가 잘못 접근 한거 같네요....

일단 다음스텝으로 넘어가질 못해서 yona 설치 경로 문제는 우선 설치경로를 program file 폴더 밖으로 빼서 진행하고 차후에 다시 봐야 할것 같습니다.

답변 감사드립니다.

**Comment by doortts** [comment]
@junho103 150번째줄이 굉장히 길텐데 다 지우고 그걸 저 한줄로 대체해 봐달라는 이야기 였습니다. 나누실 필요 없이요..

## 150번째줄 Before

set "APP_CLASSPATH=%APP_LIB_DIR%\yona.yona-1.2.0.jar;%APP_LIB_DIR%\js-engine.jar;%APP_LIB_DIR%\org.scala-lang.scala-library-2.10.4.jar;%APP_LIB_DIR%\com.typesafe.play.twirl-api_2.10-1.0.3.jar;%APP_LIB_DIR%\org.apache.commons.commons-lang3-3.1.jar;%APP_LIB_DIR%\com.typesafe.play.play_2.10-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.build-link-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-exceptions-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-iteratees_2.10-2.3.10.jar;%APP_LIB_DIR%\org.scala-stm.scala-stm_2.10-0.7.jar;%APP_LIB_DIR%\com.typesafe.config-1.2.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-json_2.10-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-functional_2.10-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-datacommons_2.10-2.3.10.jar;%APP_LIB_DIR%\joda-time.joda-time-2.3.jar;%APP_LIB_DIR%\org.joda.joda-convert-1.6.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-annotations-2.3.2.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-core-2.3.2.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-databind-2.3.2.jar;%APP_LIB_DIR%\org.scala-lang.scala-reflect-2.10.4.jar;%APP_LIB_DIR%\io.netty.netty-3.9.9.Final.jar;%APP_LIB_DIR%\com.typesafe.netty.netty-http-pipelining-1.1.2.jar;%APP_LIB_DIR%\org.slf4j.slf4j-api-1.7.6.jar;%APP_LIB_DIR%\org.slf4j.jul-to-slf4j-1.7.6.jar;%APP_LIB_DIR%\org.slf4j.jcl-over-slf4j-1.7.6.jar;%APP_LIB_DIR%\ch.qos.logback.logback-core-1.1.1.jar;%APP_LIB_DIR%\ch.qos.logback.logback-classic-1.1.1.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-actor_2.10-2.3.4.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-slf4j_2.10-2.3.4.jar;%APP_LIB_DIR%\commons-codec.commons-codec-1.9.jar;%APP_LIB_DIR%\xerces.xercesImpl-2.11.0.jar;%APP_LIB_DIR%\xml-apis.xml-apis-1.4.01.jar;%APP_LIB_DIR%\javax.transaction.jta-1.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-java_2.10-2.3.10.jar;%APP_LIB_DIR%\org.yaml.snakeyaml-1.13.jar;%APP_LIB_DIR%\org.hibernate.hibernate-validator-5.0.3.Final.jar;%APP_LIB_DIR%\javax.validation.validation-api-1.1.0.Final.jar;%APP_LIB_DIR%\com.fasterxml.classmate-1.0.0.jar;%APP_LIB_DIR%\org.jboss.logging.jboss-logging-3.2.0.Final.jar;%APP_LIB_DIR%\org.springframework.spring-context-4.0.3.RELEASE.jar;%APP_LIB_DIR%\org.javassist.javassist-3.19.0-GA.jar;%APP_LIB_DIR%\org.reflections.reflections-0.9.8.jar;%APP_LIB_DIR%\dom4j.dom4j-1.6.1.jar;%APP_LIB_DIR%\com.google.code.findbugs.jsr305-2.0.3.jar;%APP_LIB_DIR%\org.apache.tomcat.tomcat-servlet-api-8.0.5.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-jdbc_2.10-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-jdbc_2.10-2.3.10.jar;%APP_LIB_DIR%\com.jolbox.bonecp-0.8.0.RELEASE.jar;%APP_LIB_DIR%\com.h2database.h2-1.3.176.jar;%APP_LIB_DIR%\tyrex.tyrex-1.0.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-ebean_2.10-2.3.10.jar;%APP_LIB_DIR%\org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar;%APP_LIB_DIR%\org.avaje.ebeanorm.avaje-ebeanorm-agent-3.2.2.jar;%APP_LIB_DIR%\org.hibernate.javax.persistence.hibernate-jpa-2.0-api-1.0.1.Final.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-ws_2.10-2.3.10.jar;%APP_LIB_DIR%\com.typesafe.play.play-ws_2.10-2.3.10.jar;%APP_LIB_DIR%\com.ning.async-http-client-1.8.15.jar;%APP_LIB_DIR%\oauth.signpost.signpost-core-1.2.1.2.jar;%APP_LIB_DIR%\oauth.signpost.signpost-commonshttp4-1.2.1.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-cache_2.10-2.3.10.jar;%APP_LIB_DIR%\net.sf.ehcache.ehcache-core-2.6.8.jar;%APP_LIB_DIR%\com.googlecode.owasp-java-html-sanitizer.owasp-java-html-sanitizer-20160628.1.jar;%APP_LIB_DIR%\com.google.guava.guava-21.0.jar;%APP_LIB_DIR%\org.mariadb.jdbc.mariadb-java-client-1.5.5.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar;%APP_LIB_DIR%\com.jcraft.jsch-0.1.53.jar;%APP_LIB_DIR%\com.googlecode.javaewah.JavaEWAH-0.7.9.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpclient-4.3.6.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpcore-4.3.3.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit.http.server-4.5.0.201609210915-r.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit.lfs-4.5.0.201609210915-r.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit.archive-4.5.0.201609210915-r.jar;%APP_LIB_DIR%\org.apache.commons.commons-compress-1.6.jar;%APP_LIB_DIR%\org.tukaani.xz-1.4.jar;%APP_LIB_DIR%\org.osgi.org.osgi.core-4.3.1.jar;%APP_LIB_DIR%\org.tmatesoft.svnkit.svnkit-1.8.12.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.svnkit-trilead-ssh2-0.0.7.jar;%APP_LIB_DIR%\com.trilead.trilead-ssh2-1.0.0-build220.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.core-0.0.7.jar;%APP_LIB_DIR%\net.java.dev.jna.jna-platform-4.1.0.jar;%APP_LIB_DIR%\net.java.dev.jna.jna-4.1.0.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.connector-factory-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.usocket-jna-0.0.7.jar;%APP_LIB_DIR%\net.java.dev.jna.platform-3.4.0.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.usocket-nc-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.sshagent-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.pageant-0.0.7.jar;%APP_LIB_DIR%\de.regnis.q.sequence.sequence-library-1.0.3.jar;%APP_LIB_DIR%\org.tmatesoft.sqljet.sqljet-1.1.10.jar;%APP_LIB_DIR%\org.antlr.antlr-runtime-3.4.jar;%APP_LIB_DIR%\sonia.svnkit.svnkit-dav-1.8.5-scm2.jar;%APP_LIB_DIR%\org.tmatesoft.svnkit.svnkit-javahl16-1.8.11.jar;%APP_LIB_DIR%\org.apache.subversion.svn-javahl-api-1.8.1.jar;%APP_LIB_DIR%\net.sourceforge.jexcelapi.jxl-2.6.10.jar;%APP_LIB_DIR%\log4j.log4j-1.2.14.jar;%APP_LIB_DIR%\org.apache.shiro.shiro-core-1.2.1.jar;%APP_LIB_DIR%\commons-beanutils.commons-beanutils-1.8.3.jar;%APP_LIB_DIR%\info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar;%APP_LIB_DIR%\org.apache.commons.commons-email-1.3.1.jar;%APP_LIB_DIR%\javax.mail.mail-1.4.5.jar;%APP_LIB_DIR%\javax.activation.activation-1.1.1.jar;%APP_LIB_DIR%\commons-lang.commons-lang-2.6.jar;%APP_LIB_DIR%\org.apache.tika.tika-core-1.2.jar;%APP_LIB_DIR%\commons-io.commons-io-2.4.jar;%APP_LIB_DIR%\org.julienrf.play-jsmessages_2.10-1.6.2.jar;%APP_LIB_DIR%\commons-collections.commons-collections-3.2.1.jar;%APP_LIB_DIR%\org.jsoup.jsoup-1.8.3.jar;%APP_LIB_DIR%\com.googlecode.juniversalchardet.juniversalchardet-1.0.3.jar;%APP_LIB_DIR%\com.github.zafarkhaja.java-semver-0.7.2.jar;%APP_LIB_DIR%\com.googlecode.htmlcompressor.htmlcompressor-1.4.jar;%APP_LIB_DIR%\org.springframework.spring-jdbc-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.springframework.spring-beans-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.springframework.spring-core-4.1.5.RELEASE.jar;%APP_LIB_DIR%\commons-logging.commons-logging-1.2.jar;%APP_LIB_DIR%\org.springframework.spring-tx-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.mozilla.rhino-1.7.7.1.jar;%APP_LIB_DIR%\yona.yona-1.2.0-assets.jar


## 150번째 줄 After
```
set "APP_CLASSPATH=%APP_LIB_DIR%\*.jar"
```

마지막으로 한 번만 더 테스트 해주시겠어요? ;;;

**Comment by junho103** [comment]
이어서 올려주신걸 못보고 가장처음 댓글만 확인해보고 진행하였네요...;;

올려주신 구문으로 교체하여 다시 진행하는 경우 아래와 같은 결과가 던져집니다.

-----------------
F:\Program Files\yona\yona-1.2.0>bin\yona.bat
파일 F:\Program Files\yona\yona-1.2.0\bin\\\..\YONA_config.txt을(를) 찾을 수 없
습니다.
오류: 기본 클래스 play.core.server.NettyServer을(를) 찾거나 로드할 수 없습니다.

**Comment by doortts** [comment]
테스트 해주셔서 고맙습니다. 조만간 시간을 내서 해당 문제 해결방법을 찾아 보겠습니다.

**Comment by junho103** [comment]
빠쁘실텐데 시간내주셔서 감사합니다.~ !!

**Comment by junho103** [comment]
임시 조치

경로 F:\Program Files\yona\yona-1.2.0 → F:\yona\yona-1.2.0 변경

yona.bat 파일의 
11번째 줄에 SET YONA_HOME=F:\yona\yona-1.2.0 추가.

위와같이 변경후 해당 단계는 넘어 갔습니다.

**Comment by sjstyle** [comment]
1. YONA_CONFIG.txt 파일은 없어도 넘어갈 수 있습니다.
2. 입력줄이 너무 깁니다는 yona.bat을 다음과 같이 수정해 주세요.

150번째 줄을
```
set "APP_CLASSPATH=%APP_LIB_DIR%\*"
```
로 변경하면 됩니다.

**Comment by junho103** [comment]
감사합니다. 정상 동작하는것을 확인 하였습니다.

**Comment by junho103** [comment]
경로를 Program Files 아래로 가져가는 경우는 여전히 문제가 생기네요... 폴더명에 공백이 들어가서 그런거 같기도 하고... 테스트 환경을 다시 만들어서 이유를 찾아봐야 겠네요....


-------------------------------------------------------------------------------
F:\Program Files\yona\yona-1.2.0>bin\start_yona.bat

F:\Program Files\yona\yona-1.2.0>SET YONA_HOME=F:\Program Files\yona\yona-1.2.0


F:\Program Files\yona\yona-1.2.0>SET JAVA_OPTS=-Dyona.home=F:\Program Files\yona
\yona-1.2.0 -Dconfig.file=F:\Program Files\yona\yona-1.2.0\conf\application.conf
 -Dlogger.file=F:\Program Files\yona\yona-1.2.0\conf\application-logger.xml -Xmx
2048m -Xms2048m -DapplyEvolutions.default=true

F:\Program Files\yona\yona-1.2.0>bin\yona.bat
파일 F:\Program Files\yona\yona-1.2.0\YONA_config.txt을(를) 찾을 수 없습니다.
오류: 기본 클래스 Files\yona\yona-1.2.0을(를) 찾거나 로드할 수 없습니다.

F:\Program Files\yona\yona-1.2.0>

**Comment by doortts** [comment]
@junho103 말씀하신대로 공백문제일 수도 있을 것 같네요. "Program Files" <= 이런데로는 설치하지 말죠 우리! ㅎ

**Comment by junho103** [comment]
@doortts ㅎㅎ 이상한데 집착할떄가 있어서.... 위와 같은 경우가 아닐때는 경로가 깊더라도 이전문제는 모두 해결되었다고 판단됩니다. 

감사합니다. ^^;

**Comment by sjstyle** [comment]
@junho103 
SET YONA_HOME="F:\Program Files\yona\yona-1.2.0" 
로 해보시겠어요? 제가 Program Files 밑에서 테스트해봤었는데 잘 되어서요;;

**Comment by junho103** [comment]
---------------------------------------------------------------
bin\start_yona.bat 파일의 내용을 아래처럼 넣고 실행하면 아래 **[1]** 처럼 오류가 발생합니다.

**SET YONA_HOME=F:\Program Files\yona\yona-1.2.0**
SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml -Xmx2048m -Xms2048m -DapplyEvolutions.default=true
bin\yona.bat
~~~~~~~~~~~~~~~~~~~~~~~~~~~
F:\Program Files\yona\yona-1.2.0>bin\start_yona.bat

F:\Program Files\yona\yona-1.2.0>SET YONA_HOME=F:\Program Files\yona\yona-1.2.0


F:\Program Files\yona\yona-1.2.0>SET JAVA_OPTS=-Dyona.home=F:\Program Files\yona
\yona-1.2.0 -Dconfig.file=F:\Program Files\yona\yona-1.2.0\conf\application.conf
 -Dlogger.file=F:\Program Files\yona\yona-1.2.0\conf\application-logger.xml -Xmx
2048m -Xms2048m -DapplyEvolutions.default=true

F:\Program Files\yona\yona-1.2.0>bin\yona.bat
파일 F:\Program Files\yona\yona-1.2.0\YONA_config.txt을(를) 찾을 수 없습니다.
**[1]** 오류: 기본 클래스 Files\yona\yona-1.2.0을(를) 찾거나 로드할 수 없습니다.


---------------------------------------------------------------
SET YONA_HOME="F:\Program Files\yona\yona-1.2.0" 로 변경하게 되면 아래 [2] 처럼 오류가 나오네요.

F:\Program Files\yona\yona-1.2.0>bin\yona.bat
**[2]** Files\yona\yona-1.2.0""==""은(는) 예상되지 않았습니다.

**Comment by sjstyle** [comment]
저는 YONA_HOME 쪽 설정을 아예 고치지를 않았었네요

```
@REM yona launcher script
@REM
@REM Environment:
@REM JAVA_HOME - location of a JDK home dir (optional if java on path)
@REM CFG_OPTS  - JVM options (optional)
@REM Configuration:
@REM YONA_config.txt found in the YONA_HOME.
@setlocal enabledelayedexpansion

@echo off
if "%YONA_HOME%"=="" set "YONA_HOME=%~dp0\\.."
set ERROR_CODE=0

set "APP_LIB_DIR=%YONA_HOME%\lib\"

rem Detect if we were double clicked, although theoretically A user could
rem manually run cmd /c
for %%x in (%cmdcmdline%) do if %%~x==/c set DOUBLECLICKED=1

rem FIRST we load the config file of extra options.
set "CFG_FILE=%YONA_HOME%\YONA_config.txt"
set CFG_OPTS=
if exist %CFG_FILE% (
  FOR /F "tokens=* eol=# usebackq delims=" %%i IN ("%CFG_FILE%") DO (
    set DO_NOT_REUSE_ME=%%i
    rem ZOMG (Part #2) WE use !! here to delay the expansion of
    rem CFG_OPTS, otherwise it remains "" for this loop.
    set CFG_OPTS=!CFG_OPTS! !DO_NOT_REUSE_ME!
  )
)

rem We use the value of the JAVACMD environment variable if defined
set _JAVACMD=%JAVACMD%

if "%_JAVACMD%"=="" (
  if not "%JAVA_HOME%"=="" (
    if exist "%JAVA_HOME%\bin\java.exe" set "_JAVACMD=%JAVA_HOME%\bin\java.exe"
  )
)

if "%_JAVACMD%"=="" set _JAVACMD=java

rem Detect if this java is ok to use.
for /F %%j in ('"%_JAVACMD%" -version  2^>^&1') do (
  if %%~j==Java set JAVAINSTALLED=1
)

rem BAT has no logical or, so we do it OLD SCHOOL! Oppan Redmond Style
set JAVAOK=true
if not defined JAVAINSTALLED set JAVAOK=false

if "%JAVAOK%"=="false" (
  echo.
  echo A Java JDK is not installed or can't be found.
  if not "%JAVA_HOME%"=="" (
    echo JAVA_HOME = "%JAVA_HOME%"
  )
  echo.
  echo Please go to
  echo   http://www.oracle.com/technetwork/java/javase/downloads/index.html
  echo and download a valid Java JDK and install before running yona.
  echo.
  echo If you think this message is in error, please check
  echo your environment variables to see if "java.exe" and "javac.exe" are
  echo available via JAVA_HOME or PATH.
  echo.
  if defined DOUBLECLICKED pause
  exit /B 1
)


rem We use the value of the JAVA_OPTS environment variable if defined, rather than the config.
set _JAVA_OPTS=%JAVA_OPTS%
if "%_JAVA_OPTS%"=="" set _JAVA_OPTS=%CFG_OPTS%

rem We keep in _JAVA_PARAMS all -J-prefixed and -D-prefixed arguments
rem "-J" is stripped, "-D" is left as is, and everything is appended to JAVA_OPTS
set _JAVA_PARAMS=

:param_beforeloop
if [%1]==[] goto param_afterloop
set _TEST_PARAM=%~1

rem ignore arguments that do not start with '-'
if not "%_TEST_PARAM:~0,1%"=="-" (
  shift
  goto param_beforeloop
)

set _TEST_PARAM=%~1
if "%_TEST_PARAM:~0,2%"=="-J" (
  rem strip -J prefix
  set _TEST_PARAM=%_TEST_PARAM:~2%
)

if "%_TEST_PARAM:~0,2%"=="-D" (
  rem test if this was double-quoted property "-Dprop=42"
  for /F "delims== tokens=1-2" %%G in ("%_TEST_PARAM%") DO (
    if not "%%G" == "%_TEST_PARAM%" (
      rem double quoted: "-Dprop=42" -> -Dprop="42"
      set _JAVA_PARAMS=%%G="%%H"
    ) else if [%2] neq [] (
      rem it was a normal property: -Dprop=42 or -Drop="42"
      set _JAVA_PARAMS=%_TEST_PARAM%=%2
      shift
    )
  )
) else (
  rem a JVM property, we just append it
  set _JAVA_PARAMS=%_TEST_PARAM%
)

:param_loop
shift

if [%1]==[] goto param_afterloop
set _TEST_PARAM=%~1

rem ignore arguments that do not start with '-'
if not "%_TEST_PARAM:~0,1%"=="-" goto param_loop

set _TEST_PARAM=%~1
if "%_TEST_PARAM:~0,2%"=="-J" (
  rem strip -J prefix
  set _TEST_PARAM=%_TEST_PARAM:~2%
)

if "%_TEST_PARAM:~0,2%"=="-D" (
  rem test if this was double-quoted property "-Dprop=42"
  for /F "delims== tokens=1-2" %%G in ("%_TEST_PARAM%") DO (
    if not "%%G" == "%_TEST_PARAM%" (
      rem double quoted: "-Dprop=42" -> -Dprop="42"
      set _JAVA_PARAMS=%_JAVA_PARAMS% %%G="%%H"
    ) else if [%2] neq [] (
      rem it was a normal property: -Dprop=42 or -Drop="42"
      set _JAVA_PARAMS=%_JAVA_PARAMS% %_TEST_PARAM%=%2
      shift
    )
  )
) else (	
  rem a JVM property, we just append it
  set _JAVA_PARAMS=%_JAVA_PARAMS% %_TEST_PARAM%
)
goto param_loop
:param_afterloop

set _JAVA_OPTS=%_JAVA_OPTS% %_JAVA_PARAMS%
:run
 
set "APP_CLASSPATH=%APP_LIB_DIR%\*"

set "APP_MAIN_CLASS=play.core.server.NettyServer"
 if "%JAVA_OPTS%"=="" SET JAVA_OPTS=-Duser.dir=%YONA_HOME% -Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml -DapplyEvolutions.default=true


rem Call the application and pass all arguments unchanged.
"%_JAVACMD%" %_JAVA_OPTS% %YONA_OPTS% -cp "%APP_CLASSPATH%" %APP_MAIN_CLASS% %*
if ERRORLEVEL 1 goto error
goto end

:error
set ERROR_CODE=1

:end

@endlocal

exit /B %ERROR_CODE%
```

이렇게 설정해두었었습니다.

**Comment by doortts** [comment]
핵심이 이건거죠? 앞뒤로 쌍따옴표!

```
set "APP_CLASSPATH=%APP_LIB_DIR%\*"
```

**Comment by sjstyle** [comment]
@doortts 
아니요~ 수원님이 하신 것에 마지막에 .jar가 없다는 것이 핵심입니다.

**Comment by doortts** [comment]
@junho103 @sjstyle 아.. *.jar 대신에 * 로 폴더안의 모든 파일을 path로 넣는 방법이 동작하는거군요! 
@junho103 님! bat 파일의 설정은 가급적 직접 고치지 않으시는걸 추천드리고 싶어요. 한번 전문으로 붙여준 @sjstyle 님의 스크립트를 이용해서 테스트 해보시면 어떨까요?

**Comment by junho103** [comment]
@doortts 제가 사용중인 **yona.bat** 스크립트 역시 @sjstyle 님이 올려주신 스트립트와 동일합니다.
```
set "APP_CLASSPATH=%APP_LIB_DIR%\*"
set "APP_MAIN_CLASS=play.core.server.NettyServer"
```
나머지 부분역시 손대지 않았구요... 

추가로 **start_yona.bat** 스크립트를 만들어서 시작하고 있습니다.
만든 이유는 [YONA_HOME 설정](https://github.com/yona-projects/yona/wiki/YONA_HOME-%EC%84%A4%EC%A0%95 "") wiki를 참고하였습니다.

**start_yona.bat** 스크립트 내용
```
SET YONA_HOME="F:\Program Files\yona\yona-1.2.0" <- 이렇게도 해보고
SET YONA_HOME=F:\Program Files\yona\yona-1.2.0 <- 이렇게도 해보았습니다.
SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml -Xmx2048m -Xms2048m -DapplyEvolutions.default=true
bin\yona.bat
```

**Comment by junho103** [comment]
아... 저는 그동안

F:\Program Files\yona\yona-1.2.0 bin\start_yona.bat 로 실행을 해왔는데
F:\Program Files\yona\yona-1.2.0\bin yona.bat 로 실행하니 동작하네요... !! 

요점은 yona_home 을 작성하지 않고 실행하니 되네요...

**Comment by sjstyle** [comment]
@junho103 
넵 YONA_HOME을 설정하지 말고 실행하라고 댓글을 달고 있었는데 하셨군요!

**Comment by junho103** [comment]
혹 저같이 윈도우환경 Program Files 밑에 경로를 두고 사용하시는 분은

#137 마지막 부분 참고하시면 좋을것 같습니다.
