### ISSUE TITLE
git 연동 방법 ??

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#131]
안녕하세요. 매 단계 마다 도움받아가며 yona 설치 및 관리자 생성까지 성공 하였습니다.

일전에 yona에 git server가 내장되어 있다고 답변을 받았는데요.

현재 yona를 설치한 서버에서 git 서버도 같이 운영하려고 합니다. (맞게 이해했는지 모르겠으나.. yona만 설치하면 git server 도 함께 되는걸로 이해했습니다.)

yona가 설치된 서버에 있는 git서버(?)에 저장소를 만들려면 어떻게 해야하나요?? ...

개념이 잡혀있지 않아 두서없이 질문드리는거 같아 죄송합니다......

**Comment by junho103** [comment]
프로젝트를 생성하니

YONA_HOME\repo\git 경로 아래 생성되는 것으로 확인했습니다. 

git 관련 지식이 많이 없다보니... 너무 이슈만 올렸네요 ㅎㅎ;

혹시 저같은 사람이 볼만한 가이드가 있을까요??

**Comment by rtboss** [comment]
새프로젝트 생성 후 #82  답변 내용 참고해 보세요.
추가적으로 필요한 질문 있으면 답변 드리겠습니다.

**Comment by junho103** [comment]
답변 감사합니다. 보내주신 내용이면 우선 시작해볼수 있겠습니다. ^^
