### ISSUE TITLE
담당자를 여러명 지정하고 싶어요.

### ISSUE THREAD

**Issue by leesunghee1229** [yona-projects/yona#133]
담당자를 한명만 지정이 가능해서..

내이슈에서 보면 관련 담당자들은 볼수가 없네요 ㅠㅠ;

방법이 있나요?

아니면 기능개선을 해야 하는 부분인가요?

**Comment by doortts** [comment]
@leesunghee1229 기능개선을 해야 하는 부분인데요 정책적으로 고민하는 부분이기도 합니다. 

담당자하는 1명이어야 하지 않나? 라던가 
'그럼에도 실제로 여러명이 작업을 해야 하는 일은?' 
그럼 이슈를 쪼개야 하지 않나? 
본문내용은 거의 같은데? 
음.. 그럼 체크리스트로 만들던가 아니면 sub 이슈라는 개념을 넣어야 하나? 
복잡해 지는건 싫은데.. 에이 몰라~ 좀 더 고민~

<- 이런식으로 사고가 흐르곤 했었습니다.

**Comment by leesunghee1229** [comment]
이 기능이 없는게 맞군요.
너무 복잡하게 생각하지 마시고... 담당자 밑에 같이보기 라는거 만들어서 여러명 선택가능하도록 하면
어떨까요?
그렇게 하면 내이슈 페이지에서 모든 프로젝트 이슈를 확인할 수 있으니까 좋을것 같습니다.

**Comment by doortts** [comment]
혹시 구체적인 상황에 대한 예를 알 수 있을까요? 
보통 같이 봐야 하는 내용은 @ 을 이용한 mention 으로 처리하고 있거든요.

이를테면 아래 경우중에서 어떤 상황에서 일까요..
- 이 이슈의 담당자는 A이지만 B, C, D도 알고는 있으면 좋겠다 -> 이경우는 mention으로 처리
- 이 이슈는 여러명이 처리해야 하는 일이니까 A님은 1을 진행하고 B님은 2부분을 맡아주면 좋겠고 등등인건지..

**Comment by leesunghee1229** [comment]
mention 기능을 이용하면 이슈를 여러명이서 같이 볼수 있는건가요?
내이슈에 담당자가 아니더라도 나온다는거죠?
근데 mention 이용하려고 하니 오류가 나네요 ㅎㅎㅎ

**Comment by leesunghee1229** [comment]
mention 기능을 이용해도 내이슈에는 나오지 않네요.

**Comment by doortts** [comment]
![image](https://cloud.githubusercontent.com/assets/520523/22497615/4d9d459a-e896-11e6-80b6-9f512f3bb4e7.png)
에서 확인할 수 있습니다면 사실 한 이슈를 여러명에게 지정한 것 보다 임팩트가 약하긴 하죠.

**Comment by leesunghee1229** [comment]
나를 언급한 이슈라는게 있었군요.
제가 사용방법을 잘 몰랐습니다 ^^;
정말 감사합니다.
