### ISSUE TITLE
이슈 등록란에 서식을 만들고 싶어요

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#136]
안녕하세요
이슈 등록을 하다보면
이슈재현절차, 재현환경, 빈도 등 항상 적어야할 것들이 많은데
이런것들에 대한 서식을 지정할 수 있다면 좋을 것 같아요
아니면 제가 아직 못 찾았을까요?ㅎㅎ

감사합니다.

**Comment by doortts** [comment]
@haare 현재는 없는 기능인데요 있으면 괜찮을 것 같습니다. 비슷한 요구사항이 가끔 있었거든요. 복잡해지지 않으면서도 간편한 방법을 한 번 생각해 봐야겠습니다. 혹시 아이디어 있으시면 좀 주세요! : )

**Comment by sjstyle** [comment]
지금 GitHub와 비슷한 방법으로 풀어가는 방법도 있을 것 같습니다.... 만 코드가 없는 프로젝트에서는 약간 복잡해질 수도 있을 것 같습니다.

**Comment by doortts** [comment]
> 지금 GitHub와 비슷한 방법으로 풀어가는 방법 
헛! 뭐죠? Github에 관련 기능이 있었어요??

**Comment by sjstyle** [comment]
@doortts 
https://raw.githubusercontent.com/naver/pinpoint/master/ISSUE_TEMPLATE.md

이런식으로 `ISSUE_TEMPLATE.md` 파일을 작성하면 됩니다.

**Comment by doortts** [comment]
@sjstyle 맙소사!! md 파일로 만들고 그게 바로 이슈 템플릿으로 동작하다니!! 우와

**Comment by haare** [comment]
@sjstyle 오 쩔어용 이제 아무것도 모르는 저는 저 md 파일을 적용시키는 법을 찾아봐야겠네요!!

**Comment by haare** [comment]
![image](https://cloud.githubusercontent.com/assets/25476922/22767086/9cfd971c-eebc-11e6-9eb5-83210dc9e4bb.png)
!! 감사합니다.

**Comment by doortts** [comment]
@haare https://github.com/yona-projects/yona/issues/132#issuecomment-278368779 (시무룩)

**Comment by haare** [comment]
@doortts 호호호 첨에 등록할 때 잘하면 수정안해도 되져 머!!

**Comment by doortts** [comment]
v1.3부터 이슈 템플릿 기능을 제공합니다. 현재는 Windows 버전도 동일하게 동작합니다.
