### ISSUE TITLE
코드리뷰 사용법좀 알고 싶습니다.

### ISSUE THREAD

**Issue by tabago** [yona-projects/yona#138]
안녕하세요
코드리뷰를 사용할라고 하는데 리뷰메뉴를 누르면 리뷰 화면에 등록버튼이 없는데..어떤씩으로 사용하는지요..
코드리뷰 사용법좀 알려주시면 감사하겠습니다..

**Comment by doortts** [comment]
안녕하세요? 기본적으로 코드리뷰를 하려면 커밋을 만들어서 push 해야 합니다. 그러면 변경분에 해당하는 commit 들 사이의 diff 가 보여지고 그 diff 부분에 라인이나 블럭을 선택해서 코멘트를 남기는 식으로 진행합니다.

예)
https://repo.yona.io/yona-projects/yona/commit/82fbbeb9d34f9b1fdc483bd6a1585397f3e295bf#thread-14

코드리뷰 관련해서는 아래 링크를 참고하셔도 좋을 것 같습니다.
https://realm.io/kr/news/codereview-howto/

**Comment by tabago** [comment]
감사합니다.
