### ISSUE TITLE
application.conf 적용이 안됩니다.

### ISSUE THREAD

**Issue by penpen787** [yona-projects/yona#14]
안녕하세요. 윈도우7에서 배포판(바이너리)로 설치중 문제입니다.

1. yona.bat 실행 후, c:\yona\conf\application.conf 가 생성이 되었는데 mariadb PW를 변경해도 접속이 동일하게 안되는 문제가 발생하였습니다. 그래서 id 도 asdf 같은값으로 변경해보니 'yona'@'localhost' 로 기존과 동일하게 적용되네요.
**이 conf 파일이 적용이 안되는것 같은데요**, 기존 Yobi 에서도 이런 이슈가 있었던것 같습니다.
https://github.com/naver/yobi/issues/956
yona-1.0.0.jar 에 application.conf 에 들어있는 'yonadan' 으로 비밀번호를 바꾸니 잘 되네요.

2. Database 'default' needs evolution! 
위와 같은 에러가 발생하였습니다.  [https://github.com/naver/yobi/issues/459](url) 과 동일한 문제인데요, 
yona-1.0.0.jar 에 application.conf 와 application.conf.default 파일에  applyEvolutions.default=true
속성을 추가하고 리패키징 해도 동일하게 안됩니다.. 구글링해보니 play framework 옵션이라 play를 실행할 때 옵션을 주면 된다는데, 배포판으로 하다보니 어떻게 해야할 지 모르겠네요. play 프레임워크도 전혀 모르구요..

또 기타 이슈? 불편함? 으로는
A. 상대경로로 설치
binary 를 받아 설치할 경우, 반드시 'yona\' 에서  'bin\yona.bat' 커맨드를 실행해야함. bin 폴더에서 yona.bat 실행시 conf폴더가 \bin\conf 로 생기게 되네요. 반드시 'yona설치폴더\' 에서 커맨드 실행해야 하는것을 매뉴얼에 강하게! 적었으면 좋겠습니다. md 파일 수정해서 pull request 해놓겠습니다.

B. 릴리즈 파일명 혼동문제
릴리즈 페이지에서  [https://github.com/yona-projects/yona/releases](url) 에서 
- 윗부분 
v1.0.0 …
fix: Fix bug from commit 32b7d91
 ea6028e   **zip**   tar.gz
에서 zip 은 실제로는 src파일인데 파일명이 v1.0.0.zip 이고
아래 Download 부분에 바이너리 파일명은 yona-1.0.0.zip 이네요. 
소스와 바이너리 파일명이 혼란스러운데 아파치처럼 yona-1.0.0-src.zip, yona-1.0.0-bin.zip 등으로 구별하면 좋을것 같습니다.

**Comment by doortts** [comment]
1.
우선 password는 실행 단계 중
https://github.com/yona-projects/yona#db-설치후-유저-및-database-생성
에서 스크립트를 바로 복사해서 사용하신것이 아닐까 생각됩니다.
![image](https://cloud.githubusercontent.com/assets/520523/13146498/6e781aac-d699-11e5-97a5-43e27d530fa3.png)

한번 확인해봐 주시겠어요?

그리고 window 바이너리 배포판에서 conf 파일 적용이 안되는 문제는 혹시 아래 링크의 option 지정 방식으로 실행 해봐주실수 있을까요?
https://github.com/yona-projects/yona#windows의-경우

만약 그렇게 해서 잘 된다면 windows 실행 방법자체를 저렇게 하도록 변경해야 겠습니다.

(제가 테스트 할 윈도우PC가 없어서 약간 고생하고 있습니다. 패러랠즈로 실행해봤는데 메모리 에러가 나기 시작하네요. 크..)

2. 네. 설명만 간략히 되어 있긴한데 익숙치 않으신 분들은 어색하실 것 같습니다. 실행시에 evolution 이 자동 실행되도록 스크립트와 가이드를 만들어야 할 것 같습니다.
![image](https://cloud.githubusercontent.com/assets/520523/13146599/df296526-d699-11e5-8542-382687c93fe8.png)

혹시 bat 파일 만들어서 성공하시면 알려주세요!

3. 기타이슈

> A. 상대경로로 설치
 세심한 배려 경로설명 pull request 고맙습니다! 

> B. 릴리즈 파일명 혼동문제
 그 생각을 못했네요! 의견 고맙습니다. 의견주신대로 해당 네이밍으로 수정하는 것이 좋을 것 같습니다.

**Comment by penpen787** [comment]
기본적으로 conf path 잡도록 & -DapplyEvolutions.default=true 설정 yona.bat 추가
