### ISSUE TITLE
"로그인 유지하기" 체크박스 초기값 문의

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#140]
로그인시 "로그인 유지하기" 체크박스 초기값을 설정 할 수 있나요?
현재 초기값이 활성화 되어 있습니다.
공용PC에서 사용시 번거럽네요.
yona 1.3 버전 입니다. (https://repo.yona.io/도 동일합니다)

**Comment by doortts** [comment]
@rtboss 불편해지셨다니 죄송스러운 마음이드네요.. v1.3부터 '로그인 유지하기' 체크박스가 기본 체크로 바뀌었습니다.  해당 부분 우선은 조금 번거로우시겠지만 공용PC 사용이시라면 사용후 로그아웃을 꼭 하시는 쪽으로 진행해주세요.

그리고 공용PC를 자주 사용하시게 되는 상황을 조금 설명해 주시면 패치만드는데에 도움이 될 것 같습니다.

**Comment by rtboss** [comment]
회의실에서 사용하는 PC입니다.

**Comment by junho103** [comment]
@rtboss 
혹시 크롬사용 하시면 시크릿모드로 접속하시는건 어떨까요??

**Comment by rtboss** [comment]
@junho103 이런 기능도 있었네요.
그래도 뭔가를 해야 한다는 것이 번거롭네요.
답변 감사합니다.

**Comment by sjstyle** [comment]
@rtboss 만약 회의실에서 yona를 사용한다면 (크롬일경우) 이런식의 바로가기를 만들어보는건 어떨까요?

![image](https://cloud.githubusercontent.com/assets/4811664/22863695/92fc4352-f188-11e6-9285-0034367215c4.png)

대상에
```
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" https://repo.yona.io --incognito
```
라고 입력하면 됩니다.

**Comment by doortts** [comment]
최근 다수의 서비스들이 특별히 로그인 유지하기 옵션을 따로 제공하지 않고 유지하기가 기본이 되는 추세라(gmail, github 등등) 이 부분은 현재 대로 당분간 유지하려고 합니다.
