### ISSUE TITLE
[Yona-1.3.0] 마크다운 줄간격이 깨지는 것 같습니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#144]
1.3.0 업데이트 후 마크다운 줄 간격이 일정치 않게 되는 것 같습니다.

아래 첨부 이미지처럼 편집창 글 중간에 빈 라인이 있으면 줄 간격이 확 벌어져 버립니다.

![image](https://cloud.githubusercontent.com/assets/24894029/22718328/1e9790c8-ede3-11e6-8670-969eba475b1d.png)

혹시 제가 윈도우에 설치해서 그런걸까 해서 repo.yona.io 에서 테스트를 해봤는데 마찬가지네요.

**Comment by doortts** [comment]
@hyunseogi https://repo.yona.io 에서 이 부분 해결되었는지 확인 한 번 부탁드릴게요.

**Comment by hyunseogi** [comment]
댓글 확인이 좀 늦었습니다.
기왕 확인 하는 것 꼼꼼하게.. ㅋㅋ

![image](https://cloud.githubusercontent.com/assets/24894029/23194364/fcccb856-f8f0-11e6-8c37-9106aa1bd761.png)

위 스샷과 같이 미세한 차이는 남아 있는 것 같습니다만 크게 개의치 않아도 될 정도라 생각됩니다.
