### ISSUE TITLE
windows에서 java.exe 의 메모리 크기 질문

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#145]
안녕하세요

사무용 윈도우 PC에서 파일럿으로 업무 보면서 돌려보고 있는 haare입니다.
(설치환경 보긴 봤는데;; RAM : 1GB 이상 (작동 중 사용 메모리가 900메가 가까이 측정되었습니다.))

yona를 실행시키면 java.exe가 최초 800,372 KB의 메모리를 가지고 시작하는데요

이것저것 눌러보고 한시간 정도 지났는데 935,148 KB를 쓰고 있네요

버튼을 마구마구계속 누르면 983,xxxKB까지 올라가긴 하던데 죽거나 느려지는 현상은 못느꼈습니다.

**왜 자꾸 늘어나기만 하고 줄어들지는 않을까요. 터질까봐 걱정이 되고 있어요**

* 8G램을 사용중이라 위키에서 보고 SET JAVA_OPTS=-Xmx2048m -Xms2048m 설정은 하고 실행했습니다.
(최소, 최대 메모리 크기 2G 셋 맞죠?)

**Comment by sjstyle** [comment]
네 Xmx, Xms 설정을 2기가로 해두셔서, 2기가까지는 계속 메모리가 늘어날 수 있습니다. 
이후에는 GC를 통해서 메모리를 2기가 내외로 유지하게 됩니다.

**Comment by minishanell** [comment]
음... 대략 반년가까이 돌려보고 있는데..  터지는 현상은 없었어요. ^^;;
전 따로 환경세팅하지 않고... 기본세팅값으로 쓰는데요.. (라즈베리3 유저라..)
서버 부하 테스트로 접속 1000가까이 붙여도.. 특별히 메모리를 더 사용한다던가.. 하는 건 없더라구요~
대략 1기가 내외로 요나가 쓸 수 있다면 문제 없으리라 생각됩니다~~

-- 공용으로 쓰시는 경우라면.. 요나 전용으로 하나 분리해두시는게 좋아요 ^ㅇ^
