### ISSUE TITLE
이슈들을 '엑셀파일로 다운받기' 결과

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#147]
안녕하세요

여러모로 신세를 지고 있습니다.

대부분의 툴들이 지니고 있는 엑셀파일로 다운받기 기능을 써봤는데
이슈 내용이 나오지 않아 문의 드립니다.

먼저 
![image](https://cloud.githubusercontent.com/assets/25476922/22782266/9add047a-ef09-11e6-9d1b-6c30b4d5a730.png)

이런 이슈들을 하단에 엑셀파일로 다운받기 버튼을 눌렀습니다.

이슈#5번에는 이런 내용들이 들어있었구요
![image](https://cloud.githubusercontent.com/assets/25476922/22782302/c1148eba-ef09-11e6-8cdf-29c484b67598.png)

다운이 완료되고 엑셀파일을 열어보면
![image](https://cloud.githubusercontent.com/assets/25476922/22782308/ceb900f0-ef09-11e6-99a8-86f5f34d1e3f.png)

내용이 보이지 않는데 어디 숨겨진 것인지 아니면 추가로 설정해야할 부분이 있다면 알려주세요

감사합니다.

**Comment by haare** [comment]
또 어딘가에 동일 이슈 입니다.~ 이러실까봐 떨리네요 ㅎㅎㅎ

**Comment by doortts** [comment]
@haare 원래 엑셀 다운로드에서는 본문 내용은 나오지 않습니다.
만약 프로젝트 local file로 export를 생각하셨다면 [Yona Export](https://github.com/yona-projects/yona-export)를 사용하셔야 합니다.

**Comment by haare** [comment]
@doortts 안녕하세요
알려주신 Yona Export 페이지를 보고 윈도우에서 npm을 어떻게 실행시키는지 확인하다가
1. Node.js를 다운받고 설치했습니다.
2. Yona Export 폴더에서 npm install로 설치를 시도했을 때 별다른 에러 없이 설치된것 처럼 보였습니다.
3. config.json 파일을 열어서 수정하라고 쓰여있는 것을 보고 해당 파일을 찾아봤으나 안보여서 비슷한 config.js 파일을 열어 아래와 같이 수정했습니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22814167/999047d6-ef94-11e6-87ed-108dba8be29a.png)

4. 그리고 Yona Export 폴더에서 npm start를 했더니 아래와 같은 화면이 출력되며 추출이 된거 같지는 않아보입니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22814219/0d404fe6-ef95-11e6-8b0a-0dc4a8dcafcb.png)

* 로그파일입니다.[npm-debug.zip](https://github.com/yona-projects/yona/files/765698/npm-debug.zip)


자꾸 물의를 일으켜 정말 죄송합니다

**Comment by doortts** [comment]
@haare 의존 라이브러리 babel-cli를 제가 누락했나봐요.

```
npm install babel-node 
```
해 본 다음에 다시 실행해 보시겠어요?

참고: https://babeljs.io/docs/usage/cli/

**Comment by haare** [comment]
@doortts 감사합니다. 하지만 돌지는 않는것 같아용

npm install babel-node 실행 결과 아래와 같이 출력 됩니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22867828/07519920-f1d2-11e6-8862-11243e5fedba.png)

npm start 안돌길래

그래서 참고 링크로 보여주신곳에서 npm install --save-dev babel-cli 를 넣어봤습니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22867845/36a00a54-f1d2-11e6-945e-90ae421b3d9e.png)

그래도 npm start 는 안됩니다. 사전에 뭘 더 설치해야 할까요?
![image](https://cloud.githubusercontent.com/assets/25476922/22867901/0897ef9a-f1d3-11e6-97ae-295a3ed54d46.png)

언제나 도움에 진심으로 감사드립니다.

**Comment by doortts** [comment]
yona-export 프로젝트를 수정해 놓았습니다. git pull 해서 다시 실행해 보시겠어요? 제가 명령어를 잘못 적었네요. 죄송합니다.

아니시면 아래 명령어를 실행 후 다시 npm start해보셔도 되고요.
```
npm install -S babel-cli
```
실행환경때 필요한 부분이라 --save-dev 로 하시면 안되고 --save 나 -S로 하셔야 해요.

**Comment by haare** [comment]
@doortts 감사합니다.!! 일단 npm install -S babel-cli의 방법으로는 안되어서 수정하여 주신부분을 새로 다운받고 인스톨하고 npm start를 했더니 이슈들이 export되었습니다.

npm install 할 때 ERR 들이 발생을 하였지만 [로그첨부] npm start는 점잖게 결과를 뱉어냈습니다.

export된 이슈 들의 md 파일들을 열어보니 꽥꽥꽥으로 쓰여있습니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22870858/d6393880-f1ee-11e6-93cf-c25702f5194b.png)
[npm-debug.zip](https://github.com/yona-projects/yona/files/770086/npm-debug.zip)

봐주셔서 감사합니다.

**Comment by doortts** [comment]
기본 인코딩이 UTF-8로 되어 있을겁니다. 만약 윈도우 노트패드로 여셨다면 저럴수 있습니다..;;; 
sublime text / atom editor / EmEditor 등의 UTF-8 기본 지원 에디터로 한 번 열어봐 주시겠어요?

그래도 동일하다면 [Yona Export](https://github.com/yona-projects/yona-export) Project에 이슈로 등록 부탁드립니다!

**Comment by haare** [comment]
@doortts 아톰에디터로 여니 아름다운 한글이 잘 출력됩니다. 정말 감사합니다. ^_^
