### ISSUE TITLE
[제안] '엑셀파일로 다운받기' 내용에 내용과 코멘트도 포함

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#148]
안녕하세요

엑셀파일로 다운받기에 내용과 (코멘트)를 포함되는것이 좋을 것 같아 제안드립니다.
(코멘트에 대해 생각해봤는데 만약 코멘트가 포함된다면 엑셀 서식으로 표현되기에는 부적절한것 같긴합니다. 한개의 이슈에 여러개의 셀들이 주렁주렁 생길것 같긴하네요)

지난주에 그룹>프로젝트의 이슈 목록을 한번 뺏다가 내용 안나온다고 해서 개발자님의 도움으로 프로젝트 익스포트 해가는것을 배웠습니다.
하지만 막상 이슈목록을 뽑아보고 프로젝트 뽑아놓은 것을 섞어 하나의 이슈리스트로 보기좋게 만들어 보려고 했으나 id를 매칭시켜서 해야하므로 쉽지 않음을 깨닳았습니다. 

(만약 한개의 엑셀파일에 현재 출력되는 폼에 세부내용과 코멘트가 포함된다면 굳이 Yona export를 사용하지 않아도 되지 않을까 하는 생각이듭니다.)

DB에 직접 접근하여 쿼리를 사용하여 원하는 데이터만 한 화면에 만든 후 CSV파일로 뽑아내면 될것 같기도 하지만 실제 '참여자' 들은 접근하기 힘든 방법으로 생각이드네요. (물론 저도 아직 쿼리 작성할 줄 모르고요 ㅎㅎ)

좋은 툴 개발에 감사드립니다.

**Comment by doortts** [comment]
사실상 [Yona export](https://github.com/yona-projects/yona-export)는 프로젝트 백업 및 이전을 위해 만들기 시작한 기능입니다. 만약 이슈 목록을 보면서 같이 이야기하는 걸 목표로 하신다면 이슈 페이지를 그대로 같이 보면서 이야기 하시거나 마일스톤 기능을 이용해보시기는 걸 추천드리고 싶습니다.

그와는 별개로 '이슈 목록을 따로 엑셀로 만드시려는 이유'를 사용례로 남겨주신다면 참고가 될 것 같습니다. 솔직히 이야기드려서 이슈 목록 다운로드 기능 자체에 대해서 우선 저 스스로가 필요성을 잘 느끼질 못하고 있거든요. ;;; 
하지만 어쨌든 그건 제 상황인거고 앞서 적었듯 사례를 알려주시면 많은 참고에 많은 도움이 될 것 같습니다.

**Comment by haare** [comment]
안녕하세요 먼저 의견을 주셔서 감사합드립니다. 
저희 조직의 환경을 말씀드리면
아주 먼 옛날부터 수많은 프로젝트들을 각각의 엑셀 파일로 이슈들을 정리해나가며 관리해온 조직입니다.

사실 엑셀이 가지는 여러가지 한계점이 있고 요나가 이쁘고, 빠르고, 그룹, 라벨을 지원하고 개발진들의 지원도 좋지만 하기 몇가지 강점들에 부딛혀 프로젝트/이슈관리 도구로 넘어가지 못하고 있습니다.
(저한테는 클립보드로 사진 바로 붙여넣어 볼수있는거랑 라벨을 자유롭게 지원하는게 너무 좋은 툴로 와닿았습니다.)

저희쪽에서 생각하는 엑셀의 강점입니다.
1. 어디서든 작성이 가능하다.
2. 어느 조직이나 타사로든 전달이 용이하다.
3. 누구나 작성이 가능하다. (복사 붙여넣기로 취합)
4. 파일만 보관하면 어디서든 열어볼수 있다.

사실 프로젝트/이슈 관리 도구 도입에 있어 설득의 관문을 넘는데 위의 4가지 때문에 쉽지가 않네요

위의 1, 3번은 어떻게 넘어가겠는데 4번 항목이 문제입니다.

이렇게 공격 당했거든요
- 서버 문제 생기면 어떻게 할껀데?
 > 백업 잘 해놓고, 바로 교체할 수 있는 대체 PC를 만들어 놓으면 됩니다.
- 외부에서 접속은 어떻게 할껀데?
 > 전산팀 도움받아서 뚫어놓으면 됩니다.
_- 바이어나 외부 업체에서 리스트 달라그러면 어떻게 줄꺼?
 > .....
- 개발자가 중간에 삭제해버리면 그 이슈 히스토리는 어떻게 찾을꺼?
 > .....
- DB 백업외에 보관 방법은 없나
 > .....
- 나중에 관리 툴 교체하게 되면 그간 히스토리는? 다시 불러올 수 있나? 2개를 써야하나?
 > ....._

사실 현재 엑셀만 사용하고 있어도 한사이클이 끝나면 2개 이상의 별도 저장소에 따로 보관을 하고 있습니다.
공격자의 의도는 이런거 같습니다. 툴 쓰는건 다 좋은데 이중으로 가져가자. 엑셀이 주는 익숙함과 근거없는 안전함이 있네요;;

그런 상황입니다. 그래서 일단은 SQL 공부를 해서 쿼리로 원하는 데이터를 뽑는게 말처럼 쉽게 되나를 시도해볼 생각입니다.

감사합니다. @doortts

**Comment by sjstyle** [comment]
- 쿼리로 직접 뽑으실 경우에 말씀하신 경우들은 쉽게 뽑을 수 있습니다. (다만, 쿼리 공부하셔야 하는 문제가 있네요)
- 엑셀과 비교...를 하는게 좀 말이 안된다고 생각하지만 굳이 비교를 하자면 동시편집 문제에서 엑셀은 자유로울 수 없습니다. 그리고 언제 어디서든 열어볼 수 있다면, 파일을 프로젝트 외 멤버가 복사만 해가면 그 프로젝트의 이력을 모두 확인할 수 있으므로 오히려 보안상으로는 엑셀이 더 문제가 크다고 생각합니다.
- 서버 문제가 생기는 것은 yona 뿐만이 아니라 모든 시스템에서 항상 문제가 되는 부분입니다. 특히 하드웨어적인 장애는 100% 막을 수 없으며, 이중화 등을 사용하거나 주기적인 백업 혹은 백업+이중화 등으로 구성하여서 최대한 손실이 일어나지 않는 방법으로 할 수 밖에 없습니다.
- 외부 접속은 방화벽 예외 등으로 해결할 사항이고, 이는 메일 등의 나머지 시스템 역시 마찬가지로 해당됩니다.
- Mysql Workbench 등의 툴에서 DB SQL 파일 이외에 CSV, Excel 파일 등으로 내보내기를 할 수 있습니다. 다만, 이렇게 관리하기 보다는 DB Backup 파일로 가지고 있는 것이 장애시에 복구하기 쉽기 때문에 디비 백업을 권장드립니다.
- 관리툴 교체의 의미를 정확하게 이해하지 못했는데 물리 장비 교체 후에 yona를 계속 사용할 계획이라면 단순히 DB와 설정 파일 폴더, 첨부파일 폴더를 복사해서 사용하면 환경을 그대로 유지할 수 있습니다.

**Comment by haare** [comment]
@sjstyle 감사합니다.

네 이런저런 상황을 고려했을 때 쿼리를 공부를 하던 DB담당자에게 정식으로 요청을 해서 해결하는것이 현실적으로 가장 좋은 방법으로 결론을 내렸습니다.

엑셀 작업은 동시작업이 안되어서 정기적으로 취합하는 형태를 띄고 있는데요 이부분에 대한 불편도 요나 도입에 대한 이유이기도 합니다. 하지만 다행히 전사적으로 문서보안시스템을 갖추고 있어 보안 이슈는 좀 덜수 있기는 하죠

윗분께서 원하는것이 앞서 이야기 드린것도 있겠지만 한 화면에서 타이틀과 제목을 함께 보고 싶은 것도 있는것 같습니다.

mysql workbench 툴은 한번 알아보겠습니다. 

관리툴 교체는 Yona를 쓰다가 redmine이나 testlink 등등의 프로젝트툴이나 이슈트래커로 넘어갈때의 의미입니다.

감사합니다. 좋은 주말되세요

**Comment by doortts** [comment]
@haare lock-in (어떤 시스템에 고정됨)을 저도 싫어하는 편이라서 export 및 사람이 읽을 수 있는 (human readable) 포맷으로 프로젝트 데이터를 남기거나 이동하는것이 중요하다고 생각합니다. Yona도 그런 방향으로 더 보완해 나갈 예정이고요. Yona (이전 Yobi) 자체를 서비스형으로 만들지 않고 설치형으로 만든 이유도 서비스 종료와 함께 더이상 기능이 종료되는 문제도 문제라고 생각했어서입니다.

현재 Yona가 Github 으로 이전하는 기능 [Yona에서 Github으로 이사가는 방법](https://repo.yona.io/yona-projects/yona-help/post/4)외에 Yona Export를 만들고 그 데이터를 plain text로 만든 이유도 그 연장선에 있습니다. 앞으로 좀 더 발전시켜 나가야 하는 부분도 맞고요.

@haare 저랑 딜(deal) 하나 어떠세요? 사심 가득한 제안입니다만 Yona 리뷰하나 써주시면 제가 다음 버전(v1.4)에 (제가 직접만들던지 아니면 주변사람이나 옛 동료를 꼬시던 여튼 수단/방법을 가리지 않고) 이슈 본문과 코멘트 내용을 excel export 파일에 포함되도록 만들게요. 

페북이나 블로그나 트위터나 어디든 상관없고 홍보식 장점으로 쓰실필요도 없고 그냥 리뷰?정도로 솔직히 적어주시는걸로요. (개발의 작은 에너지...로 쓰려고요.ㅎ 현재는 악플보다 무섭다는 무플의 삶을 살고 있기때문에..;;)

그리고 @sjstyle 님도 언급해 주셨지만 MariaDB(=MySQL)은 테이블 내의 데이터를 cvs파일로 만들 수 있는 여러 방법이 있습니다. select 문을 이용해서 파일로 결과를 저장하는 것도 가능한데요 마침 공부하신다고 하셨길래 아래 링크도 참고해 보시면 어떨까 싶습니다. 마침 이 부분을 해결하는 여러가지 방법들이 언급되고 있네요.
http://stackoverflow.com/questions/356578/how-to-output-mysql-query-results-in-csv-format

아참! 그리고 그리고 그리고 혹시 좀 더 편히 잡담 가능한 공간을 찾으신다면 텔레그램 Yona 사용자 채널도 추천드립니다. 물론 텔레그램을 쓰신다는 가정하에서입니다만. 
https://telegram.me/joinchat/A-3VSTyfpszxjOcW2IzR2g


ps.
> 개발자가 중간에 삭제해버리면 그 이슈 히스토리는 어떻게 찾을꺼?

메일 설정을 해 놓고 사용해서 이미 메일을 받고 계신다면 메일함을 이용한 집단지성으로 복원가능합니다.. 이론상.. ;;; (...;;;)

**Comment by haare** [comment]
@doortts 
* 고급지네요 human readable !! 아마도 저희가 엑셀을 남기려는 이유가 그거 였던거 같네요. 많은 툴들이 export/import를 엑셀 형태로 지원하는 이유인것 같기도 하고요 (벗어나기 힘든 엑셀의 구렁텅이)
* 사심 가득한 제안은 이미 받아들였습니다. 글이 3탄까지 완료되면 링크를 공유해보도록 할께요
사실 yona 설치하면서 이걸 좀 남겨놔야겠다는 생각에 블로그를 저장소로 생각을 해두기는 했었습니다.
- 설치기는 돌릴 PC에 새버전을 설치하면서 기존 업무용 PC에서 백업을 이동시키는 삽질과정까지 쓰려고 하거든요
* CSV 추출방법은 HeidiSQL을 그냥 긁어서 빼면 빼지던데. 그렇게 빼면 안되나요 ?! 하루30분36강으로 배우는 책을 구입했으니 2달 정도후면 자습이 끝날듯 싶네요 ㅋㅋ
* 텔레그램 채널은 행여나 개발자님들의 언어가 외계어로 들리면 어떻할까 그래서 망설이고 있습니다.

감사합니다.

**Comment by haare** [comment]
![image](https://cloud.githubusercontent.com/assets/25476922/23115311/664d11b0-f787-11e6-8341-adc2966a94a0.png)

일단 제 네이버 블로그로 작성하고 STEN이라는 테스터들의 커뮤니티에 공유는 해놓았는데..

많은 사람들이 함께 알게되었으면 좋겠네용 :)
http://www.sten.or.kr/bbs/board.php?bo_table=free&wr_id=23726

**Comment by doortts** [comment]
@haare 우와!! 정말 실행력이 빠르시군요!! 고맙습니다! 다음 버전(v1.4)에 요구하신 기능 꼭 넣도록 하겠습니다!

**Comment by haare** [comment]
@doortts '요구' 아니고 요청 또는 제안 드린 내용입니다. ㅎㅎ 미력하지만 개발의 작은 에너지를 드릴수 있어 기쁩니다.

**Comment by haare** [comment]
안녕하세요?!
본문이 나오네요?!!

**Comment by doortts** [comment]
@haare 네 저도 약속대로 v1.4 릴리즈에 제안해주신 기능을 넣었습니다. : )
https://github.com/yona-projects/yona/issues/148#issuecomment-281055312
