### ISSUE TITLE
[기능문의] 이슈수정시 알람메일발송 기본을 비활성화로 설정하는 방법?

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#149]
안녕하세요. 이슈내용 수정시 알람메일을 보내는 기능을 디폴트로 활성화 되어있는데
디폴트로 비활성화 화는 방법이 있을까요?? 

![image](https://cloud.githubusercontent.com/assets/12494817/23012769/1ab0fd6c-f46b-11e6-8a02-82a2d79b1e8f.png)

**Comment by sjstyle** [comment]
### 현재로서는 비활성화 할 수 있는 방법은 없습니다.

일단 알림 메일 발송의 경우, 수신 여부는 수신자의 의사를 따르도록 기획되었습니다.
**수정** 기능에 한해 지나친 메일 발송을 막고자 메일 발송 여부를 선택하도록 정할 수 있고, 기본적으로 수신자에게 변경사항을 알려줄 수 있도록 무조건 보내도록 하는 것으로 되어있습니다.
사용자 별로 설정 페이지에서 프로젝트/이벤트 별로 알림 메일 수신 여부를 정할 수 있습니다. 지나친 메일로 몇몇 수신자가 불편함을 느낀다면 해당 이슈의 지켜보기를 끄거나, 알림 설정을 변경하도록 요청드려보는게 어떨까요?

**Comment by junho103** [comment]
그렇군요 확인감사 드립니다. ^^
사용자에게는 별도로 설정을 하는쪽으로 안내해 줘야겠네요~
