### ISSUE TITLE
익명 접속(Anonymous Access) 제한 적용 시 페이지 연결이 원활하지 않습니다

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#152]
익명 접속 제한 설정 후 로그인시 페이지 연결이 되지 않고 빈페이지 표시됩니다.
환경 : 윈도우 10 / yona-v1.3.1 + MariaDB

```
"application.conf" 파일의
application.allowsAnonymousAccess=false
```

yona-1.2.0 까지는 정상동작 합니다.
yona-1.3.0 및 yona-1.3.1 문제점 발생합니다. 

v1.2.0은 로그인 후 ```http://localhost:9000/```로 연결되나
v1.3.1은 로그인 후 ```http://localhost:9000/users/login```로 연결 됩니다.

아래는 v1.3.1 로그인 후 빈페이지 출력 화면 입니다.
![image](https://cloud.githubusercontent.com/assets/4962243/23150110/3c5842d2-f834-11e6-8812-33756bdffaf7.png)

**Comment by sjstyle** [comment]
아마도 https://github.com/yona-projects/yona/commit/d73aa26041decb0b74fdcf0c52180f5ad7bd25be#diff-fdebe9b141e34cc47158f8b5ce8dbf80R111 의 영향일 것 같아보여요

**Comment by doortts** [comment]
@sjstyle 네 정확히 찾아주셨네요! 👍  고맙습니다! @rtboss 오늘 밤에 관련된 패치 만들어볼게요!

**Comment by rtboss** [comment]
@sjstyle 님 @doortts 님 감사합니다.

**Comment by rtboss** [comment]
@5eae60d ```login: Fix wrong redirected utf8 char paths``` 적용 후 문제가 발생한것 같습니다.
master 브랜치에서 위 커밋 제외 후 문제 없이 동작합니다.
수정하는데 도움이 되었으면 합니다.

**Comment by rtboss** [comment]
yona-v1.3.2 문제 발생하지 않고 잘 동작합니다. 이슈는 닫겠습니다.

직접 수정하여 도움을 드리고 싶으나 이쪽은 문외한이라...
감사드리며 잘 사용하겠습니다.
