### ISSUE TITLE
Google 계정으로 로그인 시 버그

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#160]
![image](https://cloud.githubusercontent.com/assets/6817393/23489588/b7889b2e-ff36-11e6-9bf2-375862db33ea.png)

상단 화면이 새로고침하여도 계속 노출됨

**Comment by doortts** [comment]
@berryzed 버그리포트 고맙습니다. 우선은 번거로우시겠지만, 로그아웃 후 다시 로그인 해보세요. 이후로는 동일 계정에 한해서는 동일 현상이 발생하지는 않으실거에요. v1.4에서는 이 부분에 대한 fix가 포함될 예정입니다.

**Comment by doortts** [comment]
v1.3.3에 해당 문제에 대한 패치가 포함되었습니다. 이슈를 닫습니다.
