### ISSUE TITLE
yona서버에 gitlab을 설치하니...

### ISSUE THREAD

**Issue by Gojhon** [yona-projects/yona#161]
요나가 설치되어 있는 서버에 gitlab을 설치하니깐 요나가 멈추었습니다.
다시 restart가 안되고 있는 상황입니다. yona가 설치되어있는 서버에 gitlab을 설치하면
멈추나요 그리고 복구 방법좀 알수 없을까요?

**Comment by doortts** [comment]
안녕하세요? 증상과 전체 로그를 좀 더 자세히 알려주시겠어요? 
제가 GitLab를 설치해본적은 없지만 포트 충돌(9000)이나 새롭게 작업하신 DB 설정 문제 아니라면 특별히 서로 문제될 부분은 없거든요.

**Comment by Gojhon** [comment]
재시작하는 방법을 모르겠어요

**Comment by doortts** [comment]
(서비스 명령어 같은 식의) 특별한 종료 명령어는 따로 없고 kill pid 로 중단 후 다시 실행해야 합니다.
https://github.com/yona-projects/yona/blob/master/restart.sh 의 kill process 부분을 참고해주시겠어요?

**Comment by doortts** [comment]
계속 문제가 된다면 다시 열어주세요.
