### ISSUE TITLE
yona 질문드려요.

### ISSUE THREAD

**Issue by Gojhon** [yona-projects/yona#163]
요나에서 start하면 파일들이 다..지워지나요?

**Comment by Gojhon** [comment]
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips	: 6334.01
clflush size	: 64
cache_alignment	: 64
address sizes	: 38 bits physical, 48 bits virtual
power management:



Memory: 4k page, physical 3919960k(118092k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Jan 20 2017 12:32:09 by "mockbuild" with gcc 4.4.7 20120313 (Red Hat 4.4.7-17)

time: Mon Mar  6 18:11:32 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by Gojhon** [comment]
로그에는 저렇게 남습니다.

**Comment by doortts** [comment]
OpenJDK 대신에 Oracle JDK를 한 번 써보시겠어요?
