### ISSUE TITLE
새 글쓰기 취소 버튼 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#164]
아..이건 버그인듯 버그아닌 버그 네요..

게시물 본문 보기 옆에 '새 글쓰기' 버튼을 누르면 새창이 열립니다.

여기에선 '취소' 버튼이 동작 하지 않습니다.

새창이라 back을 할 수 없어서 인 듯 합니다.

**Comment by doortts** [comment]
사실.. 이 부분은 조금 고민했던 부분으로 버그는 아니고 일부러 그렇게 동작하도록 만들었습니다.. 

Yobi부터 조금씩 내려오다가 Yona에서 좀 더 개성이 드러나기 시작한 지향점이 하나 있는데 **'상황에 맞게, 그리고 신경 안써도 더 많은 경우에 적당히 잘!'**이라는 개념인데요 

이를테면 이슈를 보다가 새 이슈를 작성하는 상황은 보통 '해당 이슈와 관련이 있거나 연관되서 떠오른 점이 있을 경우'가 확률적으로 더 많다..라는 경험과 가정을 바탕에 두고 '현재 창을 좀 더 편하게 참조할 수 있도록 새창으로 뜨게 만들었다..'가 되겠습니다. 
이건 또 무슨 억지춘향이냐? 라면 사실 할 말 없지만요. ㅎㅎ

물론 동작의 일관성 측면에서는 사실 조금 고민이 되긴 했었습니다만 불편함을 줄 정도는 아니라고 판단했습니다. 그리고 취소를 원하면 그냥 창을 닫으면 되도록요.

이와 비슷한 개념이 적용된 부분으로는 본문링크 클릭에 대한 처리 부분인데요, 만약 글 본문에 링크가 있을 때 해당 링크가 사이트 내부 페이지로의 이동 일 경우에는 현재 창을 그대로 이용하고 외부 사이트에 대한 링크일 경우 새 창이 뜨도록 만든 부분이 그렇습니다. (예. https://repo.yona.io/yona-projects/yona/post/8 본문의 링크들을 보면 내부 사이트를 가르키는 링크와 github 링크는 작성시 특별한 처리를 하지 않았음에도 이야기한대로 동작합니다)

어색하시겠지만 조금만 더 써보시고 여전히 많이 어색하거나 불편하시면 알려주세요. 다시 한번 더 진지하게 고민해 보겠습니다.

**Comment by pokev25** [comment]
그렇군요. 목록으로 가게하면 신경 써야 할 게 많으니 일단 이런 부분은 지금 당장은 넘어 가는것도 방법 이겠네요.

**Comment by doortts** [comment]
v1.4부터 새 창이 열리지 않고 그대로 유지 하도록 변경되었습니다.
