### ISSUE TITLE
마이페이지-멤버로참여중인프로젝트 표시 오류

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#168]
![image](https://cloud.githubusercontent.com/assets/6817393/23741274/08501f96-04eb-11e7-9fdc-810d3ac8336d.png)

프로젝트 삭제 후 마이페이지 접근 시 상단 이미지처럼 표시됩니다!

**Comment by doortts** [comment]
admin 이라 그럴수 있습니다. admin 계정을 프로젝트 생성등에 사용하지 않는걸 추천드립니다.;;

**Comment by doortts** [comment]
#170 여기에서 같이 진행할 예정입니다.
