### ISSUE TITLE
Yona H2 Version Release 요청드립니다.

### ISSUE THREAD

**Issue by brainagenet** [yona-projects/yona#169]
Yona H2 Version도 계속해서 release 해 주시면 감사하겠습니다.

내부 프로젝트에서 잘 사용하고 있습니다.

**Comment by AhnSeongHyun** [comment]
저도 요청드립니다. 소규모 조직에 적용예정입니다.

**Comment by doortts** [comment]
@brainagenet @AhnSeongHyun H2 버전 쓰고 계시다고 알려주셔서 고맙습니다. 진지하게 다시 고민해 보겠습니다.

**Comment by doortts** [comment]
v1.4 부터 다시 H2 버전을 함께 릴리즈 하기 시작했습니다. 체력닿는데까지는 해보겠습니다...만 혹시 어떻게 쓰고 계신지 사용 사례등을 남겨주실 수 있다면 조금 더 체력이 좋아질 것 같습니다. ;;;

**Comment by AhnSeongHyun** [comment]
자회사에서 개발팀 조직하면서 소규모로 쓸수 있는 소스관리/협업툴 알아보던 중에 yona H2 버전을 추천받아서 사용하고 있습니다. 사용인원은 현재는 2명이고 git 을 이용해서 연동하고 있고, 이메일 연결해서 커밋에 대한 상세 정보를 받고 있습니다. 쉽게 설치해서 쓸수 있다는게 장점인것 같아서 선택하게 되었습니다. gitlab 보다 설치가 쉽고 github는 사용할 수 없어서 선택해서 사용하고 있습니다. 아마도 자회사 개발조직에서 계속 사용할 것 같아요 ^^

**Comment by doortts** [comment]
@AhnSeongHyun 쓰시는 환경 공유해주셔서 고맙습니다! : )
