### ISSUE TITLE
변경 내용 확인 시 한글 깨짐 문제

### ISSUE THREAD

**Issue by jaehwanglee** [yona-projects/yona#17]
안녕하세요
기존에 yobi를 사용할 때도 있었던 문제인데요.
파일 변경 내용 확인 시에만 한글이 깨지는 현상입니다.

현재 요나 데모서버에도 테스트를 해보았는데 같은 현상이 있는 것 같습니다.
아래와 같이 그냥 파일 내용에서는 한글이 잘 보입니다만
https://repo.yona.io/jhlee/test/code/HEAD

아래와 같이 변경내용 확인시에는 한글이 깨집니다.
https://repo.yona.io/jhlee/test/commits/HEAD/

혹시 해당 현상에 대해 확인 가능하신지 문의 드립니다.

**Comment by doortts** [comment]
안녕하세요? 한 번 다시 확인해 보시겠어요?
SVN 같은 경우에는 client 가 실행 OS의 기본 로케일에 민감합니다.
따라서 리눅스 계열에서는 LC_CTYPE 의 설정을 잘 잡아주지 않으면 문제가 발생할 수 있습니다. 물론 코드레벨에서 강제로 고정하거나 library등을 이용해서 encoding detection 을 하는 것도 가능한데요 보통은 [LC_CTYPE]( https://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Locale-Categories.html)을 설정하시는 것 만으로도 효과를 보실 수 있을 겁니다. 

그렇게 하고도 안된다면 그건 기본적으로 해당 파일의 인코딩 type이 yona 실행 os와 맞지 않거나 utf8 이 아닌경우일 가능성이 큽니다.

**Comment by doortts** [comment]
참고로 yona.io 는 
```
LC_CTYPE=ko_KR.utf8 
```
로 지정되어 있습니다.

**Comment by jaehwanglee** [comment]
안녕하세요
데모 페이지에서 다시 확인해 보니 utf-8로 테스트 한 경우에는 정상적으로 한글이 잘 보이게 된 것 같습니다.
하지만 EUC-KR의 경우 https://repo.yona.io/jhlee/test/commits/HEAD/
2번 리비전(한글 주석 테스트 )을 확인해 보시면 한글 깨짐 현상이 있습니다.
물론 변경내용 비교가 아닌 커밋 내용 확인 시에는 정상적으로 표시됩니다.

저희는 Visual Studio로 작업을 많이 하고 있는데 Visual Studio에서는 프로젝트 기본 생성 시
한글 OS의 경우 EUC-KR로 생성이 되기 때문에 모든 소스 파일을 전부 utf-8로 변경해서 사용하기에는 부담이 있는 상태입니다 ㅠㅜ

변경내용 비교할 때만 한글이 깨지는 문제라 확인 요청 드렸습니다.

**Comment by doortts** [comment]
네. 아쉽지만 현재 Yona의 svn 같은 경우엔 diff 생성 자체가 file by file 로 이루어지는 것이 아니라 rev by rev 으로 이루어지는 형태라 만약 비교가 되는 두 rev 에 포함된 파일들이 서로 다른 encoding 으로 섞여 있는 경우라면 어떤식으로든 문제가 발생하게 될것 같습니다. 

rev과 rev은 모든 파일이 동일한 encoding을 사용한다고 가정하고 수정하는 code를 넣는 것은 가능하지만 아무래도 추가적인 문제가 발생할 것만 같습니다. 

그보다는
설치하신 Yona의 LC_CTYPE을 EUC-KR로 변경해서 사용하시거나
아니면 프로젝트 소스 파일을 utf-8로 변경하시는걸 추천드리고 싶습니다.

인코딩 변환은 윈도우즈 유저라면 아래 링크를 참고해 주시고
http://wayiam.com/blog/?p=193

리눅스/맥 유저라면 iconv 유틸을 추천해 드리고 싶습니다.
http://linux.die.net/man/1/iconv

**Comment by jaehwanglee** [comment]
네 안내 내용 감사드립니다 :)
말씀해주신 방법을 참고해서 사용해 보도록 하겠습니다.
유틸리티 추천도 감사합니다!
