### ISSUE TITLE
마이페이지-프로젝트가 존재하지 않습니다.

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#170]
![image](https://cloud.githubusercontent.com/assets/6817393/23780910/0c632ebe-058d-11e7-9a9e-416cbb842374.png)

admin 계정이 아닌 일반 계정에서도 프로젝트 목록이 동기화되지 않은거 같습니다.

**Comment by doortts** [comment]
@berryzed 확인해주셔서 고맙습니다. 버그로 등록했습니다.
