### ISSUE TITLE
기존에 등록된 프로젝트 설정 변경 시 오류

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#171]
환경: OS X El Capitan 10.11.6, Google Chrome 56.0.2924.87(64-bit)

기존에 생성된 프로젝트에서 설정화면에 프로젝트 이름 및 설명을 변경한 후 저장하게 되면

![image](https://cloud.githubusercontent.com/assets/6817393/23838115/4c720cc4-07d5-11e7-87a1-aa902814dc6e.png)

위 화면이 나타나게 됩니다.

p.s 레드마인이 아닌 국내 오픈소스 프로젝트 관리툴을 사용하게 되어 너무너무 영광입니다.
앞으로도 더 좋은 소프트웨어를 위해 많은 피드백(ㅠ)드려도 용서해주세요!

**Comment by doortts** [comment]
@berryzed https://repo.yona.io 에서도 동일하게 재현되는지 확인 부탁드려도 될까요?

그리고 설치하신 OS가 OS X 이신건가요?

**Comment by berryzed** [comment]
공식 저장소에서는 해당 현상이 발생하지 않습니다.
제가 진행했던 상황은 저장소 이름이 'test'로 지정된걸 'TEST'로 변경하였을 때 였는데
공식에선 잘되고 저희 쪽에 설치된 서버에서는 오류가 발생합니다.

환경이라는게 테스트 환경이었고 서버는 임시로 Windows 10에서 돌리고 있습니다.

**Comment by doortts** [comment]
@berryzed windows에서는 폴더 이름을 대소문자 구분된 형태의 두 가지를 지원하지 않아서 발생하는 문제입니다. 번거로우시겠지만 오류 메시지를 보여주시겠어요? 이론상 가능할것으로 보이는 꼼수로는 우선 이름을 test2 로 먼저 바꾼 다음 다시 TEST로 변경해보시겠어요?

**Comment by berryzed** [comment]
@doortts 말씀해주신대로 하니깐 정상적으로 되네요! 감사합니다~
