### ISSUE TITLE
마이페이지 프로젝트 목록 안보이는 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#173]
설치해서 운영중인 사이트 문제는 아닙니다.

https://repo.yona.io 여기에서 눌러보다 보니
마이페이지에 목록이 보이지 않습니다.

제꺼만 문제인가 싶어서 보니 전체적으로 그런것 같네요.

https://repo.yona.io/doortts

![image](https://cloud.githubusercontent.com/assets/4251972/23838636/e113b08a-07da-11e7-93c6-42d0ee7bdfec.png)

**Comment by doortts** [comment]
이슈 등록 고맙습니다. 해당 문제는 #168과 같은 문제로 #170 에서 함께 진행할 예정입니다.
