### ISSUE TITLE
[건의] 이슈,알림 뱃지기능

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#178]
상단 오른쪽 이슈, 알림 버튼에 뱃지 아이콘을 넣어 현재 몇개가 활성화되어있는지 알 수 있으면 좋겠습니다.

**Comment by doortts** [comment]
@berryzed 어느 화면의 어떤 부분을 말씀하시는건가요?

![image](https://cloud.githubusercontent.com/assets/520523/23977979/c1cd58e6-0a34-11e7-93b6-7a5156fcaa2c.png)

<= 여기 부문에 대한 이야기이신가요?

**Comment by berryzed** [comment]
@doortts 네 저 설정버튼처럼 [알림 | 이슈]에도 나타나면 좋을거 같아요!

**Comment by doortts** [comment]
@berryzed 우선 이슈 링크에는 표기되도록 했습니다. https://repo.yona.io 에서 테스트 해 보실 수 있습니다. v1.5로 릴리즈 될 예정입니다.

**Comment by doortts** [comment]
@berryzed  알림부분은 구체적으로 숫자로 표현하기 어려워서 우선 자신에게 할당된 열린이슈만 보이도록 변경했습니다. 해당 내용은 v1.5이후에서 확인가능합니다.
