### ISSUE TITLE
sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found

### ISSUE THREAD

**Issue by okayjava** [yona-projects/yona#18]
activator 실행시 
sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found
이렇게 에러가 나는데요...

yona의 문제는 아니지만.. 
이런 경우엔 어떻게 해야 할까요???

[root@XXX yona]# /data/activator/activator
[info] Loading project definition from /data/yona/project
[info] Set current project to yona (in build file:/data/yona/)
[yona] $ update
[info] Updating {file:/data/yona/}yobi...
[info] Resolving org.apache.subversion#svn-javahl-api;1.8.1 ...
[error] Server access Error:    url=http://maven.tmatesoft.com/content/repositories/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn]  module not found: org.apache.subversion#svn-javahl-api;1.8.1
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   file:/data/activator-1.3.7-minimal/repository/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== jgit-repository: tried
[warn]   http://download.eclipse.org/jgit/maven/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== scm-manager release repository: tried
[warn]   http://maven.scm-manager.org/nexus/content/groups/public/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== tmatesoft release repository: tried
[warn]   http://maven.tmatesoft.com/content/repositories/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== julienrf.github.com: tried
[warn]   http://julienrf.github.com/repo/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[info] Resolving com.google.code.findbugs#jsr305;3.0.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.subversion#svn-javahl-api;1.8.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found
[error] Total time: 75 s, completed 2016. 3. 9  5:51:40
[yona] $

**Comment by doortts** [comment]
sonia.svnkit 저장소 서버에 문제가 생긴것이 아닌가 의심되는데요 

소스코드를 이용해서 실행중이시라면 한번 build.sbt 파일을 여셔서

```
  // javahl
  "sonia.svnkit" % "svnkit-javahl16" % "1.8.5-scm2",
```
부분을 아래와 같이 바꾸고 다시 activator를 실행해 보시겠어요?

```
  // javahl
  "org.apache.subversion" % "svn-javahl-api" % "1.8.1",
  "sonia.svnkit" % "svnkit-javahl16" % "1.8.5-scm2",
```

그렇게 해서 되신다면 알려주세요.

**Comment by okayjava** [comment]
"org.apache.subversion" % "svn-javahl-api" % "1.8.1",  << 이것만 한줄 추가 하시라는 말씀인것같아서 추가하고
activator를 실행 하고
update 햇는데
동일하게 오류가 납니다.

**Comment by doortts** [comment]
네. 위치는 sonia.svnkit 위에 적으신것이 맞지요?

**Comment by okayjava** [comment]
아래처럼 되어 있어요.

.. 중략..
     25   // svnkit
     26   "sonia.svnkit" % "svnkit" % "1.8.5-scm2",
     27   // svnkit-dav
     28   "sonia.svnkit" % "svnkit-dav" % "1.8.5-scm2",
     29   // javahl
     30   "org.apache.subversion" % "svn-javahl-api" % "1.8.1",
     31   "sonia.svnkit" % "svnkit-javahl16" % "1.8.5-scm2",
     32   "net.sourceforge.jexcelapi" % "jxl" % "2.6.10",
     33 // shiro
     34   "org.apache.shiro" % "shiro-core" % "1.2.1",
     35   // commons-codec
     36   "commons-codec" % "commons-codec" % "1.2",
     37   // apache-mails
.. 중략..

**Comment by doortts** [comment]
@okayjava  위 링크 기준으로 25번 줄 svnkit 위로도 한번 `"org.apache.subversion" % "svn-javahl-api" % "1.8.1",`를 이동해서 테스트 해봐주실수 있을까요?
