### ISSUE TITLE
프로젝트 생성 시 '공개 설정' 옵션 'Git 저장소에서 코드 가져오기'에 반영되지 않습니다

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#180]
프로젝트 생성 시 ```공개 설정``` 옵션이 ```Git 저장소에서 코드 가져오기```는 반영되지 않습니다.
'Yona-1.3.3'에서 공개 설정이 기본 '비공개'로 적용되어 있으나
'Git 저장소에서 코드 가져오기'는 '공개'로 적용됩니다.

혹시나 했어, 공개 옵션 ```"project.default.scope.when.create = "private"```이 추가된
최신 'next 브랜치'(@00321476)를 빌드 하여 확인 결과 동일합니다.

**Comment by pokev25** [comment]
당연한 결과입니다. 원본이 비공개라고해서 복사본이 비공개여야 하는건 아닙니다.

내가 만든 저장소의 공개,비공개는 내가 설정하는겁니다.

**Comment by pokev25** [comment]
1.3.3. 버전에서 비공개가 기본값 이라고 하셨는데
가져오기 버튼에서는 공개가 기본값이였던 모양이군요.

처음엔 내저장소 공개옵션은 내가 지정하는게 당연한건데 무슨뜻일까? 했네요.
   
다음버전에선 기본값이 좀 달라질 것 같습니다.

**Comment by doortts** [comment]
@rtboss @pokev25 네 제가 놓친부분이 맞습니다. 다음 버전에서는 수정할 예정입니다.

**Comment by rtboss** [comment]
@doortts 수정하셨네요.^^
수정 사항이 반영된 next 브랜치 확인결과 잘 동작합니다.
(project.default.scope.when.create = "private")
