### ISSUE TITLE
application.conf 옵션에서 signup.require.admin.confirm = true 후 승인은 어디서?..

### ISSUE THREAD

**Issue by wifiz** [yona-projects/yona#183]
현재 application.conf 에 옵션을 아래와 같이 사용하려고 합니다.
가입하고나서 관리자 승인을 얻어야 하는데 어드민 계정으로 로그인 해도 해당 사용자 승인하는 메뉴를 찾지 못하겠는데
어디서 해야 하나요?..

가입 후 관리자가 승인을 해야만 활동 가능하도록 제한하는 기능
signup.require.admin.confirm = true

**Comment by doortts** [comment]
admin 계정으로 로그인 하시면 상단에 설정 아이콘이 보이실겁니다. 
![image](https://cloud.githubusercontent.com/assets/520523/24176644/9f31893c-0ee0-11e7-90c8-9b80b8b62499.png)


관리자 메뉴에서 사용자 항목을 보시면 잠긴 사용자에 해당 유저가 보이실겁니다.
![image](https://cloud.githubusercontent.com/assets/520523/24176667/b518ab5e-0ee0-11e7-8dcb-822b1c94fc73.png)

**Comment by wifiz** [comment]
@doortts 
관리자 계정인데 해당 메뉴가 보이지 않습니다..ㅠ

<img width="1117" alt="default" src="https://cloud.githubusercontent.com/assets/26372626/24176741/390b15be-0ee1-11e7-9d79-88ce3588c3ba.png">

**Comment by wifiz** [comment]
@doortts 
이유는 알 수 없지만
db 들어가서 site_admin에 값을 넣어주느 해당 메뉴가 생겼네요.

**Comment by doortts** [comment]
@wifiz 현재 site_admin 테이블에 아이디가 몇 개 들어있나요?
그리고 설치하신 버전과 방법은 어떻게 되세요?

**Comment by wifiz** [comment]
@doortts 
요나 버전은 1.3.2 버전이구요.
현재 한개 들어가 있습니다.

해당 메뉴가 노출되지 않았을당시엔
site_admin에는 값이 하나도 없었습니다.

**Comment by doortts** [comment]
음.. 최초 설치시에 특정 오류를 겪으셨거나 이전에 DB를 직접 수정하셨던적이 있으신가요?

**Comment by wifiz** [comment]
@doortts 
설치시 오류는 없었구요. 설치 이후에 db를 수정했던적은 있어요.

**Comment by doortts** [comment]
@wifiz 네. 우선 다행히도 DB관련 지식이 있으셔서 site_admin 테이블에 추가하셨다니 이후 문제는 없을 겁니다. 다만 혹시 일반적으로 반복 발생가능한 문제인지 확인이 조금 필요해서 여쭤봤어요. 혹시 사용자 관련해서 DB수정작업을 하셨었나요?

**Comment by wifiz** [comment]
@doortts 
네. 관리자 계정 생성 후 관리자 계정으로 프로젝트 생성한 다음에 다른 유저에게 프로젝트 이관하려고 하는데 에러가 나서(어떤 에런지는 기억이 안나네요. 이관 받을 계정에서 승인해야 한다고 해서 그 계정을 가서 승인 하려고 했더니 안됐었어요.)
삭제도 안되고 해서 디비에 내용들(어드민 계정 포함)을 다 지웠던 적이 있어요. 그리고 재접속하니 관리자 계정을 생성하는 페이지가 나와서 다시 만들었었구요.

**Comment by doortts** [comment]
@wifiz 아 그렇다면 그 때 같이 지워졌던것 같습니다. 이후로는 동일문제는 발생하지 않으실것같아요. : ) 확인해 보시고 문제 없으시면 이슈 close 부탁드릴게요. 다시 발생하면 언제든 편하게 다시 열어주세요.
