### ISSUE TITLE
[Yona-1.4.0] 로컬PC에서 커밋한 파일을 온라인 수정 시 파일 전체 내용이 diff 로 표시됩니다

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#184]
Yona-1.4.0 업데이트 후 기존에 로컬 PC에서 커밋한 파일을 요나에서 수정하고 온라인 커밋을 했습니다.

그런데, 한 라인만 수정했는데 변경 내용을 확인해보니 전체 파일 내용이 diff 로 표시됩니다.

로컬 PC 와 서버 모두 Windows 이고, 로컬 PC에서는 이클립스 eGit 플러그인으로 커밋했습니다.

아마 CR/LF 때문인 것으로 보이는데, 우선 이슈로 남깁니다.

**Comment by hyunseogi** [comment]
파일 인코딩도 맞지 않는 것 같습니다.
 1. 로컬 PC에서 파일 생성 및 편집
 2. Yona Git Repository 에 Push
 3. Yona 에서 수정 후 온라인 커밋
 4. 로컬 PC에서 Pull -> 파일 내용이 깨져서 보임

로컬 PC는 윈도우즈, 이클립스에서 테스트 하였으며, 
프로젝트의 파일 인코딩은 UTF-8, 줄바꿈은 CRLF 로 선언되어 있습니다.

**Comment by sjstyle** [comment]
@hyunseogi 
https://git-scm.com/book/ko/v1/Git%EB%A7%9E%EC%B6%A4-Git-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0 를 참고해서 `core.autocrlf` 를 한번 해보시겠어요?
해당 설정 변경 후에 새로 pull 받았을때도 깨지시는지 궁금합니다.

**Comment by hyunseogi** [comment]
이클립스 eGit 의 Configuration 설정을 하고 테스트를 해 보았는데
아래와 같이 한글이 깨지는 현상이 발생합니다.
 
![image](https://cloud.githubusercontent.com/assets/24894029/24235274/d6c6ebb2-0fdf-11e7-9ca0-4be793322597.png)

 1. 이클립스에서 임의의 텍스트 파일 생성 (한글, 영문 섞어서 작성)
 2. 저장 후 Commit&Push
 3. 요나 웹 페이지에서 파일 내용 정상적으로 보임 (Raw 포맷 뷰에서도 정상 출력)
 4. 요나에서 일부 내용 수정 (온라인 커밋)
 5. 이클립스에서 Pull : 파일 내용이 깨짐 (한글만)
    * 요나 웹페이지에서도 커밋한 파일을 Raw 포맷 뷰로 보면 한글이 깨져서 출력됨
    
![image](https://cloud.githubusercontent.com/assets/24894029/24235367/4695c526-0fe0-11e7-851e-f30332de446b.png)

**Comment by sjstyle** [comment]
음 해당 상황은 yona 온라인 커밋할때 인코딩 셋이 빠지는것이 아닌가 하는 의문이 있습니다.
아직 자세히는 볼 시간이 없어서 한번 확인해봐야할 것 같네요

**Comment by doortts** [comment]
8fb790b181b2aae5571cb411f84102bf3965a3c4 에서 관련 작업을 진행했습니다. https://repo.yona.io 에서 테스트 한 번 부탁드릴게요.

**Comment by hyunseogi** [comment]
1.4.1 업데이트 적용 후 문제 없이 잘 되는 것을 확인 하였습니다.
늦은 시간까지 고생하셨습니다. ㅜ.ㅜ

이 이슈는 닫겠습니다.
