### ISSUE TITLE
[제안] 에디터

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#187]
안녕하세요?

버그 리포트가 아닌 제안을 올려서 죄송합니다...ㅠㅠ

글쓰기에 기본으로 된 문법이 좀 약한 듯 해서요, 아래의 에디터로 사용하는건 어떠신지요??

https://www.froala.com/wysiwyg-editor

에디터의 끝판왕이 아닌가 싶습니다. 

기본 문법에서 table 활용이 많이 부족해서 대안을 찾던 중 위의 에디터가 좀 아주 좋아보입니다.

감사합니다^^

**Comment by pokev25** [comment]
마크다운 에디터가 기본인지라.. 마크다운에 익숙하지 않은 비개발자를 위해서 위지윅을 지원하는것도 
옵션으로 볼 수 있겠으나....아마도 어렵지 싶습니다.

**Comment by witbox** [comment]
그렇군요.. 옵션으로라도 지원이 된다면... 구입하는거야 큰 문제는 아니겠지만, 일이 복잡해질 수 있겠네요.

감사합니다.

**Comment by doortts** [comment]
@witbox 의견주셔서 고맙습니다. 좋은 에디터는 글 쓰는걸 참 편리하게 해주죠. 마크다운은 초반 학습곡석이 조금 있는 편이고요. 그리고 이야기 주신 테이블 작성 부분은 사실 오랫동안 회사내/외 사람들이 불편해 하던 부분맞아요. 뭔가 좀 상큼한 아이디어가 있으면 한 번 도입해 볼텐데 말입다. ㅎㅎ

@pokev25 님이 글 남기신대로 당분간은 에디터 부분의 교체는 어려울 것 같습니다. 여력이 안되는 부분이 제일 크구요. : )
