### ISSUE TITLE
마일스톤에 등록된 이슈 다른 프로젝트로 이동시 문제.

### ISSUE THREAD

**Issue by wifiz** [yona-projects/yona#188]
이슈 이동시 마일스톤에 등록된 이슈를 이동시키는 경우 기존 마일스톤에서 삭제가 안되고 링크 클릭시 오작동 하는 문제가 있습니다.

**Comment by doortts** [comment]
@wifiz v1.4.1에서 해결되었습니다. 만약 재현되신다면 다시 열어주세요.
