### ISSUE TITLE
파일 내용 확인 후 "파일"탭 실행 시 미이동

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#189]
파일 내용 확인 후 "파일"탭 실행 시 파일 목록으로 이동되지 않습니다.

![file_tab](https://cloud.githubusercontent.com/assets/4962243/24275990/f4272374-1076-11e7-89ff-1d56acd2ca90.png)

문제점만 올리네요...TT

**Comment by doortts** [comment]
@rtboss https://repo.yona.io 에서 확인 부탁드릴게요. 이상없다면 v1.5에 포함될 예정입니다.

**Comment by doortts** [comment]
v1.5에서 해당 문제를 수정했습니다. 확인 후 동일 문제가 발생한다면 다시 이슈를 열어주세요.
