### ISSUE TITLE
영문이나 다국어 지원은 안되나요?

### ISSUE THREAD

**Issue by comseong** [yona-projects/yona#19]
개도국에서 일하고 있습니다. 이 나라에 자랑스런 저희 나라꺼를 소개시켜주려고 하는데요. 그 전에 제가 먼저 설치를 해봤는데, 영문 메뉴로의 전환기능이 없네요. 본래 영문이든 다국어 지원은 하지 않는 것인지요? 지원되지 않는다면 이건 feature request가 되겠군요. 안타깝지만, 다국어 되기 전까지는 GitLab 같은 다른 걸 활용해야 할 것 같네요.

**Comment by doortts** [comment]
안녕하세요? Yona는 다국어를 지원하고 있습니다.

현재는 영어와 한국어 2개 언어를 지원하고 있으며
conf 폴더 아래의 messages 와 messages.ko-KR 에서 확인 또는 다른 언어로 확장 가능합니다.

표시 언어 우선순위는 기본적으로 사용자 브라우저의 언어설정을 기반으로 동작하고 있습니다.

또한
conf/application.conf 파일내의
```
# The application languages
# ~~~~~
application.langs="en-US, ko-KR, ja-JP"`
```
부분에서 app 기준의 적용 우선순위가 기재되어 있습니다.

개도국이 어느곳인지는 모르겠지만 혹 해당국가의 언어를 지원하고 싶으시다면
messages 파일을 복사하셔서 확장자로 `지역-언어` local을 붙이시고 위 application.conf 설정 부분에 지정해 주시면 추가로도 가능합니다. 

: )

**Comment by JeongJun-Lee** [comment]
안녕하세요? 말씀해주신 messages 파일을 현지어 전에 1차 공용어로 번역을 완료하고 테스트를 진행하려고 합니다.

그런데, 설치 버전으로 설치해서 그런지 말씀하신 conf 디렉토리 안에 기존에 messages 파일들이 없습니다. 그래도, 그냥 conf 디렉토리 번역된 messages.ru-RU넣어보고 application.conf 에도 ru-RU를 제 1 우선순위로 추가했고, 이후 크롬 웹브라우저 언어변경 설정에서 러시아어로 변경해서 접근해 봤는데, 요나가 번역된 내용으로 뜨지 않습니다. 어떻게 테스트 해야 할까요?

**Comment by doortts** [comment]
@JeongJun-Lee 괜찮으시다면 제 깃헙 프로필상의 이메일로 해당 메시지 파일을 보내주실 수 있을까요?

**Comment by JeongJun-Lee** [comment]
@doortts 그런데, 아직 초벌 번역이라... 먼저, 저희 시스템에 올려놓고 번역 검증을 완료하고 pull request 하려고 하거든요. 혹시 요나 설치 버전에서는 테스트 방법이 없는지요?

**Comment by JeongJun-Lee** [comment]
@doortts 조금 더 진행을 해보았습니다. 편법입니다만 설치 디렉토리에 lib 디렉토리 안에 yona.yona-1.5.0.jar 파일 안에 언어 파일들이 들어있더군요. 아마 빌드 과정에서 언어 리소스들이 그 파일로 묶이나 봅니다. 그래서, 그 jar파일 안에 jar -uvf yona.yona-1.5.0.jar messages.ru-RU 명령어로 새로 생성한 언어 파일을 추가했습니다. 그리고 다시 크롬으로 접근해봤는데, 변화가 없더군요; 크롬에서 언어설정을 바꿨을 때 크롬 인터페이스가 해당 언어로 바뀌던데 단지 인터페이스만 바뀐 것인지요? 요나에 접근했을 때 여전히 문서에 인코딩 타입은 <html lang="en">으로 인식되더라구요.

**Comment by doortts** [comment]
@JeongJun-Lee 해당 부분 찾느라 고생하셨을텐데 미리 이야기 드릴걸 그랬어요. 저 파일 안에 넣지 않고 처리할 방법에 대해 찾아보는 중이었습니다. 해당 파일내에 언어 메시지 파일을 추가하고 재시작 하면 반영되어야 하는 것이 정상입니다. 즉, 크롬으로 접근했을때 메시지가 ru로 나와야 하는 거죠.  ru-RU 대신 ru로 한 번 해보시겠어요. 일본어 처리 할때 그렇게 했었습니다. 저도 예전 일본어 메시지 파일을 이용해서 테스트해볼게요.

**Comment by doortts** [comment]
아니 ru-RU 대신 ru로 해보라고 한 말은 취소!

**Comment by doortts** [comment]
@JeongJun-Lee 
![image](https://user-images.githubusercontent.com/520523/27113786-148d6808-50fa-11e7-8b1c-59dc32c4841e.png)
![image](https://user-images.githubusercontent.com/520523/27113797-2632dcf0-50fa-11e7-87c0-c17d9138f15e.png)

repo.yona.io 에서 위에처럼 크롬의 언어설정을 일본어로 바꾸고 우선순위를 최 상단으로 놓으면 저렇게 보입니다. 번거로우시겠지만 ru 메시지 파일을 보내주시면 저도 한 번 ru-RU로 표시되는지 한 번 반영해서 테스트를 해 보겠습니다.

**Comment by JeongJun-Lee** [comment]
넵. 메시지 파일 메일로 드렸어요^^ 제가 윈도우즈10을 쓰는데, 러시아 언어팩을 추가하고 디폴트 언어를 러시아어로 하고 엣지 브라우저를 열어보니 시작 페이지가 lang=ru-ru라고 표시되고 러시아어로 인식되어 잘뜨네요.  그런데, 요나에 접근해보면 여전히 영문이 뜨네요;;;

**Comment by doortts** [comment]
@JeongJun-Lee 
![image](https://user-images.githubusercontent.com/520523/27117534-eaf0cf18-5111-11e7-96f2-2f88c0b8a7fe.png)

보내주시신 메시지 파일 반영하고 
application.langs="en-US, ko-KR, ja-JP, ru-RU"
설정해서 접근하니까 위 스샷처럼 뜹니다.

이어서 테스트 하기 편하신 방법을 찾아볼게요

**Comment by JeongJun-Lee** [comment]
일단 된다니 다행입니다^^ 그런데, 제가 했던 것처럼 기존 실행 환경에서 라이브러리 안에 jar 파일에 메시지 파일을 추가해서 확인하신 것인지요? 아니면 새로 빌드하신 것인지요? jar 파일에 추가하는 방법으로는 저는 여전히 잘 안되고 있어서요;;;

**Comment by doortts** [comment]
@JeongJun-Lee 빌드를 새로 했습니다.
https://github.com/yona-projects/yona#소스코드를-직접-내려-받아서-빌드-실행하기

이제 배포판에서 해당 jar 파일에 메시지 파일을 넣어서 테스트 해볼게요.

**Comment by JeongJun-Lee** [comment]
네 감사합니다. 꼭 좀 부탁드릴게요. 여기 인터넷 워낙 사정이 안좋아서요; 이 나라 국가 밖 인터넷을 사용하는 비용과 또한 속도도 만만지 않습니다. 그래서, 소스와 빌드 관련 툴을 일일이 다운받아서 빌드 작업을 하기가 만만지가 않습니다. 이런 곳에서는 설치 버전이 절대적으로 유용합니다! 설치 버전으로도 검증할 방법이 있으면 좋겠습니다.

**Comment by doortts** [comment]
@JeongJun-Lee 테스트를 진행해 보았습니다.
jar 파일로 yona.yona-1.5.1.jar 파일을 특정 폴더에서 압축을 해제한 다음 메시지 파일을 추가하고 다시 jar cf 로 동일 이름으로 묶으면 정상적으로 추가되는 것을 확인했습니다.

작업순서
---
- 폴더를 하나 만들고 (예. localization)
- yona.yona-1.5.1.jar 파일을 해당 폴더로 복사한 다음, 해당 폴더(localization)로 들어가서
- jar xvf yona.yona-1.5.1.jar 
- 번역한 메시지 파일을 압축을 푼 폴더로 root로 복사하고 
- 다시 해당 폴더 위치에서 jar로 묶는다 
```
jar cf yona.yona-1.5.1.jar . 
```
- application.conf 에 해당 언어 지원을 추가하고 
```
application.langs="en-US, ko-KR, ja-JP, ru-RU"
```

재시작한다.

참고로 해당 과정이 메시지 수정을 반복 하게될 경우 번거로울수 있을 것 같아서 유틸리티를 하나 간단히 만들었습니다.

https://github.com/yona-projects/yona-translate

간단히는 위 순서대로 하시면 무난하고 유틸 필요하시면 nodejs를 설치하시고 진행하시면 될 것 같습니다.
nodejs: https://nodejs.org

그럼 해보시고 의견주세요!

**Comment by JeongJun-Lee** [comment]
그새 유틸까지 만들어 작업해 올려놓으시고 대단하세요!^^ 그런데, 저는 여전히 안되고 있습니다ㅠ.ㅠ
만들어주신 유틸을 clone하니 source 디렉토리 안에 이미 jar와 messages파일이 들어있더군요. 그래서 그냥 실행시켜서 out 파일로 메시지 파일을 합친 새로운 jar 파일을 생성했습니다. 그런데 jar 파일명 버전이 1.5.1이고, 제가 설치한 버전은 1.5.0이라 이름만 바꿔서 설치된 디렉토리 lib 안으로 덮어씌워 옮겼습니다. 그리고, 요나를 재시작 했구요. 물론 conf파일에 해당 언어는 진작부터 추가되어 있구요. 그런데, 웹브라우저로 접근해 보면 러시아어가 안뜹니다. 어디서부터 디버깅이 필요한걸까요???

**Comment by JeongJun-Lee** [comment]
아닙니다. 심려를 끼쳐드려 죄송합니다. 제 실수였습니다;;; 제가 최초 설치시 설치 가이드에 따라 yona-data라는 디렉토리를 별도로 만들고 거기에 conf 디렉토리를 복사해놨다는 것을 까맣게 잊고 있었네요. 그래서설정 변경은 거기를 고쳐야 실제 반영되는 것인데, 저는 요나 실행 파일이 위치한 디렉토리 안에 conf 디렉토리 안에 설정파일을 고쳐 놓고 계속 왜 안되지 했었던거 였네요;;; 그래서 이번 기회에 혼동을 방지하고자, 그 conf 디렉토리 명을 conf-org으로 변경해 놨습니다. 저 같은 혼동을 막기 위해 설치 가이드에도 그런 식으로 디렉토리 명을 처음부터 바꿔 놓도록 하면 어떨까 하는 제안을 드려봅니다. 그건 그렇고, 그럼, 아마 원래도  jar 파일 수정에 대한 저의 최초 시도였던 jar -uvf yona.yona-1.5.0.jar messages.ru-RU 명령어에 의한 메시지 파일 추가도 다시 확인해보진 않았습니다만, 문제없는 방법이었을 수도 있었겠단 생각이 듭니다. 

결론적으로 다국어 지원 과정에 있어 문제 파악에 또 유틸지원으로 함께해 주시고 도와주셔서 진심으로 감사드리며 이 이슈는 닫도록 하겠습니다.

**Comment by doortts** [comment]
@JeongJun-Lee 해결되셨다니 다행입니다! :D 업로드 파일이나 설정 로그 등이 Yona 업데이트와 별개로 계속 특정 위치에서 유지되도록 만들기 위해 YONA_DATA 환경변수 설정을 하도록 되어 있습니다.

이야기 주신대로 오해의 소지가 있기때문에 시간이 될때 환경변수 등도 함께 체크하는 installer 를 따로 제공해야겠다고 생각하고는 있습니다만 우선순위에서 밀려서 아직 작업을 시작못했습니다.
https://github.com/yona-projects/yona-install
(누가 해줬으면 좋겠.... ;;;)
