### ISSUE TITLE
요나 프로젝트 질문입니다.

### ISSUE THREAD

**Issue by Gojhon** [yona-projects/yona#190]
프로젝트 멤버 인데 clone을 떠서 해야하는데 제가 모르고 마스터를 만들어서 프로젝트에 올렸습니다.
이걸 취소를 할수 있는 방법은 없을까요?

**Comment by doortts** [comment]
잘못 올려진 코드가 문제라면 git reset --hard 로 이전 버전으로 돌아가신 후  git push -f 로 서버쪽 코드를 강제 리셋하셔야 할 것 같습니다.

**Comment by Gojhon** [comment]
감사합니다. 확인 해보겠습니다.^^

2017-03-24 16:53 GMT+09:00 Suwon Chae <notifications@github.com>:

**Comment by doortts** [comment]
별다른 추가 댓글이 없어서 닫음 처리합니다.
