### ISSUE TITLE
나눔바른고딕 폰트 렌더링 문제

### ISSUE THREAD

**Issue by cnabro** [yona-projects/yona#191]
안녕하세요
http://repo.yona.io 에 들렀다가 큰 문제는 아니지만
수정되면 좋을것 같아 이슈를 남깁니다 (Windows 10 / Chrome 57.0.2987.110 )

기본 font-family 가 아래처럼 적용되어있는데, 나눔바른고딕 + bold 가 먹히는 경우에 찌그러지는 현상이 있는거 같습니다. 

```
"Noto Sans", "New Roboto", "Helvetica Neue", "Helvetica", "Apple SD Gothic Neo", "Arial", "나눔고딕", "NanumGothic", "NanumGothicOTF", "맑은 고딕", -apple-system, BlinkMacSystemFont, sans-serif
```

- 나눔바른고딕 적용되었을 때
![1490338512794](https://cloud.githubusercontent.com/assets/6916639/24283829/589c94fe-10ab-11e7-954e-644923bdf555.jpg)

- 나눔바른고딕 제거했을 때
![1490338477821](https://cloud.githubusercontent.com/assets/6916639/24283854/6e67d82a-10ab-11e7-8033-08c1619df7fc.jpg)

**Comment by doortts** [comment]
스샷까지 남겨주셔서 고맙습니다. 현재는 나눔고딕, 나눔바른고딕 둘 다 설치되어 계신거죠?

**Comment by cnabro** [comment]
@doortts  네 맞습니다. 나눔고딕, 나눔바른고딕, 나눔바른고딕OTF 모두 설치되어있는 상황입니다.

**Comment by doortts** [comment]
@cnabro repo.yona.io 에서 테스트 부탁드려요!
