### ISSUE TITLE
닫힌 이슈 상세보기에서 [목록] 으로 돌아갈 때

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#192]
사소한 수정 요청 드립니다.

닫힌 이슈 상세 조회 화면에서 [목록]버튼을 누르거나 단축키 'L'을 누르면 
열린 이슈 리스트로  넘어가는데.. 
닫힌 이슈 리스트로 가는 것이 맞을 것 같아 이슈로 납깁니다.

**Comment by doortts** [comment]
@hyunseogi repo.yona.io 에서 테스트 부탁드립니다.

**Comment by hyunseogi** [comment]
닫힌 이슈 상세화면 : [목록] 버튼 -> 닫힌 이슈 리스트 로 넘어가는 것을 확인했습니다.
