### ISSUE TITLE
[건의] 소셜로그인 시 비밀번호 설정

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#193]
수고가 많으십니다.

소셜로그인으로 로그인을 한 후 SVN에서 https 프로토콜로 설정된 저장소에 접근 시 비밀번호를 물어보게 되는데
이때는 [사용자 설정-비밀번호 변경-비밀번호 재 설정] 메뉴에서 설정하여야 기능을 사용할 수 있는데요.

혹시 소셜로그인으로 가입을 하게 되면 가입하는 즉시 초기 비밀번호를 설정할 수 있는 기능이 있으면 좋겠습니다.

**Comment by doortts** [comment]
@berryzed 의견고맙습니다. 뭔가 불편하지 않으면서도 효과적으로 처리할 방법을 한 번 고민해 보겠습니다. 생각해보시다 좋은 아이디어 있으면 마찬가지로 알려주시면 큰 도움이 될 것 같습니다.

**Comment by berryzed** [comment]
어떤 웹사이트에서 SNS 로그인 시 기본적으로 OAuth에서 제공하는 이메일 주소 / 이름 / 이미지 주소 등 이외에 다른 정보를 추가 입력받을 시 정보수정 페이지로 이동이 되도록 하는걸 본적이 있습니다! 관리자 승인 또는 이메일 승인일 경우에도 특정 정보가 없으면 자동으로 해당 정보 수정페이지로 이동되는걸로 하는것도 나쁘지 않을거 같습니다!

항상 수고가 많으십니다.

**Comment by doortts** [comment]
@berryzed 
>관리자 승인 또는 이메일 승인일 경우에도 특정 정보가 없으면 자동으로 해당 정보 수정페이지로 이동 

안녕하세요? 혹시 어떤 경우를 이야기하시는건지 좀 더 구체적인 상황예를 들어주실 수 있을까요?

**Comment by doortts** [comment]
오래된 이슈로 추가적인 followup이 없어 우선 이슈 닫음 처리합니다
