### ISSUE TITLE
[문의] 프로젝트 이관 시 승인 메일 관련

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#195]
![image](https://cloud.githubusercontent.com/assets/6817393/24350042/c5c4c99e-131b-11e7-897b-b3313ac24d8a.png)

Yona 서버에 설정된 SMTP 계정이 support 입니다.
위 사진과 같이 프로젝트 이관 승인 메일 전송 시 보낸사람과 받는 사람이 같은데도
프로젝트 멤버에게는 메일이 전송이 됩니다.

뭐 여기까지는 크게 문제는 아닌데 support 계정에도 메일이 동시에 전송되고 있습니다.
혹시 이게 에러인지 아니면 의도된 것인지 궁금합니다!

Mailer에 설정된 계정으로는 보낼 필요가 없을 거 같아서요ㅎㅎ

**Comment by doortts** [comment]
현재 이관 메일만 그러신가요?

**Comment by berryzed** [comment]
@doortts 네! 애초에 Mailer 설정을 안하고 이메일 보내는 설정도 false로 해놔서 안쓰고 있다가
이관에는 무조건 이메일 수락이 필요하다고 해서 메일 설정을 했고 다른 부분에서는 테스트를 못했습니다!

**Comment by berryzed** [comment]
추가로 관리자 로그인 후 메일발송 테스트에서는 정상적으로 노출되고 있고
대량 메일 발송에서 프로젝트 검색 후 추가된걸 확인한 뒤 메일 쓰기버튼을 누르면 로딩되는거 같다가 더 진행되지 않습니다.

### 콘솔 화면
![image](https://cloud.githubusercontent.com/assets/6817393/24596983/e567a9bc-187d-11e7-9412-d3cd3a96f607.png)

**Comment by doortts** [comment]
사이트 관리자의 기능중 하나인 대량 메일 발송에서 문제가 발생한다는 이야기이신거죠?

**Comment by berryzed** [comment]
@doortts 본문은 개인계정이고 코멘트에 남긴건 관리자계정입니다!

**Comment by doortts** [comment]
@berryzed 안녕하세요? 이 부분은 어떻게 해결되셨어요?
