### ISSUE TITLE
댓글 수정 시 파일 업로드가 안됩니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#196]
이슈 댓글을 저장 후 첨부할 파일이 누락되어 수정하려고 하니
댓글 수정 시에는 파일 업로드 기능이 지원되지 않네요.
기능을 제공하지 않는 이유가 있으신건지.. 일단 지난 이슈에서는 찾지 못해 글 남깁니다.

**Comment by sjstyle** [comment]
사....실 아주 오래전부터 지원 되었어야 했지만 지원되지 않았었습니다 ㅠ.ㅠ..........

**Comment by doortts** [comment]
Yona v1.11.0 부터 댓글 수정시 파일 추가/삭제를 지원하고 있습니다.
