### ISSUE TITLE
[건의] 라벨로 이슈 검색 시 AND 조건으로 검색되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#197]
안녕하세요.

라벨로 이슈 검색 시 두 개 이상의 이슈를 입력하면 OR 로 검색이 되는데
AND 조건으로 검색이 되도록 수정되었으면 합니다.

한 이슈에 여러 분류의 이슈를 N개 지정했을 때 AND 조건으로 검색이 되면
더 빨리 원하는 결과를 찾을 수 있을 것 같습니다.

**Comment by doortts** [comment]
v1.9에서 and 조건으로 변경되었습니다.
