### ISSUE TITLE
[건의] 프로젝트 목록 관련.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#199]
지금은 프로젝트 목록을 누르면 **공개 프로젝트 목록**이 보이는데, 
그룹별 프로젝트 목록을 볼수 있는 메뉴도 있으면 좋을것 같습니다.

프로젝트목록을 누르면 그룹리스트가 콤보박스로 보인다던지요...

**Comment by sjstyle** [comment]
혹시 이런것을 찾으시는 건가요? 프로젝트 화면에서 소유자 이름을 누르면 이동할 수 있습니다.
https://repo.yona.io/organizations/yona-projects

**Comment by junho103** [comment]
네 남겨주신 링크처럼 보이는게 맞는데요... 

**프로젝트 목록**을 누르면 **공개 프로젝트 목록**이 나오는데
**프로젝트 목록**을 눌렀을때 제가 볼수있는 프로젝트를 모두 보고싶어서 남겼습니다....

로그인한 입장에서는 자기가 볼수있는 프로젝트목록이 다 나오는게 맞지 않나 생각해서요 ^^;;

**Comment by sjstyle** [comment]
이 부분은 사내에서 사용하는 버전과 달라서 정확히 답을 드리긴 어렵지만 제 추측으로는,

https://github.com/yona-projects/yona/commit/79714a88bcd672ef5462333788895e70bb8221b1#diff-290be9a340738a38c06f3011c333f951R1046
의 영향일 것 같습니다.

일단, 저 부분이 있기전에 문제는 사용자 권한을 확인해서 볼 수 없는 프로젝트를 목록에서 지움으로 인해서 #36 과 관련된 문제가 있었습니다.

**Comment by doortts** [comment]
우선 @sjstyle 님이 설명해주신 내용이 맞습니다.
v1.4부터 프로젝트 목록보는 기능이 기존에는 '자신이 접근 가능한 프로젝트 목록 + 공개 프로젝트 목록'을 보여주던 구조에서 '공개프로젝트 목록'을 보여주는 식으로 변경했습니다.

이유는 몇 가지가 있지만 가장큰이유는 프로젝트 리스트 페이지 숫자를 맞추기 위해서였습니다.
자신의 프로젝트 목록은 사용자 메뉴에서 확인하시는 것으로 대체가 가능해서 이렇게 변경했습니다.

**Comment by junho103** [comment]
그렇군요~ @sjstyle @doortts 두분 감사합니다. ^^
