### ISSUE TITLE
MariaDB Connector 라이브러리 파일이 없네요

### ISSUE THREAD

**Issue by ZerglingGo** [yona-projects/yona#2]
yona.zip 파일을 받아서 application.conf 에서 드라이버 변경후 서버를 실행했는데 드라이버 관련 오류가 발생하여 확인해보니 lib폴더에 MariaDB Connector가 없습니다..

커넥터 다운받아서 집어넣고 bin/yobi에 라이브러리 추가시켜 해결했습니다.

**Comment by doortts** [comment]
알려주셔서 고맙습니다. 혹시 Yobi에서 upgrade 하셨어요? 아니면 신규 설치세요?

**Comment by ZerglingGo** [comment]
Yobi에서 올라왔습니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.0.0-beta 에는 해당 부분 업데이트 해 놓았습니다.
