### ISSUE TITLE
yona.home 설정이 정상동작하지 않습니다.

### ISSUE THREAD

**Issue by brainagenet** [yona-projects/yona#20]
yona-1.0.0 사용자입니다.

data directory를 별도로 하기 위해 문서에 기술되어 있는 데로 YONA_HOME을 설정하였습니다. 그런데 정상동작하지 않았습니다. 그래서 yona shell script를 확인해 보니 YOBI_HOME과 yobi.home으로 되어 있어서 그걸로 설정하니 정상적으로 동작합니다.

**Comment by doortts** [comment]
안녕하세요? yona shell script라면 bin/yona 파일을 말씀하시는 거죠?

**Comment by brainagenet** [comment]
네 맞습니다. 그런데 version이 yona h2 version 입니다.
제가 버전 확인을 제대로 못했습니다.

**Comment by doortts** [comment]
네 h2 버전의 경우 build.sbt 파일이 YONA로 정확히 반영이 안된것 같습니다. 
밤에 확인해서 H2 버전은 업데이트 해 놓도록 하겠습니다.

**Comment by doortts** [comment]
YONA_HOME 환경 변수를 인식하도록 h2 버전의 bin 배포파일 업데이트 하였습니다.
https://github.com/yona-projects/yona/releases/tag/v1.0.0

원래대로라면 패치버전을 올려야 하는데 (v1.0.1로)
그냥 동일한 버전으로 배포합니다.

**Comment by brainagenet** [comment]
네 확인해 보도록 하겠습니다.
수고하셨습니다.

**Comment by doortts** [comment]
이슈가 있으면 다시 열어주세요! : )
