### ISSUE TITLE
프로젝트목록이 출력되지 않음. 

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#200]
안녕하세요. H2 버전에서 프로젝트목록이 출력되지 않습니다.

admin 계정에는 문제 없이 출력되는데, 그 외 계정에서는 "페이지를 찾을 수 없습니다" 가 발생하면서 출력되지 않습니다.
또한 왼쪽 상단에 홈버튼이 사라집니다.

![image](https://cloud.githubusercontent.com/assets/12702163/24842888/2644f188-1dd8-11e7-863c-fb7393b2acc7.png)

확인 부탁 드립니다.
감사합니다.

**Comment by yongseokleecom** [comment]
좀 더 확인해보니까 공개프로젝트가 없어서 발생한 문제였습니다.
프로젝트목록에서 권한이 있는 (멤버참여 또는 그룹참여상태) 목록은 출력이 필요한데
방법이 있을까요?

**Comment by sjstyle** [comment]
음 이것도 #199 번과 같은 이슈인데요... 단시간에 해결은 쉽지 않을 것 같아보입니다..;;;;;;;

**Comment by doortts** [comment]
@yongseokleecom 사용자 메뉴로는 부족하신가요?

![image](https://cloud.githubusercontent.com/assets/520523/24860222/81f7b28a-1e2e-11e7-930a-14fae63521bf.png)

**Comment by yongseokleecom** [comment]
오늘 사내 요나를 1.2 >  1.4.1 업그레이드 했는데
"프로젝트 목록" 이 보이지 않는다는 문의를 많이 받았습니다.

그동안 운영방식이 유사프로젝트 그룹을 생성하여 그룹멤버로 추가하고
프로젝트 멤버는 별도로 추가하지 않았습니다.
따라서 현재 조건으로는 사용자가 프로젝트 목록을 보지 못하는 문제가 발생했네요.
(물론 그룹 클릭 후 볼 수 있습니다.)

**Comment by doortts** [comment]
@yongseokleecom 자세히 설명해 주셔서 고맙습니다. 보완이 필요할것 같다는 생각이 들었습니다.

우선 불편하시다면 application.conf 에 아래처럼 설정을 지정해 보시겠어요?
```
# Display private repositories in the list
application.displayPrivateRepositories = true
```
모든 프로젝트 목록이 보이는 옵션입니다. 
다만 이 경우 프로젝트 private 프로젝트도 존재가 공개되는 사이드 이펙트가 있습니다만 무관하시다면 요.

**Comment by yongseokleecom** [comment]
@doortts 
안그래도 해당옵션을 사용해봤는데, 공개가되면 안되는 목록이라 다시 돌렸습니다 ^^

**Comment by doortts** [comment]
@yongseokleecom 페이지를 찾을 수 없다는 문구는 v1.5에서 오해의 소지가 없도록 수정했습니다. 
다만 공개 프로젝트 목록을 예전처럼 자신이 접근 가능한 모든 프로젝트가 보이도록 변경하는 부분은 여러가지로 따져보았을 때 우선 당분간은 현재처럼 유지하려고 합니다. 
다소 불편하실순 있겠지만 사용자 메뉴의 '즐겨찾기' 기능과 최근 프로젝트 목록, 그룹 탭, 알림, 마이페이지(프로필 화면) 등을 이용해주세요.
