### ISSUE TITLE
[문의] Http로 로그인 안됨.

### ISSUE THREAD

**Issue by oppop123** [yona-projects/yona#201]
안녕하세요. 웹으로 Git을 운영하기위해 Yoan를 적용해보고자 합니다.

Yona 웹에서 프로젝트를 생성하였고,  생성한 저장소의 주소를 복사해서 로컬에 Git Clone는 정상적으로 수행됩니다.

1) 이 후 관리하고자 하는 소스들을 Git Clone으로 생성
2) 관리한 소스파일을 Git Clone 디렉토리로 복사하여 Add
3) 커밋
4) Push <-- 여기서 
Git Credential Manager for Windows
Enter your credentials for http://192.168.10.151:9000/

창이 떠서 Yoan에서 생성한 아이디와 비밀번호를 입력하였는데, 
git.exe push --all --progress "origin"
remote: Invalid username or password
와 같은 에러가 뜨면서 Push가 진행되지 않습니다.

(Git Client는 TortoiseGit을 사용하고 있습니다)

**Comment by doortts** [comment]
우측 사용자 메뉴 사용자 설정을 눌러 나오는
![image](https://cloud.githubusercontent.com/assets/520523/24864067/0b5ee020-1e3e-11e7-8b33-becde1460245.png)

사용자 설정화면에서 보이는 id를 입력하셨나요?
![image](https://cloud.githubusercontent.com/assets/520523/24864037/fe482856-1e3d-11e7-9afd-f41275765ba6.png)

웹에서 로그인은 정상적으로 되는지 로그아웃 후 다시 해보시겠어요?

**Comment by oppop123** [comment]
네 웹에서 정상적으로 로그인되고 신규 계정도 생성해서 로그인되는지 확인하였습니다.

**Comment by doortts** [comment]
@oppop123 한 번 다른 도구로도 해봐주실 수 있을까요?
Source Tree 라는 무료 클라이언트 입니다. https://www.sourcetreeapp.com/

**Comment by dinobei** [comment]
저도 Yona, SourceTree로 git 연동하는데 `invalid username or password` 메시지가 뜨면서 안되는 문제가 있었습니다.

최초 가입시 소셜 로그인을 통해 가입 뒤 바로 git 푸시를 시도해보면, 위의 메시지가 발생하더라구요.
실제로 yona에서 id/pw로 로그인이 안될 때 이런 문제가 발생하는듯 합니다.

`사용자설정 - 비밀번호 설정` 으로 가셔서 **비밀번호 재 설정** 버튼을 클릭 하시고 메일 인증을 통해 패스워드를 변경하시면 이후 메일주소가 아닌 아이디로도 로그인이 가능합니다. 이때부터 git 연동이 제대로 동작합니다.

**Comment by doortts** [comment]
@oppop123 
이 이슈는 닫음처리합니다. 문제가 여전히 발생한다면 다시 열어주세요.
