### ISSUE TITLE
can not change smtp.port

### ISSUE THREAD

**Issue by buka-a4** [yona-projects/yona#202]
@outsideris hi, I can not change smtp port:
smtp.port를  465 말고 다른 포트를 주고 싶지만 application.conf 파일에 아무리 써도  default으로 465로 계속 보내요. 코드에 어든가 465라고 썼나요, 아니면 제가 config을 잘 못 하고 있나요?

**Comment by outsideris** [comment]
I can't find anywhere application use `smtp.port` from the config.
I guess that yona don't use `smtp.port` from the config in [here](https://github.com/yona-projects/yona/blob/63389190a6f1392331083dbaca9ffbdfe8dc7c95/app/controllers/SiteApp.java#L92). 
How do you think? @doortts

**Comment by doortts** [comment]
@outsideris 
Fortunatly, most of Yona's mail features depend on [play-2-mailplugin](https://github.com/schleichardt/play-modules/tree/master/mail) which I didn't participate.

I think it will take some more time to investigate...

**Comment by doortts** [comment]
Also, you can see it's dependency declaration at https://github.com/yona-projects/yona/blob/master/build.sbt#L46

**Comment by doortts** [comment]
@buka-a4 Could you let us know your smtp settings in application.conf file, except password.

**Comment by buka-a4** [comment]
@doortts  Here it is.

# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gamil smtp
smtp.host = 192.168.1.59
smtp.port = 25
smtp.ssl = true
smtp.user = "backoffice@golomtbank.local"
# Be careful!!! Not to leak password
smtp.password = ***
smtp.domain = "backoffice@golomtbank.com"
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

**Comment by buka-a4** [comment]
@doortts LDAP config또 하고 싶지만 잘 안되고 있어요 :)
우리 설정은:
LDAP_HOST=192.168.205.19
LDAP_PORT=389
LDAP_SSL_PORT=636
LDAP_DOMAIN=lynctest.local
LDAP_DC1=lynctest
LDAP_DC2=local
LDAP_ADMIN=beck
LDAP_PASS=***

#Yona에 설정한 부분은:

# LDAP Login Support
# ~~~~~~~~~~~~~~~~~
#
application.use.ldap.login.supoort = true
ldap {
    host = 192.168.205.19
    # default: ldap.port=389, ldaps.port=636
    port = 389
    # protocol: ldap or ldaps. If you want to use SSL/TLS, use 'ldaps'
    protocol = "ldap"
    baseDN = "ou=lynctest.local,dc=lynctest,dc=local"
    # If your ldap service's distinguishedName is 'CN=username,OU=user,DC=abc,DC=com', postfix is 'OU=xxx,DC=abc,DC=com'
    distinguishedNamePostfix = "OU=user,DC=abc,DC=com"
}

**Comment by doortts** [comment]
@buka-a4 
Thank you for letting us know your settings. 

### mail
If you are not going to use SSL, make ssl to false.

```
smtp.ssl = false
```
I think It may help to change smtp port.

### LDAP
According to the configuration you showed, it seems distinguishedNamePostfix isn't set properly.

If your baseDN is correct, distinguishedName may be something like this `CN=John Doe, OU=user, OU=lynctest.local,DC=lynctest,DC=local` in normally.

And except for CN,  rest corresponds to distinguishedNamePostfix. 

```
OU=user, OU=lynctest.local,DC=lynctest,DC=local
```

But first, you need to know the exact CN first. It is different from company to company.

**Comment by buka-a4** [comment]
@doortts  
Thank you.
I'll try it again and let you know :)

**Comment by buka-a4** [comment]
@doortts @outsideris  Thank you. It is working now :)

**Comment by doortts** [comment]
@buka-a4 That's good news.
Have a nice day~
