### ISSUE TITLE
이슈에 iframe 태그 삽입시 글을 로드 하지 못합니다.

### ISSUE THREAD

**Issue by SongPaul** [yona-projects/yona#203]
![cap 2017-04-13 09-34-25-335](https://cloud.githubusercontent.com/assets/8253615/24985027/874dcc10-202c-11e7-954c-d5800d352477.png)

code 를 사용하지않고 iframe 을 넣으면 위와 같이 글을 불러오지 못하는 현상이 발생합니다.

**Comment by doortts** [comment]
현재 본문에서 iframe 태그는 지원하지 않고 있습니다. 
그런데 올려주신 자바스크립트 오류는 iframe 사용시에만 발생하나요?

**Comment by SongPaul** [comment]
iframe 태그를 사용하려고 넣은 건아니고 일반텍스트로 넣으려고 한건데 저렇게 나오더라구요; ;

**Comment by doortts** [comment]
@SongPaul 혹시 어떠한 텍스트를 입력하셨는지 알 수 있을까요?

**Comment by SongPaul** [comment]
`<iframe src=”http//imp.mklaud.com/ad?id=영역번호&loc=URL 인코딩된 컨텐츠 페이지 URL” ….. >`

이런 텍스트 입니다.

**Comment by sjstyle** [comment]
해당 태그를 텍스트로 넣고 싶으실 경우는 코드로 감싸는 방법밖에 없을 것 같습니다.
yona에서는 markdown을 사용하는데, markdown은 기본적으로 HTML 코드를 허용하고 있습니다.

**Comment by SongPaul** [comment]
넵 그래서 코드로 감싸서 저장을 하였습니다만 문제는 실수로라도 iframe 태그를 코드로 감싸지 않고 글을 올릴 경우 글자체가 조회가 되지 않고 삭제 항목도 나타나지 않았습니다.

https://repo.yona.io/yona-projects/yona/issue/17

요나 프로젝트에 올려보았습니다.

**Comment by sjstyle** [comment]
@SongPaul 해당 문제는 iframe 문제라기 보다는 닫지 않은 태그가 들어왔을때 랜더링에 문제가 생기는 것으로 보입니다. 입력해주신 글을 웹으로 보았을때는 iframe 태그가 정상적으로 닫혀있지 않습니다. 

정상적인 iframe 문법은 다음과 같습니다. 

from) https://www.w3schools.com/tags/tag_iframe.asp
``` html
<iframe src="http://naver.com" style="width:500px;height:500px"></iframe>
```

이렇게 랜더링 할 경우 yona에서 해당 태그를 제거해서 아무것도 보이지 않도록 되어있습니다.

**Comment by SongPaul** [comment]
@sjstyle 태그가 삭제 되는거라면 이해 합니다 하지만 아래 링크처럼 글을 수정/ 삭제도 불가 하게 나옵니다.
https://repo.yona.io/yona-projects/yona/issue/17

**Comment by doortts** [comment]
@SongPaul @sjstyle iframe을 아예 본문에 code 블럭 이외에 태그로는 넣지 못하도록 막으면(sanitize) 어떨까요?

**Comment by sjstyle** [comment]
iframe태그를 허용하지 않기로 했다면 아예 입력을 하지못하게하는 방법도 좋을 것 같습니다. 그런데 제가 잠깐 살펴본 바로는 저 부분을 해결하려면 컨텐츠 영역을 일단 div로 싸두고 자바스크립트로 채워넣어야하지 않나는 생각이 드네요

**Comment by doortts** [comment]
@SongPaul repo.yona.io 에서 한 번 다시 테스트 해 봐 주시겠어요? 다양하게 해주시고 의견 주시면 더 좋구요! : )

**Comment by doortts** [comment]
v1.5 에서 해당 문제 해결되었습니다. 혹시 문제가 여전하거나 다시 발생하면 이슈 다시 열어주세요.
