### ISSUE TITLE
프로젝트 목록 조회시 404 에러가..

### ISSUE THREAD

**Issue by SongPaul** [yona-projects/yona#204]
==> access.log <==
127.0.0.1 - songc [13/Apr/2017:14:30:45 +0900] "GET /projects HTTP/1.1" 404 - "http://.../songc?daysAgo=7&selected=projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 3ms

/projects 조회시 404 에러가 떨어집니다.;

404 에러 페이지도 뭔가 YOBI 인것 같아요;;

![default](https://cloud.githubusercontent.com/assets/8253615/24991457/f3ac3d1e-2055-11e7-93a4-fe8c09fd3697.png)

**Comment by doortts** [comment]
@SongPaul 공개 프로젝트 목록이 하나도 없을 경우 저런 메시지가 나오는데요 
유사 이슈: https://github.com/yona-projects/yona/issues/200#issuecomment-292830070 

다음 버전에서는 메시지를 변경해야 겠습니다.
이 이슈는 #200 에서 이어가겠습니다.

**Comment by doortts** [comment]
@SongPaul 그리고 올려주신 로그에 사이트 URL이 포함되어 있어 본문을 제가 일부 수정했습니다. 공용망에서 사용하하실 예정이시면 social login 만으로 운영하시길 권합니다. 해당 내용은 이어지는 링크를 참고해 주세요.

[소셜 로그인 설정하기](https://github.com/yona-projects/yona/wiki/%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

**Comment by SongPaul** [comment]
네 감사합니다~ 공개 프로젝트가 없더라도 자기가 속한 프로젝트가 보이면 좋을 것 같내요~
