### ISSUE TITLE
프로젝트 생성 후 비어있는 코드 리포지터리 조회 시 문제점

### ISSUE THREAD

**Issue by rkttu** [yona-projects/yona#206]
프로젝트를 처음 생성한 후 비어있는 코드 리포지터리를 조회할 때, 브라우저 창에 포커스가 선택되어있으면 새로 고침이 멈추지 않고 계속 반복됩니다. 코드를 커밋해서 내용이 채워지면 문제가 해결됩니다. 새로 만든 리포지터리의 종류는 Subversion 이었습니다.

- 클라이언트 OS 버전: Windows 10 Creators Update
- 브라우저: Microsoft Edge 40.15063.0.0 / Microsoft EdgeHTML 15.15063

**Comment by doortts** [comment]
@rkttu 혹시 Git 프로젝트도 동일한지 확인 한 번 해주실수 있을까요?

**Comment by doortts** [comment]
@rkttu 확인 후 동일하게 발생한다면 다시 이슈를 열어주세요.
