### ISSUE TITLE
js code highlight 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#207]
```js
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//{$PIWIK_URL}/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', {$IDSITE}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```

이렇게 표시되어야 하는것 같은데. 요나에서는 줄바꿈이 사라집니다.

https://repo.yona.io/postimg/mdtest/post/2

**Comment by doortts** [comment]
@pokev25 안녕하세요? 이 부분은 조금 미묘한데요 버그 이기도 하고 아니기도 하고 그렇습니다.

우선 문제가 생기는 이유는
```
<!-- Piwik -->
```
이 부분 때문인데요, 이 부분이 js 구문이 아니라서 해석을 하지 못하고 highlight.js가 임의로 판단해서 xml 이라고 변경을 시켜 버리고 있습니다. 
해당 html 주석 태그를 제외하시면 아마 정상적으로 보이실겁니다.

그리고 이 부분은 Yona 버그로도 등록해 놓겠습니다.

**Comment by doortts** [comment]
@pokev25 이 부분 처리는 하일라이팅과 마크다운 렌더링 방식 변경을 통해 수정해 v1.5로 배포 될 예정입니다. 
우선 https://repo.yona.io/postimg/mdtest/post/2 에서 새로 고침을 해서 확인해주세요.

**Comment by pokev25** [comment]
네 확인 했습니다.
