### ISSUE TITLE
코드 -> 압축 파일로 내려받기 파일형식 관련.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#208]
안녕하세요. 

yona서버에 있는 코드를 내려받을때 파일형식(unix , windows)에 관한 문의 입니다.

윈도우 작업환경에서 작업중입니다.
>yona / git 설치: 윈도우서버
>client 작업환경: 윈도우

git 명령을 통해 windows형식의 파일을 서버에 올리고 내려받고 하는데는 문제가 없습니다. (윈도우 형식으로 올라가고, 윈도우형식으로 내려받아지고)

그런데 **코드 -> 압축 파일로 내려받기**로 내려받게 되면 해당 파일들이 모두 유닉스형식으로 변경되서 내려받아 집니다. 

압축파일로 받을때도 윈도우형식으로 받을수 있을까요??

**Comment by junho103** [comment]
저는 git 옵션을아래처럼 사용하고 있는데... 영향이 있을까요?
>  git config --global core.autocrlf true

**Comment by rtboss** [comment]
말씀하신 core.autocrlf 옵션과 관련이 있는것 같습니다.

autocrlf = false 로 설정하고 사용시 줄바꿈 crlf 정상 동작합니다.(압축파일 다운로드)
| yona 서버 windows 10

```autocrlf = true``` 이면 커밋을 할때 CRLF가 LF로 변경 되고,
체크아웃을 할때 LF -> CRLF로 다시변환 되는것으로 알고 있습니다.

```autocrlf = false``` 일때는 줄바꿈을 변환하지 않습니다.
CRLF 타입은 CRLF 타입으로 커밋되고,
LF 타입은 LF 타입으로 커밋이 됩니다.

간단히 CRLF 타입과 LF 타입 2개를 각각 추가하여 repo.yona.io에 test하였습니다.
( 커밋시 client 옵션은 autocrlf = false)
https://repo.yona.io/rtboss/download-zip-crlf-test
저는 개인적으로 autocrlf = false 을 사용하고 있습니다.(windows 10)

**Comment by junho103** [comment]
@rtboss 기존에 autocrlf = true 옵션으로 관리되고 있던 저장소에 대해서 fault로 옵션을 바꾸게 되면
영향이 없을까요?
음.. git에는 LF로 저장되었을꺼고 그상태에서 fault로 옵션을 바꾸게 되면 기존에 올라가있는 파일은 LF, 새로 올리는 파일은 CRLF로 되지 않을까 걱정이 되서요... 퇴근하고 한번 해봐야겠네요 ㅠㅠ

클라이언트 옵션을 바꾸셨다고 하셨는데요~ yona에 깔려있는 git은 true로 되어있는 상태인데 클라이언트에서 즉 작업자가 false로 변경해서 올린다고해도 서버설정을 따르는게 아닌지요?? @_@;;

**Comment by rtboss** [comment]
처음부터 autocrlf = false 가 아니면 말씀하신 문제는 있습니다.
기존프로젝트의 전체 파일을 LF -> CRLF 로 한번 변경해야 합니다.

**Comment by rtboss** [comment]
변경 작업은 아래 순서로 시도해 보세요.
1. autocrlf = true 옵션 상태에서 프로젝트를 클론 합니다.
   ( 파일 줄바꿈이 CRLF임)
2. autocrlf 옵션을 false로 변경합니다.
3. autocrlf = false 상태에서 클론을 한번더 합니다. (1번 프로젝트 보존)
   (파일 줄바꿈이 LF임)
4. ```1번```에서 클론한 프로젝트 전체 파일을 ```3번```에서 클론한 폴드에 덮어쓰기를 합니다.
  ( 전체 파일의 줄바꿈이 LF -> CRLF 로 변경됨)
5. 줄바꿈이 변경된 전체 파일을 커밋합니다.

위 방법으로 작업하면 LF -> CRLF 로 변경 가능합니다.
https://repo.yona.io/rtboss/lf-crlf-change 테스트 했습니다.
위 프로젝트에서 autocrlf-true 브랜치는 압축 파일로 다운로드시 줄바꿈이 LF 입니다.
master 브랜치는 LF->CRLF로 변경한 파일입니다.

git 서버는 줄바꿈 관련하여 따로 옵션이 없고,
온라인 커밋시 줄바꿈 이슈가 있는것 알고 있습니다.

**Comment by doortts** [comment]
@junho103 @rtboss 
유사한 상황이 발생하기 쉬운 부분이라 
편의를 돕기 위해 v1.5에는 코드브라우저에서 해당 파일의 줄바꿈(Ling Ending)형식을 볼 수 있는 부분이 추가될 예정입니다.  

repo.yona.io에는 반영해 놓았습니다. 아래 링크에서 미리 보실 수 있습니다.
![image](https://cloud.githubusercontent.com/assets/520523/25262302/1e6f2510-2692-11e7-902a-33c979e707c4.png)

https://repo.yona.io/rtboss/lf-crlf-change/code/master/file1.txt

**Comment by doortts** [comment]
Yona v1.5 부터 코드브라우저에 텍스트 파일의 줄바꿈 표시가 됩니다.
