### ISSUE TITLE
부모이슈 선택시 최근 100개가 넘은 이슈는 선택불가

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#209]
이제 자식이슈를 등록 잘 활용중입니다.

부모이슈를 선택하려고 보니 부모이슈가 등록되어있는데 목록에 나오질 않습니다.

원인을 파악하다보니 부모이슈 목록 최근 100개로 제한되어 있는듯합니다.
따라서 제가 선택하려는 이슈는 이미 최근 100개가 넘은 상태라 선택이 불가했습니다.

개선방안이 있는지 확인 부탁 드립니다.

**Comment by doortts** [comment]
기능 테스트때 최근 100개 이슈로 제한으로 걸었었는데요 이야기 주신대로 개선이 필요한것 같습니다.

**Comment by doortts** [comment]
@yongseokleecom 
참고로 이 만들때 이 문제에 막다른 골목(dead end)이 생기지 않도록 해 놓은 부분은 있습니다. 우선은 불편하시겠지만 다음과 같은 방식을 이용해 주세요.

이미 있는 이슈를 자식 이슈로 지정하는건 최근 100개 중에서 선택해야 하지만 기존 이슈(=부모이슈)를 선택한 다음에 새 이슈 작성을 누르시면 옵션에서 바로 자식 이슈 생성이 가능합니다. 이 부분도 암묵적 의도에 가까운거라 잘 알 수 있도록 개선은 해야 할 것 같습니다.

### [이슈 보기 화면에서 새 이슈를 누르면]
![image](https://cloud.githubusercontent.com/assets/520523/25320188/f2df3c46-28df-11e7-9055-8d7109c003e0.png)


### [해당 이슈를 부모 이슈로 하는 자식 이슈를 바로 만들 수 있음]
![image](https://cloud.githubusercontent.com/assets/520523/25320137/604fefba-28df-11e7-9b1b-c2a40da3f29c.png)

**Comment by yongseokleecom** [comment]
@doortts 
위 사용법 테스트하다가  새로운 버그를 발견했습니다.

**Comment by doortts** [comment]
@yongseokleecom 새로운 버그라는 건 #210 이야기셨던거죠?

**Comment by yongseokleecom** [comment]
@doortts 
넵 맞습니다~ 버그가 아니고 사용법 미숙이였내요
