### ISSUE TITLE
프로젝트 설정이 변경되지 않습니다.

### ISSUE THREAD

**Issue by brainagenet** [yona-projects/yona#21]
서버 두 대에 설치하여 확인해 보았습니다.

프로젝트 생성 후, 프로젝트 설정의 `메뉴 설정`의 항목 변경이 불가능 합니다.

확인 부탁드립니다.

**Comment by doortts** [comment]
네 코드 확인이 필요한 부분이라 밤에 확인해보고 이야기 드릴게요.

**Comment by brainagenet** [comment]
테스트 삼아 test project를 생성하고 바로 삭제하면 정상적으로 삭제가 됩니다. 그러나 project의 설정을 변경하고 하면 정상 동작하지 않네요. 이런 경우, Restart한 후, 삭제하면 정상적으로 삭제가 됩니다. 참고하시기 바랍니다.

**Comment by doortts** [comment]
제보 감사합니다. 해당문제는 이미 수정은 되었습니다. 다음 패치 릴리즈 때 같이 반영될 예정입니다.
