### ISSUE TITLE
이슈 내에서 '새 이슈 등록' 로 자식이슈 등록시 부모이슈풀림

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#210]
버전: 1.4.1 (H2)

이슈 내에서 '새 이슈 등록' 버튼을 눌러 자식이슈를 등록 할 수 있습니다.
본문내용을 기입했을때는 문제 없이 자식이슈로 추가되나
본문내용 없이 등록 했을때는 자식이슈로 등록되지 않고 새로운 이슈로 등록됩니다.

확인 부탁드립니다.

**Comment by doortts** [comment]
본문내용 없이...가 아니라 아마 옵션을 켜지 않고 작성하시면 그렇게 될거에요. 
제가 너무 매니악하게 만들었나봐요...

**Comment by yongseokleecom** [comment]
@doortts 
아 그렇내요. `이슈 옵션` 누르고 등록하니까 문제가 없내요.
