### ISSUE TITLE
v1.5.0 태그를 기준으로 master 브랜치를 next 브랜치로 reset 합니다

### ISSUE THREAD

**Issue by doortts** [yona-projects/yona#211]
기존 v1.4 릴리즈때 merge 실수로 인해 master와 next(=개발 브랜치)가 서로 역사(history)가 달라지는 분화(divergent)가 일어났습니다. 

곧 릴리즈 될 v1.5.0 태그를 기준으로 해당  실수를 바로잡습니다.

내용
---
- master 브랜치는 v1.5.0 tag를 기준으로 next 브랜치로 reset 합니다.
- master 브랜치를 사용하시던 분들은 새롭게 reset을 해주셔야 합니다.

사용 HEAD 브랜치가 master 브랜치 상태라면
```
git fetch origin next
git reset --hard FETCH_HEAD
```

기타
---
이후 Pull Request는 master 브랜치 기반으로 작업해서 next로 merge 요청해주세요

**Comment by hongwonjun** [comment]
@doortts 이 이슈는 이제 Close 해도 되지 않을까요?

**Comment by doortts** [comment]
@hongwonjun 네 커밋터시니까 이슈 내용들에 대해서는 쿼리없이 작업하셔도 충분할 것 같습니다. :)
