### ISSUE TITLE
[Yona 1.5.0] 코드 뷰에서 커밋 메시지에 HTML 태그가 출력됩니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#212]
![image](https://cloud.githubusercontent.com/assets/24894029/25419601/86cb9526-2a8e-11e7-8481-ac5686c1a47d.png)

상기 이미지와 같이 1.5.0 업데이트 후 코드 뷰에서 커밋 메시지에 HTML 태그가 출력됩니다.
repo.yona.io 에서도 같은 현상이 있습니다.

**Comment by doortts** [comment]
@hyunseogi 릴리즈 파일을 한 번 다시 내려받아보시겠어요?

**Comment by hyunseogi** [comment]
릴리즈 파일 다시 다운로드 받아 테스트 결과 이미지가 정상적으로 출력되는 것을 확인했습니다.
