### ISSUE TITLE
[Yona v1.5.0] 이슈 메일 발송 가능 여부

### ISSUE THREAD

**Issue by tonghyun** [yona-projects/yona#214]
application.conf의 Mailer 부분에 gmail 계정을 추가 설정하고 난 뒤
smtp.mock = false로 최종 변경하여 YONA를 재시작하여
admin 계정으로 접속하여 "메일 발송" 기능으로 메일 발송이 되는것을 확인하여
정상으로 gmail 계정이 추가 된 것을 확인하였습니다.

# Mailer
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = **아이디기입**
smtp.password = **암호기입**
smtp.domain = gmail.com
smtp.mock = false
smtp.archive.size = 5

그런데, 이렇게 SMTP 메일 계정을 추가하더라도 담당자를 지정하여 이슈 등록을 하더라도 해당 이슈 내용이 담당자에게 메일로 발송되지 않습니다. 지원 되는 기능으로 생각 했었는데요.
SMTP 계정 설정으로 메일 발송이 지원되는 기능이 어떤것 들이 있는지요?

**Comment by doortts** [comment]
지정하신 담당자가 해당 프로젝트를 지켜보지 않으면 담당자로 지정시에 메일이 가지 않습니다.
다만 @ 으로 지정하는 사용자 멘션의 경우에는 해당 프로젝트를 지켜보지 않더라도 멘션된 사용자에게 본문의 내용이 알림메일로 발송됩니다.

**Comment by tonghyun** [comment]
답변 감사드립니다. 지원 되는 기능은 맞는 거네요.

그런데, 담당자는 해당 프로젝트를 지켜보기 설정이 되어 있습니다.
이슈를 등록하면 담당자의 "내 이슈"에는 추가가 되는데, 메일로는 오지 않네요.
'@'로 멘션을 지정해도 메일 발송은 되지 않았습니다.
담당자의 메일 주소로 admin 계정으로 "메일 발송" 기능으로 메일을 보내면 담당자 메일로 수신은 됩니다.

어떤 설정 부분을 놓친 걸까요?

**Comment by doortts** [comment]
@tonghyun 추가로 이메일로 노티가 가는 항목은
사용자설정 - 알림설정 에서 보실 수 있습니다.
예) https://repo.yona.io/user/editform/notifications

![image](https://cloud.githubusercontent.com/assets/520523/25510943/bd763b00-2bfe-11e7-853d-d450b814d867.png)

**Comment by doortts** [comment]
@tonghyun 아! 그러시군요.
이런경우는 몇 가지 원인이 있는데요 확인 방법으로는
- 설치된 yona의 log 폴더에서 mail.log 를 보셔서 정상 발송되었는지 보기
- 수신자 메일함의 휴지통이나 스팸함에 없는지 보기
- gmail일 경우 보안설정 조정
   - 참고: https://github.com/yona-projects/yona/wiki/Yona-%EB%A9%94%EC%9D%BC%EC%84%9C%EB%B2%84-%EC%84%A4%EC%A0%95

로 확인을 진행해 보시면 좋을 것 같습니다.

**Comment by tonghyun** [comment]
사용자설정 - 알림설정 부분에서 해당 프로젝트에서는 모든 알림이 On으로 되어 있습니다.
 Yona v1.5.0의 H2 버전을 사용하고 있는데 H2 버전에서 나오는 문제 같지는 않는데요.

![sh](https://cloud.githubusercontent.com/assets/17894923/25511107/cb2425fe-2bff-11e7-807a-5992f0aa3a66.png)

**Comment by tonghyun** [comment]
말씀 하신 부분을 체크해 보았습니다.

- 설치된 yona의 log 폴더에서 mail.log 를 보셔서 정상 발송되었는지 보기
: mail.log에는 아무런 내용도 들어 있지 않습니다.
- 수신자 메일함의 휴지통이나 스팸함에 없는지 보기
: 휴지통, 스팸함에 없습니다.
- gmail일 경우 보안설정 조정
: 보안수준이 낮은 앱 허용 설정이 되어 있었지만 재설정을 해서 테스트 해 보았습니다.

여전히 되지 않았습니다.

그런데, YONA를 멈추고 나서 다시 시작시키고,
테스트로 이슈를 3개를 만들었는데, 그 중 1개가 메일로 수신이 되었습니다.
실제로 mail.log를 보니 그 이슈만 메일로 발송이 된 log가 있습니다.

> /yona-data/logs$ cat mail.log
> 2017-04-28 10:57:30,411 - [INFO] - from mail.out in application-akka.actor.default-dispatcher-3
"[...] test issue 2 (#13)" [EROUM project <...@gmail.com>, =?UTF-8?B?6rmA64+Z7ZiE?= <...@gmail.com>]
> /yona-data/logs$
>

결국, YONA에서 메일 발송이 안 되는 현상이 있는 것 같은데 뭔가 환경 설정을 잘못해서 운영상의 문제가 있는지는 조금 더 테스트를 해 보아야 할 것 같습니다.

**Comment by tonghyun** [comment]
테스트를 해 보니
특정 계정으로 자신을 담당자로 등록한 이슈에 대해서,
또는, 특정 계정으로 직접 작성한 이슈에 자신을 멘션을 등록하는 경우에 대해서는
메일로 발송이 되지 않는 것으로 보입니다.

그리고, "이슈"를 등록하더라도 바로 메일로 발송이 되지 않아서 헷갈린 부분이 있었습니다.
이 코멘트에 1, 3번은 자신이 등록한 이슈에 자신을 담당자 또는 멘션으로 지정한 것이었고,
2번째는 admin 계정으로 이슈를 지정하고, 다른 계정을 담당자로 지정한 경우였습니다.
그래서, 조금 시간이 지난 뒤에 2번째는 메일로 발송이 되었던 것 같습니다.

**Comment by doortts** [comment]
@tonghyun 네 확인해주셔서 고맙습니다. Yona가 기본적으로 자신이 쓴 글(즉, 스스로 내용을 확인한 내용)은 다시 자신에게 메일로 가지 않게 되어 있던 부분이라 그렇게 되었던것 같습니다.

**Comment by lucaryu** [comment]
구글 메일의 경우 2단계 인증으로 안되는거 같습니다.
앱 비밀번호 사용으로 정상 메일이 가는 것을 확인하였습니다.
메일이 가는 시간이 조금 오래 걸리는것 같습니다.

**Comment by seok-hee97** [comment]
> 메일이 가는 시간이 조금 오래 걸리는것 같습니다. 

 _Originally posted by @lucaryu in [#214](https://github.com/yona-projects/yona/issues/214#issuecomment-805593106)_

- conf/application.conf
```
# Notification
# ~~~~~~~~~~~~
# Check mails to send every this seconds.
application.notification.bymail.interval = 60s
# Sending a notification mail delays this seconds.
application.notification.bymail.delay = 180s
```
application.notification.bymail.interval : 메일 발송 작업을 확인하는 주기.
application.notification.bymail.delay    : 알림 메일 발송 지연 시간.
(불필요한 중복 알림을 줄이고 시스템 리소스를 효율적으로 관리하기 위한 설계)

application.conf 파일에 해당 메일 전송 딜레이 관련해서 설정하는 부분이 있습니다.
해당 부분의 숫자(초) 를 조절하시면 좀더 빠르게 전송됩니다
