### ISSUE TITLE
[의견] #165 이슈에 대한 해결방법

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#215]
#165 의 이슈를 보시면 저장소를 SVN으로 생성하고 C#으로 생성한 파일(*.cs, *.meta) 파일 커밋 시 오류가 발생합니다.
![image](https://cloud.githubusercontent.com/assets/6817393/25511003/27403dba-2bff-11e7-8a49-bb5de4c6d2c7.png)

http://ebanshi.cc/questions/825943/svn-no-element-found-error
위 링크를 통해 확인해본 결과 루트 디렉토리에 바로 커밋하지 말고 SVN 스타일인
[trunk branch tag] 형식으로 폴더를 생성한 뒤 원하는 폴더에 파일 이동 후 커밋하면 정상적으로 올라가는 것을 확인하였습니다.

![image](https://cloud.githubusercontent.com/assets/6817393/25511060/80c3c62c-2bff-11e7-95ae-716b731daf02.png)

아마도 이 부분이 제가 svn의 형태를 잘 알지 못해서 생긴 문제이긴하나 혹시 개발자님께서 가능하시다면
svn으로 저장소 생성 시 기본적으로 위 3개의 폴더를 같이 생성해주는 기능이 있으면 좋을거 같습니다!

좋은 연휴 보내세요~

**Comment by doortts** [comment]
@berryzed 자세히 알려주셔서 고맙습니다. 
안그래도 최근에 유사한 오류를 접한적이 있는데요 svn은 trunk, branch, tag 같은 기본 브랜치가 필수인건지 옵션인건지 확인이 필요할것 같습니다. 
SVN쪽은 사실상 기능적으로도 제한이 많고 대부분 git 쪽으로만 기능을 개발하는 추세라 다소 미흡한 부분은 너그럽게 양해부탁드릴게요.

**Comment by berryzed** [comment]
@doortts 맞습니다 ㅠㅠ프로젝트마다 PL마음대로라서..허허 수고하세요! 이건 닫을게요~

**Comment by doortts** [comment]
저도 SVN시절에 trunk, branch, tag 폴더 썼었는데요 이젠 기억도 가물해서 그게 SVN 컨벤션이었는지 어쨌는지 기억도 잘 안나네요. 혹시 이게 SVN 기본 컨벤션이면 추가해 놓는건 어려운 일은 아닐것 같아서요.
