### ISSUE TITLE
[Yona v1.5.0] 내 이슈에서 페이징이 정상동작하지 않습니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#216]
내 이슈 화면에서 페이징이 정상동작하지 않습니다.
페이지 이동을 해도 첫 페이지 목록만 계속 출력됩니다.
repo.yona.io 에서도 동일 문제 발생을 확인하였습니다.

![image](https://cloud.githubusercontent.com/assets/24894029/25512300/a05d9dc0-2c07-11e7-8304-65a97682e8a0.png)

**Comment by doortts** [comment]
@hyunseogi repo.yona.io 에서 다시 확인해주실 수 있을까요? 
패치버전을 내야 할 것 같네요.

**Comment by hyunseogi** [comment]
repo.yona.io 에서 내 이슈 목록 : 페이징 정상 동작 확인했습니다.

**Comment by doortts** [comment]
v1.5.1에서 해결되었습니다.
