### ISSUE TITLE
[문의] SVN 저장소 태그 관련 문제

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#217]
1. SVN 저장소 생성 후 루트 폴더에 프로젝트 폴더를 넣고 커밋을 했습니다.
2. #165 번 이슈처럼 파일이 정상적으로 올라가지 않아 #215 번 이슈처럼 해결합니다.
2-1. 이 과정 중에서 루트폴더에 있던 폴더들을 다 삭제합니다.
2-2. 루트폴더에 trunk폴더를 만들고 그 안에 프로젝트 폴더를 넣습니다.
3. 커밋을 하면 정상적으로 올라갑니다.
4. 커밋된 파일을 보기 위해 코드란을 확인합니다.
5. 2-1에서 삭제한 폴더들이 보입니다. SVN의 저장소 브라우저에서는 보이지 않은것들이요.
6. 주소창에 HEAD부분을 trunk로 바꾸면 커밋된 파일들이 정상적으로 보입니다.

**Comment by doortts** [comment]
@berryzed 혹시 가능하시다면 repo.yona.io 에서도 재현되는지 확인 한 번 해주실 수 있을까요?

**Comment by berryzed** [comment]
@doortts 네 방금 https://repo.yona.io/berryzed91/YonaTEST 여기에서 테스트 완료했습니다!
최초 trunk 폴더에 작업한 파일 넣고 커밋하고 다시 svn remove로 삭제한 뒤 test란 폴더를 만들어서 커밋했습니다.
그러면 코드란에 보면 trunk가 남아있고 파일목록은 보이지만 파일선택 시 확인이 불가능하고

주소창에 https://repo.yona.io/berryzed91/YonaTEST/code/HEAD/test/ 라고 입력해야지 정상적으로 보입니다.

**Comment by berryzed** [comment]
v1.5.1로 업그레이드한 후 정상적으로 접근이 되어서 닫도록 하겠습니다!
