### ISSUE TITLE
issue등록시 slack등의 연동 알림

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#22]
연동 서비스를 활용하도록 API를 구성하면 되지 않을까 싶습니다.

https://ifttt.com/recipes/180907-post-github-issues-in-slack-automatically

https://zapier.com/zapbook/zaps/396/stay-top-github-issues-slack/

ps. 개발 도움 문서나 방법이 있을까 해서 잠깐 찾아봤는데..잘 안보이네요.

**Comment by pokev25** [comment]
http://blog.remotty.com/blog/2014/01/30/github-hook-api-slack-sample/

webhook을  issue등록시에 사용 할 수 있도록 확장 하는 방법이 있네요

**Comment by hongwonjun** [comment]
https://api.slack.com/incoming-webhooks

참고할 URL 입니다.

**Comment by doortts** [comment]
@hongwonjun 님이 도와주셔서 v1.7 부터 해당 기능을 제공합니다.
문제 발생시 다시 이슈 열어주세요.
