### ISSUE TITLE
[질문] 관리자가 관리자 비밀번호를 잊었을 때는 어떻게 하나요?

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#221]
기억력이 안 좋은 관리자가 질문 드립니다.

:(

**Comment by haare** [comment]
> 비밀번호는 적어놓은 파일을 찾아서 알아냈습니다만 궁금합니다?!

**Comment by pokev25** [comment]
[관리자 암호를 잊어버렸을 때](https://github.com/yona-projects/yona/wiki/%EA%B4%80%EB%A6%AC%EC%9E%90-%EC%95%94%ED%98%B8%EB%A5%BC-%EC%9E%8A%EC%96%B4%EB%B2%84%EB%A0%B8%EC%9D%84-%EB%95%8C)

**Comment by haare** [comment]
감사합니다. @pokev25
