### ISSUE TITLE
자동 최신 버전 업데이트 확인을 끌 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#224]
안녕하세요?

아마 아래와 같은 경고가 주기적으로 발생하는 걸 보니, 최초 실행시와 종료 전에 업데이트를 자동 확인하는게 아닌가 합니다. 저희가 외부망과 연결이 안된 내부 네트워크에서 사용하기에 어차피 업데이트 체크는 불가능해서요. 옵션을 이용해서 자동 업데이트 확인을 끌 수 있으면 좋겠습니다. 감사합니다.

[warn] application - Failed to fetch the latest Yobi version to update
org.eclipse.jgit.api.errors.TransportException: https://github.com/yona-projects/yona:           cannot open git-upload-pack

**Comment by doortts** [comment]
안녕하세요? application.conf 에서 업데이트 체크 옵션을 false로 변경 후 재시작 해주세요
https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L236

**Comment by JeongJun-Lee** [comment]
네 말씀해주신데로 업데이트 확인을 껐습니다. 감사합니다.
