### ISSUE TITLE
삭제된 사용자를 영원히 지울 수는 없나요?

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#225]
제가 설치 후 시험해 보느라  제 id로 가입해 본 후 이것 저것 살펴보고, 관리자 계정에서 그 계정을 삭제시켰습니다. 그런데, 그래도 완전 계정 삭제가 되는 건 아니더라구요. 다시 먼저 그 id로 가입하려니까, 이미 있는 id라고 사용할 수 없다고 뜨네요. 관리자 계정으로 지운 id를 요나에서 다시 활용하고 싶습니다. 어떻게 하면 가능할까요?

**Comment by doortts** [comment]
@JeongJun-Lee 네 이런경우 아직 본격 운영이 시작되지 않았다면 DB를 지우고 다시 만드는 것이 제일 확실하고 실수 발생 가능성이 적습니다. 
그것이 부담된다면 db에 직접 접근해서 n4user 테이블에서 해당 유저를 삭제하는 방법도 있습니다.

**Comment by JeongJun-Lee** [comment]
네 n4user에서 삭제하였더니, 다시 재가입 잘되네요. 감사합니다^^

**Comment by luxury515** [comment]
n4user 에서 사용자를 지우니
기존 삭제된 사용자가 포함된 이슈를 액세스 할수가 없네요.

**Comment by doortts** [comment]
> n4user 에서 사용자를 지우니 기존 삭제된 사용자가 포함된 이슈를 액세스 할수가 없네요.

n4user 에서 사용자를  SQL 문을 이용해 강제로 지우면 동작을 예측하기가 어렵습니다. 
이런경우 지운 유저의 id 값(loginId가 아닌 id 컬럼 값)을 찾아서 새 유저로 하나 만드시고 어드민에서 해당 유저를 삭제해 보세요.
