### ISSUE TITLE
wiki문서 기여 방법 문의

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#227]
안녕하세요? wiki 문서에 기여하고 싶은데 어떤 방법으로 가능할지 문의 드립니다.

정확히는 이 문서(https://github.com/yona-projects/yona/wiki/%EB%B6%80%ED%8C%85-%EC%8B%9C-Yona-%EC%9E%90%EB%8F%99-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0%28%EB%A6%AC%EB%88%85%EC%8A%A4%29) 제가 사용하는 방법을 소개해 드리고 싶어서요. 어떻게 전달해 드리면 좋을지 가이드를 부탁드립니다.

감사합니다.

**Comment by doortts** [comment]
@JeongJun-Lee 님! 먼저 경험공유/기여 이야기주셔서 고맙습니다! 프로젝트 멤버초대드렸습니다. :D

**Comment by JeongJun-Lee** [comment]
@doortts 문서를 업데이트 했습니다. 한번 확인해 주시면 감사합니다.

**Comment by doortts** [comment]
@JeongJun-Lee 업데이트 고맙습니다. 쉘도 확인했습니다. 쉘에 쉘을 지정하는 것은 중요한데 빠져있었네요. 고맙습니다.

**Comment by JeongJun-Lee** [comment]
@doortts 별말씀을요. 도움이 될 수 있어 저도 감사합니다. 그 밖에 추가로 언급하고
 싶은 내용은 https://github.com/yona-projects/yona/blob/next/restart.sh 에 하나 더 수정이 필요한 부분이 있는데요. systemd로 프로세스를 살리고 죽이고 하기 때문에 구지 restart.sh 안에 kill 명령어가 필요는 없겠습니다. 그리고, 배포 버전에 restart.sh를 아예 포함해 배포한다면 사용자에게 더 편리하지 않을까 하기도 하구요.

**Comment by doortts** [comment]
systemd 의 호환성은 어떤가요? 제가 리눅스를 잘 알지 못해서요. 만약 pull request가 가능하시다면 아예 support scripts 에 linux 용 실행파일을 하나 추가해 주셔도 좋을 것 같습니다.

**Comment by doortts** [comment]
@JeongJun-Lee https://github.com/yona-projects/yona/tree/master/support-script 여기입니다.

**Comment by JeongJun-Lee** [comment]
systemd의 호환성은 문제없습니다. 이제 리눅스 서비스 관리 데몬에 현재는 다 systemd로 이미 바뀌었고, 심지어 라즈베리
파이도 systemd를 사용하고 있으니까요. 그런데, 어떤 실행 파일을 넣어 달라는 말씀이신지 systemd에 등록할 참고용 예제
스크립트를 하나 넣어놓으면 될런지요?

2017-06-01 13:15 GMT+05:00 Suwon Chae <notifications@github.com>:

**Comment by doortts** [comment]
@JeongJun-Lee 네 맞습니다. 사용하시는 restart 쉘 있으시면 support-script 에 좀 더 리눅스 유저 환경에 맞게 설정? 설치? 하는 방법이나 적용된 쉘을 넣어주시면 좋을 것 같아서요. : )

**Comment by JeongJun-Lee** [comment]
저도 쉘 스크립트를 잘 아는게 아니어서요?^^; 여기서 샘플로 제공된 것(restart.sh)을 약간 고친 수준(프로세스를 찾아 kill 하는 부분을 주석처리) 입니다. 그래서 더 잘 아시는 분이 해주시면 더 나을 것 같아요. 참고로 저는 개도국에서 봉사요원으로 일하고 있고, 이곳에 요나를 전파하고자 합니다^^ 그래서, 이곳 학생들과 함께 여기 현지어와 공용어로 번역 작업 중에 있습니다. 1차로 러시아어 번역이 완료되었고, 한번 더 전체적으로 리뷰 후 조금 더 완벽을 기한 후 pull request 요청하겠습니다. 감사합니다!

**Comment by doortts** [comment]
@JeongJun-Lee 사용하시는 내용 공유주셔서 고맙습니다. 정말 좋은일 하고 계세요. 멋지십니다! 혹시라도 도움 필요 부분이 생기시면 언제든 알려주세요. :D

**Comment by doortts** [comment]
@JeongJun-Lee 그리고 번역은 생각도 못했던 부분이었는데 왠지 제가 부끄럽네요. 저도 열심히 하겠습니다.
