### ISSUE TITLE
기존 80포트 웹서비스와 요나의 공존 가능 여부

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#229]
안녕하세요? 설치 문의 드립니다.

요나를 디폴트 9000 포트가 아닌 80 포트에서 사용하고 싶은데요. 문제는 기존에 아파치 웹서버 80포트에서 홈페이지를 서비스 중에 있습니다. 80 포트를 홈페이지용 웹서비스와 요나를 겸해서 쓸 수 있는지요? 그리고, 요나의 경우 yona.abc.com 처럼 서브 도메인으로 독립 도메인을 할당하려고 합니다. 제 생각엔 동일 포트로 요나를 실행시키는게 가능하지는 않을 것 같은데 그렇다면 아파치에서 포트 포워딩 하듯이 트래픽을 서브 도메인에 따라 다른 포트로 넘겨줘야 할 것 같은데요. 어떻게 설정을 잡아야 할까요? 경험 있으신 분 있으신가요?

감사합니다.

**Comment by sjstyle** [comment]
안녕하세요.
요나를 9000번 포트에 띄워두고, Apache httpd.conf 파일 수정을 통해 특정 도메인으로 들어올때는 yona로 reverse-proxy 하는 방법이 좋을 것 같습니다.

ex) 도메인이 `example.com`일 경우

```
www.example.com -> apache -> static page / dynamic web app (php, jsp, html ....)
yona.example.com -> apache -> yona
```

`httpd.conf` 를 다음을 참고해서 수정해보시겠어요?

```
NameVirtualHost *:80

<VirtualHost *:80>
    DocumentRoot /var/www/root  # 여기에 기존 파일 위치
    ServerName www.example.com 
</VirtualHost>

<VirtualHost *:80>
    ServerName yona.example.com
    ProxyPreserveHost on
    ProxyPass / http://localhost:9000/ nocanon
    ProxyPassReverse / http://localhost:9000/
    ProxyTimeout 3600
</VirtualHost>
```

참고하실만한 문서

* apache virtualhost : https://httpd.apache.org/docs/2.4/ko/vhosts/examples.html
* apache reverse proxy: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by JeongJun-Lee** [comment]
빠른 답변에 정말 감사드립니다^^ 이런 좋은 답변은 wiki에 포함되면 다른 분들께도 큰 도움이 될 것 같은데요?

**Comment by dinobei** [comment]
같은 서버상의 apache 웹서버와 yona의 공동운영을 reverse-proxy로 하는 방법 잘 참고하였습니다.

yona 서버와 apache 서버가 서로 다른곳에 있을 때 어떻게 하는지 궁금합니다.
위의 방법으로 하면 500 Internal Error가 나네요.. 

제 상황은, 같은 공간에 서로 다른 2명의 서버 관리자가 있어서 다른 서버를 운영하는데요,

예를들어,
 **80 포트**로 서비스하고있는 **메인 apache 서버는 `example.com` 도메인**을 연결해 두었고,
**8080 포트**로 서비스하고 있는 **서브 apache 서버는 `test.com` 도메인**을 연결해두었습니다.
`test.com` 도메인이 연결된 **서브 apache 서버**에서 yona를 운영중이라고 할 때,
사용자가 `yona.example.com`으로 접속시 `test.com:9000`으로 이동되도록하고싶습니다. (`example.com`이 대표 도메인입니다.)

```
<VirtualHost *:80>
    ServerName yona
    Redirect / http://ijoon.iptime.org:9000
</VirtualHost>
```

위와 같이 redirect를 써서 하면 연결은 되지만,  주소가 바뀌어버린다는 문제가 있죠..

DNS 서버쪽에서는 웹포워딩을 고정형으로 할 경우에는 클릭재킹문제로 정상동작을 안하더라구요.
결국 apache에서 처리 해줘야할걸로 생각이 드는데.. 방법이 없을까요?

**Comment by sjstyle** [comment]
@dinobei 
질문을 잘 이해를 못해서 그런것일수도 있지만, 이렇게 하면 되지 않나요??

```
<VirtualHost *:80>
    ServerName yona.example.com
    ProxyPreserveHost on
    ProxyPass / http://test.com:9000/ nocanon
    ProxyPassReverse / http://test.com:9000/
    ProxyTimeout 3600
</VirtualHost>
```

**Comment by dinobei** [comment]
@sjstyle 
이 방법으로 해봤는데, 500 Internal Error가 나더라구요.
localhost에서만 되는게 아니고 말씀하신 방식이 되는건가요?
혹 제가 잘못 테스트를 한건지...

한 컴퓨터에서 yona, apache를 동시 운영하는 상태에서 `ProxyPassReverse / localhost:9000/` 방식으로는 아직 환경구축이 안되어 테스트해보지 못했습니다.
환경 구축이 되어 여기 질문의 최초 답변대로 해봐서 동작하는지 확인하면 답이 나오겠네요..

**Comment by sjstyle** [comment]
음 이상하네요.. `ProxyPass`, `ProxyPassReverse`가 모두 설정되었다면, 잘 접속되어야 정상입니다.

`yona.example.com`의 아파치에서 `curl http://test.com:9000`(윈도우는 그냥 크롬같은 브라우저로 접속) 은 접속이 되나요?

**Comment by dinobei** [comment]
@sjstyle 
답변 감사합니다.
방금 yona, apache를 동시 운영하는 서버를 구축해서 테스트해봤습니다.
동일한 오류가 발생해서, apache2/error.log 파일의 로그를 참고해서 좀더 구글링을 해봤습니다.

결론적으로, mod_proxy_http 모듈이 enable 되어있지 않으면 이런 문제가 발생할 수 있다고 하네요.
말씀대로 `localhost:9000`, `test.com:9000` 둘다 모두 정상 작동합니다!

(https://stackoverflow.com/questions/23931987/apache-proxy-no-protocol-handler-was-valid)

**Comment by doortts** [comment]
@dinobei 
해당옵션(mod_proxy_http)을 통해 위 문제는 해결되었나요?

**Comment by dinobei** [comment]
네 해결되었습니다.
링크에 포함된 내용대로 a2enmod 명령어로 모듈을 추가하고 실행하니 잘 동작합니다.
