### ISSUE TITLE
SVN Remote 디렉토리 생성

### ISSUE THREAD

**Issue by jisoon** [yona-projects/yona#23]
저장소를 SVN 으로 사용을 하고 있는데 프로젝트 생성한 계정으로는 원격 저장소에 디렉토리를 생성 할 수가 없습니다.

admin 계정으로 하면 되는데 말이죠.

어떤 문제가 있을까요?

**Comment by doortts** [comment]
리눅스 환경이신가요? admin 계정으로 하면 된다는게 어떤 의미이신가요? admin은 yona의 admin 계정을 말씀하시는건지...

**Comment by jisoon** [comment]
네 맞습니다. yona 의 admin 계정으로 svn 인증을 하고 IDE 에서 원격 디렉토리를 생성 하면 이상없이 생성이 됩니다.

하지만 admin 이 아닌 프로젝트를 생성한 계정(예 jisoon) 으로 만들려고 하면 
IDE(eclipse, intellij) 에서 무한 로딩이 발생 합니다.

추가적으로 yona 는 리눅스 환경에서 동작을 하고 있구요 
yona 리눅스 계정을 따로 생성하여 동작 하고 있습니다.

글을 쓰다보니 혹 IDE 에 문제 인가? 라는 생각이 들긴 하네요. 
저도 svn client 로 테스트를 다시 해보겠습니다.

*** 참고로
GIT 은 잘됩니다.

**Comment by jisoon** [comment]
IDE(eclipse, intellij)  svn repositories 브라우져에서 직접 원격 디렉토리를 생성 하려면 무한 로딩에 빠지는것 같습니다.

command 명령과 TortoiesSVN 에서는 잘 동작 합니다.
정확한 원인은 모르겠구요.

결국 SVN 디렉토리 command 로 해야 될것 같습니다.
이글을 보시면 이슈 close 하셔도 됩니다.

**Comment by doortts** [comment]
@jisoon 님. 파일 커밋은 없이 원격으로 디렉터리를 만들때만인거죠?
SVNKit module에 해당 문제가 있는지, 그리고 업그레이드로 해결되는지 한번 시도해 보겠습니다.

**Comment by jisoon** [comment]
네 파일 커밋 없이 디렉터리 구조만 만들려고 했습니다.

회사에서 문서관리를 svn 으로 하는 시스템이라 
먼저 디렉토리 구조를 만들어야 하는 경우가 발생 하더라구요

**Comment by doortts** [comment]
@jisoon 님
v1.0.1 부터 svn 서버 라이브러리를 최신으로 업그레이드 시켰습니다.
v1.0.2 에서도 여전히 발생하는지 테스트 부탁드릴게요.

**Comment by jisoon** [comment]
@doortts 님
고생 하셨습니다. 이젠 정상적으로 생성이 됩니다. ^^

추가 적으로 한글 특수 문자도 이상없이 잘 생성 됩니다.
