### ISSUE TITLE
프로젝트가 제대로 fork 안되는 문제.

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#231]
![2017-06-16 10 25 16](https://user-images.githubusercontent.com/20082776/27208109-a301908e-527e-11e7-8071-41aabe87a2e4.png)

프로젝트를 fork해서 fork된 프로젝트로 들어갔지만 위와 같은 이미지를 보여주며 아무 기능도 사용할 수 없습니다.

프로젝트를 삭제하려고해도 해당 프로젝트 화면이 보여야 할 수 있으므로 해결책이 없는 상황입니다.

**Comment by doortts** [comment]
@E-nuri 사용하시는 OS와 Yona 버전이 어떻게 되세요? 그리고 repo.yona.io 에서도 유사한 방식으로 한 번 테스트 해주실 수 있을까요?

**Comment by E-nuri** [comment]
@doortts OS는 mac sierra 10.12.5이구요. yona 버전은 담당자분이 부재중이셔서 확인하지 못했습니다. 몇번 프로젝트를 fork 더 해봤지만 동일증상은 재현되질 않고있습니다.

저 현상이 나왔을 때 작업상황은 fork를 누른 뒤 아무런 반응이 없어서 새로고침을 했었습니다. 새로고침 한 뒤 목록을 보니 프로젝트 이름은 생성되어있었지만 정작 프로젝트 안으로 들어가면 위와 같은 화면만을 보여주고 있구요.

yona 버전은 담당자분 오시면 확인해서 다시 코멘트 작성하겠습니다.

**Comment by doortts** [comment]
@E-nuri 네 확인해주셔서 고맙습니다. 기존 프로젝트의 소스코드 사이즈가 큰경우 fork에 시간이 다소 걸릴수 있습니다. 중간에 refresh 하게되면 어떻게 될지 한 번 살펴봐야겠습니다. 그런 가정이 안되었을 수도 있겠네요.

**Comment by doortts** [comment]
@E-nuri 
코멘트 및 추가 이슈가 없어서 우선 닫음처리합니다. 필요시 다시 열어주세요.
