### ISSUE TITLE
다국어 적용을 추가했습니다. 메인 페이지 타이틀에 중앙 정렬이 깨지는거 같은데요?

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#233]
지역 언어를 적용했습니다. 첫 접속을 해보니 첨부 이미지처럼 메인 페이지 타이틀에 중앙 정렬이 안된 것 같이 보여서요.
![image](https://user-images.githubusercontent.com/11474775/27221589-8433daee-52a2-11e7-8968-009a0f90f082.png)

**Comment by doortts** [comment]
@JeongJun-Lee 사용하신 브라우저가 어떻게 되세요? 
그리고 repo.yona.io 에서도 한 번 확인해봐주시겠어요?

**Comment by JeongJun-Lee** [comment]
그러네요. repo.yona.io 도 동일하네요. 브라우저는 크롬을 사용 중입니다. 제 기억에 전에 중앙정렬이 되었던
 것으로 기억이 나서 이슈를 올린건데... 원래 크롬에서는 중앙정렬이 아닌지요? 참고로 마이크로소프트 엣지로 열어보니 에서는 중앙정렬이 잘되네요.

**Comment by doortts** [comment]
@JeongJun-Lee 
![image](https://user-images.githubusercontent.com/520523/27251811-0f566bfe-538a-11e7-875e-fb88391d3a99.png)
제 맥PC+ 크롬에서는 이렇게 보이는데요 흠.. 이것도 OS 종특인가... 

그런데 번역화면이 약간 다르네요?

**Comment by doortts** [comment]
이건 Window 10 + Chrome
![image](https://user-images.githubusercontent.com/520523/27251842-0040f5d4-538b-11e7-8671-529497bb7190.png)

**Comment by JeongJun-Lee** [comment]
저도 윈10+크롬 입니다. 디버그 스크린 캡쳐해드립니다.
![image](https://user-images.githubusercontent.com/11474775/27251938-1289cd9e-536b-11e7-90e8-5c299ebe6551.png)

**Comment by doortts** [comment]
@JeongJun-Lee 마침 정확히 딱 해당부분 찍으셨는데요 오른쪽의 검사기(Inspector) 스크롤을 조금 올리셔서 siteintro-cover 클래스의 적용상태 를 보여주시겠어요?
![image](https://user-images.githubusercontent.com/520523/27252155-e0fcc6ec-5391-11e7-92b4-8ada97f75e8a.png)

그리고 콘솔탭에 찍히고 있는 오류 메시지도 같이 부탁드릴게요.

**Comment by JeongJun-Lee** [comment]
![image](https://user-images.githubusercontent.com/11474775/27252744-5f731016-537f-11e7-9559-e240b7def97b.png)

**Comment by doortts** [comment]
@JeongJun-Lee 우와~ 이거 진짜 어렵네요. 아직까지는 전!혀! 모르겠어요. 

- 혹시 IE나 Firefox로도 테스트 한 번 해주실 수 있을까요?
- 크롬의 Incognito 모드로 repo.yona.io 를 한 번 접근해봐주시겠어요?
![image](https://user-images.githubusercontent.com/520523/27253283-73da767a-53ac-11e7-8d91-bb94d8f2cc49.png)
- 마지막으로, 혹시 제가 해당 서버 접근이 가능할까요?

**Comment by JeongJun-Lee** [comment]
크롬 incognito모드로 열어도 문제가 재현됩니다. IE로 했을 때 문제가 없습니다. FireFox는 제가 없어서 확인 못해봤습니다. 아마도 모든 PC에서 발생하는 일반적인 이슈는 아닌가 봅니다. 일단 그냥 넘어가도 되는 수준에 이슈일 수도 있겠네요.

**Comment by sjstyle** [comment]
@doortts 
이런 문제이거나 다른 크롬 확장프로그램과 충돌...(은 incognito 모드에서 거의 발생할 것 같진 않네요) 이 의심됩니다.
https://stackoverflow.com/questions/5734199/auto-margins-dont-center-image-in-page

@JeongJun-Lee 
혹시 크롬 업데이트는 자동으로 되게 해두고 계신가요?

**Comment by JeongJun-Lee** [comment]
@sjstyle 네 자동으로 되어있고, 방금도 최신 버전을 업데이트 한 후 접근해 보았으나, 증상은 동일합니다. 그런데, 이런 상황이 언급하신데로 크롬 자체 확장 프로그램과의 충돌로 인한 예외적인 버그라면 이 이슈는 닫아도 되지 않을까 싶네요.

**Comment by doortts** [comment]
@JeongJun-Lee 우선 이슈를 닫겠습니다. 필요하시면 다시 열어주세요.
