### ISSUE TITLE
[질문] 이메일 알림 기능

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#234]
안녕하세요.

이번에 이메일 알림기능을 사용하고 싶어 `notification.bymail.enabled = true`옵션을 활성화 하였습니다.
그러자마자 알림 메일이 폭탄처럼 쏟아졌습니다.

이 부분은 의도한 부분인지 알고 싶습니다.
위 옵션을 false로 했을 때 하단에 알림 메일 보내기에 체크해제 하지 않고 이슈를 등록해서 그런건지요?

수고하세요!

**Comment by berryzed** [comment]
추가적으로 이메일 설정에 넣었던 보내는 사람의 이메일로도 모든 알림메일이 도착하던데 이건 기능을 끄지는 못하는건가요?

**Comment by doortts** [comment]
@berryzed 
> 알림 메일이 폭탄처럼 쏟아졌습니다. 

그 동안 못 받은 메일들이 쏟아진 상황인거죠? 메일어택!!
폭탄을 의도한적은 없는데 그럴수 있겠다는 생각이 들었습니다. 
패치해야겠네요.

> 추가적으로 이메일 설정에 넣었던 보내는 사람의 이메일로도 모든 알림메일이 도착하던데 이건 기능을 끄지는 못하는건가요?

이메일 설정에는 개인 메일을 사용하지 않는걸 추천드립니다. 자칫 제일 위험한 보안 hole이 될 수 있습니다.
보통은 발신 후 메일을 삭제하는 옵션을 제공하는 계정을 사용하거나 발신전용 서비스를 사용하시기를 추천드립니다.

**Comment by berryzed** [comment]
@doortts 네 첫번째는 패치되면 다른 분들에게도 좋을거 같습니다ㅎㅎ
두번째는 발신전용 계정으로 변경하는 것으로 해결하였구요!
마지막으로
![image](https://user-images.githubusercontent.com/6817393/27425789-8ff75e1a-5774-11e7-992e-d95a527ee50a.png)
이런식으로 To와 From부분이 정상적으로 보이지 않는데
이메일 서버쪽 문제인지 아니면 요나 설정을 잘못한건지 확인 부탁드립니다!

**Comment by doortts** [comment]
@berryzed  
Mailbox Service 기능을 활성화 시켜 놓으셨나봅니다.

https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L173

https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L196

https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L199

메일박스 서비스는 Yona가 발신 기능만 하는 것이 아니라 메일을 수신해서 이슈, 댓글로도 등록해주는 기능입니다.
imap 기능을 사용해서 구현되었습니다.

**Comment by berryzed** [comment]
@doortts 흠 ㅠㅠ imap.user = false로 비활성화 되어있습니당...

**Comment by doortts** [comment]
우선 저 항목 이름을 바꿔보시겠어요?
그리고 

> To와 From부분이 정상적으로 보이지 않는데

그럼~ To 와 From이 어떻게  나오면 좋으시겠어요?

수신자 목록이 표시되도록 만들려면
https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L223
을 false로 해주세요

**Comment by doortts** [comment]
@berryzed 문제 발생시 다시 이슈 오픈해주세요.
