### ISSUE TITLE
SVN 프로젝트에서 소스가 표시 안되는 문제.

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#235]
현재 Centos 6.5를 사용 중입니다.

```
/etc/issue:CentOS release 6.5 (Final)
/etc/issue:Kernel \r on an \m
/etc/issue.net:CentOS release 6.5 (Final)
/etc/issue.net:Kernel \r on an \m

```

YONA1.0.4 를 사용하다가, 이번에 1.5.1 로 업그레이드를 했습니다.
설정 파일 및 repo , upgrade를 이관하고 재시작하니 큰 문제 없이 이관 된 것 같습니다.

그런데, 다른 쪽에서 문제가 발생하네요.
"코드" 메뉴에서 소스가 보이지 않는 문제가 발생합니다.

프로젝트로 이동해서, 코드 탭으로 이동했습니다. root 리스트는 나옵니다.
![image](https://user-images.githubusercontent.com/8743784/27718439-e894c0cc-5d86-11e7-8f09-9b472f71949d.png)

해당 폴더를 클릭하면 아래 화면 처럼 코드 화면으로 넘어가지 않고, 경로만 바뀐상태가 됩니다.
![image](https://user-images.githubusercontent.com/8743784/27718456-083350f6-5d87-11e7-9717-387ccb2e9f43.png)

강제로 폴더를 클릭해서 이동하면 아래 화면 처럼 빈 화면만 나옵니다.
![image](https://user-images.githubusercontent.com/8743784/27718465-1a43019c-5d87-11e7-9ebf-4b70f5c4bd07.png)

혹시나 해서 서버에 접속해서 로그를 보니까... Illegal SVN revision : HEAD라는 메시지가 있더군요.
![image](https://user-images.githubusercontent.com/8743784/27718484-318e1da0-5d87-11e7-97ec-87988cdf792c.png)

SVN 오류인가 해서 내부적으로 아래와 같이 입력을 해보았는데.. 파일 리스트는 나옵니다.
![image](https://user-images.githubusercontent.com/8743784/27718512-5f8993e2-5d87-11e7-92b3-59da9ca30e3d.png)

검토 부탁드립니다.

**Comment by doortts** [comment]
@neohind 안녕하세요?
혹시 https://repo.yona.io 에서도 동일한 현상으로 재현되는지 테스트 한 번 부탁드릴게요.

**Comment by neohind** [comment]
테스트용 프로젝트로 import를 통해서 업로드 하는데, 아래와 같은 오류가 나타나네요.

![image](https://user-images.githubusercontent.com/8743784/27775516-9e90f83e-5fdd-11e7-97ab-550d7d2b9714.png)

제가 가지고 있는 totorise SVN 클라이언트 문제일까요?
현재 사용중인 Totorise 버전은 아래와 같습니다.

```
TortoiseSVN 1.9.5, Build 27581 - 64 Bit , 2016/11/26 09:18:58
Subversion 1.9.5, -release
apr 1.5.2
apr-util 1.5.4
serf 1.3.9
OpenSSL 1.0.2j  26 Sep 2016
zlib 1.2.8
SQLite 3.14.1
```

혹시나 해서 제가 등록하려고 했던 폴더도 같이 첨부로 올려드립니다.

[WindowsFormsApplication1.zip](https://github.com/yona-projects/yona/files/1118259/WindowsFormsApplication1.zip)

**Comment by doortts** [comment]
@neohind 
디렉터리 최상위에 trunk, branch, tags 폴더가 없어서 발생하는 문제일 수 있습니다.

https://github.com/yona-projects/yona/issues/215

디렉터리 최 상단에 저 3개의 디렉터리를 만들어서 그 하위로 소스코드를 넣어 작업해도 동일한지 확인부탁드릴게요.
이게 svn의 강제화된 기본 컨벤션인건지는 잘 알지 못하여 이어서 수정을 하고 있지는 않습니다.

**Comment by neohind** [comment]
네 말씀하신 대로, trunk, branch, tags 폴더 문제로 업로드가 안되는 것은 해결했습니다.
세가지 폴더를 추가하니, 업로드는 정상적으로 수행됩니다.

하지만, 소스 브라우징(yona 내에서)을 시도해본 결과 제가 처음에 제시드린 Issue와 동일하게 소스가 보이지 않습니다.

trunk를 클릭하면 아무런 이동 처리 없이, 상위 폴더 이름만 변경되구요.
![image](https://user-images.githubusercontent.com/8743784/27776030-47c0424e-5fe2-11e7-8adb-82a5bbce3e72.png)

![image](https://user-images.githubusercontent.com/8743784/27776036-4fd63588-5fe2-11e7-89de-d2b54143a821.png)


다시 trunk를 클릭하면 빈 화면만 뜹니다.
![image](https://user-images.githubusercontent.com/8743784/27776048-5dbd9a24-5fe2-11e7-9295-ae4495eacf96.png)


감사합니다.

**Comment by doortts** [comment]
@neohind 
테스트 프로젝트 URL을 알려주시겠어요? 저도 확인해 보겠습니다.

**Comment by neohind** [comment]
URL이 누락되었군요... https://repo.yona.io/neohind/SVN_TEST 입니다.

계정 두개 추가 했습니다.

![image](https://user-images.githubusercontent.com/8743784/27778990-b632388c-5ffa-11e7-9411-698960c57a03.png)

**Comment by neohind** [comment]
지금 브라우저를 바꾸어서 확인하니, 되는군요..

현재 제가 사용중인 브라우저가 WaterFox 인데요..

![image](https://user-images.githubusercontent.com/8743784/27779016-f1428c92-5ffa-11e7-85c9-e03507082d62.png)

여기서는 제가 캡쳐한 화면처럼 되고,

Chrome에서는 밑으로 나열되네요..

스크립트 오류인지도 모르겠네요.

**Comment by doortts** [comment]
@neohind 
혹시 가능하시다면 firefox 도 동일한 현상이 발생하는지 확인 부탁드려도 될까요?

**Comment by doortts** [comment]
알려주신 URL에서 chrome에서도 스크립트 오류가 발생하는 걸 확인했습니다.

**Comment by neohind** [comment]
@doortts 
아, firefox 설치된 PC에서 확인해보도록 할께요. (현재 개발 PC에는 Waterfox 밖에 없어서요 -_-;; )

**Comment by sjstyle** [comment]
이 이슈를 확인해보니까 어느버전 이후로부터 폴더를 클릭했을때 `new-file-link` 라는 `새 파일` 버튼의 href를 참조하도록 변경되어있네요.

svn에는 새 파일 기능이 제공 되지 않아서 이것 때문에 문제가 발생하고 있는 것 같습니다;;;

수정까지는 배터리가 없어서 다음에 하는걸로..;;;;;;;;;;;;;;;;;;;;

**Comment by sjstyle** [comment]
@neohind 
해당 문제를 해결한 버전이 v1.7.0으로 배포되었습니다. 확인해보시고 문제가 있으시면 알려주세요~
