### ISSUE TITLE
최초 실행 시 mariadb 접속 불가 현상.

### ISSUE THREAD

**Issue by nazuna1** [yona-projects/yona#236]
#3  #89 #222  와 유사한 에러입니다. 

mariadb 정상 접속이 되고 SULinux 17의 Java OpenJDK 1.8.0_102 yona 1.5.1입니다.
Wiki의 Mariadb 설정 및 yona 설정 확인하고 따라했으나

최초 발생 에러는 application.conf가 mariadb를 설정되어 있고, mysql이 주석되어 있음에도 mysql 드라이버로 접속을 시도한 문제가 있었습니다.

> `[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
> [error] c.j.b.ConnectionHandle - Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = HY000
> Oops, cannot start the server.
> java.sql.SQLException: Connection is closed!
> 	at com.jolbox.bonecp.ConnectionHandle.checkClosed(ConnectionHandle.java:459)
> 	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1011)
> 	at play.api.db.evolutions.Evolutions$.prepare(Evolutions.scala:128)
> 	at play.api.db.evolutions.Evolutions$.updateLastProblem$1(Evolutions.scala:247)
> 	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:289)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:496)
> 	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
> 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
> 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
> 	at play.api.Play$.start(Play.scala:90)
> 	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
> 	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
> 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
> 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
> 	at scala.Option.map(Option.scala:145)
> 	at play.core.server.NettyServer$.main(NettyServer.scala:284)
> 	at play.core.server.NettyServer.main(NettyServer.scala)`

#89  #222 의 트래커 내용을 따라서 YONA_DATA export하고 아래와 같이 실행 시

> `_JAVA_OPTIONS="-Xmx2048m -Xms1024m -Dyona.data=$YONA_DATA -DapplyEvolutions.default=true -Dhttp.port=$PORT" bin/yona`

정상적으로 mariadb를 호출하지만 아래와 같은 메시지를 출력합니다.

> `[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES).Message:Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
> `

설정파일을 확인하면 비밀번호는 정상으로 들어가있고, mysql -uyona -p로 접속 확인해보아도 접속이 정상적으로 되고 있습니다.

**Comment by doortts** [comment]
안녕하세요? @nazuna1 님
우선 친절하게 로그등을 적어주셔서 상황을 빠르게 이해하는데에 많은 도움이 되었습니다.
고맙습니다.

YONA_DATA 환경변수가 잘못 설정된 경우는 아닌지 확인이 필요할 것 같습니다.


```
echo $YONA_DATA
```
했을때 어떻게 출력되나요?

참고로 아래 링크는 linux/unix 용 실행 쉘 스크립트 샘플입니다.
https://github.com/yona-projects/yona/blob/master/restart.sh

**Comment by nazuna1** [comment]
처음에는 /yona-data로 나오고 있었고, 혹시나 해서 /root/yona/yona-1.5.1/yona-data 로 디렉토리를 생성하여 추가해줘도 동일한 에러가 발생합니다.

또, 처음 이슈 제보시에는 MariaDB가 5.5임을 확인하여 DB 버전문제인줄 알고 10.2로 재설치하였으나 동일한 증상을 보이고 있습니다.

**Comment by doortts** [comment]
에러 메시지 자체는 id/pw 문제라고 보고 되는 상황인데요
db로 접속하셔서 내용이 어떻게 되는지 알려주시겠어요?
```
SELECT User, Host FROM mysql.user;
```

그리고 어느 유저로 yona를 실행하셨나요?
혹시 /root/yona/yona-1.5.1/yona-data 하위에 conf 와 logs 폴더와 파일이 정상적으로 잘 생성되어 있고 권한이 있는지 확인부탁드릴게요.

**Comment by nazuna1** [comment]
user Table 내용 : 

>  `+------+------------------+
> | user | host             |
> +------+------------------+
> | root | 127.0.0.1        |
> | root | ::1              |
> |      | git.kunsan.ac.kr |
> | root | git.kunsan.ac.kr |
> |      | localhost        |
> | root | localhost        |
> | yona | localhost        |
> +------+------------------+
> `

입니다.
그리고 처음 최초 1회 실행시에는 conf 폴더와 안의 내용물이 정상으로 생성되었는데, 어느 순간 conf 디렉토리가 사라지고 yona를 새로 압축 해제해도 다시는 conf가 생성되지 않고 있습니다.

**Comment by doortts** [comment]
@nazuna1 
네 확인감사합니다.
유저 생성도 정상인것 같습니다.
그리고 yona 유저도 정상적으로 실행된 것 같구요.

최초 1회 실행시에만 conf 폴더/파일이 하위로 생기는 것은 정상입니다.
이후는 YONA_DATA 로 지정된 디렉터리 하위의 conf 와 logs 등의 폴더를 사용하게 됩니다.

즉, $YONA_DATA/conf/application.conf 파일이 환경 설정이후 설정파일이 되는 셈입니다.

vi $YONA_DATA/conf/application.conf  열어서 다시 한번 yona 패스워가 어떻게 적혀 있는지 확인해 보시겠어요?

**Comment by nazuna1** [comment]
$YONA_DATA/conf/application.conf 의 파일이 입력해주었던 비밀번호가 아니라 password로 잘못 들어가 있음을 확인했습니다.
해당 mariadb 섹션에서 비밀번호를 다시 입력 후 bin/yona 실행하니 다시 또 mariadb 드라이버가 아닌 mysql 드라이버로 접속을 시도하고 있습니다.

> `[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
> [error] play - 
> Oops, cannot start the server.
> @74fcn8bpd: Database 'default' is in an inconsistent state!
> 	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
> 	at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
> 	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
> 	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
> 	at scala.Option.map(Option.scala:145)
> 	at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
> 	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
> 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
> 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
> 	at scala.collection.immutable.List.foreach(List.scala:318)
> 	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
> 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
> 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
> 	at play.api.Play$.start(Play.scala:90)
> 	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
> 	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
> 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
> 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
> 	at scala.Option.map(Option.scala:145)
> 	at play.core.server.NettyServer$.main(NettyServer.scala:284)
> 	at play.core.server.NettyServer.main(NettyServer.scala)
> `
>

**Comment by doortts** [comment]
@nazuna1 
음.. 이상하네요.. 배포판이나 소스코드내에서도 mysql driver 는 탑재되어 있지 않기 때문에 mysql driver 자체를 찾을 수 없다는 에러가 먼저 나야합니다. 혹시 클래스 패스나 혹은 lib등으로 mysql driver를 혹시 따로 추가하셨나요?

**Comment by nazuna1** [comment]
제가 본래 자바를 하던 사람이 아니라 무엇을 의미하는지는 알겠는데 어디서 확인하는지 모르겠어서 알려주실 수 있으신가요?
환경은 SULinux17 인스톨 후 gitlab과 yona 비교 위해서 gitlab을 먼저 설치해본 상태입니다.
제가 알기로는 gitlab은 자바를 사용하지 않는 것으로 알고 있습니다. (Ruby on Rails, Go, Node.js..)

**Comment by doortts** [comment]
@nazuna1 

아하, 그렇군요. 혹시 제가 서버에 잠시 접근해서 살펴봐도 괜찮을까요? 
만약 가능하시다면 제 프로필의 메일로 잠시 접근 가능한 정보를 보내주시면 제가 직접 살펴보고 이야기 드릴게요.

**Comment by nazuna1** [comment]
프로필의 navercorp.com 메일로 응신하였습니다.

주말에도 이렇게 도와주셔서 감사합니다.

**Comment by nazuna1** [comment]
응신메일 확인하였습니다. 감사합니다. 
위키에 있는 sql을 복사 붙여넣기 했는데 무언가 잘못 입력되었나 봅니다.
그런데 yona를 백그라운드로 실행하려면 어떻게 해야하나요? Ctrl +D 라던지 nohup 등이 안먹네요..

**Comment by doortts** [comment]
yona 디렉터리에 restart.sh 을 만들어 넣어놓았습니다. 
참고해주세요.
: )

**Comment by noxbix** [comment]
제가 지금 이 상황인거 같은데... 혹 어떤게 문제였는지 좀 알 수 있을까요??
나름 확인할 수 있는건 다 해본거 같은데..

**Comment by doortts** [comment]
@noxbix 사용하시는 자바 버전과 오류 메시지를 알 수 있을까요?

**Comment by noxbix** [comment]
@doortts 해결했습니다. mariaDB 10.3 이 깔려 있었는데.. 다 지우고 10.2를 다시 설치했고, 테이블도 다시 만드니 동작하네요.  CentOS 7 이고, Java 1,8 이었습니다. 감사합니다 :)
