### ISSUE TITLE
[자체해결 공유] SVN Malformed XML: no element found 문제 

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#237]
Yona를 이용한 프로젝트를 등록했을 때 매우 부정확한 조건 별로 SVN 에러가 발생합니다.
대략적인 환경은 아래와 같습니다.

1. Yona : 1.5.1
2. SVN : tortorise 1.9.5 

자주 발생하는 것이 아니라, 간혹 바이너리 파일을 올릴 때 발생하기도 하고, 재 Commit을 하면 문제없이 넘어가는 경우도 있습니다. 그러나 간혹 아래와 같은 메시지가 뜨면서 진행이 안되는 경우가 있습니다.
Malformed XML: no element found
파일을 다른 것으로 바꾸면 종종 Commit 되는 것을 확인했지만, 이것도 될 때가 있고, 안될 때가 있습니다. branch 및 tags 폴더를 만들면 되기도 하지만, 어쩔 때는 안됩니다.
도저히 제대로 재현이 안되서, 포기하는 마음으로 두었는데, 정작 중요한 소스가 Commit이 안되니 결국 다시 잡게 하는군요....

자체적으로 확인해본 결과 Tortorise 1.9.4 ~ 1.9.5 에서만 이 문제가 발생합니다. 

**아예 다운그레이드 해서 1.8.12 로 실행해보니, 큰 문제 없이 동작합니다.** 

제 개인적인 결론적으로는 SVN 클라이언트 문제로 판단됩니다.
( 더 다양한 케이스로 테스트하기에는 시간이 안되서요 -_-;;; )

**Comment by doortts** [comment]
@neohind 
관련 내용 공유해주셔서 고맙습니다. 유사한 문제를 겪을 분들에게 도움이 될 것 같습니다.

그런데 어차피 이렇게 된거 이번 기회에 Git world로 넘어오시죠!

**Comment by neohind** [comment]
Git 이 생각보다 쉽진 않네요;;;;; 팀원들도 은근 SVN으로 자꾸 가기도 하구요 ㅋ
일단 개인 프로젝트들을 이 쪽 GitHub에 등록하면서 하나씩 써보면서 Git 월드로 넘거가봐야겠죠 ^^

감사합니다.

**Comment by ssi10** [comment]
같은(?) 문제를 해결한 경험 공유합니다.

commit 시 파일이 정상적으로 없을 경우 404 를 리턴하는데 content-type이 xml인 경우와 plain text인 경우가 랜덤으로 출력되는게 문제더군요.

return code가 404 이면서 content-type이 xml인 경우 일부 클라이언트에서 Malformed XML 이라며 에러를 내는데 content-type을 text/plain;로 바꿔주시면 해결이 됩니다. ( 저희는 nginx에서 걸렀습니다. )

**Comment by cpascal** [comment]
원인은 @ssi10님께서 설명해주셨고..

검색해보았더니, 공식 SVNKit repo에는 수정되지 않았지만, SVNKit을 가져다 쓰는 몇몇 프로젝트들에서는 관련하여 수정한 상태네요. (svnkit_dav 모듈: Exception 났을 때, Content-Type 처리)

패치파일: https://bitbucket.org/sdorra/svnkit-mq/src/94f87942ddd950d106206b0439e1b546b184f128/wrong-content-type-on-error.patch

관련이슈: https://bitbucket.org/sdorra/scm-manager/issues/897/svn-changing-locked-file-response-contains

**Comment by misari03** [comment]
동일한 오류가 발생하는데요. "content-type을 text/plain;로 바꿔주시면 해결이 됩니다" 어느 부분에서 수정해 주어야 하나요?
현재 구성은 yona-1.6.1-h2 버전을 apache2 아래에서 proxy로 운영하고 있습니다.

**Comment by ezsimple** [comment]
ubuntu 16.04 & svn, version 1.9.3 & Yona 에서 발생하고 있습니다.
svnserver를 변경하면 발생하지 않네요... 
svn 1.8 로 다운그래이드 안되네요. (의존성 문제로 인해)

**Comment by misari03** [comment]
svnserver는 어떻게 변경하나요?
현재 svnserver를 별도로 설치하지 않았고, yona에 내장된 svnkit을 쓰고 있습니다.
어느 글타래에선가 yona는 svn, git이 내부에 통합되어 있다고 본 것 같습니다.

**Comment by doortts** [comment]
@ezsimple 님의 이야기는 다른 svnserver 를 쓰면 괜찮은데 지금 Yona SVN 기능을 쓰면 발생한다.. 의 의미인것으로 해석됩니다.  
@misari03  맞죠?

**Comment by misari03** [comment]
@doortts 님 말이 맞는 것 같습니다. 제가 좀 난독이라...

**Comment by ezsimple** [comment]
OS : Ubuntu 16.04 LTS

$ svn --version 
svn, version 1.9.3

$ svnserve --version
svnserve, version 1.9.3

를 사용하여 테스트 했습니다. 

[참고자료]
1. https://goo.gl/NDApxV
2. https://goo.gl/Gg9kCS

**Comment by cpascal** [comment]
Malformed XML 문제 해결한 코드 Pull Request 해두었습니다. #287 
테스트하실 분들은 [https://github.com/cpascal/yona/releases/download/v1.7.0-fix_svn_malformed/yona-1.7.0-fix_svn_malformed.zip](https://github.com/cpascal/yona/releases/download/v1.7.0-fix_svn_malformed/yona-1.7.0-fix_svn_malformed.zip) 로 부탁드리겠습니다.

**Comment by ezsimple** [comment]
OS : Ubuntu 16.04 LTS
svn, version 1.9.3 client로 테스트 했습니다.
예전 발생했던 상황과 동일하게 하고, 
svn checkin시, svn: Fix malformed xml error 발생하지 않는군요.
감사합니다.

**Comment by doortts** [comment]
@cpascal 님의 도움으로 v1.8 에서 해당 버그 수정되었습니다.
@ezsimple  @misari03 @neohind 님 확인해 보시고 이상있으시면 다시 열어주세요

**Comment by misari03** [comment]
@cpascal @doortts 감사합니다. 확인해 보겠습니다.
