### ISSUE TITLE
프로젝트 README에 파일 링크를 클릭하면 다운로드가 안되는 증상입니다.

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#239]
`README`에 문서파일을 여러개 올려두고 각각을 클릭해서 다운로드 받을 수 있도록 해서 사용중입니다.
게시판에서는 아무 문제없이 다운로드가 가능한데,
`홈`에 나오는 `README` 부분에서 클릭하면 아래와 같은 메시지가 발생합니다.

> master 브랜치가 없습니다. 기본 브랜치 설정을 확인해 주세요.

모든 링크가 전부 다운로드가 안되는 증상은 아닌것같네요. 
3개 파일로 테스트해보니, 1번 파일만 다운로드 가능하거나, 1,3번 파일이 다운로드 가능한 경우가 있습니다.

혹시나해서 프로젝트를 새로 만들어서 시도해도 동일한 증상이 발생하는거같아서 문의드립니다.

**Comment by dinobei** [comment]
혹시나 해서 yona 데모 사이트에서도 테스트해보니 동일 증상입니다. 

https://repo.yona.io/dinobei/README-파일첨부-테스트

**Comment by sjstyle** [comment]
https://github.com/yona-projects/yona/issues/124 이슈로 인해서 README.md 에 **상대경로로** 랜더링 되는 것은 **프로젝트 코드 저장소**에 있는 것만 가능하게 되었습니다.

절대 링크로 고쳐주시면 정상 작동 할 것으로 보입니다. (각 링크 앞에 http://repo.yona.io/ 삽입) 

첫번째 링크가 정상 동작하는 것은 버그로 보입니다.

* 관련 커밋 

https://github.com/yona-projects/yona/commit/2fc86459b39479a76237d650be9e42518b967c13#diff-face86450cd60bebf6644717cc144f81R232

**Comment by dinobei** [comment]
답변 감사합니다. 
절대경로로 수정해서 해결하였습니다.

그런데, 혹시 이 문제는 개선 계획이 없나요?
게시글 작성할 때, 브라우저로 드래그해서 파일 첨부시 자동으로 링크가 입력되는데, 각 사용자에게 일일이 사용방법을 알려주기는 부담이 될 것 같아요.

**Comment by doortts** [comment]
@dinobei 
README 가 딱 애매한 부분에 위치하고 있는 영역인것 같습니다.

왜냐하면 생성은 게시글처럼 하지만 실제로는 코드 커밋이 일어나서 파일로 만들어지는 존재이기 때문입니다.
코드인가 게시글인가!

어느쪽 기준이든 한쪽으로 놓고 내부 링크의 경로를 정하게되면 문제가 반드시 생길수밖에 없는 구조이죠.

흠..

@dinobei @sjstyle 
코드 메뉴가 없는 프로젝트일 경우 README의 내용은 그냥 게시글로 간주해서 파싱한다..는 룰은 어떠세요?
오히려 더 혼란스러우려나요?

**Comment by sjstyle** [comment]
네 저는 그런룰은 반대합니다. 차라리 files 경로만 상대경로로 치환하는게 좋을 것 같습니다.

**Comment by doortts** [comment]
@sjstyle 
그런식으로 작업하는것도 생각해 봤었는데 코드 저장소에서 root 바로 아래에 files 폴더를 만들어서 사용하는 프로젝트의 경우 문제가 생길것 같아서 생각을 접었습니다.

**Comment by sjstyle** [comment]
결국 git repo에 파일 체킹 로직 없이는 이 요구사항을 완벽히 해결할 수 없네요

**Comment by dinobei** [comment]
그렇군요.. 우선 이대로 사용해야겠네요.

**Comment by doortts** [comment]
@dinobei https://repo.yona.io/dinobei/README-파일첨부-테스트 다시 테스트 해보시겠어요?
관련 커밋: c71437db

**Comment by dinobei** [comment]
@doortts 수정본이 올라왔었네요.
코드 게시판을 사용하면 기존의 방식대로 동작하고 (**for 개발자**)
사용하지 않을 경우(**for 비개발자**) 에는 게시판처럼 간주하도록 처리되었군요.

업무에 더 사용하기 편해질듯합니다. 프로젝트 기본 설정에서  개발자 관련 게시판은 기본값을 false로 두고 사용하면 딱이겠네요.

테스트해보았더니 정상 동작합니다. 감사합니다!
