### ISSUE TITLE
비공개 프로젝트에서 이슈 작성 권한 문제.

### ISSUE THREAD

**Issue by wifiz** [yona-projects/yona#242]
비공개 프로젝트에서 참여자가 이슈 작성시에 권한이 없습니다. 라는 메시지가 나옵니다.
해당 참여자를 관리자로 변경하거나 공개로 전환시에는 발생되지 않고 비공개 프로젝트에서만 발생됩니다.

**Comment by doortts** [comment]
안녕하세요 @wifiz 님
[v1.6.1](https://github.com/yona-projects/yona/releases/tag/v1.6.1) 에서 수정했습니다. 확인부탁드려요.

**Comment by wifi-z** [comment]
@doortts 
1.6.1 버전으로 이슈 작성되는거 확인됐습니다.

감사합니다.
