### ISSUE TITLE
모바일 view에서 게시판 [새글쓰기] 버튼

### ISSUE THREAD

**Issue by playok** [yona-projects/yona#244]
모바일 스킨에서 게시판에 [새글쓰기] 버튼을 Touch 하기가 쉽지 않습니다.

2번째 첨부된 이미지 처럼 div가 버튼을 가리고 있습니다.

![image](https://user-images.githubusercontent.com/253674/28502997-1b174f14-7039-11e7-9f15-fa61bc5c7dc4.png)

![image](https://user-images.githubusercontent.com/253674/28503024-7aae2d12-7039-11e7-9006-12112fa9aa62.png)

**Comment by playok** [comment]
수고하셨습니다.^^

**Comment by doortts** [comment]
원인까지 정확히 찾아주셔서 빠르게 처리할 수 있었습니다. 고맙습니다!
