### ISSUE TITLE
서버 배포관련 문의합니다.

### ISSUE THREAD

**Issue by wndud5112** [yona-projects/yona#248]
안녕하세요.

배포관련 문의드립니다.
playframework 처음 접하는데,
Tomcat이나 jeus에 배포가 가능한가요? 
관련 정보를 찾아봐도 나오는 정보가 없던데, 
가능하다면 관련 정보를 알려주실 수 있을까요??

**Comment by doortts** [comment]
playframework 가 Tomcat 이나 jeus 역할을 하고 있습니다

데모서버로 운영중인 https://repo.yona.io 의 서버 구성사례를 보시면 조금 더 이해가 잘 되시지 않을까 싶습니다.
https://repo.yona.io/yona-projects/yona-help/post/5

**Comment by sjstyle** [comment]
오잉 제가 소환되었군요 ;;

한줄요약 : **Yona는 자체 서버 기능이 있어 tomcat, jeus 같은 것 없이도 동작이 가능합니다. 다른 서비스들과 같이 도메인과 포트를 공유해야한다면 reverse proxy를 고려해보세요.**

조금 더 부연설명을 드리자면 Yona의 기반이 되는 Play Framework는 내부적으로 Netty라는 통신 구현체를 사용하고 있습니다. 이 기반 위에 HTTP 서버를 직접 구현해서 사용하고 있기에, tomcat 이나 jeus 같은 web application server 없이도 동작이 가능합니다. 브라우저는 HTTP 스펙을 지킨 어떤 서버와도 통신할 수 있기에 사용자에게는 다른 서비스와 차이를 느낄 수 없습니다.

하지만, 하나의 서버에서 여러 웹 어플리케이션들을 실행시켜야 하고, 이 경우에 Yona를 WAS 밑에 두고 싶어하는 수요가 있을 수 있습니다. 이럴 경우 reverse proxy 기능을 고려해 볼 수 있습니다. 이 기능은 간단히 설명하자면, 지금 쓰고 계시는 apache, nginx, jeus 들을 맨 앞단에 두시고, 앞에 설정한 서버를 통해서 Yona에게 요청이 들어오게 되며, Yona의 응답을 다시 설정한 서버를 통해서 보낼 수 있게 됩니다.

**Comment by wndud5112** [comment]
답변 감사합니다~
reverse proxy로 방향을 잡고 진행해 보겠습니다.
