### ISSUE TITLE
1.6.1로 업데이트한 후 이슈페이지의 리스트가 보이지 않습니다.

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#249]
이번에 1.6.1로 업데이트를 진행했는데요..
아래 페이지처럼 이슈 페이지의 리스트가 보이지 않는 현상이 발견되었습니다.
![lorapi](https://user-images.githubusercontent.com/13401664/28600578-c98b6098-71ed-11e7-88a0-809ad3413263.JPG)

사용 환경 : 라즈베리파이3, 리눅스 커널 4.9.39 , MariaDB 사용중.

ps. 기타 다른 설정은 건드리지 않았구요..
1.6.0을 다시 실행하니.. DB에서 에러나버리네요.. 업데이트하면서 뭔가 바뀌었는지... >ㅇ<
백업 하지 않고 올렸었는데.... 다소 걱정이 되긴 하네요.

ps. 이슈 내용은 내이슈 란에서 내용확인이 가능한 것으로 보아, 그대로 있는 것 같습니다.

**Comment by minishanell** [comment]
텔레그램에서 개발자님의 도움을 받아 임시로 1.6.0으로 다운그레이드 했습니다.

1.6.0 폴더엣 yona 실행전, 명령어를 추가입력하시면 DB조정이 된다고 합니다.
참고로 적어두어봅니다.

_JAVA_OPTIONS="-DapplyDownEvolutions.default=true" bin/yona&

**Comment by junho103** [comment]
저도 같은 문제인데... "내 이슈" 클릭해서 들어가면 이슈목록이 보이네요..
![image](https://user-images.githubusercontent.com/12494817/28602189-a3c6f50c-71f7-11e7-8820-68e94b58674e.png)

프로젝트 -> 이슈 화면 들어가서 안보이는 문제 같습니다.

**Comment by doortts** [comment]
@minishanell @junho103 
제가 배포 파일을 빌드 할 때 실수를 한 것 같습니다.  새로 빌드해서 릴리즈 메뉴에 업로드 해 놓았습니다. 다시 내려받으시면 될거에요.

https://github.com/yona-projects/yona/releases/tag/v1.6.1

**Comment by junho103** [comment]
다시 반영하고, 정상적으로 이슈목록 보이는거 확인했습니다.
감사합니다.

@doortts
