### ISSUE TITLE
클론시 http 505에러가 납니다

### ISSUE THREAD

**Issue by comseong** [yona-projects/yona#253]
git clone http://bbb@yona.aaa.com/bbb/test
Cloning into 'test'...
error: RPC failed; HTTP 505 curl 22 The requested URL returnfed error: 505 HTTP Version Not Supported
atal: The remote end hung up unexpectedly

다음은 서버쪽 에러 로그입니다.
Aug 03 20:36:08 aaa.com restart_yona.sh[493]: [info] a./bbb/test/info/refs?service=git-upload-pack - 83.69.138.223 - bbb [03/Aug/2017:20:36:08 +0500] "GET /bbb/test/info/refs?service=git-upload-pack HTTP/1.0" 200 - - "git/2.12.0.windows.1" 153ms
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [debug] play - Chunked response to HTTP/1.0 request, sending 505 response.
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [info] a./bbb/test/git-upload-pack - 83.69.138.223 - bbb [03/Aug/2017:20:36:09 +0500] "POST /bbb/test/git-upload-pack HTTP/1.0" 200 - - "git/2.12.0.windows.1" 35ms
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [error] application - uploadPack failed
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: java.io.IOException: Pipe closed
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedInputStream.receive(PipedInputStream.java:226) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at org.eclipse.jgit.transport.PacketLineOut.writePacket(PacketLineOut.java:141) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at org.eclipse.jgit.transport.PacketLineOut.writePacket(PacketLineOut.java:122) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]

**Comment by doortts** [comment]
@comseong 안녕하세요?
https://repo.yona.io 에서도 테스트 한 번 해주시겠어요?

**Comment by JeongJun-Lee** [comment]
안녕하세요? repo.yona.io 에 했을 때는 이상이 없습니다. 참고로 요나 버전은 1.5입니다.

**Comment by project-yona** [comment]
네. 설치 os와 클론하신 도구는 어떻게되세요?

2017년 8월 6일 (일) 오후 3:57, JJ <notifications@github.com>님이 작성:

**Comment by JeongJun-Lee** [comment]
centos 7이고, clone은 mingw64에서 터미널창 열어서 했습니다.

**Comment by doortts** [comment]
흠.. 특별히 이상한 부분은 없어보이는데요 

- 혹시 mingw64에서 터미널창 말고 다른 곳에서도 clone 시에 동일한 에러가 발생하나요?
- git --version 은 어떻게 되세요?

**Comment by JeongJun-Lee** [comment]
윈도우즈 내장 터미널에서 했을 때도 동일합니다.
git버전은 git version 2.12.0.windows.1 입니다.

**Comment by doortts** [comment]
@JeongJun-Lee 그렇다면.. 혹시 중간에 apache나 nginx 등을 사용하고 계신가요?

**Comment by JeongJun-Lee** [comment]
그렇습니다. 기억에 전에 잘 되었던거 같은데 안되는 걸 보니 그새 누군가 관련 설정을 변경했으려나요?
2017. 8. 6. 오후 2:16에 "Suwon Chae" <notifications@github.com>님이 작성:

**Comment by doortts** [comment]
@JeongJun-Lee 
한 번 확인해 보시면 좋을 것 같습니다.
우선 현재 오류인 `505 HTTP Version Not Supported`는 흔한 에러는 아니기도 하고 HTTP Version 이 맞지 않는다는건 클라이언트의 요청, 혹은 proxy에서 무언가 version 을 특정하는 상황이 발생한 것으로 보입니다.

만약 내부 포트로 직접 접근이 가능하시다면 yona 서버와 port를 직접 지정해서 git clone 을 해보신다면 어느 쪽 문제인지는 확실해 질 것 같습니다.

**Comment by JeongJun-Lee** [comment]
확인해 보았습니다. git clone http://bbb@yona.aaa.com:9000/bbb/test 처럼 port를 특정해서 했더니 에러가 없네요;;; 혹시 포트를 특정하지 않고 기본 80포트를 사용해서 클론하는 방법은 없을런지요?

**Comment by doortts** [comment]
만약 중간에 있는 nginx 서버가 별달히 하는 일이 없다면 Yona를 80 포트로 운영하는 것도 한가지 방법입니다.

![image](https://user-images.githubusercontent.com/520523/29128003-94732906-7d5d-11e7-9823-50c0e2b4bf41.png)
참고: https://github.com/yona-projects/yona/wiki#yona-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

**Comment by JeongJun-Lee** [comment]
친절한 안내에 다시금 감사드립니다. 그런데 저희 서버에 다른 웹사이트도 같이 돌고 있어서 전적으로 요나를 80에 할당하기가 어려웠네요.

웹서치를 하던 중 저와 같은 문제를 겪으신 분이 이전 요비 프로젝트 때 계셨더라구요^^;

그 분이 하셨던 솔루션을 적용했더니 포트번호없이 클론이 되고 있습니다. 다른 분들에게도 도움이 될까하여 링크를 남깁니다. 감사합니다.

https://github.com/naver/yobi/issues/930
2017. 8. 9. 오후 7:51에 "Suwon Chae" <notifications@github.com>님이 작성:
