### ISSUE TITLE
yona 실행 시 Listening for HTTP 에서 멈춰있습니다.

### ISSUE THREAD

**Issue by yyy-222** [yona-projects/yona#254]
안녕하세요 :)

yona 를 사용하고자 하여 설치 후 실행중에
다음과 같은 부분에서 계속 멈춰 있고, 다른 에러로그가 발생하지 않아 문의드립니다.

/bin/yona 를 실행하면

[info] play - database [default] connected at jdbc:mysql://localhost:3306/yona
[info] play - Starting application default Akka system.
[debug] application - Registered AuthProvider 'google'
[debug] application - Registered AuthProvider 'github'
[info] play - Application started (Prod)
[info] application - User uploaded temporary files are cleaned up...(0 of 0)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

이 부분까지는 정상적으로 로그가 찍히는데, 이후 추가 진행사항이 없습니다.
port를 변경하여 시도 해보았지만 동일한 부분에서 멈춰있었습니다.

개발환경 : CentOS7
설치파일 : yona-1.3.0

위의 문제에 대한 해결방법이 있다면
확인 부탁드리겠습니다~

감사합니다

**Comment by doortts** [comment]
@yyy-222 
멈춰있는것이 아니라 정상 기동되어 9000 번 포트에 대해 대기중인 화면으로 보입니다.
http://127.0.0.1:9000 으로 접속해보시겠어요?

**Comment by yyy-222** [comment]
@doortts 아... 그 주소로 접속을 하였는데 연결 실패로 나와서 문의드렸습니다ㅠㅠ
로그상으로는 [info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000 이 부분이 기동로그의 마지막 부분인가요~?

**Comment by yyy-222** [comment]
추가적으로 질문이 있어서 다시 올립니다^^;
YONA를 설치한 서버를 제 로컬에서 ssh로 접속하여 작업을 하였는데, 
제 로컬의 web browser 에서는 YONA 페이지가 접속이 되지 않아서,
혹시나 하여 해당서버 내부의 web brower에서 접속을 하니 정상적으로 화면이 나왔습니다.

이럴 경우, YONA 쪽에서 따로 ip나 port 등록을 해야하는가요?

**Comment by doortts** [comment]
@yyy-222 : ) 설정을 잘 마치셨다면 최초 실행시에 너무 빨리 저 메시지가 떠서 계속 기다리시는 분들이 가끔 있습니다.

**Comment by gpmlily** [comment]
여기까지 되었는데 페이지가 안열리면 어떻게 하나요?

**Comment by doortts** [comment]
@gpmlily 웹 브라우저 화면에 뭐라고 표시되나요?

**Comment by gpmlily** [comment]
제 VMWare IP 로는 ... 접속시 안되는 군요.. 아마 방화벽이나 포트 문제일거같습니다..
