### ISSUE TITLE
저장소가 비어있습니다 나오는데 어떻게 해야하나요??

### ISSUE THREAD

**Issue by gogoalswo** [yona-projects/yona#255]
코드 주고받기 등 하려고 하는데
저장소가 없다고 안된다고 하네요..
저장소 어떻게 만들고 어떻게 연동하는건가요??

**Comment by doortts** [comment]
@gogoalswo 
코드 push 는 하셨죠? 
https://repo.yona.io 에서 테스트 한 번 부탁드려요.

**Comment by gogoalswo** [comment]
파일을 안올리면 저장소가 비어있다고 나오네요...
깃허브를 첨 써봐서 많이 헷갈리네요 ㅎㅎ
답변 감사합니다.^^
