### ISSUE TITLE
사용자 페이지의 pinned repositories 문의

### ISSUE THREAD

**Issue by hurcy** [yona-projects/yona#259]
깃헙 사용자 페이지의 pinned repositories(6개 저장소)와 유사한 기능-사용자가 고른 저장소를 원하는 순서대로 나열하는 기능- 이 있는지 문의드립니다.

**Comment by sjstyle** [comment]
현재는 해당 기능이 없는 것으로 알고있습니다.

**Comment by doortts** [comment]
@hurcy 
어떤 용도로 사용하고 싶으세요?

**Comment by hurcy** [comment]
@doortts 사용자가 가장 자주 방문하는 repository를 사용자가 원하는 순서대로 배열하면 좋을 것 같아서요.
사이드 네비게이션의 프로젝트 별표를 쓰면 되려나요?

**Comment by doortts** [comment]
@hurcy 
네 만약 본인기준으로 편하게 접근하기 위한 목적이라면 사이드의 사용자 메뉴 별표=즐겨찾기를 이용하시면 어떨까요?

![image](https://user-images.githubusercontent.com/520523/29709220-8bdebf92-89c6-11e7-8e4f-f855ad8d076c.png)
