### ISSUE TITLE
admin 계정은 어떻게 되는지요?

### ISSUE THREAD

**Issue by woojookeom** [yona-projects/yona#26]
사흘이나 걸린 우여곡절끝에 윈도7에 설치 완료했습니다.

둑흔둑흔 거리는 맘으로 페이지를 열었더니 어리둥절행....

Admin 계정은 어떻게 해야 하는지요?

**Comment by YJSoft** [comment]
새로 설치라면.. 설치 이후 접속하면 admin 계정 생성 화면이 떠야 정상입니다.

**Comment by woojookeom** [comment]
전 그냥 초기화면이 뜨더라구요.
관리자생성화면은 안보이네요. ㅠ

**Comment by woojookeom** [comment]
전 그냥 초기화면이 뜨더라구요.
관리자생성화면은 안보이네요. ㅠ

**Comment by woojookeom** [comment]
다시 해봐도 여전하네유.

127.0.0.1:9000으로 접속하면
요나시작하기 버튼과 하단에 주요기능 소개 이런 초기페이지가 뜹니다.

ㅠ

관리자 설정페이지는 어디인지 알 수 있을까요?

**Comment by doortts** [comment]
@woojookeom 만약 중간에 이런저런 문제로 서버를 계속 재시작하셨다면 admin의 password가 기본 패스워드로 바뀌었을 가능성이 있습니다.

id 는 admin 
password는 admin00 으로 로그인해보시겠어요?

만약 로그인이 되신다면 곧바로 admin의 패스워드를 변경하시는걸 권해드립니다.

**Comment by doortts** [comment]
@woojookeom 님 해당 문제 해결하셨는지 아니면 여전한지 확인부탁드려요. 동일 문제라면 다시 이슈를 열어주세요.

**Comment by woojookeom** [comment]
댓글깜박했네유.
일단은 누군가가 알려주신 초기 관리자 계정정보를 통해 해결했습니다.
감사합니다.

**Comment by woojookeom** [comment]
댓글깜박했네유.
일단은 누군가가 알려주신 초기 관리자 계정정보를 통해 해결했습니다.
감사합니다.
