### ISSUE TITLE
그룹 페이지에 Pull Request 리스트 추가

### ISSUE THREAD

**Issue by hongwonjun** [yona-projects/yona#260]
현재 그룹 페이지가 홈 / 이슈 / 게시판 으로 구성되어 있는데,
Pull Request 를 추가하면 좋을 것 같습니다.

**Comment by E-nuri** [comment]
@hongwonjun 회사에서 쓰는 요나에서는 아래의 이미지처럼 Pull Request메뉴가 있습니다.
혹시 요나 설정에서 뭔가 누락된게 아닐까요?
(제가 회사 요나 담당자가 아니라서 해당 게시판 보기 상태를 설정할 수 있는지는 모르겠습니다..)

<img width="774" alt="2017-08-16 9 30 00" src="https://user-images.githubusercontent.com/20082776/29342429-a75cc3da-8265-11e7-9269-739e3ca5d111.png">

**Comment by hongwonjun** [comment]
@E-nuri 올려주신 이미지는 프로젝트 페이지 같은데요.
이슈는 그룹 페이지에 대한 이슈입니다.
그룹 페이지는 Issue 와 Board 만 보일텐데 한번 확인 부탁드리겠습니다.

**Comment by E-nuri** [comment]
@hongwonjun 확인했습니다. 제가 혼동하고 있었습니다.

**Comment by berryzed** [comment]
기본 Yona에는 `Pull Request`메뉴가 없는거 같은데...

**Comment by hongwonjun** [comment]
@berryzed 기본 Yona 는 무엇을 말씀하시는건가요?

**Comment by E-nuri** [comment]
@hongwonjun @berryzed 
아마도 제가 
> '확인했습니다. 제가 혼동하고 있었습니다.'
라는 코멘트를 남겨서 헷갈리신게 아닐까..합니다.

기본 Yona(디폴트로 실행되는 Yona)에는 pull request 메뉴가 없는게 맞습니다.
저는 프로젝트 내부에 있는 Pull request 메뉴를 보고 해당 메뉴가 있다고 코멘트를 작성했던거구요.

**Comment by berryzed** [comment]
@E-nuri 아 요나 커스텀버전인가보군요 ㅎㅎㅎ
@hongwonjun Github에 릴리즈되고 있는 요나를 뜻합니다! 저는 저 사진보고...제가 사용하는 요나에만 없는줄 알았습니다 ㅠㅋ

**Comment by hongwonjun** [comment]
v1.9.0 에서 개발되었습니다.
