### ISSUE TITLE
PR을 보낼 때 어떤 branch로 보내야 하는지에 관한 질문

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#262]
#252 이슈를 한번 PR해보려고 코멘트해주신대로 설치를 진행중입니다.

그런데 소스코드를 수정하고 PR할때 어떤 branch로 보내야할까요?

**Comment by E-nuri** [comment]
해당 내용에 대해 정책이 결정되면 README에도 추가되면 좋겠습니다.

**Comment by doortts** [comment]
`next` 브랜치 기준으로 작업하셔서 `next` 로 보내시면 될 것 같습니다. README에도 업데이트 해 놓겠습니다.

**Comment by E-nuri** [comment]
@doortts 답변 감사합니다. 이 이슈는 닫겠습니다.
