### ISSUE TITLE
[버그] 태그 할 대상자가 없음에도 불구하고 태깅리스트에 뜨는 현상

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#263]
## 현재상황(문제점)
요나에서 다른 팀원을 태깅할 때 멤버가 아닌 사람도 리스트에 띄워준다.
기존에 멤버였다가 멤버에서 제외된 사람의 정보를 어딘가에서 저장하고있는게 아닌가 하는 생각이 듭니다.

**멤버에는 없는 moonchoi님이 리스트에 보여짐**
<img width="287" alt="kakaotalk_photo_2017-08-18-09-43-53" src="https://user-images.githubusercontent.com/20082776/29440252-16be0a74-83fe-11e7-85ee-84b5f95c1717.png">

## 문제가 영향을 미치는 곳
이슈 발행페이지, 이슈 수정페이지, 멤버를 태깅하는 모든 부분

**Comment by doortts** [comment]
이슈를 등록했던 사람도 작업 후 확인 담당자로 지정할 수 있도록 되어 있습니다.
꼭 멤버가 아니더라도 상황에 따라 담당자로 지정할 수 있도록 구성되어 있며 이 부분은 향후에 좀 더 확대될 예정입니다.
담당자 지정이나 멘션등의 자동완성에 표시될 뿐이니 별다른 불편은 없으실겁니다.

**Comment by E-nuri** [comment]
@doortts 
아~ 태그를 작성할 때 당시에 프로젝트의 멤버가 아니더라도 '확인 담당자는 이 사람이다/이었다'를 표시하기 위해서 의도된 표현이었군요?
의도를 모르고 그저 버그인줄 알았습니다. 코멘트 감사합니다.

**Comment by sjstyle** [comment]
버그가 아닌 스펙이여서 이슈를 종료합니다. 추가적인 의견이 있으실 경우 이슈를 다시 열어주시면 됩니다.
