### ISSUE TITLE
[질문] Yona를 개발 할 때 알아둬야 할 것들이 궁금합니다.

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#267]
웹개발을 해본적 없고, Yona도 처음써보는 왕초보입니다.

다른 오픈소스들과 달리 규모가 작은 오픈소스이다보니 빠른 피드백이 좋아서 좀 더 열심히 해보고 싶습니다.

소스코드를 다운받아 보니 코드들 앞에 @가 붙어있는걸 봤습니다.
분명 확장자는 .html인데 @가 붙어있는 소스코드들은 어떤 언어를 공부해야 이해 할 수 있을까요??

<img width="365" alt="2017-08-21 9 11 12" src="https://user-images.githubusercontent.com/20082776/29518726-74441d32-86b5-11e7-8422-029e610aca3b.png">

자바스크립트라고 나오는데 자바스크립트에서도 못 본 문법들이구요..
요나 처음 설치할 때 JDK를 설치하는점, 소스코드에 .java가 있는점을 보면 자바 언어를 공부해야하는건가요??

**Comment by doortts** [comment]
---
html 인데 @ 이 붙은 부분은 play framework의 scala template 입니다. 기본적으로 scala 문법이라고 보면 됩니다.
참고: https://playframework.com/documentation/2.3.0/JavaTemplates

---
Yona는 서버 코드가 java 혹은 scala로 구성되어 있습니다.

기반이 되는 프레임워크는 play framework 인데요 서버와 템플릿엔진, 의존관리등이 프레임워크에 포함되어 있는 프레임워크로 scala 진영의 대표 웹 프레임워크입니다.
https://playframework.com

---
만약 웹 개발입문과 같이 시작하신다면 우선 자바를 학습하시는걸 추천드려요. 

자바 문법책은 아무거나 가급적 얇은 책으로 하나 빠르게 보시고 그 다음애 [자바 웹 프로그래밍 Next Step](http://www.yes24.com/24/Goods/31869154?Acode=101)을 추천하고 싶습니다.

읽다가 궁금한건 물어보면 저자분이 아주 잘 알려줍니다. 

그럼 포스가 함께 하시길!
(May the force be with you!)
