### ISSUE TITLE
[문의] 버전 업데이트 시 application.conf 파일 내용 관련

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#270]
수고하십니다!

문득 1.6.1로 버전 업데이트 하면서 드는 생각이 바이너리와 라이브러리는 붙여넣기로 업데이트하면되는데
설정 파일의 경우 버전 업데이트 시 새로 생겨난 부분은 어떻게 채워지는지 궁금합니다!

**Comment by doortts** [comment]
- 기본적으로 기존 설정파일(applicatoin.conf)은 건드리지 않습니다.
- 추가된 옵션은 기존 사용자에게 영향을 주지 않는 형태로 기본값으로 동작합니다.
- 기본 설정이나 추가된 설정은 릴리즈 노트를 확인하거나 [기본 설정값파일](https://github.com/yona-projects/yona/blob/master/conf/application.conf.default), 혹은 [서버 관련 설정들](https://github.com/yona-projects/yona#서버-관련-설정들)의 [application.conf 설명](https://github.com/yona-projects/yona/blob/master/docs/ko/application-conf-desc.md)을 참고해 주세요.

**Comment by berryzed** [comment]
@doortts 감사합니다!
