### ISSUE TITLE
[버그] 이슈 닫은 후에도 Overdue 표시

### ISSUE THREAD

**Issue by hurcy** [yona-projects/yona#271]
- 현재 상태
이슈의 due date 설정한 경우, 그 날짜가 지나면 무조건 overdue로 보입니다.

- 해결 방안
이슈의 due date 설정한 경우, 이슈를 그 날짜 이전에 닫으면 overdue 표시가 없어야할것 같습니다.

**Comment by sjstyle** [comment]
@hurcy 
해당 문제를 해결한 버전이 v1.7.0으로 배포되었습니다. 확인해보시고 문제가 있으시면 알려주세요~
