### ISSUE TITLE
등록된 프로젝트에서 git repository만 초기화할 수있을 까요?

### ISSUE THREAD

**Issue by bokdol** [yona-projects/yona#273]
이슈와 게시판 등을 놔둔채로 git repository를 완전 초기화해서 새로운 마음으로 소스를 관리하고 싶은데 방법이 없을 까요?  git를 이용해서 일단 모두 삭제하여 커밋해봤는데 history 등이 남아서 뭔가 묵은 때가 남은 듯한 느낌을 지울 수 없네요... 혹시 방법이 있을런지....

**Comment by sjstyle** [comment]
프로젝트 관리자일 경우 설정 메뉴에서 "코드 저장소 타입 변경"을 이용해서 초기화 할 수 있습니다.
ex) Git Repo의 경우
Git -> Svn 변환 -> Git 변환 : 깔끔한 Git Repository 완성!

이렇게 할 경우 코드주고받기, 리뷰의 항목들은 지워질 수 있으므로 주의해야 합니다. (이슈, 게시물은 안전합니다.)

**Comment by bokdol** [comment]
감사합니다... 사랑합니다..
