### ISSUE TITLE
[1.6.1] 메일 내용 잘림

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#281]
안녕하세요. 메일로 전달된 내용이 잘리는 현상입니다.
"방금 전 그룹공개 프로젝트의 게시판 댓글 알림이 왔는데, bullet 내용이 포함되지 않고 왔습니다."

![screenshot 2017-09-04 10 51 45](https://user-images.githubusercontent.com/718691/30089771-c8f61674-92e9-11e7-8449-84b30bb959bb.png)
![screenshot 2017-09-04 10 49 22](https://user-images.githubusercontent.com/718691/30089772-ca33e8b8-92e9-11e7-8599-9e515570cc0c.png)

^^ 잘 쓰고 있습니다.
감사합니다.

**Comment by doortts** [comment]
@kenu 알려주셔서 고맙습니다. 
v1.6에서 발생한 문제로 v1.7에 해당 문제에 대한 fix가 포함되었습니다.

**Comment by kenu** [comment]
감사합니다. 👍
