### ISSUE TITLE
1.7.0 Download link broken

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#282]
admin에서 다운로드 버튼을 클릭하면 타투인 행성이 보입니다.
![screen shot 2017-09-06 at 10 04 20 am](https://user-images.githubusercontent.com/718691/30089927-f2edbfb2-92ea-11e7-8a70-eaa135c1b9e0.png)

https://github.com/doortts/yona/releases/tag/v1.7.0
![screen shot 2017-09-06 at 10 04 36 am](https://user-images.githubusercontent.com/718691/30089931-f9430390-92ea-11e7-9aff-d0e66c15177f.png)

**Comment by doortts** [comment]
#269 와 동일선상에서 발생하는 문제입니다.

v1.6 포함 그 이전 사용자는 동일 문제 발생시 
https://github.com/yona-projects/yona/issues/269#issuecomment-325996901 내용을 참고해서 수정해 주세요.

v1.7부터 새로 설치하는 인스턴스에서는 해당 부분이 fix 되어 있습니다.

**Comment by kenu** [comment]
감사합니다.
