### ISSUE TITLE
새로운 파일 생성시 문의

### ISSUE THREAD

**Issue by gogoalswo** [yona-projects/yona#283]
파일을 새로 생성하면
해당 파일이 '?' 모양으로 나와야 하자나요??
근데 '?' 모양이 안나오고 커밋 하려고해도 바뀐 파일 목록에 해당 파일이 없는데
어떻게 해야 하나요..
첨 써봐서 넘 어렵네요..흐규

**Comment by doortts** [comment]
@gogoalswo 

> 파일을 새로 생성하면

어디에서 무슨 파일을 생성하는 경우를 말하나요?
상황을 조금 더 자세히 설명해주시겠어요?

**Comment by doortts** [comment]
추가 조사가 불가능해서 해당 이슈를 닫습니다.
필요시 다시 열어주세요
