### ISSUE TITLE
사용자 메뉴에서 그룹을 선택해서 들어갈때 간헐적으로 페이지를 찾을 수 없는 문제

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#285]
안녕하세요. yona 1.7 버전을 사용하고있습니다.

사용자 메뉴의 그룹 리스트 중 특정 그룹을 선택해서 그룹 페이지로 들어갈 때 다음과 같이 페이지를 찾지 못합니다. 항상 못찾는게 아니고 간헐적으로 이런 증상이 발생합니다. 
![2017-09-06 9 16 00](https://user-images.githubusercontent.com/7797499/30111667-875a2bfa-9349-11e7-89c3-dc784da674b6.png)

이슈올리기전에 확인해보니 프로젝트 선택에선 문제가 발생하지 않고 그룹에서만 발생하는것으로 보입니다.

**Comment by doortts** [comment]
@dinobei 제보고맙습니다.

v1.7.1 버전에서 패치되겠네요.

**Comment by doortts** [comment]
@dinobei 
v1.8 에서 해당 버그 수정되었습니다.
확인해 보시고 이상있으시면 다시 열어주세요
