### ISSUE TITLE
프로젝트명 또는 그룹명에 한글이 있는 경우 오류

### ISSUE THREAD

**Issue by comternet** [yona-projects/yona#286]
프로젝트나 그룹 생성시에 한글도 가능하다고 표기되어 있는데,
정작 한글로 생성하려하면 오류가 발생합니다.

[error] play - Cannot invoke the action, eventually got an error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /yona/data/repo/git/jjwon/??_???.git/config
[error] application -

! @758nh6mm5 - Internal server error, for (POST) [/projects] ->

play.api.Application$$anon$1: Execution exception[[InvalidPathException: Malformed input or input contains unmappable characters: /yona/data/repo/git/jjwon/??_???.git/config]]

로그를 보면 위와 같은 형태로 에러가 발생해요.
어찌하면 좋을까요? 
운용 OS는 우분투 16.04.3 LTS 이고 pokev25님의 docker를 이용해 설치했습니다.

**Comment by doortts** [comment]
@comternet 
설치하신 OS에서 
```
echo $LANG

locale -a | grep ko
```
위 두 명령어의 실행 결과가 어떻게 되나요?

**Comment by comternet** [comment]
root@git:~/docker-yona# locale -a | grep ko
ko_KR.utf8
root@git:~/docker-yona#


위와 같이 나옵니다.

**Comment by doortts** [comment]
@comternet 
echo $LANG 결과도 부탁드려요

**Comment by doortts** [comment]
@comternet 
지원되는 locale ko 목록과 실제 세팅이 다른것처럼 보이는데요

```
# 지원되는 locale = locale -a
ko_KR.utf8

#실제 설정 = echo $LANG
ko_KR.UTF-8
```

@pokev25 님 혹시 관련해서 코멘트 가능할까요?

**Comment by comternet** [comment]
@doortts 

리눅스에 대해서 잘 몰라서 로케일이 뭐가 잘못된 건지 모르겠습니다.
$LANG 환경변수가 ko_KR.utf8 과 불일치해서 그런건가요?

**Comment by doortts** [comment]
우선 로컬 콘솔에서 한글 폴더 생성이 가능한지 한 번 테스트 해보세요
```
mkdir "한글폴더"
```
생성된다면 문제없는거고 아니라면

```
LANG=ko_KR.utf8
export LANG;
echo $LANG
```
해보셔서 변경되었는지 확인해보시고 다시 

```
mkdir "한글폴더"
```
해서 만들어지나 확인해보세요.

만들어진다면 다시 해당 창에서 Yona를 실행해서 테스트해봐주세요

**Comment by comternet** [comment]
@doortts 

한글 폴더는 정상적으로 만들어집니다.
그런데 한글 프로젝트명으로 생성시 오류가 발생하는 것은 그대로네요.

혹시 제가 도커를 사용하기 때문에 러닝중인 컨테이너 환경에서의 로케일이 문제일 수도 있다는
생각이 문득 들어서 도커 이미지 내에 로케일을 설정해보고 테스트 해볼까 합니다.
해보고 결과가 어떤지 다시 피드백 올리겠습니다.

**Comment by comternet** [comment]
@doortts 

도커 컨테이너의 환경에 로케일을 ko_KR.UTF-8 로 잡아주고 나서 한글 프로젝트명 생성에 성공했습니다.
혼자서는 문제가 뭔지 추측도 못하고 있던 상황이었는데, 도움주신 @doortts 님 정말 고맙습니다.

**Comment by pokev25** [comment]
@comternet host OS는 무엇인가요? 
테스트 해봐야겠네요..

**Comment by comternet** [comment]
@doortts 
호스트는 우분투 16.04.3 LTS 입니다.
도커 컨테이너는pokev25님의 Dockerfile을 열어보니 debian:jessie 를 사용했네요.

**Comment by comternet** [comment]
@doortts 

오늘 오전에 회사 컴퓨터에서 프로젝트 clone 하려했더니 한글로된 프로젝트가 아래와 같이 오류가 나옵니다.
`
D:\WorkSpace\git>git clone http://210.180.118.38:9000/한글그룹/%ED%95%9C%EA%B8%80%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8
Cloning into '%ED%95%9C%EA%B8%80%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8'...
fatal: repository 'http://210.180.118.38:9000/한글그룹/%ED%95%9C%EA%B8%80%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/' not found
`



요나가 돌고있는 docker 컨테이너의 로케일 설정은 아래와 같은 상태입니다.
`
root@git:/yona# echo $LANG
ko_KR.UTF-8
root@git:/yona# locale
LANG=ko_KR.UTF-8
LANGUAGE=ko_KR.UTF-8
LC_CTYPE="ko_KR.UTF-8"
LC_NUMERIC="ko_KR.UTF-8"
LC_TIME="ko_KR.UTF-8"
LC_COLLATE="ko_KR.UTF-8"
LC_MONETARY="ko_KR.UTF-8"
LC_MESSAGES="ko_KR.UTF-8"
LC_PAPER="ko_KR.UTF-8"
LC_NAME="ko_KR.UTF-8"
LC_ADDRESS="ko_KR.UTF-8"
LC_TELEPHONE="ko_KR.UTF-8"
LC_MEASUREMENT="ko_KR.UTF-8"
LC_IDENTIFICATION="ko_KR.UTF-8"
LC_ALL=ko_KR.UTF-8
root@git:/yona#
`

**Comment by pokev25** [comment]
데비안이 로케일 문제가 좀 있네요. 수정 작업 중입니다.

**Comment by pokev25** [comment]
clone 테스트 해보니 
프로젝트 명칭은 escape 되어있는데 그룹은 안되어 있어서 못찾네요.

도커는 로케일 지정테스트 완료 되었습니다. 1.7.0 정식으로 릴리즈 변경되면 배포될 예정입니다.
(ko_KR.UTF-8일 필요는 없습니다. en-US.UTF-8로 해서 한글 프로젝트 생성 잘되네요.)

**Comment by doortts** [comment]
@comternet 
v1.8 에서 해당 버그 수정되었습니다.
확인해 보시고 이상없으시면 이슈 닫음처리해주세요.

**Comment by comternet** [comment]
수정된 것 확인했습니다.
