### ISSUE TITLE
주소 복사 라이브러리 변경 제안

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#288]
개인적으로는 플래시를 끄고 사용합니다. 

'주소복사' 버튼이 플래시는 사용하는것 같은데요. 
깃헙도 언젠가 부터 바꿨더라구요.

플래시 안쓰는 기능으로 바꾸면 좋지 않을까 합니다. 

https://clipboardjs.com/

**Comment by doortts** [comment]
@sjstyle 님의 도움으로 v1.8 에서 해당 내용 수정되었습니다.
https://repo.yona.io 에서 확인 가능합니다. 
보시고 이상있으면 다시 이슈 열어주세요.
