### ISSUE TITLE
SVN 사용시 파일명에 한글명이나 특수문자가 있으면 에러가 납니다.

### ISSUE THREAD

**Issue by zunesuh** [yona-projects/yona#29]
먼저 yona 잘 사용하고 있습니다. 그런데 사용중에 에러가 발생하여 문의 드립니다.

SVN 사용해서 프로젝트를 Import나 Checkout, Commit, Update 하려고 하니 계속 에러가 발생하는데 원인을 찾아보니 파일명에 한글이나 특수문자가 들어가 있더군요.
yona에서 생성하는 SVN은 영문파일명만 지원하나요? 아니면 인코딩 세팅을 따로 해주는게 있는지 궁금합니다.

**Comment by doortts** [comment]
안녕하세요? 설치하신 OS가 어떻게 되세요?

**Comment by zunesuh** [comment]
현재 yona는 windows10에서 테스트 중이고
지금까지는 yobi 마지막 버전 Linux centos 3.10.0-229.14.1.el7.x86_64 에서 사용하고 있습니다.
두개 다 한글이나 특수문자 들어가면 에러가 발생하네요.

![image](https://cloud.githubusercontent.com/assets/18160323/14135766/53d41a5e-f69a-11e5-9657-94cbc80829d8.png)



참고로 git 사용시에는 한글 파일명도 문제 없네요

**Comment by doortts** [comment]
@zunesuh 흠.. 혹시 중간에 프록시나 아파치를 경유하고 있나요?

**Comment by zunesuh** [comment]
아니요. 따로 경유하는 곳은 없습니다...

**Comment by doortts** [comment]
@zunesuh 님 v1.0.1로 업그레이드 하시고 한 번 테스트 해 봐 주시겠엉? 
https://github.com/yona-projects/yona/releases/tag/v1.0.1

**Comment by brainagenet** [comment]
실행 스크립트를 확인해 주실 수 있나요? -Dfile.encoding=UTF-8 을 실행 스크립트에 추가하여 주시고 사용해 봐 주시기 바랍니다.

**Comment by doortts** [comment]
@zunesuh 님 v1.0.3을 사용해 보시고 @brainagenet 님의 코멘트대로 실행시에도 여전히 문제 발생한다면 다시 이슈 열어주세요.
