### ISSUE TITLE
[기능 개선 제안] milstone 탭에서 이슈별로 붙어있는 label을 보여주는 기능

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#292]
## 현재상태
yona의 milestone 탭에서 이슈를 확인할 때 이슈번호와 제목만 보여주고있다.
해당 마일스톤에서 이슈가 어떤 상태인지 확인하려면 해당 이슈를 클릭하고 들어가서만 확인 할 수 있다.

해당 이슈의 상태에 달려있는 label를 보여주는 기능 추가를 제안합니다.

**Comment by doortts** [comment]
@E-nuri 
현재 yona에서  milestone 탭에서 이슈를 확인할 때 이슈번호와 제목 뿐 아니라 완료 여부도 같이 보여주고 있습니다.
![image](https://user-images.githubusercontent.com/520523/30255599-df550746-96df-11e7-9bd6-1958438c5109.png)

**Comment by E-nuri** [comment]
@doortts 
네 맞습니다. 완료여부는 지금 적용되어 있는 기능이지요.
완료여부 뿐만아니라 이슈를 발행할 때 적용했던 라벨들을 마일스톤 탭에서 출력되는 이슈제목 옆에 띄워주는겁니다.

예를 들어서 A 이슈에 '협의필요'라는 라벨을 붙여놨을 때 마일스톤 탭에서는 해당 이슈 제목을 클릭 후 들어가서 보기전까지는 어떤 상태인지(완료/진행중 상태가 아닌 개발상태를 뜻합니다.) 알 수 없습니다.

라벨을 별도로 붙여둔다면 굳이 이슈 제목을 클릭해서 들어가지 않고도 한눈에 볼 수 있지않을까..해서 제안드렸습니다.

**Comment by berryzed** [comment]
기능 개선 제안에 의견드리고 싶어서 남깁니다!
UI 흐름에 벗어나지 않는 선에서 해당 이슈 마우스 오버 시에 이슈 라벨을 보여주는건 어떨까 적어봅니다!

**Comment by doortts** [comment]
@berryzed 
아이디어 제안 고맙습니다.
우선 마우스 오버시에 이슈 라벨이 보이게 만드는건 괜찮은 아이디어인것 같습니다.

다만 보통 폰이나 스마트 패드류의 장치에서 mouse 오버기능동작이 어렵기 때문에
툴팁외에는 이벤트 기반 동작이나 표시를 최소화 하는 방향으로 만들고 있습니다.
이 부분을 어떻게 조화시킬지 조금 더 보완 아이디어가 필요할 것 같습니다.
고민해 보겠습니다.

ps.
그리고 아래 주소로 contributor 관련 메일 드렸는데 확인부탁드려요
![image](https://user-images.githubusercontent.com/520523/30259076-a98414ee-96f9-11e7-9eba-219b04068e7b.png)

**Comment by sjstyle** [comment]
목록 우측에 그냥 라벨을 표시하면 문제가 있을까요? 대략 이런 느낌이 될 것 같습니다.

![image](https://user-images.githubusercontent.com/4811664/30327814-580efa60-9808-11e7-8dd9-8b1f6c488de9.png)

**Comment by doortts** [comment]
@sjstyle 
그럴듯하네요. 왠지 다 만들어진 느낌이네요ㅋ

**Comment by E-nuri** [comment]
@sjstyle 와~!! 멋지십니다 ㅎㅎㅎ

**Comment by doortts** [comment]
@sjstyle 님의 도움으로 v1.8 부터 마일스톤 이슈목록에서 라벨 표시를 지원합니다.
https://repo.yona.io 에서 확인 가능합니다. 
보시고 이상있으면 다시 이슈 열어주세요.
