### ISSUE TITLE
yona 실행시 참조하는 application.conf 위치

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#293]
안녕하세요.

application.conf 파일의 참조 위치가 어디인가요?
`환경변수 YONA_DATA에 지정된 conf 디렉터리`인지, `yona 실행파일 경로의 conf 디렉터리`인지 모르겠습니다.

최초 yona 압축파일을 다운받아서 unzip하고나서 실행할 때 항상 conf 디렉토리가 생기고,
YONA_EXPORT 환경변수와 무관하게 yona-data 폴더를 다른 곳으로 지정하고 실행해도 DB는 yona 디렉토리 내에 새로 생성된 conf 디렉토리를 참조해서, db에 접속 시도를 합니다.

yona 디렉터리 내에 생성된 conf파일을 수정해서 db 정보를 입력해주면 정상적으로 서버가 실행되고, 웹으로 접속해보면 관리자 등록 페이지가 뜹니다. 기존 서버 관리자 정보를 입력해도 되는걸 봐서, 서버관리자 정보는 별도로 저장되는듯합니다. 이후 YONA_DATA 환경변수와는 별개로 db 접속은 잘 됩니다. (YONA_DATA 환경변수에 지정된 application.conf의 db 패스워드를 잘못된 값으로 입력하여 테스트)

혹시 conf 디렉터리 참조 우선순위가 있나요?

**Comment by doortts** [comment]
우선순위는 고려하지 않고 YONA_DATA 환경변수 설정을 필수로 가정하고 있습니다.

참고: https://github.com/yona-projects/yona/blob/master/docs/ko/install-yona-server.md#본격적인-첫-화면-보기-위한-실행

**Comment by dinobei** [comment]
@doortts 
답변 감사합니다.
그렇다면, yona 사용자가 이런 순서로 실행을 해야하는거죠?
1. yona 압축파일 다운로드 및 압축 해제
2. yona 디렉터리에 들어가서 bin/yona 실행 -> conf 디렉터리 생성, db 패스워드 틀려서 실행 실패
3. application.conf 의 db 패스워드를 옳게 변경
4. YONA_DATA 환경변수 설정 및 conf 디렉토리를 환경변수로 이동
5. bin/yona 실행

처음 사용할 때 약간 헤매던 부분이라 백업/복구 테스트하면서 실험하고 있는데,
추축하기엔 다양한 가능성 때문에 질문드렸습니다.

**Comment by dinobei** [comment]
답변주신 내용, 참조자료 토대로 다시 실험해보니
bin/yona 실행시에는 항상 conf 디렉터리가 생성되네요.
- 최초 실행일 때
- 실행하고 관리자 설정까지 끝마치고나서 conf 디렉토리를 YONA_DATA 디렉터리에 복사하고 원본은 삭제했을 때

YONA_DATA 디렉터리에 있는 conf 파일은 무시되고있습니다.

**Comment by doortts** [comment]
@dinobei 
네 환경변수로 YONA_DATA를 지정하지 않으면 내장된 기본값을 따르게 되어 있고 일반적인 방법으로는 서버 설정을 임의로 할 수 없게 됩니다.

**Comment by dinobei** [comment]
@doortts 
음... 그런데 제가 테스트한 결과는..
환경변수 YONA_DATA를 지정해줬는데도 지정한 위치의 conf 파일을 참조하지 않고 실행한 위치의 conf 파일을 참조하는거 같습니다. 

* 압축 푼 파일: `/home/dinobei/yona-1.7.0`
* YONA_DATA = `/usr/local/yona-data`

위와 같은 상황에서 bin/yona를 실행할 때 ,
YONA_DATA가 설정되어있는데도 yona-1.7.0 폴더에 conf 폴더가 없으면 실행되지 않고, conf 폴더가 생성됩니다.
이후 /home/dinobei/yona-1.7.0/conf 폴더가 생성되고, 이 폴더의 application.conf에 db 패스워드가 틀리면 정상 실행이 되지 않는 상황입니다.

**Comment by doortts** [comment]
@dinobei 안녕하세요? 이 문제는 어떻게 되셨나요?

**Comment by dinobei** [comment]
@doortts 
답변이 너무 늦었네요.
오랜만에 들어와서 이슈 살펴보고서야 기억이 났습니다.

지금 다시 테스트해보니 bin/yona 실행시 conf 폴더가 생성되는 증상은 없습니다.
아마도.. 저 이슈를 올릴 당시 환경변수 세팅에 오타가 있었다거나 하는 실수로 인해 착각한듯합니다.

항상 고생 많으십니다. 감사합니다!
