### ISSUE TITLE
메일 하단에 Yona 링크가 제대로 동작하지 않습니다.

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#294]
프로젝트 알람을 통해 메일을 수신받았을 때, 관련 내용과 함께 아래쪽에
*Yona에서 자세히 보거나 혹은 이 메일에 직접 회신하실 수도 있습니다.* 부분에 Yona 링크를 클릭하면, 도메인 링크가 아닌 http://172.17.0.1/user_id/project_name/issue/3 과 같은 형식으로 링크가 됩니다.

다른 분들은 이상없이 쓰고 계신듯 한데.. 어디를 확인해봐야할까요?

**Comment by berryzed** [comment]
음.....아마
https://github.com/yona-projects/yona/blob/7558fb5cc67b32d3f73616b6e211408f09bffb8f/conf/application.conf.default#L169-L171
위 부분에서 호스트 네임을 변경하면 되지 않을까요~~?

**Comment by dinobei** [comment]
@berryzed 
아.. 그렇군요. 적용해보니 잘 됩니다. 감사합니다!
