### ISSUE TITLE
[기능 개선 제안] Pull Request 탭에서 어느 branch로 PR을 보내는지 출력되게 하는 기능

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#295]
## 현재상태
Pull request 메뉴에서 PR을 보낼 때 어느 브랜치로 PR을 보내는지 바로 확인할 수 없다.
PR merge 후 시간이 흘러 과거 PR기록을 찾아봐야할 때 어느브랜치로 PR된건지 특정 이슈를 찾기위해서는 일일이 들어가봐야 한다.

## 개선 제안
PR을 보낸 사용자 이름 , 시간 옆자리에 PR을 어디서 어디로 보내는지 나타나게 한다.

![auctionblue pull request dev auctionblue](https://user-images.githubusercontent.com/20082776/30324865-805fa6c8-97fd-11e7-99d4-7aa1909d265f.jpg)

**Comment by E-nuri** [comment]
회사에서 사용하면서 불편함을 느끼는것들을 올리다보니 비슷하거나 중복되는 내용이 많습니다.
지난번에 제안했던 이슈들도 비슷한 부분들입니다.

**Comment by doortts** [comment]
v1.8 부터 해당 기능 지원합니다.
https://repo.yona.io 에서 확인 가능합니다.
