### ISSUE TITLE
이슈 라벨에 대한 질문

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#30]
1. 현재 프로젝트 생성시  이슈 라벨 항목은 비어 있는데요.
    기본값을 줄 방법이나 다른 프로젝트의 이슈 라벨을 가져올 방법은 없나요?

2. 분류 라벨을 하나만 선택 하는것과 여러개 선택 하는 것의 차이점은 무엇인가요?
    해봐도 딱히 차이점을 모르겠습니다.

**Comment by doortts** [comment]
@pokev25 추가적인 이슈나 질문이 없으시면 이 이슈는 우선 닫도록 하겠습니다. 필요하다면 다시 열어주세요. ^^;

**Comment by pokev25** [comment]
네 질문은 0.8.2. 버전에 대한 내용이였습니다. (뭘 하더라도 중복 선택이 되더라구요)
1.0.1 버전 업글 후 확인해보고 이상하다 싶으면 다시 질문 하겠습니다.
