### ISSUE TITLE
Yona 답신 메일주소 %2F 문자 이슈

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#300]
요나에서 답신 이슈 등록 테스트 중인데, `/`이 `%2F`로 이메일 주소에 표시 됩니다.

web+HN%2Fplayground%2Fissue_post%2F16@hellonature.net

어디를 손 봐야 할까요?

메일 서버는 gmail을 사용하고 있습니다.
요나는 1.7.0 입니다.

**Comment by doortts** [comment]
v1.8 에서 해당 버그 수정되었습니다.
확인해 보시고 이상없으시면 이슈 닫음처리해주세요.

**Comment by doortts** [comment]
우선 닫음처리 합니다. 이상 발생시 다시 열어주세요

**Comment by kenu** [comment]
감사합니다. 👍
