### ISSUE TITLE
svn 커밋 속도 문제

### ISSUE THREAD

**Issue by hsoo** [yona-projects/yona#301]
windows용 yona-h2-v1.7.0-bin.zip으로 테스트 중입니다.

svn으로 커밋시 파일 크기에 비래해서 PUT 속도가 무척 느립니다.
네트워크 트래픽 그래프를 봐서는 전송은 금방 끝나는데 파일 검증등 후처리에서 부하가 걸리는 거 같습니다.

아래 파일은 20MB정도 되는데 svn으로 커밋할때 70여초 걸리지만 git은 1~2초 정도 소요됩니다.

```
192.168.0.59 - admin [21/Sep/2017:16:21:03 +0900] "PUT /svn/admin/test/!svn/wrk/4990aa40-ce71-4865-a1ac-a2b80832cd21/Content/FirstPersonBP/Maps/f.txt HTTP/1.1" 201 - - "SVN/1.9.2 (x86_64-unknown-cygwin) serf/1.3.8" 72914ms
192.168.0.59 - admin [21/Sep/2017:16:21:03 +0900] "PROPPATCH /svn/admin/test/!svn/wrk/4990aa40-ce71-4865-a1ac-a2b80832cd21/Content/FirstPersonBP/Maps/f.txt HTTP/1.1" 207 - - "SVN/1.9.2 (x86_64-unknown-cygwin) serf/1.3.8" 63ms

```

**Comment by doortts** [comment]
@hsoo 
https://repo.yona.io 에서도 동일한지 한 번 테스트 부탁드릴게요

**Comment by hsoo** [comment]
https://repo.yona.io/hslee/svn_bigfile/issue/1

해당서버의 사양이 어떻게 되는지는 모르지만  20여초 딜레이가 발생하네요.

**Comment by doortts** [comment]
@hsoo 
https://repo.yona.io 에서 다시 한번 테스트 부탁드릴게요.

**Comment by hsoo** [comment]
테스트 해보니 전송후 딜레이는 없어진거 같습니다. (rev:2)

추가로 샘플 프로젝트(크기 80mb)를 커밋(rev:3)해 봤는데 저장소가 rev:1로 리셋되어 있고 로그도 rev:1이 되어있던데... 테스트 서버 저장소 용량제한이 있는건가요?

**Comment by doortts** [comment]
@hsoo 
확인해 주셔서 고맙습니다. 현재 특별히 저장소에 대한 용량제한은 없습니다. 
번거로우시겠지만 새 프로젝트를 하나 만드셔서 테스트 부탁드려도 될까요?

**Comment by hsoo** [comment]
새 프로젝트에서 이전 테스트와 같이 순서대로 커밋해 보니 이상 없습니다.

수고하셨습니다.

**Comment by doortts** [comment]
@hsoo 번거로우셨을텐데 확인해주셔서 고맙습니다. v1.8.1 릴리즈에 포함하겠습니다. 패치버전 릴리즈 예상시점은 금주 내 입니다.
