### ISSUE TITLE
1.7.0 로 업그레이드 이후 커밋 등 이메일 발송이 잘 안되는것 같습니다.

### ISSUE THREAD

**Issue by siro012** [yona-projects/yona#302]
정확하게는 파악을 못했습니다만..
1.7.0 으로 업그레이드 이후 1.6.1 을 쓸때보다 메일수가 줄어서 보고 있습니다.
그런데 git push 됬거나 하는 메일을 보게 해놓았는데 그런게 안 들어오는 것 같습니다.
이슈 답글 달때도 @로 설정한 모든 사람한테 안 나가는 경우도 있는것 같구요.

**Comment by doortts** [comment]
@siro012 
v1.8.0 으로 업데이트 되었습니다. 해당 버전으로 테스트해주시겠어요?
https://repo.yona.io 에서도 테스트 가능합니다.

**Comment by doortts** [comment]
@bloodybear 님도 참고해주세요.

**Comment by siro012** [comment]
@doortts 업데이트 해서 git push 했는데 메일은 안오네요.
issue, board 에서 글을쓸때는 일부 메일은 오고 관리자 기능에서 메일전송기능에서도 잘 됩니다.
