### ISSUE TITLE
[개선 제안] 댓글 템플릿

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#308]
안녕하세요
덕분에 요나를 잘 사용하고 있습니다.

사용하다보니 고정된 서식으로 이슈 히스토리를 남겨야하는 경우가 간혹 발생하고 있습니다.

이슈템플릿을 제공하는것 처럼 댓글도 기본 템플릿이 있으면 어떨까 생각이 들어 제안 요청드립니다.

감사합니다.

**Comment by doortts** [comment]
제안 고맙습니다. 말씀하신 상황에대한 예를 좀더 들어주실수 있을까요?

**Comment by haare** [comment]
처음 이슈가 등록될 때 다양한 조건에 대한 테스트 결과값을 Table(표) 형태로 등록해놨을 때 
형상이 변경됨에 따라 댓글로 테스트 결과를 입력해야 할 경우 Table을 다시 그리고 조건을 다시 기입하고 결과값을 기입할 상황입니다.

제가 예로 든건 표이지만 정해진 서식을 좋아하는 팀(?), 사람(?) 들은 소소하게 필요한 기능일거라 생각이 들어서요

![image](https://user-images.githubusercontent.com/25476922/31474837-3ab47f70-af38-11e7-805e-aea6941ed25c.png)

**Comment by doortts** [comment]
@haare 
본문 이슈의 템플릿을 복사해서 댓글에서 쓰라고 하는건 어떠세요?

다른 사람글들도 원문보기가 가능하거든요. 수정이 안될뿐.
즉 이슈 본문에 한 번 적어주신걸 다른 사람들은 복사해서 붙여서 댓글로 남기는 식은 많이 불편하려나요? (제가 안해봐서..)

**Comment by pokev25** [comment]
이런건 기능으로 들어갈게 아니라 해당부서에서 서식 정해서 쓰면 되지 않을까요?

이슈는 모든 사용자가 특정 형식에 맞추는게 맞지만

댓글은 해당 템플릿이 특정경우에만 필요한것 같은데요.

**Comment by haare** [comment]
@pokev25 네 특정 경우가 계속 반복되는 상황이어서 방법을 찾고 있었습니다. 사실 댓글을 자유롭게 남기는게 좋지만 정의된 서식을 사용하면 형상별로 나왔던 내용을 빠르게 인지할 수 있을것 같아서요

@doortts 서식을 망가뜨리고 그냥 입력하면 댓글마다 모양새가 틀어질것 같아서요 (제가 OCD가 조금);;
1. 원문을 복사해서 수정하는 방법 > 등록당시의 결과값을 지워야하는 과정이 발생
2. 빈 서식을 복사해서 기입하는 방법 > 빈 서식을 어딘가에 유지해야함

-> 그래서 2번을 차용하려다 그냥 서식용 엑셀파일을 배포하고 거기에 기입하고 엑셀 셀을 드래그, 카피 앤 페이스트 하니 보기 좋게 이미지형태로 업로드가 되네요

일단 엑셀을 드래그 카피앤 페이스트 해서 써보려고 합니다.

**Comment by doortts** [comment]
@haare 
네 쓰시다가 에이 이건 좀 많이 불편한데! 싶으시면 알려주세요! 같이 방법을 찾아보죠!
