### ISSUE TITLE
새버전 업데이트 알림 링크 수정 필요 (1.8.0 업데이트 안내)

### ISSUE THREAD

**Issue by KOR-Believer** [yona-projects/yona#309]
https://github.com/yona-projects/yona/releases/tag/v1.8.0 로 링크 되어야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/8975134/31424589-029deac4-ae96-11e7-8fb2-4a93c855c132.png)

**Comment by KOR-Believer** [comment]
1. application.conf 기본값 오타 수정
application.update.releaesUrlFormat 
=>
application.update.releaseUrlFormat

2. app/models/YobiUpdate.java line 46
"https://github.com/doortts/yona/releases/tag/v%s" 
=>
"https://github.com/yona-projects/yona/releases/tag/v%s" 

하면 될것 같아요.

**Comment by doortts** [comment]
@KOR-Believer 
네 https://github.com/yona-projects/yona/commit/b7aab45e3746a8f2510de96123060227e319bbae 에서 패치되었고 곧 릴리즈 될 v1.8.1 에 포함될 예정입니다.
