### ISSUE TITLE
가입 이메일 인증 시 url이 localhost로 표시됩니다

### ISSUE THREAD

**Issue by eunpoong** [yona-projects/yona#315]
window server + yona 1.8.1 + IIS 8.0 (reverse proxy)

application.conf 의 application.hostname 값을 도메인으로 변경 적용 했으나

회원 가입 시 발송되는 이메일 인증 내용 상

제목, 본문의 유효 이메일 확인 링크, URL, Password reset 의

URL 표기가 http://localhost:9000 로 표시됩니다.

**Comment by doortts** [comment]
@eunpoong 
혹시 설정파일을 잘못 수정하신건 아닌가 싶기도 합니다.
YONA_DATA 위치를 어디로 설정하셨나요?
%YONA_DATA% 아래 conf 폴더의 application.conf 를 수정하셨는지 확인 부탁드릴게요

**Comment by eunpoong** [comment]
@doortts 
yona-run.bat
  cd D:\yona-1.8.1
  del RUNNING_PID
  SET YONA_DATA=d:\yona-data
  SET JAVA_OPTS=-Dyona.home=d:/yona-1.8.1 -Dconfig.file=d:/yona-data/conf/application.conf -
  Dlogger.file=d:/yona-data/conf/application-logger.xml -Xmx2048m -Xms2048m
  bin\yona.bat

D:\yona-data\conf\application.conf 에서 아래와 같이 설정했습니다.

# Components used to construct the URL to this application.
application.scheme="https"
application.hostname="도메인"
#application.port="443"

비밀번호 재설정이나 프로젝트 멤버 등록 등의 메일에서는 
설정한 application.hostname 으로 url이 표시됩니다.

**Comment by doortts** [comment]
@eunpoong v1.9 에서 해당 부분이 수정되었습니다. 확인 부탁드려요.

**Comment by doortts** [comment]
이슈를 닫습니다. 문제가 재발생 할 경우 다시 이슈를 열어주세요.
