### ISSUE TITLE
버그? 닫힌 이슈 재 오픈시

### ISSUE THREAD

**Issue by wifiz** [yona-projects/yona#316]
서버 오류가 발생하여 서비스를 이용할 수 없습니다. 라고 나옵니다.

댓글에 내용이 입력된 상태에선 정상작동하고 있습니다.

**Comment by doortts** [comment]
@wifiz http:s//repo.yona.io 에서도 동일하게 재현되는지 확인 한 번 해주시겠어요?

**Comment by wifiz** [comment]
@doortts 1.8.1 버전에서 확인해보니 재현되지 않네요..ㅎ

**Comment by doortts** [comment]
@wifiz 로컬에 설치해서 사용중인 1.8.1버전에서 잘 되신다는 이야기신거죠?
맞으시면 이슈 닫아주세요! : )
