### ISSUE TITLE
재시작 오래 걸리는 이슈

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#317]
안녕하세요.
요나를 재시작할 때 `[info] mail.in - {Subject: ...}` 로그가 오랫동안(30분 넘게) 기록되면서 지연되고 있습니다.
지난 재시작 이후 메시지들을 한꺼번에 처리하면서 생기는 지연같은데, 
바로 시작할 수 있는 방법은 없는지요?

감사합니다.

**Comment by doortts** [comment]
@kenu 
메일발송을 기능을 사용하지 않고 있었다가 메일 설정을 하고 나서 최초로 다시 띄울때를 말씀하시는거죠?

**Comment by kenu** [comment]
아닙니다. 메일 발송 기능은 계속 사용하고 있고, 메일도 잘 오고 있습니다.
하지만, 서버를 재시동할 때마다 같은 메시지를 보면서 기다리고 있습니다. 오늘은 38분 걸렸습니다. ^^;

**Comment by doortts** [comment]
@kenu 
혹시 확인해 보셨나요?

**Comment by kenu** [comment]
아직 여전합니다.
Proxy 설정을 여러 번 바꿔 봤지만, 여전히 같은 증상입니다.
해결하게 되면 공유하겠습니다.

**Comment by doortts** [comment]
@kenu v1.9 부터는 시작시점에 단계별 소요시간이 표시되도록 변경했고 일부 의심가는 기능(Mailbox 기능 설정)에대한 수정을 했습니다. (async로 동작하도록) 
확인 부탁드릴게요.

**Comment by kenu** [comment]
감사합니다. 주말에 업그레이드할 계획입니다.
결과 알려드리겠습니다. ^^

**Comment by kenu** [comment]
@doortts 
안녕하세요. 1.9.0으로 업그레이드하고, 재시작 시간 이슈는 수정되었습니다.
감사합니다. ^^
