### ISSUE TITLE
(중복)라벨 선택 시 AND 검색이 되도록 하면 좋겠습니다.

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#325]
안녕하세요,

#197 과 같은 내용인데, 라벨 선택 시 OR 이 아닌 AND 검색이 되면 좋겠습니다. 라벨을 중복으로 선택(검색)하면 정확도가 점점 떨어집니다.

감사합니다.

**Comment by doortts** [comment]
@witbox 
하하하 네 반영해 볼게요

**Comment by doortts** [comment]
@witbox v1.9부터는 and 조건으로 동작하도록 변경되었습니다 . 확인 부탁드릴게요. 보시고 의도대로 동작하시면 이슈 닫아주세요.

**Comment by doortts** [comment]
우선 이슈를 닫습니다. 문제가 재발생 할 경우 다시 이슈를 열어주세요.
