### ISSUE TITLE
[건의] '엑셀파일로 다운받기'에 마일스톤도 포함

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#326]
안녕하세요,

제목 그대로 '엑셀파일로 다운받기'에 마일스톤도 행에 포함되면 좋겠습니다.

노고에 감사합니다.

**Comment by doortts** [comment]
@witbox v1.9 부터는 엑셀에 마일스톤도 포함되도록 변경했습니다. 확인 부탁려요.

**Comment by doortts** [comment]
이슈를 닫습니다. 문제가 해결되지 않았거나 재 발생할 경우 다시 이슈를 열어주세요.
