### ISSUE TITLE
프로젝트 삭제 실패 문제

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#327]
안녕하세요.

현재 1.8.0 버전을 사용중인데, 특정 프로젝트가 삭제되지 않는 문제가 있습니다.

들은바로는, 
이슈를 다른 프로젝트로 옮기고 삭제하려고했더니 오류가 발생했다고 뜬다고 하는데..
repo.yona.io 에서 테스트해보니 이 문제는 아닌듯합니다.

현 상황은,
프로젝트 생성한 아이디로 프로젝트 삭제를 시도하면, `프로젝트를 삭제하는 중에 오류가 발생했습니다.` 라고 팝업이 뜹니다.,
관리자계정으로 로그인해서 프로젝트 삭제를 시도해봐도 동일합니다.
관리자 계정으로 로그인 뒤 사이트 관리-프로젝트 탭에서 해당 프로젝트를 삭제하려고하면, 삭제 버튼이 클릭되지 않습니다. 이건 모든 프로젝트가 다 그런거보니 버그인거같네요.

그래서,
서버에서 해당 프로젝트.git 폴더와 db 관련 row를 직접 삭제하려고하는데, 
project 테이블에서만 삭제하니 해당 사용자계정으로 로그인시 비정상동작하더라구요.
강제로 다시 원래대로 입력했더니 돌아왔는데 프로젝트를 지울 수 없는건 여전합니다.

어떻게해야 db 테이블에서 프로젝트를 강제 삭제 할 수 있을까요?

**Comment by doortts** [comment]
@dinobei 
- 우선 v1.8.1로 업그레이드 후 테스트를 해 봐주세요
- 프로젝트를 삭제 할때 서버 로그를 첨부해 주실 수 있을까요?
- DB를 직접 건드리는건 저도 잘 하지 않는 작업이라 추천드리고 싶지 않습니다.

**Comment by dinobei** [comment]
@doortts 
옮겼던 이슈를 다시 원래 프로젝트로 옮긴 후에 삭제를 시도하니 삭제되었다고합니다.
문제 발생했을 때 서버로그 캡쳐는 해놨었는데, 실수로 전부 삭제를 해서 현재 첨부가 어렵네요..

**Comment by dinobei** [comment]
우선 이슈를 닫고 문제가 생기면 다시 열도록 하겠습니다.

**Comment by cpascal** [comment]
이슈 관련내용 맞을 것으로 생각됩니다. (단순하게 이슈라기 보다는..  이슈라벨 관련으로 추측?)
과거에 다른 분이 비슷한 상황을 겪고 계시길래..  에러로그를 본 적이 있었는데.. 
프로젝트 제거시, issue_label 테이블의 내용 지울때.. Foreign Key constraint fails 상황 저도 두세번 보긴했습니다. 그냥 FOREIGN_CHECK 끄고 해당필드들만 지운다음에 프로젝트 지우기 다시 실행해서 넘어갔던 기억이...
