### ISSUE TITLE
(건의) 허용된 아이피만 사이트 접속이 가능하도록 하는 기능

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#328]
안녕하세요. 

yona를 사용하는 팀에서 사이트 사용 관련 회의중 보안 문제가 거론되었습니다.
그래서 외부 접속을 막을지 말지를 논의하다가 
허용된 아이피만 접속 가능하도록 하는 기능이 있으면 좋지 않을까 하는 결론이 도출되어 문의 드립니다.

**Comment by doortts** [comment]
허용된 IP만 제한하는 기능은 현재 Yona에서 제공하고 있지 않습니다. 

- 다만 가입시 관리자가 승인을 해야 사용가능하게 하는 기능은 제공하고 있습니다.
https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L46
- 특정 도메인의 이메일만 수신을 가능하게 제한하는 기능도 필요하시면 사용하실 수 있습니다.
https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L53

위 기능은 최초 가입시 메일로 유효 메일 확인을 하는 기능과 같이 결합하면 특정 회사 도메인의 계정만 가입 및 활동이 가능하게 만드실 수 있습니다.
- https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L58

로그인 하지 않으면 어떠한 페이지도 보이지 않게 만드는 옵션도 있고요
- https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L22

허용된 ip만 사이트에 접속이 가능하게 되는 기능을 제공하면 어떤식으로 사용하실 예정이신지 설명을 해주시면 좀 더 도움이 될 것 같습니다.

**Comment by dinobei** [comment]
@doortts 
현재 가입시 관리자 승인을 거쳐야 사용가능하게 하는 기능은 잘 활용하고있습니다.

다만, 본격적으로 yona를 업무에 활용하려다보니 웹페이지가 외부에 노출되어있다는점이 보안에 취약할 수 있지 않을까? 라는 의견이 있었습니다. 그렇다고 회사 내부에서만 접속 가능하게하면 불편할 수 있기 때문에.. 절충안이 필요해서 제안드리는 기능입니다.

h2버전의 출장용 yona를 활용해서 외부업무를 보고 돌아오면 본서버에 이전하는 방식도 고려했습니다만, 팀원들이 쉽게 사용하지 못할 것 같아서 패스했습니다.

제안드리는 기능이 추가되면, 원하는 팀원들의 접속 IP를 개별적으로 수집해서 서버에 접속 가능하도록 허용해두는 방식으로 활용할 예정입니다.

혹시 yona의 보안이 안전하다 라고 팀원들에게 설명/주장할 수 있는 근거 자료 혹은 설명이 없을까요?

**Comment by pokev25** [comment]
ip 제한 기능이 필요하신거면 아파치에 설정을 하시면 될 것 같습니다.

**Comment by dinobei** [comment]
@pokev25 
저는 아파치로 메인 웹서버(example.com)를 사용중이고, 리버스프록시로 yona를 (yona.example.com)사용하고있습니다. 

메인 웹서버는 아무나 접속이 가능하도록 둔채로 yona만 ip제한을 하고싶은데, 
이런 경우에도 아파치 설정이 가능한가요?

**Comment by pokev25** [comment]
virtualhost로 해두셨을테니 가능합니다.
yona 도메인쪽에 allow deny 설정 하시면 되겠네요.

**Comment by dinobei** [comment]
@pokev25 
답변감사합니다. 덕분에 해결했습니다.

현재 메인 서버가 https로만 접속되게 되어있고, yona는 reverse proxy 로 연결하고있었는데, reverse proxy 관련 VirtualHost를 다음과 같이 Location 구문을 추가하여 해결했습니다.

```
<VirtualHost *:80>
    <Location />
        Order deny,allow
        Deny from all
        Allow from 1.2.3.4 # 접속을 허용하길 원하는
        Allow from 5.6.7.8 # IP주소 입력
    </Location>
    ServerName yona.example.com
    ProxyPreserveHost on
    ProxyPass / http://localhost:9000/ nocanon
    ProxyPassReverse / http://localhost:9000/
    ProxyTimeout 3600
</VirtualHost>
```
