### ISSUE TITLE
README Tab 제안

### ISSUE THREAD

**Issue by jisoon** [yona-projects/yona#33]
항상 감사히 잘 사용 하고 있습니다.

사내에서 사용중인데 소스는 yona 가 아닌 다른 저장소를 이용하고 이슈 관리만 yona로 사용하는 경우가 있습니다.

코드 저장소가 없다보니 프로젝트 첫화면인 README 탭이 비어 있어서 왠지 사용하지 않는 프로젝트 같은 느낌이 들더라구요.

혹 코드 저장소가 없는 프로젝트 첫 화면을 README 대신 최근 이력이나 대시보드를 보여 주는게 좋지 않을까 생각 됩니다.

**Comment by doortts** [comment]
의견감사합니다.
다만 프로젝트에서 첫 화면에 자신의 프로젝트를 설명하는 README를 간단하게라도 적는걸 권장하고 싶은 의도도 있어서 주신제안은 좀 더 논의가 되어야 할 것 같습니다.

![image](https://cloud.githubusercontent.com/assets/520523/14401793/1471aeaa-fe59-11e5-9587-66dd9063ac37.png)

코드저장소를 사용하지 않아도 해당기능을 이용해서 설명을 간단하게라도 적는건 도움되는 경우가 많거든요.
아니면 때로는 팀 멤버들이 항상 보면 좋은 공지나 이번 작업스케쥴등을 기록해 놓기도 합니다.

물론 이야기 주신부분은 그런 요구가 필요하지 않은 상황에서도 빈 화면이 보이는것에 대한이야기이셨지만요 ㅎ

**Comment by jisoon** [comment]
@doortts 답변 감사합니다. 주말 출근이라 noti 가 와서 저도 코멘트 추가 합니다.

git 은 답변해 주신 이미지와 같이 만들기 버튼이 있는데 SVN 은 그런 기능이 없네요.

혹 SVN 도 가능 하도록 추가 해 주실 용의가 있으신지요 ^^;

**Comment by doortts** [comment]
아! 그럼 저장소는 안쓰신다고 하셨으니까 
![image](https://cloud.githubusercontent.com/assets/520523/14401856/be99dc12-fe5a-11e5-9fd9-ceaaafd7839e.png)

저장소 타입을 프로젝트 설정에서 변환하시고

![image](https://cloud.githubusercontent.com/assets/520523/14401861/da515bba-fe5a-11e5-9932-c3bb8b59986d.png)

메뉴설정에서는 안 쓰시는 메뉴 감추시면 어떠세요?

ps
만들기 싫어서 그러는거... 맞아요. 하하하

**Comment by jisoon** [comment]
일단 말씀 하신 데로 저장소를 git 으로 변경하고 README.md 파일을 작성 하게 한 다음 메뉴에서 안보이게 하도록 전파 하겠습니다.

감사 합니다.
