### ISSUE TITLE
[버그] 프로젝트 이관시 수락 링크를 연달아 누르면, 문제 발생.

### ISSUE THREAD

**Issue by cpascal** [yona-projects/yona#330]
Yona에서 개인 프로젝트로 하다가, 조직 프로젝트로 이관하는 경우 때문에 프로젝트 이관기능을 종종 사용하는데요.

프로젝트 이관 신청을 하면, 메일로 "수락 요청"메일이 오는데.. 이 링크를 누른 후에, 이관작업이 마무리 되기 전에 다시 연달아서 누르면..  repo 폴더는 옮겨지고, db는 기존 상태 그대로가 되는 꼬인 상태가 됩니다.

여러번 경험한 것이라..  요즘은 "수락" 링크를 누를 때, 두번 누르지 않도록 조심하고 있습니다.

**Comment by doortts** [comment]
@witbox v1.9에서 해당 부분을 개선해 보았습니다. 확인 부탁드릴게요.

**Comment by doortts** [comment]
이슈 관리를 위해 우선 현재 이슈를 닫음 처리합니다. 문제가 해결되지 않았거나 재 발생할 경우 다시 이슈를 열어주세요.
