### ISSUE TITLE
[건의] 사용자 인증코드 통합

### ISSUE THREAD

**Issue by cpascal** [yona-projects/yona#331]
Yona가 사용하는 routes path 종류에 따라서, 유저인증규약이 아래 세가지 종류인 것 같은데요.

- 쿠키: 웹브라우저에서 로그인하여, 쿠키를 사용하는 방식
- User-token: API 들
- HTTP-Auth: WebDAV 등

대부분의 routes path에서, 쿠키세션/토큰방식/HTTP-Auth를 모두(any) 지원하면 편할 것 같습니다.

예를 들어, CI툴에서 git 프로젝트에서 "Download as .zip file" 기능을 사용하려면..   쿠키를 사용하는 방식이기 때문에..   CI툴에서 먼저 로그인 패킷 한번 보내서, 쿠키를 저장하고.. 해당 쿠키를 사용해서 다운로드 요청을 하는 방식으로 하고 있습니다. 해당 API가 User-token이나 HTTP-Auth를 지원할 경우, 두번 요청할 필요도 없고.. 쿠키를 지원하지 않는 http 프로그램으로도 사용할 수 있기에 편리할 것 같습니다.

※ Yona가 git remote archive기능을 지원안하는 것으로 알고 있는데요. git 클라이언트로 다운로드할 경우, .git 폴더가 생성되기 때문에, 불필요한 전송(용량 등)이 있어서..  "Download as .zip file" 기능을 사용하고 있습니다.

지금은 Yona를 CI툴에서 기능을 사용할 때, 이 API는 User-token 방식인지 쿠키방식인지 매번 코드보면서 추가해야해서..  여러가지로 시간이 걸리더라고요.

**Comment by doortts** [comment]
@cpascal 
좋은 의견이신것 같아요. 고맙습니다.

TOKEN을 이용한 API는 나중에 추가되기 시작했는데요 우선 필요하신 api 를 알려주시면 해당 기능부터 TOKEN 기반 요청을 지원해 보겠습니다.

**Comment by cpascal** [comment]
@doortts 
감사합니다. 지금은 로그인하여 쿠키를 한번 더 저장하는 방식으로 수정한 상태라, 급한 것은 없고요.
그래도, 가장 일반적으로 많이 쓰실만한 걸로는.. 

/:user/:project/code/:branch/download

는 쿠키없이 다운로드 가능했으면 좋을 것 같습니다.

※ 약간 다른 이야기지만, download가 ZIP만 지원하는데..  tar나 tar.gz등의 다른 포맷도 다운로드 가능하면 좀 더 편할 것 같습니다. Unix에서는 tar나, tar.gz용 프로그램들이 아무래도 스트리밍으로 다운로드하면서 풀어내기도 편하고요.
Yona에서 사용하는 jgit도 zip말고도, tar.gz등도 지원하더라고요. 몇줄만 고쳐도 간단히 지원 될 것 같아서..

**Comment by doortts** [comment]
요청하신 링크의 접근 인증은 v1.9 에서 적용하겠습니다.

저도 쉘 스크립트를 쓰고 있는데요 (맥과 centos 에서) unzip 명령어를 사용하고 있습니다. 

![image](https://user-images.githubusercontent.com/520523/33197973-aa1c943c-d12b-11e7-8fc9-dc82c69aa57f.png)

어느 OS에서까지 지원하는 기본 내장 유틸리티인지는 모르겠습니다.

**Comment by cpascal** [comment]
@doortts 
감사합니다.

tar의 경우는 아래와 같이 사용중입니다.
curl "https://curl.haxx.se/download/curl-7.56.1.tar.gz" | tar xvfz -
위처럼 할 경우, 파이프를 이용해서 다운로드 시작하자마자 압축이 풀리기 시작하는데요. (파일이 다운로드 완료안되어도 풀기시작하고, archive file을 disk에 쓰지 않기 때문에, 용량차지도 안하고.. 압축푼다음에 archive file 지울필요도 없기 때문에, archive file자체가 불필요할 떄 사용하고 있습니다)

리눅스 배포판에 포함되어있는 unzip의 경우, pipe를 지원하지 않다보니까.. 무조건 파일이 다운로드 완료된 이후에 풀기시작합니다. 용량이 큰 archive download의 경우, 몇%의 추가 시간이 걸리게 되고, 다운로드된 파일도 지워야 하고..  pipe를 지원하는 경우가 더 유용한 경우들이 있습니다.

물론, zip 프로그램들도.. funzip, bsdtar이나, jar를 사용하면 pipe를 사용가능하긴 하지만요.
tar의 경우, Android 기기나 임베디드 등 유닉스계열이면 지원안하는 경우가 거의 없다보니..
아무래도 유닉스 계열에선 tar 관련이 활용도가 높아서..  있으면 좋을 것 같긴 합니다.

**Comment by doortts** [comment]
@cpascal 
아하! 자세히 설명해 주셔서 고맙습니다. 저런 좋은 점이 있었네요!

**Comment by doortts** [comment]
@cpascal 
v1.9 부터 cookie 없이  Authorization Header 를 사용해서 기존 대부분의 HTTP GET 방식의 접근(파일 다른로드, 엑셀 내려 받기 등등)이 curl 등의 도구등을 통해 좀 더 편하게 접근 가능하도록 변경되었습니다.

확인 부탁드릴게요.

참고: https://github.com/yona-projects/yona/releases

**Comment by doortts** [comment]
이슈 관리를 위해 우선 현재 이슈를 닫음 처리합니다. 문제가 해결되지 않았거나 재 발생할 경우 다시 이슈를 열어주세요.
