### ISSUE TITLE
사용자 언급 기능시 Internal server error 발생

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#335]
안녕하세요!
지금까지 우분투 16.04 기반 서버에 yona 1.8.1, mariadb 10.2 버전을 설치하여 잘 사용하다가,
다른 서버로 이전하면서, docker 기반으로 yona 1.8.1 mariadb 10.0.33 버전을 설치하여 사용중입니다.
(mariadb 10.0.33 버전을 설치한 이유는 10.2 버전에서 #299 이슈때문입니다.)

기존 자료를 모두 백업복원하여 사용하고있었는데, 상대방 언급기능`(@id)`이 동작하지 않아서 서버로그를 보니 다음과 같았습니다.

![2017-11-15 7 37 01](https://user-images.githubusercontent.com/7797499/32831925-3c2c5d30-ca3d-11e7-9a9e-2e5dcff66e59.png)

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/32834477-16652f42-ca46-11e7-97e6-70d96e76569e.png)

이슈테이블이 없다고 에러가 나오는데 이해하기가 조금 어렵네요.

> 기존 자료를 모두 백업복원하여 

어떤식으로 복원하셨나요?

MariaDB 10.0 에서는 저도 테스트 해본적이 없어서 10.1.x 로 해주시겠어요?

**Comment by dinobei** [comment]
네 10.1 로 테스트 해보고 말씀드릴께요~

**Comment by dinobei** [comment]
@doortts 
방금 10.1로 테스트 해보았습니다.
10.1에서도 동일한 오류 메시지가 뜨네요..

> 기존 자료를 모두 백업복원하여
에 대한 답변을 안드렸네요.
 데이터는 YONA_DATA 경로상에 있는 폴더 자체를 백업하였고, db는 여기 readme에 있는 메뉴얼대로 진행하였습니다. 백업/복원은 한 서버에서 그동안 여러번 있어서 문제없이 사용했던적이 있습니다.

몇가지 더 테스트해보니, 프로젝트/그룹 멤버 추가부분에서는 상대방 언급기능이 정상동작하는데, 이슈에서만 동작하지 않고있습니다.

**Comment by dinobei** [comment]
@doortts 
혹시 백업 데이터에 문제가 있나 해서 추가적인 테스트를 진행했습니다.
yona 사이트 데이터를 모두 지우고, db설정도 초기설정으로 다시 수행하였습니다.
그래도 동일한 오류가 발생하네요..

(데이터 문제도 아니라면) 기존에 제가 사용하던 방식과 달라진건,
지금 yona가 동작하는 환경이 docker 컨테이너 내부에 설치한 mariaDB 10.1 stable 이라서 문제가 발생하는게 아닐지 의심되네요.

**Comment by doortts** [comment]
@dinobei 
저한테 개인 메일 하나 주시겠어요?
![image](https://user-images.githubusercontent.com/520523/33197799-e437a216-d12a-11e7-819f-74713c5d9f98.png) 입니다. 
같이 해결해 보셔요!

**Comment by sjstyle** [comment]
제 느낌은 왠지 https://mariadb.com/kb/en/library/server-system-variables/#lower_case_table_names 요것과 관련있는것 같습니다. 

테이블 이름이 대문자인데 아마도 생성 스크립트에서 만드는 테이블은 소문자로 만들것 같네요.

**Comment by doortts** [comment]
@sjstyle 
아! 그럴수 있겠네요.

@dinobei 
https://github.com/yona-projects/yona/blob/master/docs/ko/install-mariadb.md
에서 

![image](https://user-images.githubusercontent.com/520523/33226386-a78f539a-d1cf-11e7-91df-d5dfa4d6bcc6.png)
부분 확인해 주시겠어요?

**Comment by dinobei** [comment]
@doortts 
해당 설정 확인해보았는데 맞게 설정 되어있네요..

우선은 개인 메일 보내드리겠습니다.

**Comment by doortts** [comment]
@dinobei 
```
mysql -u root -p 암호
```

db에 root로 접속하셔서

```
SHOW VARIABLES LIKE 'lower_case%';
```
결과가 어떻게 되는지 확인해 주시겠어요?

**Comment by dinobei** [comment]
DB 설정 파일(my.cnf)이 제대로 적용되지 않아 생긴문제로 확인되었습니다.
my.cnf 파일 작성 뒤 db를 재시작해서 해결되었습니다.
관련 markdown 문서에 해당 내용 추가한 PR보내드렸습니다.
