### ISSUE TITLE
프로젝트 일반 멤버에게도 pull request에 병합 승인 권한이 주어집니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#337]
안녕하세요? 저희는 요나로 fork없이 직접  중앙 repo에 pull request하는 shared repository 개발 모델로 개발하고자 합니다.

그런데, 문제가 프로젝트 관리자 멤버가 아닌 일반 멤버들이 pull request를 생성한 후, 마치 관리자 권한을 가진듯 pull request의 병합을 승인하는 주황색 병합버튼이 보이고 자기가 만든 pull request는 물론이고, 심지어 남들이 신청한 pull request까지 병합시킬 수가 있네요??? 

프로젝 생성자나 관리자가 아닌 사람들이 이러한 권한을 갖는 것은 정상은 아닌 듯 합니다. 왜냐면 동일한 방식으로 Github에서 테스트 했을 때 저희가 예상한데로 프로젝트 생성자를 제외한 다른 일반 참여자들은 pull request를 승인할 권한이 없기에 병합 녹색버튼 자체가 뜨지 않거든요.

참고로 yona 1.5 사용 중에 최근 1.8.1로 업그레이드 했고, 업그레이드 한 버전에서 테스트했습니다.

감사합니다.

**Comment by doortts** [comment]
안녕하세요?

프로젝트에 멤버로 지정되면 프로젝트 설정을 제외하고는 프로젝트 멤버와 프로젝트 관리자는 권한이 동일합니다.
여기에는 Yobi에서부터 이어지는 Yona의 컨셉이 있는데요 '프로젝트 멤버는 최대한 동등한 권한과 책임을 가진다.'는 생각을 바탕으로 구현되었고 구현되고 있습니다.  

만약 pull request 를 마음대로 merge 하는 것이 문제라면 팀 내에서 그렇게 하지 않기로 서로 규칙을 세우면 좋을 것 같습니다. 시스템적으로의 보완은 프로젝트 설정에서 리뷰어 기능을 on으로 설정해서 pull request 시 리뷰 완료 숫자를 올려서 최소 2명이상이 승인해야 머지가능하게 하는 기능을 사용해 보시면 어떨까 싶습니다.

![image](https://user-images.githubusercontent.com/520523/32937984-00d1f402-cbbe-11e7-8590-6a778fa5cdca.png)

**Comment by JeongJun-Lee** [comment]
네 철학이었군요. 잘 알겠습니다. 말씀하신데로 구두로 서로 약속을 지키자고 해야겠네요. 감사합니다^^
