### ISSUE TITLE
폐쇄망에서 사용가능토록 가급적 인터넷망 리소스 사용을 줄일 수는 없을까요?

### ISSUE THREAD

**Issue by bokdol** [yona-projects/yona#339]
너무나도 훌륭한 프로젝트 잘 사용하고 있습니다.

다만..  인터넷으로 연결되지 않는 내부망에서 사용 시 인터넷망에서 가져오는 일부 리소스(아바타 이미지, 폰트, 등등 )로 인해  많은 불편사항이 있습니다. ( 각 메뉴 이동 시 해당 리소스가 timeout될 때 까지 브라우저가 멈추고 있습니다. ) 

현재는 소스를 직접 받아다가 강제로 수정해서 사용은 하고 있습니다만...
매번 수정해야하는 어려움이 있습니다..
( 특히 H2DB버전의 경우 제가 실력이 모자라서 못찾은 건지  모르지만 최신버전이  github에 등록되지 않은 듯 싶습니다..  ㅜ.ㅜ )

혹시 향후 릴리즈 시 폐쇄망을 고려해주실 수 없으신지....  

배려가 계속되면 권리인줄 착각하는건 아니지만... 그래도.. 가능하시다면..  ㅎㅎㅎ

**Comment by doortts** [comment]
@bokdol 
안녕하세요? 해당 내용에 대해 작업중입니다. 확인을 위해
보통 어떤 부분을 수정하셨었는지 알려주시겠어요?

**Comment by bokdol** [comment]
일단.. 모든 페이지가 영향을 받는 부분만 고쳐서 사용했습니다.

app/views/layout.scala.html 중 

```
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
```
를
```
<!-- <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">  -->
```
요렇게 했습니다....

그 밖에 avata 이미지 부분도 외부망을 사용하는 것 같은데.. 그것까지는 수정안했습니다.

**Comment by doortts** [comment]
@bokdol 안녕하세요? v1.9 부터는 이야기 주신 내용와 Gravatar 등을 비롯해 외부 네트워크 리소스를 최소한으로 쓰도록 줄였습니다. 확인 부탁드릴게요.

**Comment by doortts** [comment]
이슈를 닫습니다. 문제가 해결되지 않았거나 재 발생할 경우 다시 이슈를 열어주세요.
