### ISSUE TITLE
[문의] 메일 하단에 Yona에서 자세히 보거나 혹은 이 메일에 직접 회신하실 수도 있습니다. 의 Yona 링크가 수정되지 않아요

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#344]
안녕하세요

이슈 알림 메일 하단의 Yona를 눌러보면
http://127.0.0.1/그룹/프로젝트/issue/9 로 링크가 걸려서

다른분의 글을 참조하여
https://github.com/yona-projects/yona/issues/294

\yona-data\conf\application.conf 을 아래와 같이 수정했습니다.
![image](https://user-images.githubusercontent.com/25476922/33755487-552f9d3e-dc34-11e7-9dc9-a69d658ac390.png)

(http://172.16.3.247:9000/ 로 접속하면 요나 접근이 가능합니다.)

또 어디를 수정해야될지 알려주실 수 있으실까요?

**Comment by dinobei** [comment]
@haare 
hostname과 port 맨 앞에 붙은 #을 삭제하셨나요?

**Comment by haare** [comment]
@dinobei 감사합니다!!
