### ISSUE TITLE
이슈 등록하려고하면 권한이 없다고나옵니다.

### ISSUE THREAD

**Issue by hwangmoa** [yona-projects/yona#349]
이슈 등록하려고하면 권한이 없다고나옵니다.
어제까지 잘사용했는데 갑자기 참여자 모두 권한이 없다고나와 이슈 내용 확인 불가합니다.
확인 부탁드립니다.

**Comment by doortts** [comment]
@hwangmoa 해결 안되셨으면 다시 열어주세요!
