### ISSUE TITLE
비공개 프로젝트 문의

### ISSUE THREAD

**Issue by jongjunseo** [yona-projects/yona#35]
yona-1.0.1 셋업하여 사용중입니다.(windows, mariaDB)

프로젝트를 비공개로 생성한 후
팀원A를 프로젝트 멤버 추가 하였습니다.

이후 팀원A 접속시 권한이 없다고 나오며 접속이 불가합니다.
> "권한이 없거나 존재하지 않는 프로젝트입니다." 

제가 모르는 부분이 있는건지. 오류인건지.
문의드립니다.

**Comment by doortts** [comment]
문제 내용 추척중입니다. 한번 yona를 재시작 후 동일한 문제가 발생하는지 확인해 주시겠어요?
저도 확인 후 패치를 만들도록 할게요.

**Comment by jongjunseo** [comment]
네. 재시작 후에도 동일한 증상이 있습니다.
감사합니다.

**Comment by siro012** [comment]
yona-1.0.0 을 사용하고 있는데 저도 마찬가지 현상이 나타납니다.

**Comment by doortts** [comment]
@siro012 v1.0.2 에서 유사 문제에 대한 패치가 적용되였습니다.
https://github.com/yona-projects/yona/releases/tag/v1.0.2

**Comment by jongjunseo** [comment]
v1.0.2 패치 이후 정상 동작하는 것 확인했습니다
감사합니다. 잘 사용하겠습니다.

**Comment by siro012** [comment]
감사합니다.
