### ISSUE TITLE
yona서버 실행이 안됨

### ISSUE THREAD

**Issue by hazzi8** [yona-projects/yona#351]
안녕하세요 윈도우10에 yona를 설치했습니다

한동안 잘 사용하고 있다가
어제 저녁에 서버가 꺼져있더라구요

오늘 아침에 다시 키니
yona 서버가 중지되어 있습니다  

재부팅을해도 고쳐지질 않네요

nssm 으로 윈도우 부팅시 자동실행하게끔 했는데요
(경로 D:\nssm\win64\nssm.exe)

로컬 컴퓨터에서 yona 서비스를 시작하지 못했습니다. 
라고 뜹니다.

yona설치된 디렉토리에서 yona.bat도 실행해봤는데 접속이 전혀 안되네요 
이럴땐 어떻게 해야 하나요?

**Comment by doortts** [comment]
@hazzi8 안녕하세요? 오류메시지가 어떻게 되나요?

**Comment by hazzi8** [comment]
@doortts cmd로 실행시 오류메세지는 안나오고 서비스에서 yona실행시
로컬컴퓨터에서 yona서비스를 시작하지 못했습니다. 
서비스에서 오류가 반환되지 않았습니다. 
라고 나옵니다 ㅜ

**Comment by doortts** [comment]
@hazzi8 네 그럼 cmd 에서 yona.bat 실행시 어떤 메시지가 보이는지 보여주실 수 있을까요?

**Comment by hazzi8** [comment]
Play server process ID is 5296
This application is already running (Or delete D:\yona\RUNNING_PID file).

라고 나옵니다!

**Comment by doortts** [comment]
> Or delete D:\yona\RUNNING_PID file !!!!

D:\yona\RUNNING_PID 파일을 한 번 지워보시겠어요?

**Comment by hazzi8** [comment]
@doortts 감사합니다 ㅠㅠㅠㅠㅠㅠㅠㅠ 새해복 두배 아니 100배 받으세요 ㅠ

**Comment by hazzi8** [comment]
@doortts 어 .. 근데 yona.bat실행하고 cmd콘솔창을 종료하면 다시 접속이안되고 RUNNING_PID파일이 재 생성되네요 ㅠㅠ

**Comment by hazzi8** [comment]
@doortts  처리했습니다 감사합니다!
