### ISSUE TITLE
서브폴더에 요나설치시 /assets/images/loading-gif-2.gif not found

### ISSUE THREAD

**Issue by yhbyun** [yona-projects/yona#353]
서브폴더에 요나를 설치한 경우는 /assets/images/loading-gif-2.gif 가 
404 not found가 나옵니다. 

`app/assets/stylesheets/less/_page.less` 6987 라인을 보면

```css
background: #FFF url('/assets/images/loading-gif-2.gif') no-repeat center;
```

이 부분 오류 일것 같은데, 제가 수정할 능력은 안되고, 사소한 거지만 알려드려야 할것 같아서 적습니다.

**Comment by doortts** [comment]
@yhbyun 
알려주셔서 고맙습니다. 해당 내용은 다음 릴리즈때 포함시키도록 하겠습니다.

**Comment by doortts** [comment]
@yhbyun v1.9에서 해당 기능이 수정되었습니다.

**Comment by doortts** [comment]
이슈를 닫습니다. 문제가 재발생 할 경우 다시 이슈를 열어주세요.
