### ISSUE TITLE
[제안] 이슈의 라벨 변경 이력이 출력되면 좋겠습니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#355]
안녕하세요.

현재 이슈에는 이슈의 열림/닫힘, 커밋에서 언급, 댓글이 본문 아래 이력으로 표시가 되는데
여기에 라벨의 변경 이력도 같이 출력되면 좋을 것 같습니다.

예를 들어, 이슈의 열림/닫힘 외에 세부적인 상태 관리를 위해 라벨을 활용할 경우
최초 상태에서 다음 상태로 라벨을 변경하면 누가 이슈의 라벨을 '시작'->'완료' 로 변경했다는
이력이 출력되면 조금 더 세밀한 이슈 트랙킹이 가능할 것 같아 제안을 드려봅니다.

**Comment by doortts** [comment]
@hyunseogi 
의견고맙습니다. 생각해보니 정말 그렇네요. 라벨도 이슈의 status니까 있어야 할 것 같습니다.

**Comment by doortts** [comment]
@hyunseogi v1.9부터 이슈 라벨 변경도 이력이 남도록 변경되었습니다. 확인 부탁드릴게요.

**Comment by doortts** [comment]
이슈를 닫습니다. 문제가 해결되지 않았거나 재 발생할 경우 다시 이슈를 열어주세요.

**Comment by doortts** [comment]
@hyunseogi 확인 고맙습니다! : )
