### ISSUE TITLE
Database 'default' is in an inconsistent state!에러 때문에 문의드립니다

### ISSUE THREAD

**Issue by neighborpil** [yona-projects/yona#358]
어제부터 리눅스에 요나 설치를 시도하고 있습니다.

centos7에
마리아 db 버전은 5.5.56입니다
자바 컴파일러 버전은 1.8.0입니다

설치를 계속 반복해서 해봐도  계속 database inconsistence error가 나면서 실행이 되지 않습니다.

처음에 yona를 실행하면 password에러가 뜨는 부분까지는 잘 되고 있습니다

$YONA_DATA를 설정하여 그 안에 conf폴더 안에 application.conf파일이 있고 비밀번호를 바꾸워주었습니다.

그 뒤에 실행을 하면 아래와 같은 메세지가 뜨는데 도저히 이유를 모르겠습니다.

아래의 이슈들을 보고 다 따라해봐도 안되네요

default db가 불일치한다는데 어디서 손대야할지 모르겠네요;;ㅠㅠ

![image](https://user-images.githubusercontent.com/22423285/35950722-38511186-0cbb-11e8-9774-58c7a2b05962.png)

**Comment by neighborpil** [comment]
자문자답인데 문제를 알아냈습니다;;

아래의 링크를 보고 따라 설정을 했었는데

innodb_file_per_table 설정도 on으로 해야 동작하는군요

혹시 안되신다면 확인하고 설정하시기 바랍니다

https://repo.yona.io/yona-projects/yona/code/next/docs/ko/install-mariadb.md

**Comment by doortts** [comment]
@neighborpil 
안녕하세요? 방법을 찾으시고 공유해주셔서 고맙습니다.
그런데 MariaDB 버전이  5.5.56 을 쓰고 계신가요?

최신 버전인 10.1이나 10.2를 기준으로 동작하는데요 버전 확인 한 번 부탁드려요.

**Comment by neighborpil** [comment]
음? MariaDB 5.5.56 Stable 2017-05-03
리눅스에서 yum으로 이버전으로 설치가 되던데 바꿔야할까요?;;
현재 동작은 잘 되고 있습니다

**Comment by doortts** [comment]
@neighborpil known issue 로 남겨놓고 이슈 닫도록 하겠습니다. : )
