### ISSUE TITLE
Webhook 등록시 공백이 포함되면 정상작동이 되지 않음

### ISSUE THREAD

**Issue by hongwonjun** [yona-projects/yona#359]
Webhook 등록시 공백이 포함되는 경우 Webhook 이 제대로 작동하지 않습니다.
(Yona 에서 기존에 등록한 URL 을 싹 드래그하면 가장 끝에 공백이 한 칸 포함 됩니다.)

등록시 좌우 공백을 체크해서 제거하는 로직을 추가해야 할 것 같습니다.

**Comment by doortts** [comment]
@hongwonjun https://github.com/yona-projects/yona/blob/next/app/controllers/ProjectApp.java#L1269 에서 webhook.payloadUrl 등을 trim() 처리하면 될 것 같습니다.

**Comment by hongwonjun** [comment]
@doortts 네 처리해서 PR 보내도록 할게요
