### ISSUE TITLE
프로젝트 목록에서 페이지수가 정확하지 않습니다.

### ISSUE THREAD

**Issue by jongjunseo** [yona-projects/yona#36]
yona-1.0.1 셋업하여 사용중입니다.(windows, mariaDB)

프로젝트는 9개를 등록하였고 1페이지 분량으로 보입니다.

그러나 하단의 페이징 네비게이션에는 4페이지까지 이동 가능합니다.

페이지수가 정확하지 않습니다.

**Comment by doortts** [comment]
수정해야 하는 버그 맞습니다. 이유는 하단의 총 페이지 계산은 단순히 전체 프로젝트 목록을 기준으로 하는데 실제 페이징내용은 private 등의 이유로 본인이 확인 불가능한 프로젝트 목록은 제외되기 때문에 발생하는 버그입니다.
