### ISSUE TITLE
1.9.0 으로 업데이트 후 실행 불가 (윈도우즈)

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#361]
안녕하세요
평소처럼 요나 업뎃을 하고 실행을 하니 

아래 내용이 출력되며 실행이 되지 않습니다.
![image](https://user-images.githubusercontent.com/25476922/37083447-e1957cb4-2232-11e8-8a02-efa905449bb2.png)

1.8.1로 다시 원복 시켜봤는데 실행이 안되네요 ㅠㅠ

**Comment by doortts** [comment]
안녕하세요? 우선 이 문제는 2가지 해결 방법이 있습니다.

방법1  (추천 방법)
---
DB를 10.2로 업그레이드 (추천)
- https://mariadb.com/kb/en/library/upgrading-from-mariadb-101-to-mariadb-102/

방법2 (빠른 방법)
---
릴리즈 페이지에서 yona-v1.9.0-mariadb-10.1.bin.zip 을 내려 받으시고 
DB 접속하셔서
```
delete from play_evolutions where id = 20;
```
실행 후 다시 Yona 실행

해보시고 알려주세요. 더 빠른 피드백을 원하신 경우에는 [텔레그램 유저그룹](https://telegram.me/joinchat/A-3VSTyfpszxjOcW2IzR2g)으로 메시지 주세요.

**Comment by haare** [comment]
방법1을 진행했는데 뭐가 문제인지 알수 없이 전과 동일한 메시지만 출력했습니다.

이어 방법 2를 진행하려했으나 10.1에서 진행을 해야하는거 같아서 깨끗하게 다시 설치하려고 합니다.

지원에 감사드립니다.

**Comment by doortts** [comment]
@haare 네 해보시고 알려주세요!

**Comment by haare** [comment]
깨끗하게 재설치하고

오늘 문제가 생기기 전의 DB A를 백업해서 구동했을 때 정상 동작을 확인 했습니다.

금일 문제가 발생한 이후의 DB B를 넣고 구동했을 때 구동되지 않았습니다.
그 상태에서 다시 DB A를 넣고 구동했을 때 구동되지 않네요

여기서 도움을 요청 드립니다.
1. 현재 상태에서 뭘 수정해서 구동이 될까요? 
2. 재설치를 하고 DB B를 포기해야하나요?

감사합니다.

**Comment by doortts** [comment]
@haare 종료 후에 DB B에 접속해서 
```
delete from play_evolutions where id = 20;
```
를 실행하신 다음

다시 띄워보셨어요?
