### ISSUE TITLE
이슈에서 mention 처리시 목록이 안나오는데 설정을 별도로 해야 하는지요?

### ISSUE THREAD

**Issue by siro012** [yona-projects/yona#366]
이슈등에서 담당자를 mention 처리할 경우 목록이 안나타나는듯 하여 별도 설정을 해야 하는지 문의 드립니다.

![image](https://user-images.githubusercontent.com/17733295/37251724-e95a3632-2558-11e8-96ce-7a7c39a97d27.png)

**Comment by doortts** [comment]
@siro012 안녕하세요? 어떤 경우에도 mention 은 site admin을 지칭하는 것을 제외하고 동작해야 정상입니다. 

- 사용하시는 Yona 버전, 그리고 위 스샷의 OS와 브라우저 종류를 알려주시겠어요?
- 크롬을 경우 개발자 도구를 선택하셔서 콘솔창에 오류가 보이는지 알려주세요.
![image](https://user-images.githubusercontent.com/520523/37253809-11eff840-257a-11e8-9017-2bb86004545f.png)
- IE일 경우에는 개발자 도구 단축키 F12 (기억이 가물..) 누르셔서 마찬가지로 확인 부탁드립니다.

**Comment by siro012** [comment]
@doortts 개발자도구로 볼 경우 500 에러가 납니다.
이에 서버 로그를 확인해보니 아래와 같습니다.
mariadb 의 issue 테이블이 소문자라서 나타나는 현상일까요?

Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'yona.ISSUE' doesn't exist
Query is: select distinct author_id id FROM ISSUE where project_id=5
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:172) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:230) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	... 56 common frames omitted

그리고 mariadb 는 아래와 같습니다.

MariaDB [yona]> show fields from issue;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| title           | varchar(255) | YES  |     | NULL    |                |
| body            | longtext     | YES  |     | NULL    |                |
| created_date    | datetime     | YES  | MUL | NULL    |                |
| updated_date    | datetime     | YES  |     | NULL    |                |
| author_id       | bigint(20)   | YES  | MUL | NULL    |                |
| author_login_id | varchar(255) | YES  |     | NULL    |                |
| author_name     | varchar(255) | YES  |     | NULL    |                |
| project_id      | bigint(20)   | YES  | MUL | NULL    |                |
| number          | bigint(20)   | YES  |     | NULL    |                |
| num_of_comments | int(11)      | YES  |     | NULL    |                |
| state           | int(11)      | YES  |     | NULL    |                |
| due_date        | datetime     | YES  |     | NULL    |                |
| milestone_id    | bigint(20)   | YES  | MUL | NULL    |                |
| assignee_id     | bigint(20)   | YES  | MUL | NULL    |                |
| history         | longtext     | YES  |     | NULL    |                |
| parent_id       | bigint(20)   | YES  | MUL | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
17 rows in set (0.00 sec)

**Comment by doortts** [comment]
@siro012 아 이건 #135 이슈와 동일 이슈가 아닌가 싶습니다.

MariaDB 설치하실때 설정 옵션 하나를 누락하신것 같아요.
(안해도 잘 동작하면 좋겠지만... 죄송..)

![image](https://user-images.githubusercontent.com/520523/37254302-5e60198a-257f-11e8-91c0-bd0287c844bf.png)

참고: https://github.com/yona-projects/yona/blob/master/docs/ko/install-mariadb.md

**Comment by siro012** [comment]
@doortts 감사합니다. 제가 설정했네요.. 다시한번 감사드립니다.
