### ISSUE TITLE
[버그] 이슈 라벨 제거시 Object 형태로 출력.

### ISSUE THREAD

**Issue by thorwel** [yona-projects/yona#368]
repo.yona.io에서 테스트 하였으나 동일 증상입니다.

이슈 게시판에서, 이슈를 셀렉트하여 상단에서 라벨 제거를 클릭하면

[Object Object] 형태로 나옵니다.

물론 작동도 안하구요~

**Comment by doortts** [comment]
@thorwel 
#322 와 동일 이슈인것 같은데 맞나요?

**Comment by thorwel** [comment]
@doortts 아 이미 리포팅된 내용이네요..

다음부턴 꼼꼼히 검색후에 ...

**Comment by doortts** [comment]
@thorwel 아니에요. 중복된건 중복처리하면 되니까 괜찮습니다~ 우선 중복이슈로 닫을게요~
