### ISSUE TITLE
알림 메일 상에 링크 URL 이상

### ISSUE THREAD

**Issue by jongjunseo** [yona-projects/yona#37]
yona-1.0.1 셋업하여 사용중입니다.(windows, mariaDB)

이슈에 대해 이미지를 첨부한 경우
알림 메일에서 링크가 127.0.0.1 로 되어 있어서 보이지 않습니다.

또한 Yona 링크, 그만 지켜보기, 알림 설정 링크 등도 127.0.0.1 로 되어 있어서 
메일에서 yona 연결이 되지 않습니다.

설정이 부족한 것인지 문의드립니다.

**Comment by pokev25** [comment]
application.hostname 에 서버 주소를 넣으셔야 할 껍니다.

**Comment by jongjunseo** [comment]
감사합니다. 바로 확인해 보겠습니다. ^^
