### ISSUE TITLE
[문의] 삭제된 이슈에 대한 관리

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#370]
안녕하세요

제목처럼 삭제된 이슈에 대해 이력이 남는지 문의 드립니다. 또는 복원이 가능한지  문의드립니다.

악의든 실수든 삭제된 이슈에 대해 어떤 이력이 있었는지와 누가 삭제 했는지 말입니다.

DB 복원 방식 말고 YONA 페이지 내에서 관리될 수 있다면 물론 다들 믿고 쓰는거지만 
또 하나의 안전장치가 되지 않을까 생각합니다.

감사합니다.

**Comment by doortts** [comment]
@haare 우선 알림에 대해서는 v1.9 부터는 삭제시에 누가 삭제했는지 프로젝트 지켜보기를 한 사람에게 발송됩니다. 삭제된 이슈에 대한 복구 기능은 따로 지원하고 있지 않습니다. 

고민했던 적이 있었는데, 지켜보기를 한 사람 누군가는 이전 내용에 대한 알림메일을 받은 사람이 있을거라고 판단해서 입니다. 

그런데 사실 말씀하신 부분에 대한 문제로 등록된 이슈의 삭제를 지원하지 않는 경우가 종종있습니다. 이를테면 Github 이 그렇죠.

**Comment by haare** [comment]
@doortts 감사합니다. 일단 메일 발송을 통한 안전장치로 이용해볼께요:)
