### ISSUE TITLE
smtp.port 변경이 불가능합니다.

### ISSUE THREAD

**Issue by kiros33** [yona-projects/yona#372]
### smtp.port 미반영 이슈
`application.conf` 설정파일에서 smtp.port = 465 값을 변경하여도 적용되지 않는 문제가 있습니다.

아래와 같이 의도적으로 잘못된 포트로 설정하더라도 정상적으로 메일이 발송됩니다.

```
# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gmail smtp
smtp.host = smtp.gmail.com
smtp.port = 4655
smtp.ssl = true
```

소스 내부에서 smpt.port 설정 값을 사용하는 부분이 없음도 확인하였습니다.

---

[outlook.com](http://outlook.com) 계정을 설정하기 위해 테스트 하던 중 포트가 적용되지 않는 문제를 발견하였습니다.

**Comment by doortts** [comment]
안녕하세요? 오류 제보 고맙습니다.

우선
`이거 뭐지? 코드에서도 사용하는 곳이 없잖아? fake 설정인가???` 라고 생각하실 수도 있는데요 

mail 은 MailPlugin 에 의존하고 있고 위 설정은 그 플러그인에서 지정하도록 되어 있는 내용입니다.

이 문제는 좀 더 살펴보고 이야기 드릴게요.

**Comment by doortts** [comment]
@kiros33 최근 @strcpyy 님에 방법을 찾아내셔서 wiki 에도 업데이트 해 주셨습니다. 참고해주세요.
 https://github.com/yona-projects/yona/wiki/Yona-%EB%A9%94%EC%9D%BC%EC%84%9C%EB%B2%84-%EC%84%A4%EC%A0%95#tls587-port%EB%A1%9C-%EC%84%A4%EC%A0%95%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
