### ISSUE TITLE
issue table명 대문자로 인한 인식 문제.

### ISSUE THREAD

**Issue by thorwel** [yona-projects/yona#373]
app/models/Project.java
 ```
   private Set<User> getIssueUsers() {
        String issueSql = "SELECT distinct author_id id FROM ISSUE where project_id=" + this.id;
        return User.find.setRawSql(RawSqlBuilder.parse(issueSql).create()).findSet();
    }
```
해당 쿼리에서 ISSSUE 테이블명이 대문자로 되어 있어서 테이블을 찾지 못하는 문제가 발생합니다.
이 문제는 요나의 문제라기보다는 MariaDB 설정 문제인 것 같은데...
다른 쿼리문은 전부 소문자로 작성되어 있어서 버그 리포팅 드립니다.

repo.yona.io는 정상 작동 하는 것을 확인 했습니다.

발생하는 위치.
게시판 등, 멘션 사용시 사용자나 커밋을 불러오지 못합니다.

서버 환경은
Fedora 28
Yona 1.9.0
MariaDB 10.2 기본 설정입니다.

**Comment by doortts** [comment]
@thorwel 제보 고맙습니다. 이 부분은 소스코드에서도 예방하도록 처리해야겠습니다.

참고로 현재 상황에서의 처리는 https://github.com/yona-projects/yona/issues/366#issuecomment-372117436 부분을 참고하시면 우선 해결은 되실거에요.

**Comment by doortts** [comment]
@thorwel v1.9.1 에서 이 부분 코드도 함께 수정되었습니다.
