### ISSUE TITLE
[건의] API를 이용한 이슈/게시글 등록시 지켜보는 사람들에게 메일 발송

### ISSUE THREAD

**Issue by lotiony** [yona-projects/yona#374]
이슈등록, 게시글등록 등 API를 사용해  신규 글을 등록하는 경우
지켜보는 멤버에게 푸쉬 알람 설정에 따라 메일이 같이 발송되면 어떨까 합니다. 

현재는 API를 통한 이슈등록시  알림메일이 오지 않습니다.

이부분도 json 데이터 또는 헤더에 옵션값으로 사용여부를 지정할 수 있으면 더 좋을 것 같습니다.

**Comment by doortts** [comment]
[v1.10](https://github.com/yona-projects/yona/releases/tag/v1.10.0) 에서 api를 통한 이슈 등록시 알림 발송 여부를 정할 수 있게 수정했습니다.

최상단 property 로 sendNotification 라는 이름의 key 가 존재하면 이슈 알림을 발송합니다.

```
{
sendNotification: "아무값이나 존재"
}
```
그런데 적고 보니 true / false 로 할 걸 그랬다는 생각이 드네요. 음.

**Comment by lotiony** [comment]
테스트해보니 알림이 잘 옵니다!
적용해 주셔서 감사합니다.
근데 마지막에 언급하신것처럼 true, false 인게 좀더 나았을것 같기도 합니다 ㅎㅎ

제가 https://github.com/lotiony/YonaHelper 만들어서 쓰는데,
저처럼 object to json으로 사용을 하게 되면 class에 sendNotification property를 추가해야 하고
알람 on/off 선택의 여지가 없게 되네요 ㅎㅎ
