### ISSUE TITLE
서버 이전시 Maria DB 내용을 잃어버린 상태서 복구 문의

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#379]
안녕하세요? 요나 프로젝을 사랑하는 일인입니다.

최근 요나를 호스팅하던 서버를 새로 이전하게 되면서, 
https://github.com/yona-projects/yona/blob/master/docs/ko/yona-backup-restore.md 문서에 안내되어 있는데로 작업 진행을 계획했습니다.

그런데 요나 이전을 위한 기존 데이터 백업을 맡은 엔지니어가 실수로 Maria DB 안에 Yona 데이터베이스를 백업 안했고, 이미 이전 서버에선 데이터가 다 완전히 깨끗이 지워진 상태라 어떤 것도 복구할 수 없게 되었고, 결국 기존 Maria DB 안에 Yona 데이터는 영원히 살 수 없는 상태가 되었습니다ㅜ.ㅜ

다만, yona-data 디렉토리 안에 4개의 서브 디렉토리(conf, logs, upload, repo)들만 살았습니다. 현재 요나를 새로 설치한 후 이들 4개의 디렉토리를 새로 설치한 디렉토리 안에 추가해서 요나 서비스를 띄워 요나 최초 화면이 정상적으로 뜨는 것까지는 작업된 상태입니다. 궁금한 것은 repo안에 소스들이 살아있는 기존 git 프로젝트들을 어떻게 다시 등록시켜서 활성화해 사용할 수 있을까요? 
저희가 지금 남은 백업자료(yona-data)만 가지고 최대한 복원을 한다면 어디까지 어떤 방법으로 가능할지 안내를 받을 수 있을까요?

늘 문제마다 도움을 주시는 요나팀에게 다시 한번 미리 감사를 남깁니다. 
감사합니다.

**Comment by doortts** [comment]
안녕하세요? 우선 올리신 이슈를 보고 한 참 멍하니 쳐다보았습니다. 

- 우선 저장소의 코드는 100% 복구 할 수 있습니다. (repo 폴더 이하)
- 업로드 파일도 upload 폴더에 모두 잘 보관되어 있긴합니다만 중복파일 업로드시 편의를 위해 hash id로 이름이 변경되어 있고 실제 파일명은 DB에 저장되어 있어서 DB 파일이 없으면 이름을 살려내긴 현실적으로 어렵습니다.
   - 다만 유닉스 명령어를 이용해서 어떤 종류의 파일인지 직접 찾아내고 확장자를 변경해서 읽을 수 있게 변경가능합니다.
```
file --mime-type 55c15232e51565530d73ed71ab7eb00e51bfa97573aa96b043ceabd34724ebc6

55c15232e51565530d73ed71ab7eb00e51bfa97573aa96b043ceabd34724ebc6: image/png
```

git 저장소 복구 방법
---

방법1 - Yona 에서 뜨도록 만드는 방법
---
- 새로 이전한 Yona 서버에서 미리 동일 소유자 및 동일 이름의 프로젝트를 만듭니다.
- 그 다음 repo/git 폴더에 이전 폴더를 덮어쓰기로 넣어 놓습니다.

예를 들면 이전에 JeongJun 소유자 하위에 translation 이라는 저장소가 있었다면 repo/git 폴더에 JeongJun 폴더와 그 하위에 translation 이라는 폴더가 보이실겁니다.
이 부분을 새 서버에 미리 만들어 놓은 폴더로 기존 파일들을 디렉터리째 붙여 넣으시면 저장소 코드가 보이기 시작하실 겁니다.


방법2 - 로컬PC에서 저장소만 복구하는 방법
---

백업받은 폴더가 /backup/repo/... 식일 경우 내 /home 아래로 저장소 코드 살려낸다고 가정한다면

```
git clone /backup/repo/JeongJun/translation 
```
하시면 현재 명령 실해 폴더(/home 으로 가정) 아래로 소스코드들이 되살아난 것이 보이실 겁니다.


음. 우선 부디 많은 데이터가 유실된건 아니길 먼저 바랍니다. 저희도 뭔가 이런 불의의 상황에 대비해서 반복되지 않게 시스템적으로 보완할 방법을 한 번 찾아보도록 하겠습니다.

**Comment by JeongJun-Lee** [comment]
빠르고 자세한 답변에 먼저 감사를 드립니다. 말씀해 주신 방법으로 차근차근 복구 중에 있고, 다행히 소스코드가 살아서 물론 각 개발자의 노트북 안에도 살아있긴 했었지만, 번거롭지 않게 기존 백업된 저장소를 덮어쓰는 방식으로 복구해 나가고 있습니다. 이런 실수 흔히 발견되긴 어려운 상황이지만, 혹시라도 도움이 되실 수 있게 wiki에 이 가이드를 남겨놓아도 좋지 않을까 싶네요^^ 

그건 그렇고, 하나 이슈인지 발견된 것은 새로 사내 로컬서버로 호스팅 장소를 옮기면서, 당연히 저장소 참조 URL이 변경되었습니다. 그래서, application.conf 안에 application.hostname 부분을 코멘트 처리한 후 요나를 다시 실행시켜 보았습니다. 그런데 이상하게도 기존에 url이 계속 살아서 돌아다니네요; 제가 실험삼아 new project를 만들어 copy url의 경로를 살펴봤는데, 이상하게도 기존에 url이 살아서 표시되고 있습니다. 참고로 요나 버전은 1.8입니다.

**Comment by doortts** [comment]
@JeongJun-Lee 주신 의견대로 wiki로 내용을 일부 옮겨 봤습니다.

![image](https://user-images.githubusercontent.com/520523/38789043-84a7294e-4172-11e8-9dd0-1693aa050868.png)

[Maria DB 내용을 잃어버린 상태에서의 복구 방법](https://github.com/yona-projects/yona/wiki/Maria-DB-%EB%82%B4%EC%9A%A9%EC%9D%84-%EC%9E%83%EC%96%B4%EB%B2%84%EB%A6%B0-%EC%83%81%ED%83%9C%EC%97%90%EC%84%9C%EC%9D%98-%EB%B3%B5%EA%B5%AC-%EB%B0%A9%EB%B2%95)

그리고 개발자 로컬 컴퓨터상의 git 저장소로 서버를 복구하는 방법에 대해서도 방법3으로 추가해서 간단히 적어 보았습니다.
[방법3 - 개발자 PC로부터 서버 코드 저장소 복](https://github.com/yona-projects/yona/wiki/Maria-DB-%EB%82%B4%EC%9A%A9%EC%9D%84-%EC%9E%83%EC%96%B4%EB%B2%84%EB%A6%B0-%EC%83%81%ED%83%9C%EC%97%90%EC%84%9C%EC%9D%98-%EB%B3%B5%EA%B5%AC-%EB%B0%A9%EB%B2%95#%EB%B0%A9%EB%B2%953---%EA%B0%9C%EB%B0%9C%EC%9E%90-pc%EB%A1%9C%EB%B6%80%ED%84%B0-%EC%84%9C%EB%B2%84-%EC%BD%94%EB%93%9C-%EC%A0%80%EC%9E%A5%EC%86%8C-%EB%B3%B5%EA%B5%AC)

**Comment by JeongJun-Lee** [comment]
오, 아주 깔끔하게 정리되었네요^^ 꼭 요나 뿐 아니라, 일반적인 git 사용에도 유용한 복구방법 안내가 아닐까 합니다. 수고 많이 해주셨네요. 그럼 이 이슈는 닫도록 하겠습니다! 감사합니다.
