### ISSUE TITLE
h2-v1.9.1 데이타 export/import 메뉴가 없습니다.

### ISSUE THREAD

**Issue by hsoo** [yona-projects/yona#384]
h2-1.8.1에서 h2-1.9.1로 업그레이드 할려고 우선 기본설정으로 임시 설치해 봤는데 데이타 메뉴가 안보입니다.

![h2-191-nodata](https://user-images.githubusercontent.com/1224237/39611344-f1296956-4f91-11e8-9551-e3374e9ef150.png)

**Comment by doortts** [comment]
Yona H2 배포판의 버전업의 특별히 export / import 기능을 사용하실 필요가 없습니다. 
[Yona 업그레이드](https://github.com/yona-projects/yona/wiki/Yona-%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%93%9C) 문서를 봐주세요.

그리고 v1.9부터는 해당 메뉴는 더이상 사용하지 않는 메뉴로 분류 되었습니다.

**Comment by hsoo** [comment]
https://github.com/yona-projects/yona-export 를 사용하여 1.9.1-mariadb 로 이전 했습니다.
