### ISSUE TITLE
이슈 템플릿 기능 위치

### ISSUE THREAD

**Issue by Charles1229** [yona-projects/yona#387]
안녕하세요.
v1.9.1 H2 버전으로 이슈 관리툴로 활용해 보고자 이것저것을 해보고 있습니다.

지난 이슈를 살펴보는 중 "이슈 템플릿" 이라는 좋은 기능이 적용되었음을 확인했습니다.
하지만, 제가 사용하는 버전에서는 찾기가 어려워 여쭤보고자 합니다.

제가 보고 있는 프로젝트 관리자 화면을 캡춰하였습니다.

![image](https://user-images.githubusercontent.com/30788230/39910271-7c114404-5531-11e8-8b3b-bdb27eb60b57.png)

**Comment by doortts** [comment]
@Charles1229 안녕하세요? 현재 이슈템플릿 기능은 git 기반의 프로젝트에서만 제공하고 있습니다.

**Comment by Charles1229** [comment]
넵 알겠습니다 답변 감사드려요~~
