### ISSUE TITLE
추가 한 이메일의 상태가 이상합니다.

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#39]
FF(Firefox) 에서 이메일을 추가 하고 확인 메일을 보냈습니다.

크롬에서 확인을 하니 크롬에서는 정상적으로 등록되었지지만 FF에서는 상태가 안변합니다.

이상해서 FF에서 다시  확인메일 전송 을 누르고 FF에서 확인하니 제대로 나오는데

이번에는 크롬에서 상태가 변경되었습니다. 이게 의도된 설계인가요?

정리..하면  

메일 확인을 한 브라우저는 '대표 이메일로 설정' 이 표시되고
![yona2](https://cloud.githubusercontent.com/assets/4251972/14591430/88df5acc-054c-11e6-98ee-29ed8d056667.png)

그렇지 않은 브라우저는  '확인 메일 전송' 이 표시됩니다.
![yona1](https://cloud.githubusercontent.com/assets/4251972/14591431/88e1750a-054c-11e6-8d1c-22df24f8d6da.png)

**Comment by doortts** [comment]
repo.yona.io 에서도 동일 문제를 발견하였고 패치를 만들어 v1.0.2 로 릴리즈 했습니다.
https://github.com/yona-projects/yona/releases/tag/v1.0.2
