### ISSUE TITLE
[건의] file://host/path URL 링크 적용

### ISSUE THREAD

**Issue by hsoo** [yona-projects/yona#392]
첨부하기 곤란한 대용량 동영상은 NAS로 공유중인데 link 가 생성이 안되서 file URL을 copy해서 브라우저에 paste해서 보고 있습니다.

file URL도 link가 되면 개발자들이 조금 편해질 것 같습니다. :)

**Comment by doortts** [comment]
@sjstyle 님의 도움으로 [v1.10](https://github.com/yona-projects/yona/releases/tag/v1.10.0) 에서 해당 내용 수정하였습니다. 적용 여부 확인 부탁드려요.

**Comment by hsoo** [comment]
링크는 잘 생성되는데 브라우져(크롬, IE11)에서 링크가 열리지 않네요.
왜 그런지 찾아보니 보안 이슈 때문에 file 링크를 클릭해서 여는것은 막았다고 하는데 기능을 요청한 사람으로써 좀 당황스럽네요.
그래도 url을 drag없이 우클릭으로 바로 링크복사가 되니까 조금 편해지긴 했습니다.
수고하셨습니다.

**Comment by sjstyle** [comment]
@hsoo 
안녕하세요. Yona에서는 file protocol을 완전히 허용했습니다만, 브라우저에서 file 프로토콜을 차단했기 때문에 여전히 클릭은 되지 않을 것이라 생각됩니다.

사실, file 프로토콜을 여는 것은 보안적으로 좋은 해결책이 아닙니다. 방문자의 파일들을 몰래 공격자의 서버로 전송할 수 있는 이슈를 만들 수 있습니다.

브라우저에서 차단했기 때문에 yona (를 포함한 어떤 웹 어플리케이션도) 에 코드로는 해결이 불가능하며, 브라우저에서 보안 옵션을 해제함으로써 사용할 수 있습니다.

https://stackoverflow.com/questions/22026984/trying-to-disable-chrome-same-origin-policy/22027002#22027002 를 참고하시어 Chorme 실행 옵션 뒤에 `--disable-web-security --allow-file-access-from-file` 를 붙이면 사용이 가능할 것으로 보입니다.

단, 해당 옵션을 끄게 되면 공격자가 심어놓은 스크립트로 사용자의 파일에 접근할 수 있게 되는 보안 문제가 생긴다는 것을 염두해 두셔야할 것 같습니다. (가급적 외부망과 단절된 PC에서만 사용하는 것을 추천합니다.)
