### ISSUE TITLE
[문의] 코드보기- 파일명에 '+' 포함된 파일

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#393]
## 발생 순서
- iOS Objective-C 프로젝트에서 엔티티 생성 시 자동으로 생성되는 파일 중 '+'가 포함된 파일명이 있음.
- 요나에서 Git 코드보기에서 해당 파일 선택 시 `master 브랜치가 없습니다. 기본 브랜치 설정을 확인해 주세요.` 메시지가 나타남.
- `http://domain/group/project-iOS/code/master/project%20folder/AgentData+CoreDataClass.m`
- 주소는 위와 같이 나타남.

**Comment by doortts** [comment]
[v1.10](https://github.com/yona-projects/yona/releases/tag/v1.10.0) 에서 해당 내용 수정하였습니다. 
확인 부탁드려요.

**Comment by berryzed** [comment]
@doortts 정상동작 확인하였습니다. 감사합니다!
