### ISSUE TITLE
[버그] 마일스톤 변경시 변경 안됨

### ISSUE THREAD

**Issue by spowner** [yona-projects/yona#395]
- 저는 관리자 권한이 있습니다

다른 사용자가 올린 이슈에 마일스톤이 배당되지 않아 마일스톤을 선택했습니다

![image](https://user-images.githubusercontent.com/5735665/40762131-5457353c-64da-11e8-9d7e-2da9d898061d.png)

변경되었다고 메시지가 표시되었지만, 실제로 해당 이슈는 마일스톤이 변경되지 않고 다음과 같이 표시됩니다.

![image](https://user-images.githubusercontent.com/5735665/40762156-7e076f8c-64da-11e8-8793-b51523a4f3b3.png)

위의 표시는 실제로 마일스톤을 없음으로 변경한 것이 아니라 마일스톤을 선택했는데도 불구하고 없음으로 변경된 모습입니다.

현재 설치형이 아닌 https://repo.yona.io에 프로젝트를 신설하여 사용하고 있고 URL주소는

https://spowner@repo.yona.io/spowner/pavetech 입니다

**Comment by doortts** [comment]
@spowner 안녕하세요? 혹시 가능하시다면 공개 프로젝트로 샘플하나 만들어서 재현해 주실 수 있을까요? 현재 링크 주신 곳은 비공개라 접근이 안되네요.

**Comment by hongwonjun** [comment]
@spowner 안녕하세요? 혹시 webhook 을 사용하고 계신가요?

**Comment by spowner** [comment]
네 webhook 쓰고 있습니다. IFTTT 연결되어 있습니다

**Comment by doortts** [comment]
[v1.10](https://github.com/yona-projects/yona/releases/tag/v1.10.0) 에서 해당 내용 수정하였습니다. 
확인 부탁드려요.
