### ISSUE TITLE
[버그?] 웹훅 설정한 프로젝트의 이슈 본문 변경이 되지 않습니다.

### ISSUE THREAD

**Issue by hyunseogi** [yona-projects/yona#396]
슬랙에 웹훅 설정을 한 프로젝트의 이슈 본문이 변경되지 않습니다.

정확히는 본인이 작성한 이슈 수정 시 '수정 알림 메일 전송' 체크박스를 해제 시에는 수정이 되나,

그 외 체크박스 설정 시에나 다른 사람이 작성한 이슈 본문은 변경 내용이 저장되지 않습니다.

웹훅 설정을 삭제했더니 정상적으로 본문 수정이 되는 것을 확인하였습니다.

**Comment by doortts** [comment]
[v1.10](https://github.com/yona-projects/yona/releases/tag/v1.10.0) 에서 해당 내용 수정하였습니다. 
확인 부탁드려요.

**Comment by doortts** [comment]
다른 문제가 발견되어서 현재 해당 fix 를 revert 하였습니다. 수정확인하지 않으셔도 되어요.
