### ISSUE TITLE
웹폰트 에 대하여

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#40]
시간 나실 때 정리 하는 것이 좋을듯 하여 건의 드립니다.

yona를 SSL 적용시켜서 테스트중 발견한 내용입니다.

1. yona는 docker에 올려서 포트 9000으로 올리고 아파치에 proxy로 연결합니다.
2. startssl 의 인증서를 발급 받아서 아파치에 적용했습니다.
3. application.conf에서 application.scheme="https"를 적용하니 잘 동작합니다.

**사용상의 문제점은 안 보입니다.  화면이 깨지지도 않습니다.**

크롬의 개발자 콘솔에서만 Mixed Content를 경고 합니다.

![font](https://cloud.githubusercontent.com/assets/4251972/14666564/326f6c5c-0715-11e6-88c6-625a292b8e2c.png)

http://deview.kr/font/ 의 경로에 있는 웹폰트들 입니다.

아마도 yona의 전신인 yobi가 deview에서 발표되던 시점에 리소스들이 아닐까 싶습니다.

대체가 가능하다면

https://www.xpressengine.com/forum/22768426
jsdeliver CDN에 올려져 있는 폰트로 대체하는게 어떨까 합니다.

yona에서 사용하는 nanum light도 있습니다. 
http://www.jsdelivr.com/?query=font-nanum

이상 건의 사항입니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.0.3 에서 해결합니다
