### ISSUE TITLE
비공개 프로젝트의 경우 프로젝트 목록에서 노출되지 않습니다.

### ISSUE THREAD

**Issue by jongjunseo** [yona-projects/yona#41]
먼저 v1.0.2 패치를 통해 비공개 프로젝트를 잘 쓰고 있습니다. 감사합니다.

다만 비공개 프로젝트의 경우 권한이 없는 사람들에게는 프로젝트 목록에서 노출되지 않아 다시 문의드립니다.

프로젝트 생성시 비공개 선택시 아래의 문구를 볼수 있는데.
> 멤버로 등록한 사람만 접근할 수 있습니다. 단, 프로젝트 이름, 설명, 로고 등은 모든 사용자가 볼 수 있습니다.

해당 문구로 유추해 볼때 원래 의도는 프로젝트 목록에서는 노출이 되는게 아닐까 생각했습니다.

확인 부탁드립니다.
감사합니다.

**Comment by doortts** [comment]
@jongjunseo 
초창기에는 비공개 프로젝트도 이름등이 노출되었었습니다만 추후에 의견이 모아진것이 `비공개는 그 존재자체도 다른 사람이 몰라야 한다.`였습니다.
아마 그렇게 변경후에 설명이나 몇 가지 변경을 미처 하지 못했거니 #36 과 같은 문제가 발생했습니다.

변경해야 할 것 같습니다.

**Comment by jongjunseo** [comment]
빠른 답변 감사합니다.
그렇군요. 저희는 보이는게 좋겠다 했었는데. 아쉽네요.

**Comment by painh** [comment]
저희도 사용하다보니 프로젝트 이름 정도는 나와야 한다 라는 니즈가 생겼는데, 혹시 설정 파일 등으로 분리할 수 없을까요?

**Comment by doortts** [comment]
@painh 음.. 예를 들면 어떤 경우에 그런 니즈가 강하게 느껴지셨었어요?

**Comment by painh** [comment]
@doortts 사내에 커밋된 소스 코드들엔 불행하게도 db 접속 정보등이 커밋되어 있어서 기본적으로 오픈을 할 수 없는 프로젝트들이 있습니다. 인프라 운영을 위한 간단한 툴이나, 정책이 불분명했을때 생성된 저장소들이 이런 상황이에요 또한 비개발자 직군도 저장소를 사용하면서 민감한 프로젝트들이 비공개로 생성되기 시작했습니다.

그런데 내부 개발자가 다른 팀 프로젝트의 소스코드를 참고 하고 싶다는 요구가 들어왔어요. 개인적인 호기심이나, 업무 효율성에 의한 것입니다. 타당한 사유이므로 진행하고 싶고요. ( http://channy.creation.net/blog/1110#.V3_bTLiLTuo )

그런데 여기서 문제가... 비공개 프로젝트가 다수가 된 상황이다보니, 최고관리자에게 어떤 것들이 있는지 물어보고 허락을 구하는 상황이 되었습니다 ^^;;

여기서부턴 아무래도 장벽이 생기다보니 한 단계라도 장벽을 줄이고 싶고, 때문에 원래 사라진 기능의 복구가 필요하게 되었네요.

감사합니다.
