### ISSUE TITLE
[버그] 크롬 브라우저에서 닫힌 PR 페이지가 보이지 않음

### ISSUE THREAD

**Issue by hurcy** [yona-projects/yona#414]
**증상**
{yona_project_url}/closedPullRequests?filter=&contributorId=#
크롬 브라우저에서 닫힌 PR 페이지가 보이지 않음.

**Comment by doortts** [comment]
@hurcy https://repo.yona.io 에서 재현 테스트 한 번 부탁드릴게요.

**Comment by hongwonjun** [comment]
크롬에서는 Pull Request 메뉴에서 탭 이동이 안 되는 현상이 발생하네요.
(https://repo.yona.io 에서 확인했습니다.)

Firefox 에서는 정상작동합니다.

**Comment by hurcy** [comment]
query params `?filter=&contributorId=#` 를 제거하면 닫힌 PR 목록이 보입니다.
