### ISSUE TITLE
서버이전 방법 문의.

### ISSUE THREAD

**Issue by junho103** [yona-projects/yona#415]
안녕하세요. 서버이전을 하게되서 yona를 옮겨야 하는 상황입니다.

신규서버에, 마리아디비, 요나 설치까지 진행한 상태입니다.

기존서버에 디비는 백업했구요

이후 과정은 어떻게 하면 되는지 궁금합니다.
 1. 사용자들이 올린 git 데이터 이전
 2. 요나 게시판에 올린 데이터들 (디비 백업해보니 용량이 얼마안되서, 게시판에 올린 첨부파일은 따로 옮겨야 하나 싶어서 문의합니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/blob/master/docs/ko/yona-backup-restore.md 를 참고해주세요!

**Comment by junho103** [comment]
@doortts 알려주신 링크참고해서 이전 잘 마무리했습니다. ^^ 감사합니다.~!
