### ISSUE TITLE
사용자 권한에 대한 질문입니다.

### ISSUE THREAD

**Issue by SmileJM** [yona-projects/yona#423]
yona를 사용하려고 하는데요
회원 가입 후 admin 이 사용자를 guest로 만들었는데도 guest 사용자가 프로젝트를 생성하고 그룹을 만드는데 지장이 없습니다. 안된다고 릴리즈 노트에서 보았는데 왜 그럴까요?
(현재 계정이 게스트인데도 가능합니다.)
![image](https://user-images.githubusercontent.com/27933203/43888290-3d141da0-9bfc-11e8-8614-37d57a334ca1.png)

또한, 그룹 멤버들이 readme.md 를 수정하거나 다른 멤버가 작성한 게시글을 수정하는 것을 막는 것은 할 수 없나요?

**Comment by doortts** [comment]
- 게스트 유저도 자신의 계정 하위에 프로젝트를 만드는 것에는 제약이 없습니다. 

게스트 계정 관련해서는 [게스트계정(Guest Account) 처리와 게스트 계정의 권한](https://github.com/yona-projects/yona/wiki/%EA%B2%8C%EC%8A%A4%ED%8A%B8%EA%B3%84%EC%A0%95(Guest-Account)-%EC%B2%98%EB%A6%AC%EC%99%80-%EA%B2%8C%EC%8A%A4%ED%8A%B8-%EA%B3%84%EC%A0%95%EC%9D%98-%EA%B6%8C%ED%95%9C)을 참고해주세요.
