### ISSUE TITLE
관리비 명세서 관련

### ISSUE THREAD

**Issue by suseo** [yona-projects/yona#429]
현재 날짜로 관리비 명세서 확인해보면

사육일이 마이너스로 나오는 cage 들이 있습니다.

정상인지 모르겠네요?

**Comment by doortts** [comment]
안녕하세요? 남겨주신 이슈만으로는 어떤 오류인지 판단이 어려운데요
문제되는 화면의 스크린 샷을 공유해주시거나 조금 더 상세히 설명을 해주실 수 있다면 상황 이해에 좀 더 도움이 될 것 같습니다.
