### ISSUE TITLE
시작 페이지 문구 변경 가능한가요?

### ISSUE THREAD

**Issue by iyananda** [yona-projects/yona#434]
21st Century Software Development Platform
Just focus on what you have to do

안녕하세요 개인 PC에 요나를 설치해서 잘 사용중입니다. 궁금한 점이 있는데, 시작 페이지의 이 문구 수정할 수 있는 방법이 있을까요?

**Comment by doortts** [comment]
현재는 해당 메시지를 수정하는 기능을 제공하고 있지 않습니다. 로그인하면 이후에는 보이지 않거든요. 
만약 강제 수정을 원하시는 경우에는 소스를 수정하셔서 새로 빌드하시면 변경가능합니다.

참고: https://repo.yona.io/yona-projects/yona/post/5

**Comment by iyananda** [comment]
답변 감사합니다!
