### ISSUE TITLE
yona 시작 페이지를 변경할 수 있나요?

### ISSUE THREAD

**Issue by SmileJM** [yona-projects/yona#438]
요나를 설치한 후 url로 접속하면 기본 제공되는 yona 페이지가 나오잖아요~
그런데 그것을 다른 화면으로 대체할 수 있나요?
처음 방문하였을 때, 이 사이트가 우리의 페이지라는 것을 보여주고 싶어요~
시작 페이지를 변경할 수 있는 방법이 있으면 알려주세요~

**Comment by sjstyle** [comment]
#434 와 동일한 문의로 보입니다.

**Comment by SmileJM** [comment]
감사합니다^^

**Comment by SmileJM** [comment]
소스코드를 내려 받아서 설치를 했는데요 혹시 어떤 파일을 수정해야 메인 페이지를 변경할 수 있는지 알 수 있을까요?

**Comment by SmileJM** [comment]
네 감사합니다^^
