### ISSUE TITLE
프로젝트,게시물,이슈등 삭제시 업로드한 파일삭제여부

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#44]
안녕하세요. 궁금한점이 있어 글을 작성합니다.

요비/요나에서 게시물,이슈에 파일업로드가 가능합니다.
만약 프로젝트,게시물,이슈 등이 삭제 되는경우 업로드된 파일도 같이 삭제가 됩니까?
db 및 uploads 폴더에 있는 파일삭제여부가 궁금합니다.

**Comment by doortts** [comment]
네 db 및 uploads 폴더에서 삭제됩니다. 다만 완전동일한 파일을 서로 다른 프로젝트에서 동시에 올렸을 경우에는 파일시스템에서 제거되지는 않습니다. 이유는 동일 파일을 여러번 업로드할 경우 서버 자원의 낭비를 막기위해 실제 파일은 하나만 시스템내에 존재하도록 설계되어 있기 때문입니다.

즉, 100M 짜리 인기 동영상을 누군가가 업로드를 여러번 여기저기 프로젝트에 하더라도 서버에는 100M 짜리 파일 하나만 존재하게됩니다. 모든 프로젝트가 삭제되거나 해당 파일이 첨부된 이슈나 게시글이 모두 삭제되면 그 때 시스템에서 파일도 같이 삭제됩니다. 그런데 엄격한 레벨의 100% 보장하는건 아니라서 해당 파일의 업로드나 삭제에 대한 트래픽이 클 경우에는 이론상 드물게 고아상태로 파일이 남을 가능성이 있습니다.

**Comment by yongseokleecom** [comment]
@doortts 
답변 감사합니다.
프로젝트 일부를 다른 요비로 이관해야 하는데, 요비간 프로젝트 이관방법이 없어
요비를 포크 후 이관 대상 프로젝트를 제외한 나머지 프로젝트를 모두 삭제 하는 방식을 진행하려 합니다.
업로드된 파일는 어떻게 되는지 궁금했습니다 ^^
