### ISSUE TITLE
windows server 2016에서 ssl 설정은 어떻게 하나요?

### ISSUE THREAD

**Issue by iyananda** [yona-projects/yona#442]
안녕하세요, 대학원 내의 협업지원 용도로 yona를 사용하려고 합니다. 일단 설치 후 작동이 되는것까진 확인해놓은 상태입니다.

저희가 도메인과 공인IP는 모두 가지고 있는 상태인데, 외부에서도 해당 시스템에 접속이 가능하게 하려고 합니다.

이런 상황에서 https로 yona에 접속하려면 어떻게 해야 할까요?

리눅스 시스템에 관한 내용은 많은데, windows server에 관한 내용을 찾기가 어려워 질문 올려봅니다.

**Comment by doortts** [comment]
- 우선 인증서 처리를 위한 아파치나 nginx 같은 웹서버가 필요합니다.
- 그리고 SSL 인증서가 필요합니다.
- SSL 인증서 설치는 letsencrypt 를 적용하시는 것이 합리적이고 SSL 인증서 설치용 봇은 https://github.com/PKISharp/win-acme 를 이용해보세요. 
- 웹서버 설정은 os 와 별개이므로 설정 관련 문서를 찾기 쉬우실거에요.
    - 위키 페이지의 [repo.yona.io 서버 구성 사례](https://github.com/yona-projects/yona/wiki#%EA%B8%B0%ED%83%80)를 참고해 보셔도 좋을 것 같습니다.
- 마지막으로는 application.conf 설정파일에서 schema에 https 적용을 표시하시고 도메인 이름을 hostname 에 적으시면 됩니다.

```
# Server
# ~~~~~

# Server name used by servlet, as the value of "Server" field in HTTP response message.
application.server="Play/2.3"

# Components used to construct the URL to this application.
application.scheme="https"
# application.hostname="www.yourdomain.com"
# application.port="8080"
```

**Comment by iyananda** [comment]
한가지 더 궁금한게 있는데, SSL설정은 어떻게든 해결을 할 수 있을 것 같습니다.

다만 현재 방식대로면 ip:9000으로 접속이 가능한 상태인데, https 설정을 통해 443포트만 열고 9000은 내부에서만 접속이 가능하도록 하고 싶습니다.

사용가능한 서버가 한대일때도 이 방법이 가능한지요?

**Comment by doortts** [comment]
https://repo.yona.io/yona-projects/yona-help/post/5 를 참고해 보시겠어요?

**Comment by iyananda** [comment]
음 이 설정은 알고있는데, 제가 말씀드리는건 요나 접근 자체를 외부에 오픈하지 않는 방식을 말씀드리는 거에요.

지금은 ip:9000으로 외부에서 http접속이 가능한데 이것 자체를 막는것이 가능한가 하는건데, repo 사례 문서에서는 yona2의 설정을 알 수가 없어서요

**Comment by doortts** [comment]
OS 가 어떤건가요? 윈도우를 쓰신다면 방화벽을 리눅스라면 iptables 를 이용하시면 어떨까요?
https://unix.stackexchange.com/questions/11851/iptables-allow-certain-ips-and-block-all-other-connection

**Comment by iyananda** [comment]
빠른 답변 감사합니다
OS는 windows server 쓰고있습니다
방화벽 세팅을 리버스 프록시에서만 읽을 수 있게 할 수 있나요?

**Comment by pokev25** [comment]
iis ssl  로 구글링 하시면 자료가 많이 나옵니다. 그대로 설정 하시고
요나와 iis 연결은 iis proxy로 검색 하시면 자료가 나옵니다.
서버의 기본 방화벽 설정에서 9000 포트를 열어주지 않으면 밖에선 접속 안되는게 기본입니다.

https://support.microsoft.com/ko-kr/help/324069/how-to-set-up-an-https-service-in-iis

http://studyforus.tistory.com/195

**Comment by iyananda** [comment]
예 빠른 답변 감사드립니다
