### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by fvlasie** [yona-projects/yona#445]
안녕하세요?

What are the hardware requirements for running Yona?

Specifically how much RAM does it require?

감사합니다

**Comment by doortts** [comment]
Hi~ 
You can use any os and machine which can install Java.
If you are using H2 DB version, basic RAM requirement is 1.5Gbyte. But we recommend using a machine which has more than 2Gb RAM.
We are running demo site https://repo.yona.io  in a 4Gb memory machine and also MariaDB has installed the same server.

**Comment by fvlasie** [comment]
감사합니다~
