### ISSUE TITLE
코드 검색이 되나요?

### ISSUE THREAD

**Issue by darongE** [yona-projects/yona#449]
프로젝트 소스코드를 검색하고 싶은데, 키워드를 넣으면
검색을 할 수 있나요?

**Comment by doortts** [comment]
TL;DR
---
아쉽지만 현재 소스코드 문자열 검색을 지원하고 있지 않습니다.

설명
---
예전에 코드 검색기능 구현을 위해 조사를 해 본 적이 있습니다. 조사 결과 Elastic Search 와 같은 검색엔진을 따로 설치해서 연동시켜야 한다는 결론에 이르렀고 여건상 지원이 어렵다고 판단했습니다.
