### ISSUE TITLE
Application.conf 파일이 적용이 안됩니다.

### ISSUE THREAD

**Issue by welikeheon** [yona-projects/yona#45]
안녕하세요,
우선 환경은 리눅스(우분투 14.04)이고, mariadb 를 사용하고 있습니다.

bin/yobi 를 통해 실행시키니, 문제가 다음과 같이 발생합니다.

<img width="762" alt="2016-04-27 5 07 27" src="https://cloud.githubusercontent.com/assets/8732888/14845650/8e00561e-0c9a-11e6-9dd0-204fd1c0bcf1.png">

application.conf 파일에는 분명히 주석으로 되어있는데,  mariadb@~~ 로 되지 않고, mysql@~~ 으로 되는 것을 보면 application.conf 파일이 제대로 적용이 되지 않는 것 같아보입니다.

application.conf 경로를 강제로 잡게 하는 방법은 있나요?

혹시나 해서 /etc/environment 에 YONA_HOME=/설치경로 로 잡고, source /etc/environment 로 갱신해봤습니다만,, 안되네요...ㅠㅠ

도와주세요!!

![c0085950_50f936856df00](https://cloud.githubusercontent.com/assets/8732888/14845731/1f0c365a-0c9b-11e6-8312-c51aad840792.jpg)

**Comment by brainagenet** [comment]
안녕하세요.
제가 사용하고 있는 startYona.sh Shell Script를 공유합니다.
참고가 되셨으면 좋겠습니다.

```bash
#!/bin/sh
# startYona.sh

export JAVA_HOME=/usr/java/jdk1.8.0
export YONA_HOME="/home/yona/data"
export YOBI_HOME=${YONA_HOME}
export YONA_BASE="/home/yona/engine/yona-1.0.0"

JAVA_OPTS="-server"
JAVA_OPTS="${JAVA_OPTS} -Xms2048m"
JAVA_OPTS="${JAVA_OPTS} -Xmx2048m"
JAVA_OPTS="${JAVA_OPTS} -Dsun.lang.ClassLoader.allowArraySyntax=true"
JAVA_OPTS="${JAVA_OPTS} -Djava.awt.headless=true"
JAVA_OPTS="${JAVA_OPTS} -Djava.net.preferIPv4Stack=true"
JAVA_OPTS="${JAVA_OPTS} -Dhttp.port=39000"
JAVA_OPTS="${JAVA_OPTS} -Dyona.home=${YONA_HOME}"
JAVA_OPTS="${JAVA_OPTS} -Dyobi.home=${YONA_HOME}"
JAVA_OPTS="${JAVA_OPTS} -Dconfig.file=/home/yona/data/conf/application.conf"
JAVA_OPTS="${JAVA_OPTS} -Dlogger.file=/home/yona/data/conf/application-logger.xml"
export JAVA_OPTS

nohup bin/yona > ./logs/server.log 2>&1 &
```

위와 같이 사용하여 Yona Upgrade시 `YONA_BASE` 경로만 변경해 주고 있습니다. 실제 데이타는 `YONA_HOME` 에 별도로 저장되고 있습니다.
