### ISSUE TITLE
소스빌드 사용시 다운로드 에러가 뜹니다

### ISSUE THREAD

**Issue by iyananda** [yona-projects/yona#453]
안녕하세요

요나 설치 버전을 잘 사용하고 있는 중입니다.

소스빌드로 사용해보려고 시도를 해보고 있는데, 

:::: WARNINGS
                [NOT FOUND  ] org.scala-lang#scala-reflect;2.11.1!scala-reflect.jar (0ms)

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::              FAILED DOWNLOADS            ::

                :: ^ see resolution messages for details  ^ ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-lang#scala-reflect;2.11.1!scala-reflect.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-lang#scala-reflect;2.11.1!scala-reflect.jar
Error during sbt execution: Error retrieving required libraries
  (see C:\Users\usr\.sbt\boot\update.log for complete log)
Error: Could not retrieve Scala 2.11.1

위와같은 메시지가 뜨면서 실행이 되지 않고 있습니다.

activator은 1.2.10 버전 사용했구요,

혹시나 버전 문제가 싶어서 1.3.7 버전을 사용해도

[error] (*:update) sbt.ResolveException: download failed: org.scalaz#scalaz-core_2.10;7.0.2!scalaz-core_2.10.jar(bundle)
[error] download failed: org.scalaz#scalaz-effect_2.10;7.0.2!scalaz-effect_2.10.jar(bundle)

이런 메시지가 나오면서 진행이 되지 않습니다.

어떻게 진행해야 할까요?

**Comment by doortts** [comment]
build.sbt 파일을 여서서
아래처럼 한 줄 추가해보시겠어요?
```
resolvers += "maven central" at "https://repo1.maven.org/maven2/",
```
![image](https://user-images.githubusercontent.com/520523/45548485-6fafdb80-b85f-11e8-8794-ac7c313e3ac1.png)

**Comment by iyananda** [comment]
말씀하신대로 하니 resolving이 작동합니다.

그런데 중간에 

[info] downloading http://repo1.maven.org/maven2/com/h2database/h2/1.3.176/h2-1.3.176.jar ...

이 부분에서 stuck이 되네요. 해당 파일을 웹에서 다운로드해보니 역시 98% 가량에서 진행이 되지 않고 멈추는 현상이 있습니다. central 에서 받아도 같은 현상이 발생합니다.

**Comment by iyananda** [comment]
.ivy2\cache\com.h2database\h2\jars\h2-1.3.175.jar

에 해당 파일을 인터넷에서 받아서 넣는 것으로 일단 해결이 됐습니다

mariadb-java-client-1.5.5.jar에서도 같은 문제가 생겨서 동일한 방법으로 해결했습니다.

**Comment by iyananda** [comment]
[warn] Note: F:\y\yona\app\utils\Markdown.java uses or overrides a deprecated API.
[warn] Note: Recompile with -Xlint:deprecation for details.
[warn] Note: F:\y\yona\app\controllers\CodeApp.java uses unchecked or unsafe operations.
[warn] Note: Recompile with -Xlint:unchecked for details.
[info] Packaging F:\y\yona\target\scala-2.10\yona_2.10-1.11.0.jar ...
[info] Done packaging.

(Starting server. Type Ctrl+D to exit logs, the server will remain in background)

입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다.

위와 같은 메시지가 뜨면서 실행이 되지 않습니다.

운영체제는 windows 10 입니다.

폴더는 위에 나와있듯 f:\y\ 입니다.

일단 인터넷에서 받은 h2-1.3.175.jar 파일은 공식 리포에서 받은 파일은 아니고, https://jar-download.com 에서 받은 파일입니다.

**Comment by doortts** [comment]
뭔가 저장소로부터 다운로드가 되지 않는 현상이 있는것 같네요. 말씀해주신 라이브러리들은 업데이트를 확인해 보겠습니다.

실행은 어떤 명령어로 하셨나요?

**Comment by iyananda** [comment]
실행은 ..\activator 이후에 start로 했습니다
일단 지금은 실행이 안 되는 문제가 생겼네요

JDK 버전은 1.8.0_181 로 사용하고 있습니다.

지금은
----

[info] Loading project definition from F:\y\yona\project
[info] Set current project to yona (in build file:/F:/y/yona/)
[yona] $ start
[info] Wrote F:\y\yona\target\scala-2.10\yona_2.10-1.11.0.pom
[info] Packaging F:\y\yona\target\scala-2.10\yona_2.10-1.11.0.jar ...
[info] Done packaging.

(Starting server. Type Ctrl+D to exit logs, the server will remain in background)

입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다.

-----

위와 같은 메시지가 나오면서 실행이 안 되네요

**Comment by doortts** [comment]
YONA_DATA 은 어디로 지정하셨나요?

[YONA_DATA 설정 (v1.3 이후 버전) (Windows)](https://github.com/yona-projects/yona/wiki/YONA_DATA-%EC%84%A4%EC%A0%95-%28v1.3-%EC%9D%B4%ED%9B%84-%EB%B2%84%EC%A0%84%29-%28Windows%29)

**Comment by iyananda** [comment]
f:\yona-data 로 지정되어 있습니다
start 말고 run으로 하니 일단 켜지기는 하는데, 접속을 하면 

![error](https://user-images.githubusercontent.com/38367140/45621879-00372780-babd-11e8-89be-e84b3d0ec4bb.png)

위와 같은 내용이 나오면서 실행이 되지 않습니다.

**Comment by doortts** [comment]
혹시 OpenJDK를 쓰고 계신가요?
저 문제는 뭐랄까.. 일반적인 상황에서 발생하는 에러는 아니거든요.

**Comment by iyananda** [comment]
아뇨 오라클에서 배포하는 버전입니다
처음부터 다시 시도해봐야겠네요

**Comment by doortts** [comment]
```
java -version
```
결과 알려주세요.
이상 없다면 다시 지우시고 처음부터 해보셔야 할 것 같습니다. bytecode 레벨에서 에러가 나는 상황이네요.

**Comment by iyananda** [comment]
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

JAVA_HOME 에 설정되어 있는건 1.8.181인데, 이게 javapath 라는 환경변수랑 충돌이 되었던 것 같습니다.

처음부터 다시 빌드해서 이제 실행이 됩니다만, 여전히  start로는 구문에러가 뜹니다. yona.bat의 150번째 줄 문제인듯 합니다.

run으로 가능하기 때문에, dist 버전을 만들어서 yona.bat을 수정하여 실행하면 실행이 됩니다.
아마 #8 과 같은 문제였던 것 같습니다.

이건 play activator 자체 문제인지요?

**Comment by doortts** [comment]
아. 150번째 줄을 지우세요. 
윈도우 유저의 슬픔입니다.

**Comment by doortts** [comment]
조금 더 설명을 드리면 start로 실행을 하면 package build 를 하게 되는데요 이때 관련 라이브러리들이 classpath 로 잡히게 됩니다. 그런데 윈도우에서는 이 classpath 지정에 글자수 제한이 있어서 문제가 발생합니다. 제가 보완 코드를 넣어 놓았어서 지우셔도 문제는 없습니다.

**Comment by iyananda** [comment]
음 그렇다면 윈도우의 경우는 start로는 불가능하고 dist를 해서 하는게 최선이겠군요

빠른 답변 감사드립니다
