### ISSUE TITLE
DB 초기화가 가능할까요?

### ISSUE THREAD

**Issue by iyananda** [yona-projects/yona#455]
안녕하세요

이번에 테스트를 끝내고 정식으로 내부망에 요나 서비스를 시작하려고 하고 있습니다.

혹시 데이터(git, 유저, 이슈)를 모두 초기화하는 방법이 있을까요?

**Comment by doortts** [comment]
다음 두 단계로 진행하시면 됩니다.

- DB DROP 및 재 생성
   - [DB-백업-및-이전-복구-방법](https://github.com/yona-projects/yona/wiki/DB-%EB%B0%B1%EC%97%85-%EB%B0%8F-%EC%9D%B4%EC%A0%84-%EB%B3%B5%EA%B5%AC-%EB%B0%A9%EB%B2%95#%EB%B3%B5%EA%B5%AC) 에서 DB 재생성 하는 부분을 참고해주세요
- 기존 폴더 내용 삭제
  - YONA_DATA 폴더 하위의 upload 와 repos 를 지우시고 재시작 하세요.

**Comment by iyananda** [comment]
예 감사합니다 정상적으로 작동합니다
