### ISSUE TITLE
다른 서버로 DB와 DATA를 옮겨도 정상작동하나요?

### ISSUE THREAD

**Issue by BaeJungHo** [yona-projects/yona#461]
설치 사용하던 유저입니다.

서버 유지비용 문제로 다른 서버로 옮기려고 하는데 DB 와 DATA 자료들을 그대로 옮겨서

사용해도 문제가 없나요??

**Comment by doortts** [comment]
네 문제 없습니다.
https://github.com/yona-projects/yona/blob/master/docs/ko/yona-backup-restore.md 를 참고해주세요.

**Comment by RenoKim** [comment]
저도 이전해봤는데 이상없었습니다.
