### ISSUE TITLE
gmail 사용 ID/PW 암호화 관련

### ISSUE THREAD

**Issue by edolramba** [yona-projects/yona#463]
mail 사용을 위해 conf 파일에 넣어놓은 ID/PW 는 암호화해서 전송이 되는지요?
yona 서버에서 mail 서버에 ID/PW 를 전송할 때 보안상의 이슈가 없는지 궁금합니다.
(보안상의 이슈가 있는 경우 메일 기능은 제외하려고 합니다.)
특별한 암호화 알고리즘을 사용해서 conf 파일에 넣을 수 있다면 해당 방법도 가이드 해주시면 감사하겠습니다.
현재 1.9.1 사용하고 있습니다.

**Comment by doortts** [comment]
요약
---
- 해당 위험이 존재합니다.
- 서버 자체의 접근 보안을 잘 유지해야 합니다.

설명
--
서버 설정파일에 들어가는 원격 메일서버의 id/pw 는 말씀하신 보안상의 이슈가 발생가능합니다. 

즉 만약 악의적인 목적을 가진 누군가가 서버에 접속하게 되는 경우 해당 문제가 발생할 수 있습니다. 따라서 서버 접속권한을 좀더 보수적으로 운영하시는 것이 좋습니다. 원격 메일 서버 같은 경우에는 id/pw 기반의 인증을 사용하지 않고 메일서버에서 허가된 ip 에서만 접근을 허용하는 식으로 다른 곳에서는 접근하지 못하게 하는 방식으로 보안을 제공하는 것도 고려해보세요. 메일 서버 설정에 따라 가능한 것으로 알고 있습니다.

**Comment by pokev25** [comment]
질문 내용이 메일을 전송 하기 위해서 메일 서버에 요청을 보낼때 평문으로 전송 하는가? 
라는 질문이라면 서버에 따라서 다를것 같습니다.  ssl을 지원 하는 서버면 암호화해서 전송 될껍니다.

**Comment by edolramba** [comment]
네, 답변 감사드립니다.
