### ISSUE TITLE
Github 프로젝트 연동할 때 Authentication failed 뜨는 경우

### ISSUE THREAD

**Issue by SooJungChae** [yona-projects/yona#464]
github 에서 작업하던 프로젝트를 요나로 가져오려고 합니다.

remote 는 연동한 상태고 push 를 해야하는데 
**Password for ...** 가 뜨더라구요.

저는 요나에 github 아이디로 로그인하기 때문에 github 비밀번호를 적었는데,
**Authentication failed** 가 뜹니다.

이런 경우에는 어떻게 해야하나요?

**Comment by doortts** [comment]
아래래와 같은 식으로 프로젝트 생성 할때 저장소를 불러오는 기능 말씀이신거죠?

![image](https://user-images.githubusercontent.com/520523/47003495-4ccc5c00-d16a-11e8-8853-40f391c5bf2f.png)

**Comment by SooJungChae** [comment]
저 화면은 어디서 볼 수 있나요?
#82 여기 링크 보면서 터미널로 따라했었습니다.

**Comment by doortts** [comment]
새 프로젝트 만들기를 선택 후
![image](https://user-images.githubusercontent.com/520523/47005794-7e93f180-d16f-11e8-8883-7fb47b109062.png)
하신다음

github 저장소 url을 입력하시고 
![image](https://user-images.githubusercontent.com/520523/47005833-93708500-d16f-11e8-9f5e-6c0702e3605c.png)

하면 remote git 저장소로부터 해당 저장소를 가져와서 프로젝트를 생성합니다.

**Comment by SooJungChae** [comment]
요나 프로젝트는 이미 있습니다.

기존에 있는 요나 프로젝트에 
기존에 있는 github 프로젝트를 추가하고 싶어서요

**Comment by pokev25** [comment]
git 저장소에서 코드 가져 오기 기능으로 코드를 가져오면 
요나는 요나대로 동작하고 github은 github대로 각자 저장소로 동작 합니다.

두개의 저장소가 하나처럼 동작 하지 않습니다.

터미널로 하셨다고 하니 다음의 명령으로 어느 서버로 push가 되고 있는지
remote 설정을 확인해보세요. 
```
git remote -v
```

**Comment by sjstyle** [comment]
@pokev25 님이 말씀하신것 처럼, `git remote -v` 명령을 수행해서 해당 저장소가 예전의 github 프로젝트와 연결되어있는것이 아닌지 확인해봐야할 것 같습니다.

다음과 같이 remote 경로에 github 이 있다면, 작업하고 계신것이 yona가 아닌 github.com에 올라가는 것입니다.

![screenshot from 2018-10-16 23-47-57](https://user-images.githubusercontent.com/4811664/47025183-f11bc600-d19d-11e8-9f3c-3ec3aa084572.png)

이런 경우, 다음 명령어를 통해서 yona를 추가할 수 있습니다.
아래 명령어에서 http로 시작하는 경로부분은 설치한 Yona의 경로에 맞게 수정해야합니다.

![screenshot from 2018-10-16 23-50-21](https://user-images.githubusercontent.com/4811664/47025381-4f48a900-d19e-11e8-82de-f35e9f13a3a0.png)

이렇게 설정하고 `git push yona master` 를 수행하게 되면 정상적으로 올리는 것을 볼 수 있습니다.
![screenshot from 2018-10-16 23-51-38](https://user-images.githubusercontent.com/4811664/47025487-8e76fa00-d19e-11e8-946d-7801acfe9338.png)

**Comment by SooJungChae** [comment]
안녕하세요 @pokev25 님, @sjstyle 님이 말씀하신 것처럼 현재상황은 remote 가 origin 과 yona 2개로 되어있습니다. yona 쪽으로 push 할 때 "패스워드가 다르다" 라는 문제가 나오는 상황입니다.

yona 는 github 로 로그인 한 상태이고,
push 할 경우 계정에 대한 로그인 정보를 물어보는데, 깃헙 패스워드를 치니까 오류가 나는 것 같습니다.

이럴 경우를 위해 yona 에 소셜 로그인이 아니라 새로운 아이디로 가입해둬야 하는건지 궁금하네요.

**Comment by sjstyle** [comment]
아, 그 경우에는 `사용자 설정-비밀번호 변경-비밀번호 재 설정` 에서 비밀번호를 설정해주셔야 합니다.

**Comment by SooJungChae** [comment]
해결했습니다!!! 감사합니다 😍
