### ISSUE TITLE
mobile에서 sub-issue생성메뉴가 안보여요

### ISSUE THREAD

**Issue by breadkim** [yona-projects/yona#467]
모바일에서는 서브이슈를 작성하기 지원이 어렵나요?

**Comment by doortts** [comment]
놓치고 있던 부분인데요 다음 버전에서 지원해 볼게요. 어렵지 않을것 같아요.

**Comment by doortts** [comment]
v1.12.0 에서 해당 문제를 수정했습니다. [릴리즈 노트](https://github.com/yona-projects/yona/releases)를 참고해주세요.
