### ISSUE TITLE
project transfer error

### ISSUE THREAD

**Issue by breadkim** [yona-projects/yona#468]
B group을 생성한 후
A group에 있는 프로젝트를  B로 옮긴후
이메일을 클릭해서 승인했는데
여전히 A group 소속으로 프로젝트가 존재하네요

**Comment by doortts** [comment]
https://repo.yona.io 에서 재현 테스트 부탁드려요.

**Comment by breadkim** [comment]
네, 이제 잘 되네요
감사합니다 :)
