### ISSUE TITLE
'MariaDB 767 byte 에러' 해결안됨

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#47]
'MariaDB 767 byte 에러'가 해결이 안됩니다.

- os : CentOS 6.7 x64
- java : 1.8 (yum install)

/etc/my.cnf

> [client-server]
> 
> [client]
> default-character-set=utf8mb4
> 
> [mysql]
> default-character-set=utf8mb4
> 
> [mysqld]
> collation-server=utf8mb4_unicode_ci
> init-connect='SET NAMES utf8mb4'
> character-set-server=utf8mb4
> lower_case_table_names=1
> 
> innodb_file_format=barracuda
> innodb_large_prefix=on

처음에 show variables like 'innodb_file%'; 을 했을 때 다른 값이 있었습니다.
그래서 
>MariaDB [(none)]> set global innodb_file_format_max = BARRACUDA;

을 넣어서 세팅을 변경했구요.

> MariaDB [(none)]> show variables like 'innodb_file%';
> +--------------------------+-----------+
> | Variable_name            | Value     |
> +--------------------------+-----------+
> | innodb_file_format       | Barracuda |
> | innodb_file_format_check | ON        |
> | innodb_file_format_max   | Barracuda |
> | innodb_file_per_table    | ON        |
> +--------------------------+-----------+
> 4 rows in set (0.00 sec)

그런데도 767 에러가 해결이 되지 않습니다.
서버 리붓 후에도 결과는 똑같네요... 다른 방법은 더 없을까요??

**Comment by doortts** [comment]
이미 한번 DB가 생성되버린 다음에 file format을 BARRACUDA 로 바꾸셔도 마찬가지로 767 에러가 발생하실거에요.

```sql
drop database yona; 
```
해보신다음 다시 진행해 보시겠어요?

**Comment by witbox** [comment]
넵. 잘 됩니다.
감사합니다^^
