### ISSUE TITLE
[문의]웹후크로 받은 메시지의 요나 이슈 링크 주소가 localhost 로 나오는 현상

### ISSUE THREAD

**Issue by dinoLee** [yona-projects/yona#478]
안녕하세요.
요나 버전 : 1.10.0

https://repo.yona.io/yona-projects/yona-help/post/6 을 보고, 
슬랙으로 요나의 이슈 메시지를 전송받고 있습니다.

그런데, 슬랙에 전송된 메시지에서 요나의 이슈 링크를 선택하면,
localhost:9000/ren/ThemeSolitaire/issue/36 처럼, 요나가 설치된 서버 주소가 아닌 localhost 로 표시되어, 해당 링크를 선택하면, 요나 이슈를 볼 수 없는 상태입니다.
관련되어 검색을 하니,
https://github.com/yona-projects/yona/issues/315
에서 application.conf 에서 application.hostname="" 의 주석을 풀고 여기에 설정하면, 제대로 될 까 싶어, 
application.hostname="192.168.0.90"  처럼 요나가 설치된 곳의 IP 주소를 넣었습니다.
요나를 재시작하고, 슬랙으로 메시지를 보냈으나, 동일하게 localhost 로 시작하는 링크가 나오고 있습니다. 
제가 기대하는 것은 192.168.0.90:9000/ren/ThemeSolitaire/issue/36 처럼 나오는 것입니다.
도움이 필요합니다.

추가.
https://repo.yona.io/yona-projects/yona/code/e33aa6bdbdb32e77a76929412c810f3b6563f1c8/docs/ko/technical/webhook-server-internal.md 에서 보니, 샘플데이터에,
"url":"http://localhost:9000/dddeeee/commit/c2f9f27ea16004020d1f4e846217c2825d217a12" 로 localhost 로 표시되고 있습니다.

추가.
https://github.com/yona-projects/yona/pull/324 와 비슷한 문제로 보입니다.

> 해결.
YONA_DATA 폴더의 application.conf 파일을 수정해야 하는데, 다른 곳의 application.conf 파일을 수정하여, 생긴 현상이었습니다. ^^;

**Comment by doortts** [comment]
@dinoLee 해당 문제는 새 버전으로 해결되셨나요?

**Comment by dinoLee** [comment]
1.10 버전애서 해결했습니다. YONA_DATA 폴더의 application.conf 파일을 수정해야 하는데 같은 이름의 다른곳의 파일을 수정하여 안되었습니다 ^^;

**Comment by veinfx** [comment]
감사합니다.  localhost 로 webhook 에서 스크립트 수정하고 이것저것하다 위글보고 해결했습니다.
