### ISSUE TITLE
Yobi - Yona H2 버전 문의사항

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#48]
안녕하세요.
소규모 인원이 사용하고 있어 H2 버전을 관리가 쉬워 사용을 선호합니다만
Yona는 H2 버전이 메인이 아님으로 선뜻 선택이 어려운것 또한 사실입니다.
선택을 참고하기 위해 두가지 질문이 있습니다.

1. Yobi 0.8.2 > Yona 1.0.x H2 버전을 사용하다. Yona 1.0.x > Yobi 0.8.2 변경이 가능한가요?
2. MariraDB 버전에 있는 데이터 Export/Import 기능을 H2 버전에서 지원이 불가한지?
![image](https://cloud.githubusercontent.com/assets/12702163/15118885/17e1c22a-1649-11e6-8177-d64270fba7b3.png)

답변 기다리겠습니다.^^
감사합니다.

**Comment by pokev25** [comment]
*주의! H2 버전은 v.1.0.0 이후로는 소극적으로 버전업이 될 가능성이 높으며 이후 MariaDB로의 이전은 지원하지 않습니다! *

라고 하셨으니 안될 것 같습니다.

다운그레이드도...보통 안되는게 맞겠지요. DB스키마가 다르니까요.

**Comment by yongseokleecom** [comment]
@pokev25 
아마도 지원계획은 없을꺼 같았는데, 재 확인차 이슈를 남겼습니다. ^^
감사합니다.
