### ISSUE TITLE
이슈의 날짜 input에 autocomplete 속성 off

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#480]
브라우저 자동완성 기능 때문에 불편합니다.

<img width="295" alt="2018-12-04 5 36 35" src="https://user-images.githubusercontent.com/718691/49429240-62194a80-f7eb-11e8-8911-56e35cf5a04b.png">

아래처럼 바로 보이게 해주세요.
<img width="301" alt="2018-12-04 5 36 41" src="https://user-images.githubusercontent.com/718691/49429239-62194a80-f7eb-11e8-804d-82b4a3d04440.png">

감사합니다. 잘 쓰고 있습니다.

**Comment by doortts** [comment]
v1.12.0 에서 해당 문제를 수정했습니다. [릴리즈 노트](https://github.com/yona-projects/yona/releases)를 참고해주세요.
