### ISSUE TITLE
issue에 첨부하는 파일의 용량한계를 설정할 수 있나요?

### ISSUE THREAD

**Issue by iyananda** [yona-projects/yona#482]
안녕하세요 연구실 업무용으로 yona를 설치해서 잘 이용하고 있습니다.
혹시 issue에 첨부할 수 있는 파일의 용량한계를 알 수 있을지요?
또 좀더 높은 용량으로 바꿀 수 있을까요?

항상 답변 주셔서 감사합니다.

**Comment by hyeonjae** [comment]
`application.conf` 의 `application.maxFileSize`으로 지정할 수 있습니다.
```yml
application.maxFileSize = 2147483454
```

**Comment by iyananda** [comment]
음 제가 사용하는 시스템에서 30메가 정도의 파일을 올리면 404 error이 출력됩니다.

![image](https://user-images.githubusercontent.com/38367140/49776312-dcdbeb80-fd3e-11e8-96e5-1dd00a56ee74.png)

설정은 초기값(=2gb)로 되어있는데, 어떤 문제가 있는걸까요?

**Comment by doortts** [comment]
혹시 아파치 같은 웹서버와 함께 사용하고 계신가요?

**Comment by iyananda** [comment]
음 방금 IIS의 설정이 용량제약을 걸고 있었다는 점을 발견했습니다.
도움 주셔서 감사합니다.
