### ISSUE TITLE
마일스톤 완료율 수정은 어떻게 하는 건가요?

### ISSUE THREAD

**Issue by nine4d** [yona-projects/yona#485]
마일스톤 완료율을 수정할 수 있는 방법이 있기는 한건지 궁금합니다.

**Comment by doortts** [comment]
미일스톤 완료율은 해당 마일스톤에 해당하는 이슈의 닫힘 비율로 자동으로 표시됩니다. 즉 따로 %를 지정할 수는 없게 되어 있습니다.
