### ISSUE TITLE
repository 에 문제가 있습니다.(opencastproject.org)

### ISSUE THREAD

**Issue by binarythink** [yona-projects/yona#49]
yona 를 설치해서 사용하다가.. play 프레임워크도 배울겸, 필요에 맞게 조금조금 소스를 바꿔보고,
싶은 마음에 github 를 클론해서 activator 에 직접 실행해보고 있는데요..

빌드 중에 `http://repository.opencastproject.org/nexus/content/repositories/public` 관련해서
아래와 같은 메시지가 자꾸 뜹니다.

> Server access Error: Connection timed out: connect url=http://repository.opencastproject.org/nexus/content/repositories/public/org/apache/apache/10/apache-10.jar

위에 저장된 라이브러리 파일 을 다른 레포지터리에서 받을 수 있는 방법은 없나요?

**Comment by doortts** [comment]
안녕하세요?
full log가 아니라서 어떤 라이브러리가 안 받아지는 건지 알수가 없습니다.
그리고 저장소는 여러개가 등록되어 있어서 한 곳에서 안 받아지면 다른 저장소에 물어보는 형식으로 되어 있기때문에 빌드 자체가 실패하는 것이 아니라 몇 저장소가 안되는 걸로 나오는건 무방합니다 .

물론 타임아웃이 걸릴때까지 시도하게 되서 최초 빌드 시간이 더 늦어지는 문제는 있긴 하죠.

추가로 사용하시는 java 버전과 OS, 그리고 play 버전도 알려주시겠어요?

**Comment by binarythink** [comment]
Window 10 입니다.
상세 버전은 다음과 같습니다.
* activator-dist-1.3.10
* java version "1.8.0_51"

**Comment by doortts** [comment]
내려받으신 play의 버전을 알려주시겠어요?
그리고 실행에는 문제가 없나요? 아니면 빌드가 실패하면서 실행도 되지 않나요?
