### ISSUE TITLE
아이디 로그인이 안됩니다.

### ISSUE THREAD

**Issue by ghost** [yona-projects/yona#492]
yona아이디를 만들었는데 로그인이 안됩니다. 
가장 큰 문제점은 비밀번호를 찾으려고 해도 찾아지지가 않습니다.

분명 username과 이메일 제대로 입력했음에도 불구하고 잘못됐다고만 나올 뿐입니다.

email은 peter.choi@biosenstech.com입니다. 확인 부탁드립니다.

**Comment by doortts** [comment]
repo.yona.io 에 만들었다는 이야기 이신거죠?

**Comment by chlwogns414** [comment]
yona를 설치하고 로컬 서버에서 아이디를 만들었는데 로그인이 불가하다고 나옵니다.

**Comment by doortts** [comment]
# application.use.email.verification = true

application.conf 에서 혹시 이부분을 설정하셨나요?

YONA_DATA 환경변수를 설정하셨는지도 확인해보시겠어요?

**Comment by doortts** [comment]
응답이 없는 이슈로 종결합니다
