### ISSUE TITLE
README.md 파일 수정이 안됩니다.

### ISSUE THREAD

**Issue by ferjjang** [yona-projects/yona#493]
README.md 파일을 수정/적용하려고 하는데 잘 안되네요;; 무슨 문제일까요?

repo.yona.io에서도 동일한 것 같습니다.

![1](https://user-images.githubusercontent.com/11627701/51376045-be8dba80-1b4a-11e9-9075-ce6f05a08a7d.jpg)

![2](https://user-images.githubusercontent.com/11627701/51376250-39ef6c00-1b4b-11e9-801e-4e9247c2967d.jpg)
![3](https://user-images.githubusercontent.com/11627701/51376272-42e03d80-1b4b-11e9-8e2c-950ef1d5e000.jpg)

**Comment by doortts** [comment]
repo.yona.io 에서 테스트 한 번 부탁드릴게요.

**Comment by doortts** [comment]
아! SVN은 README 온라인에서 수정이 안됩니다.

**Comment by ferjjang** [comment]
네 ㅜㅜ 감사합니다.
