### ISSUE TITLE
[문의] 이슈 라벨 api는 어떻게 써야 하는지요

### ISSUE THREAD

**Issue by pjinyang** [yona-projects/yona#494]
안녕하세요.

Api 사용 관련한 문의인데요,

/-_-api/v1/owners/:owner/projects/:projectName/issuelabel/:number
이슈 라벨을 부여하는 게 이 api로 하는게 맞는지요.

이슈 라벨 api를 호출할 때,
메시지 body가 어떤 형식이 되어야 하는지요.

**Comment by doortts** [comment]
우선 api 문서가 없어서 죄송합니다. 
네 맞습니다.

:number 는 이슈 번호이고
Body는 json 형식이고 라벨id를 배열형식으로 넘겨야 합니다.

프로젝트의 라벨아이디는 `/:user/:project/issue/labels`로 확인가능합니다.

예)
https://repo.yona.io/yona-projects/yona/issue/labels


인증이 필요한 모든 API 호출에는 HTTP 헤더에 인증정보를 같이 넘겨야 하는데요 

![image](https://user-images.githubusercontent.com/520523/51665946-3737bf80-2000-11e9-99ad-317d7fdd5a98.png)

두 가지 형식으로 지원합니다. 둘 다 동작은 동일합니다.

**Comment by doortts** [comment]
```
    @Transactional
    public static Result updateIssueLabel(String owner, String projectName, Long number) {
        JsonNode json = request().body().asJson();
        if(json == null) {
            return badRequest("Expecting Json data");
        }
        Project project = Project.findByOwnerAndProjectName(owner, projectName);
        Issue issue = Issue.findByNumber(project, number);
        Set<IssueLabel> labels = new HashSet<>();

        for(JsonNode node: json){
            Long labelId = Long.parseLong(node.asText());
            labels.add(IssueLabel.finder.byId(labelId));
        }

        issue.labels = labels;
        issue.save();

        ObjectNode result = Json.newObject();
        result.put("id", project.owner);
        result.put("labels", toJson(issue.labels.size()));
        return ok(result);
    }
```
