### ISSUE TITLE
yona 재실행이 안됩니다

### ISSUE THREAD

**Issue by jjw0216** [yona-projects/yona#496]
yona를 설치하고 실행 후 관리자 id도 만들고 저장소도 만들고 했었습니다.
그런데 오늘 서버가 재부팅된 후 yona를 다시 실행하려고 하니 아래와 같은 에러가 뜨면서 안되네요

![image](https://user-images.githubusercontent.com/7454538/51957126-b3615580-248d-11e9-9ff3-b7ff68a5d570.png)

yona가 설치된 경로는 아래와 같습니다
![image](https://user-images.githubusercontent.com/7454538/51957173-df7cd680-248d-11e9-9254-0488889ede1d.png)

JAVA_HOME 경로는 다음과 같이 설정해두었습니다
C:\Program Files\Java\jdk1.8.0_201

java폴더에는 다음과 같은 파일들이 설치되어 있습니다
![image](https://user-images.githubusercontent.com/7454538/51957214-0c30ee00-248e-11e9-94c7-35643c94a45d.png)

원인이 무엇이고 어떻게 해결해야 되는지 알려주시면 감사하겠습니다

**Comment by doortts** [comment]
실행하실때 사용하시는 자바 버전이 다른것 같습니다

```
java -version 
```

결과를 알려주시겠어요?

**Comment by jjw0216** [comment]
안녕하세요
답장 감사합니다
 
해당 명령어 실행 결과입니다
 
 
 
-----Original Message-----

**Comment by doortts** [comment]
@jjw0216 결과가 안보입니다.

**Comment by jjw0216** [comment]
![image](https://user-images.githubusercontent.com/7454538/52101592-a5433e80-261f-11e9-8359-0167b9c18e49.png)

실행 이미지입니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/blob/master/docs/ko/yona-run-options.md#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0 
를 참고해주세여.

- 환경변수 지정
- `./bin/yona` 로 실행

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/52104759-62896280-262f-11e9-9efa-60149f16e2f0.png)

**Comment by RenoKim** [comment]
잘모르지만, 간혹 RUNNING_PID 파일로 인해 안되는 경우가 있습니다. 지우고 실행해 보세요
