### ISSUE TITLE
[문의] 마크다운 편집기에서 코드 블럭 표현 오류

### ISSUE THREAD

**Issue by kiros33** [yona-projects/yona#497]
현재 1.11.1 버전으로 사용중입니다.

동일한 문법에 대해 github(및 다른 로컬 에디터)의 결과과 yona의 결과가 달라 문의드립니다.
(1.9 이전 버전과 1.10 혹은 1.11 의 결과도 다른 것 같습니다. 버전업을 해버려서 비교는 해보지 못했습니다.)

이슈는 두 가지 입니다.

1) 코드 블럭이 인라인으로 변경되어 표시됨
2) 공백을 앞에 추가해서 indentation 처리가 불가능함

결과는 아래와 같습니다.

github [gfm.md](https://gist.github.com/kiros33/d917033706905b17790d3b98594b5857)

<img width="857" alt="screenshot 2019-01-30 17 17 45" src="https://user-images.githubusercontent.com/1563133/51967926-f59d8d80-24b3-11e9-8dd1-ffd365e5e5ba.png">

yona

<img width="834" alt="screenshot 2019-01-30 17 17 33" src="https://user-images.githubusercontent.com/1563133/51967981-1ebe1e00-24b4-11e9-83f8-36538f581692.png">

**Comment by doortts** [comment]
해당 문제는 Yona 의 markdown 렌더링을 의존하고 있는 marked.js 의 문제로 보입니다.
Yona의 marked 버전업을 말씀주신 버전에서 진행했고 관련해서 발생한 문제로 판단됩니다.

marked 에서도 코드블럭 관련 버그 수정이 최근에 나왔고 Yona 다음 버전에서 반영하게 될 것 같습니다.

수정된 marked 대상버전: https://github.com/markedjs/marked/releases/tag/v0.6.0

**Comment by doortts** [comment]
v1.12.0 에서 해당 문제를 수정했습니다. [릴리즈 노트](https://github.com/yona-projects/yona/releases)를 참고해주세요.
