### ISSUE TITLE
h2 에서 mariadb로 한번에 마이그는 불가능 한가요?

### ISSUE THREAD

**Issue by drsmin** [yona-projects/yona#499]
안녕하세요

먼저 좋은 소프트웨어를 개발 공유 해주신 개발진들에게 감사의 말씀을 드립니다.

처음에 도입할 때 생각없이 h2 로 사용하다가 mariadb로 바꾸고 싶은데 
프로젝트 별로는 넘기는 기능이 있는거 같은데 한번에 다 넘기는 방법은 없을까요?

감사합니다.

**Comment by doortts** [comment]
아쉽지만 현재는 H2 에서 MariaDB로는 프로젝트별로 넘기는 방법만 제공하고 있습니다. 다만 스크립트를 만드시면 벌크(bulk)식으로 옮기시는 것이 가능합니다.

[project-import-bulk-실행](https://github.com/yona-projects/yona-export#project-import-bulk-%EC%8B%A4%ED%96%89) 의 스크립트를 응용하시면 될 것 같습니다.

**Comment by drsmin** [comment]
답변감사드립니다 환경그대로 다 넘기는 방법은 없나보네요 일단은 h2를 유지해야겠네요

**Comment by doortts** [comment]
저희는 MariaDB 사용을 권장하고 있습니다. H2 DB를 사용하실때는 백업등에 특히 유의해주세요. 고맙습니다
