### ISSUE TITLE
에디트 창에서 # 또는 @ 에러

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#50]
안녕하세요?

CentOS 6.7, Yona 1.0.2 bin 설치해서 테스트 중입니다.

근데 에디트 창에서 # 이나 @ 를 치면 팝업이 떠서 이슈나 참조 목록이 떠야하는데, 바람개비만 돌다가 나타나지는 않습니다.

작성을 마치고 본문창에서는 마우스오버 시 제대로 내용이 요약되어서 보입니다.

혹시 이런 이슈가 있는지요??

**Comment by doortts** [comment]
브라우저는 어떤걸 쓰세요?
chrome 브라우저에도 한 번 테스트 해 봐주시겠어요?

**Comment by witbox** [comment]
아,, 일시적인 문제였는듯 합니다. 서버 재시작하고 해결되었습니다.
