### ISSUE TITLE
[문의] 링크를 현재 페이지에서 열수는 없나요?

### ISSUE THREAD

**Issue by HEROHJK** [yona-projects/yona#500]
목록의 메뉴들을 클릭하면 항상 새 창으로 열리는것 같은데,

이걸 현재창으로 열수는 없나요?

버전은 1.11.1, Chrome 브라우저에서 사용중입니다.

**Comment by doortts** [comment]
같은 창으로 열렸었는데 변경된 부분인데요 현재 어떤 부분이 불편하신건가요?

**Comment by HEROHJK** [comment]
즐겨찾기의 모든 항목들이 새창으로 옮겨지네요,

업무일지, 코드관리를 다 다른데서 하다보니 왔다갔다 하기가 힘든데,

현재는 그냥 창을 미리 몇개 띄워놓고 쓰고 있습니다!
