### ISSUE TITLE
특정상황에서 Commit 메시지 한글 깨짐

### ISSUE THREAD

**Issue by HEROHJK** [yona-projects/yona#501]
[요나 프로젝트 페이지](https://repo.yona.io/testherohjk/%ED%95%9C%EA%B8%80%EA%B9%A8%EC%A7%90%ED%85%8C%EC%8A%A4%ED%8A%B8/code/master)

yona 1.11.1 버전을 이용하고 있습니다.

작업 중 mac Xcode에서 푸시한 자료에서 커밋메시지가 깨진다는 이슈를 받고 테스트를 해 보았습니다.

Chrome에선 이상없구요, IE 11에서 확인해본 결과 모음자음이 몽땅 분리되어서 나오네요

그래서 repo.yona.io 공식 데모페이지에서 실험 해 봤더니 역시나 똑같은 상황이 발생합니다.

PS. 

추가로 Edge브라우저에서 확인 해 본 결과 ,똑같이 한글이 깨지네요

**Comment by HEROHJK** [comment]
PS2.

다시 확인 한 결과 이건 github도 똑같은 상황이 발생하네요 ㅠㅠ Yona 이슈는 아닌것같아서 그냥 닫겠습니다 ㅠ

**Comment by pokev25** [comment]
https://blog.asamaru.net/2016/10/19/mac-os-git-korean-file-name-error/

https://blog.asamaru.net/2017/06/26/mac-os-git-korean-file-name-corequotepath/

이 옵션이면 아마도 해결 될 것 같습니다.
