### ISSUE TITLE
회원등급별 그룹/프로젝트 생성권한

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#51]
안녕하세요?

yona를 업무용으로 제대로 활용하려고 합니다.

회사의 업무용으로 사용하기에도 아주 좋은데, 한가지 기능이 추가되었으면 합니다.

참여자,관리자의 등급에 따라 그룹이나 프로젝트 생성권한이 달라지면 좋겠다는 것입니다.

예를 들어 admin 만 그룹생성 권한이 있고, admin 이 지정한 그룹관리자가 프로젝트 생성을 할 수 있는, 또는 프로젝트 생성권한도 부여할 수 있는, 이런 식의 제한을 두는 것입니다.

멤버는 누구나 그룹이나 프로젝트를 생성할 수 있는 자유로움을 조금은 제한하는게 좋겠다 싶어서 제안드립니다.

개발자님의 노고에 항상 감사드립니다.

**Comment by binarythink** [comment]
저도 최근에 회사에 적용을 생각하고 프로젝트를 관심있게 지켜보고 있습니다. ㅎ
사실 현재의 깃 허브와 너무 비슷해서 자도 오히려 권한에 중점을 두는 것은 어떤가 하는 생각입니다. 
그런데 아무래도 프로젝트를 시작하면서 고려하셨던 것들이 있었을 태니 요청이 쉽지는 않더라고요. 

저도 application.conf 파일로 허가제 가입등 사용할 수 있는 옵션들이 몇가지 있었지만 프로젝트내에 사용자 권한에 따라 코드 메뉴를 사용할 수 있는 권한이 추가되면 개발자들만을 위한 플렛폼이 아닌 기획자 테스터 모두 사용할 수 있는 개발 플렛폼이 되지 않을까 하는 생각이 듭니다.

**Comment by doortts** [comment]
@witbox 현재 그룹은 그룹 어드민이 아니면 그룹내에 프로젝트를 생성할 수 없습니다. (아니라면 버그리포팅해주세요)
다만 그룹내 프로젝트 생성에 대해 저는 `누구나 생성 가능`을 지지하는 편인데요 왜냐하면 멤버가 불필요하게 만들면 나중에 어드민이 옮겨주세요~ 말하면 되는데 반대로 그룹에 프로젝트를 생성하려면 구성원이 어드민에게 요청을 해서 생성받고 권한받고 해야 하는데 그게 더 불편하다고 생각해서입니다. 

@binarythink 메뉴별 접근권한에 대해서는 적지 않은 요청이 있었습니다. 권한체계를 추가로 만들거나 복잡하게 만들지 않으면서도 해당 기능을 지원하려면 어떤방법이 좋을지 고민입니다.

현재 권한은 일반 프로젝트 기준 관리자/멤버/게스트의 간단한 구성이거든요. 그리고 (의도적으로) 관리자와 멤버간의 권한 차이는 프로젝트 설정 관련이외에는 차이가 없는 상태입니다. 

어떻게 메뉴별 권한을 구성 하면 좋을까요?

**Comment by witbox** [comment]
@doortts admin이 그룹 생성 권한을 갖고 그룹관리자를 지정해 두면 그룹관리자는 프로젝트 생성권한을 갖도록 하는게 어떨까요?

**Comment by haare** [comment]
[https://docs.google.com/spreadsheets/d/1-BTL5gpkh4ULBKOUVLCPo6xt2TFsZn1zzNXd9AkoOzA/edit?usp=sharing](url)

@doortts 저희 조직 게시판같이 생각해봤는데용 어떠세요?

**Comment by sjstyle** [comment]
@haare 
말씀하신 권한은 현재 yona 설정으로도 가능합니다.
시스템 관리자 : admin
프로젝트 관리자 : 그룹 관리자
작성자 멤버 : 그룹 멤버
일반 멤버 : 그룹 멤버가 아닌 사용자 or 비회원(application.conf에서 접근이 허용 가능할 경우)

**Comment by haare** [comment]
@sjstyle 현재 돌려보고 있는데 참여자를 2분류로 (호스트/게스트???)나눌 필요가 '저희 조직'에는 있는것 같아요
물론 조바심이겠지만. 
이슈를 해결해야하는 입장에서 악의를 품고 이슈들을 다 삭제해버린다거나 다 닫아버린다면
이슈를 등록한 입장에선 벙찔 수도 있을 거 같아요
걸리면 실수였어요~ 라고 할 사람들도 있을거 같고 말이죠

한 프로젝트에 엄청 많은 이슈가 등록되었을 때 어떤 이슈에 변동이 생겼는지 다 알아채긴 힘듬을 악용하는 사람들이 없는 세상이 왔으면 좋겠어요 ㅋㅋ

**Comment by piriripipipi** [comment]
검색하다보니 여기까지 왔네요.
부서 안에서 이슈기능만 1년 반정도 사용하였고 타부서에도 적용을 해볼까 하는데요.

프로젝트 내용 자체는 공개더라도 이슈 작성, 편집은 해당부서에서만 할수 있도록 해야하는데 멤버가 아니어도 이슈 편집이 가능하여 약간 걱정이 됩니다.
기능이 없는 것인지 설정을 어디서 해야하는지 모르겠습니다.(1.15 버전입니다)
프로젝트를 비공개로 하기에는 로그인 안하고 내용만 확인하는 경우도 많아서 불편함이 있네요.

긍정적 검토 부탁드립니다 ㅠㅠ

**Comment by doortts** [comment]
@piriripipipi 의견 주셔서 감사합니다. 

>  멤버가 아니어도 이슈 편집이 가능하여 약간 걱정이 됩니다.

멤버가 아니면 이슈 편집 화면은 들어가져도 편집 자체는 안될거에요. (저장 버튼 자체도 표시되지 않아요)

그룹 멤버일 경우에는 조금 다른데 그 경우 해당 그룹내의 프로젝트 이슈에 대해서는 수정이 가능하지만 수정 내용은 이슈 변경 이력에 남고, 자신의 이슈가 아닌경우에는 해당 변경 내용이 지켜보는 모든 사람에게 발송되도록 되어 있습니다.

크게 걱정은 안하셔도 괜찮지 않을까 싶은데 어떨까요?

**Comment by piriripipipi** [comment]
@doortts 이슈작성이 가능하길래 당연히 편집이나 삭제도 가능하다고 착각했네요.

감사히 사용하도록 하겠습니다.
