### ISSUE TITLE
session timeout 설정

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#511]
yona 홈페이지에 로그인이 유지된 상태에서 로그아웃이 안되는 현상이 발생하네요.
session timeout을 설정하고 싶은데요. 어디서 설정할수  있는지 알고 싶습니다.

**Comment by doortts** [comment]
로그아웃을 클릭 해도 로그아웃이 안된다는 이야기 이신건가요?

![image](https://user-images.githubusercontent.com/520523/56332974-55f7bd80-61cd-11e9-805f-a7af62609ec4.png)

**Comment by iowtis** [comment]
로그아웃 버튼은 잘 동작합니다.
장시간 이용하는 이용자에 대해 session timeout 시간을 설정하고 싶어서요!

**Comment by doortts** [comment]
아쉽게도 세션 타임아웃을 따로 지정하는 기능은 현재 없습니다.

**Comment by iowtis** [comment]
답변 감사합니다~!
