### ISSUE TITLE
사용자 패스워드 강제 변경

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#513]
관리자가 사용자 계정 생성 후,
사용자가 로그인시 강제로 패스워드를 변경하게 하고 싶습니다.
그런 기능이 있을까요??

**Comment by doortts** [comment]
현재 아쉽게도 그런 기능은 없습니다. 다만 의도하신 동작을 우회해서 강요할 수는 있는데요 이를테면
계정을 만든다음 패스워드를 알려주지 말고 패스워드 찾기를 이용해서 로그인하도록 안내 한다던가 하는 식으로요.

그런데 계정을 관리자가 만들어서 제공하게 되는 상황은 어떤 이유때문인지 들을 수 있을까요?

**Comment by iowtis** [comment]
초기 구축단계인데 한명씩 회원가입하는 과정이 아니라, 
인사db에 있는 사용자들을 db에 넣고 계정 제공하려고 하거든요.
초기 로그인시, 패스워드를 변경하는 부분이 있는지 알고 싶었습니다 ㅠ_ㅠ

**Comment by doortts** [comment]
혹시 LDAP 을 사용할 수 있는 상황이신가요?

**Comment by iowtis** [comment]
따로 사용하지 않을 예정입니다
