### ISSUE TITLE
기본 담당자 지정

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#514]
프로젝트에 기본 담당자를 지정하고 싶은데요.
어디서 설정 가능한지 알고 싶습니다!

**Comment by doortts** [comment]
기본담당자라는건 어떤 역할이나 기능을 의미하시는건가요?

**Comment by iowtis** [comment]
![image](https://user-images.githubusercontent.com/39899020/56780009-8d431b80-6818-11e9-9e1f-32bfda4e1951.png)

이슈 등록시, 담당자가 디폴트로 할당되지 않은 상태인데요
이슈 등록시, 담당자를 제가 지정한 사용자로 변경하고 싶습니다.

**Comment by doortts** [comment]
특정 프로젝트에서 이슈를 만들면 특별히 지정하지 않아도 미리 지정된 누군가가 기본적으로 해당 이슈의 담당자가 되도록 만드는 기능을 말하시는 거지요?

**Comment by iowtis** [comment]
네 맞습니다!

**Comment by iowtis** [comment]
해당 이슈의 담당자가 되도록 만드는 기능이 있을까요?

**Comment by doortts** [comment]
아쉽게도 현재 자동으로 담당자를 지정하는 기능은 없습니다

**Comment by iowtis** [comment]
넵! 확인 감사합니다
