### ISSUE TITLE
이슈 공유 기능

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#515]
![image](https://user-images.githubusercontent.com/39899020/56790932-d0b18000-6840-11e9-8f51-1016dd02790b.png)

이슈 공유를 통해 다른 프로젝트에 이슈 공유를 하고 싶은데요.
프로젝트 검색을 어떤식으로 해야 하나요?
(프로젝트명을 바로 입력했을때는 검색되지 않습니다.)

**Comment by doortts** [comment]
확인해본결과 현재는 프로젝트 공개 범위가 "공개"로 되어 있는 프로젝트(의 멤버들) 혹은 사이트 내의 멤버, 둘 중 하나만 가능한 것으로 되어있네요.

**Comment by iowtis** [comment]
비공개 프로젝트는 공유가 안되는건가요?

**Comment by doortts** [comment]
네 현재는 어떤 이슈를 특정 비공개 프로젝트(의 멤버들)로 일괄 지정은 안되게 되어 있습니다. 자신이 접근 가능한 비공개 프로젝트도 지정가능하게 변경되면 좋겠네요.

**Comment by iowtis** [comment]
넵! 확인 감사합니다
