### ISSUE TITLE
Yona 최초 실행 불가

### ISSUE THREAD

**Issue by jinmh716** [yona-projects/yona#517]
안녕하세요.

MariaDB 1.12 기본 버전을 다운로드 했고
![image](https://user-images.githubusercontent.com/39205443/56950130-55650c80-6b67-11e9-9800-25f0f9181ed0.png)

MariaDB 버전으로 10.2인데 최초 실행이 안되고 있습니다.
![image](https://user-images.githubusercontent.com/39205443/56950240-95c48a80-6b67-11e9-88ad-65cb6c7bfed0.png)

Window OS환경이구요 
실행시 아래와 같은 에러 문구가 뜹니다.
![image](https://user-images.githubusercontent.com/39205443/56950324-cb697380-6b67-11e9-9979-8db43994933e.png)

DB에 일부 테이블은 생성된것으로 보입니다.
![image](https://user-images.githubusercontent.com/39205443/56950398-f784f480-6b67-11e9-85ea-d4ccaa217a2b.png)

conf파일도 첨부하였습니다.

감사합니다.
[application.txt](https://github.com/yona-projects/yona/files/3130519/application.txt)

**Comment by doortts** [comment]
DB가 일관성이 깨졌다고 에러가 나오는 상황으로 중간에 문제가 발생했다가 재개 한 것으로 보입니다. 
Yona 인스턴스를 내리신다음 DB를 삭제 재 구성 해보시겠어요?

**Comment by jinmh716** [comment]
해결 되었습니다.
감사합니다.
