### ISSUE TITLE
파일 업로드 용량

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#520]
안녕하세요.
프로젝트 이슈에 파일을 업로드하려고 하는데요.
파일 업로드 용량에 제한이 있는지 1MB 이상 업로드하면 에러가 나옵니다.

용량을 변경할수 있는 설정이 있을까요?

**Comment by iowtis** [comment]
에러코드는 error(413)입니다.

**Comment by iowtis** [comment]
Attachment Upload File Size Limit은 2GB 디폴트 설정으로 되어 있는데,

Zip,pdf 파일 올릴시, 업로드가 안되네요

**Comment by doortts** [comment]
apache 나 nginx 등의 web server를 사용하고 있으실 경우 그 쪽에서 사이즈 제한이 걸려 있을때 발생하는 에러로 유추됩니다.

**Comment by iowtis** [comment]
확인 감사합니다!! nginx 파일 업로드 디폴트 설정이 1MB이네요!

**Comment by iowtis** [comment]
혹시, 다운로드 전송속도 제한도 nginx 쪽일까요?

**Comment by doortts** [comment]
전송속도 제한은 잘 모르겠네요. Yona 에서는 특별한 제한을 걸고 있진 않습니다.

**Comment by iowtis** [comment]
답변 감사합니다.
