### ISSUE TITLE
[defect] 마일스톤 필터 > 이슈 상세 페이지 진입 > back key 동작으로 이전페이지 이동시 , 이슈 갯수 및 결함 상태값 오류(열림/닫힘)

### ISSUE THREAD

**Issue by jklee83** [yona-projects/yona#523]
![이미지 149](https://user-images.githubusercontent.com/49898957/58139434-8f609480-7c75-11e9-9d63-ed5885fb6d99.png)

[재현경로]
1. 이슈 탭 > 마일스톤 A 선택
2. 임의 이슈 선택 > 이슈 상세페이지 진입
3. back key 동작으로 이전 페이지로 이동 

[발생결함]
마일스톤 A에 등록된 이슈 개수 및 이슈 상태값(열림/닫힘) 오류 

[테스트 환경]
win7 / chrome

**Comment by jangyk27** [comment]
Windows 10 / Chrome 환경에서는 오류가 발생하지 않네요..ㅠㅠ

**Comment by jklee83** [comment]
테스트 주 환경이 win7 이라.. 수정 가능여부 확인 부탁드립니다 ㅠㅠ .. 이슈 상세 진입 후 이전 화면으로 돌아올 시 다시 마일스톤을 리셋후  재선택해야 하는 상황입니다 ㅠㅠ

**Comment by doortts** [comment]
@jklee83 chrome 버전이 어떻게 되나요?

**Comment by jklee83** [comment]
버전 74.0.3729.157(공식 빌드) (64비트)에서  74.0.3729.169(공식 빌드) (64비트) 로 업데이트 진행 후 확인 시, 해당 이슈 해결되었습니다.  버전 문제였네요 ㅠ 확인 감사합니다.
이슈 종료 처리 하겠습니다.
