### ISSUE TITLE
Yona 에서 GSuite LDAP 설정 질문드립니다.

### ISSUE THREAD

**Issue by dlehdanakf** [yona-projects/yona#524]
안녕하세요, 이번에 yona를 도입하면서 Gsuite 계정과 연동하기 위해 LDAP 기능을 사용하려고 하는데요,
대중적(?)으로 이용하는 기능이 아니다보니 별도 문서가 없는 것 같아서 불가피하게 질문드립니다.
yona 설치 주소는 `http://yona.intra.kung.kr/` 이구요!

LDAP 설정을 위해 `conf/application.conf` 파일에서 hostname 까지는 설정이 수월했는데 그 이후부터는 어떤 용어인지 모르겠어서 막혔습니다.

```
ldap {
    host = "ldap.google.com"
    port = 389
    protocol = "ldap"
    baseDN = "ou=scientists,dc=example,dc=com"
    distinguishedNamePostfix = "OU=user,DC=abc,DC=com"
    loginProperty = "sAMAccountName"
    displayNameProperty = "displayName"
    userNameProperty = "CN"
    emailProperty = "mail"
    options {
      useEmailBaseLogin = false
      fallbackToLocalLogin = false
      englishNameAttributeName = "givenName"
    }
}
```

위 설정값에서 `baseDN` 이하 옵션들에 어떤 값들을 넣어야하는지 감이 안옵니다..ㅠ
구글 설명서 링크는 https://support.google.com/a/answer/9089736?hl=ko 입니다.

![스크린샷 2019-05-30 오후 5 10 58](https://user-images.githubusercontent.com/12992959/58618569-ef9ea880-82fd-11e9-9e83-b5634babe013.png)

설명에서 주소가 `exmple.com` 으로 1차 도메인인데, 저와 같이 `yona.intra.kung.kr` 인 경우에는 어떻게 설정을 해줄 수 있을지 고민입니다..

도움 부탁드립니다 🙏
감사합니다.

**Comment by doortts** [comment]
저도 GSuite와 연동을 해본적이 없어서 뭐라 설명드리기가 조금 어려운데요
baseDN 은 dc=yona, dc=intra, dc=kung, dc=kr 처럼 하셔야 하는데요 
그것보다 GSuite 에서 제공하는 LDAP을 해본적이 없어서 뭐라 이야기 하기가..
