### ISSUE TITLE
첫 실행시 아래와 같이 에러가 발생합니다. 도움 부탁 드립니다.

### ISSUE THREAD

**Issue by rougevin** [yona-projects/yona#527]
리눅스에서 H2 DB 내장형(yona-h2-v1.12.0-bin.zip) 사용하려고 하고 있습니다.
java 버전은 1.8.0_211-b12 이구요.

bin/yona 실행하면 다음과 같은 에러가 발생합니다.
host 관련 에러인거 같은데 무슨 문제인지 잘 모르겠네요. 도움 부탁 드립니다.
host 명 : chtest

![image](https://user-images.githubusercontent.com/12853947/58933083-18f98180-87a1-11e9-9d4c-8ad38c15868e.png)

**Comment by doortts** [comment]
/etc/hosts 파일내에서 chtest 설정이 어떻게 되어 있나요?

**Comment by rougevin** [comment]
127.0.0.1   [chtest] localhost  
이렇게 되어 있습니다.

**Comment by doortts** [comment]
아 그런데 생각해보니 h2 DB 버전은 embedded 모드로 동작할거라 host를 찾아서 연결하는 과정이 없거든요. 혹시 어떤 설정을 따로 하셨나요?

**Comment by rougevin** [comment]
압축 풀고 bin/yona 실행한거 말고는 없습니다...

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/58936795-90cca980-87ab-11e9-9260-206d59d0cfcf.png)
실행하면 이런 식으로 로그가 올라와야 하는데요 혹시 다른 버전의 Yona가 설치되어 있나요? 그리고 환경변수에 YONA_DATA 가 어떤식으로 설정되어 있는지 알 수 있을까요?

**Comment by rougevin** [comment]
127.0.0.1 [chtest] localhost 이게 잘못된거네요.. 
127.0.0.1 chtest localhost  이렇게 변경하니 됩니다
근데 브라우저로 접속이 안되는건 왜일까요??

**Comment by doortts** [comment]
해당서버가 방화벽이나 네트워크의 분리등으로 80 포트로 접근이 안되는건 아닐까요? 

Yona를 우선 중단시키시고

```
python -m SimpleHTTPServer 9000
```
으로 실행해서 브라우저에서 해당서버 9000 으로 접근되나 확인해봐보세요

**Comment by rougevin** [comment]
네트워크 담당자에게 확인해보니 막혀있었네요. 답변 감사드립니다.
지금 admin 계정 만들었는데.. 서버 재시작 해야한다고 나오는데 재시작 해야하는거죠?

**Comment by doortts** [comment]
네. 이슈닫을게요.
