### ISSUE TITLE
신규 가입자가 그룹/프로젝트 생성 가능

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#53]
안녕하세요?

아래의 이슈에 이어서 하나 더 올립니다.

신규 가입자가 그룹을 생성하고 프로젝트를 생성하는게 당연하게 생각했는데, 원래 안되는거라는 내용을 보고 이슈 오픈합니다.

테스트계정은 이메일로 보내드리겠습니다.

**Comment by doortts** [comment]
오래된 이슈라 조용히 닫아봅니다.. 필요하시다면 다시 열어주세요.
