### ISSUE TITLE
yona 설치 및 git 설치 후 코드관리 문의

### ISSUE THREAD

**Issue by idhunters** [yona-projects/yona#541]
CentOS 7.2 버전과 MariaDB 10.2 사용을 하고있습니다.

설치버전을 다운받아 메뉴얼대로 설치완료 및 어드민 계정까지 끝낸 상태로 

시범적으로 프로젝트를 만들어서 소스관리 부분을 해보려는데 샘플명령어대로 git를 호출하면 no search directory가 나오네요

홈부분에 있는 README 파일 역시 작성하고 나면 작업할수없다 라고 나오며 등록이 안됩니다.

확인해야 될 부분이 있을까요

**Comment by rimichoi** [comment]
사용하시고 계시는 OS에 GIT 클라이언트가 설치되어있나요?

**Comment by idhunters** [comment]
[root@localhost ~]# rpm -qa | grep git
net-tools-2.0-0.24.20131004git.el7.x86_64
libglvnd-1.0.1-0.8.git5baa1e5.el7.x86_64
crontabs-1.11-6.20121102git.el7.noarch
libglvnd-glx-1.0.1-0.8.git5baa1e5.el7.x86_64
libglvnd-egl-1.0.1-0.8.git5baa1e5.el7.x86_64
linux-firmware-20180220-62.git6d51311.el7.noarch
git-1.8.3.1-20.el7.x86_64

이렇게 설치되어있습니다.

그리고 README.md 파일 만들기 시 아래와 같이 나오고
![image](https://user-images.githubusercontent.com/53301572/61926530-e6535480-afab-11e9-9018-0f7dcc5772a1.png)
![image](https://user-images.githubusercontent.com/53301572/61926553-f53a0700-afab-11e9-96ce-32691df29edf.png)


코드 부분에서 git와 연결하여 저장소를 만드려고 할 시

[root@localhost git_storage]# git clone http://bjh@192.168.1.230:9000/%ED%98%84%EB%8C%80%ED%95%B4%EC%83%81/%EB%B3%B4%EC%95%88%EC%8B%9C%EC%8A%A4%ED%85%9C_%EC%9E%91%EC%97%85%EC%8B%A0%EC%B2%AD%EA%B4%80%EB%A6%AC_%ED%85%8C%ED%8A%B8%EB%9D%BC%ED%8F%AC%EB%93%9C TEST
Cloning into 'TEST'...
warning: remote HEAD refers to nonexistent ref, unable to checkout.

[root@localhost git_storage]# cd TEST/
'# echo "# TEST" > README.md
'# git add README.md
'# git commit -m "Hello Yona"
[master (root-commit) cf321a5] Hello Yona
 Committer: root <root@localhost.localdomain>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1 insertion(+)
 create mode 100644 README.md

'# git push origin master
Password for 'http://bjh@192.168.1.230:9000':
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 268 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
**error: unpack failed: error No such file or directory**
To http://bjh@192.168.1.230:9000/%ED%98%84%EB%8C%80%ED%95%B4%EC%83%81/%EB%B3%B4%EC%95%88%EC%8B%9C%EC%8A%A4%ED%85%9C_%EC%9E%91%EC%97%85%EC%8B%A0%EC%B2%AD%EA%B4%80%EB%A6%AC_%ED%85%8C%ED%8A%B8%EB%9D%BC%ED%8F%AC%EB%93%9C
 ! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'http://bjh@192.168.1.230:9000/%ED%98%84%EB%8C%80%ED%95%B4%EC%83%81/%EB%B3%B4%EC%95%88%EC%8B%9C%EC%8A%A4%ED%85%9C_%EC%9E%91%EC%97%85%EC%8B%A0%EC%B2%AD%EA%B4%80%EB%A6%AC_%ED%85%8C%ED%8A%B8%EB%9D%BC%ED%8F%AC%EB%93%9C'

이와 같이 나옵니다. 테스트 프로젝트의 경우 이름만 TEST로 변경처리해서 CLI의 명령어 결과값 그대로 올렸습니다..

**Comment by doortts** [comment]
이경우 서버쪽의 환경설정 YONA_DATA 가 잘 지정되었는지, 그리고 해당 디렉터리에 yona를 실행한 계정이 wirte 권한이 있는지도 한 번 확인해 봐 주세요.

**Comment by idhunters** [comment]
확인 되었습니다.
여러 케이스를 확인하다보니 원인은 모르겠지만
1. 처음 요나 설치 후 테스트 및 서버 종료
2. 다음 서버를 on 했음에도 터미널로 실행했던 요나서비스가 죽어있었음
3. 백그라운드 실행 쉘을 만들어 작동시킴 (이과정에서 yona-data 경로가 변경됨)
4. 기존에 테스트때 만들어둔 프로젝트들이 제경로를 못찾음
5. 기존 yona-data 경로에서 값을  가져오면 정상작동

해결입니다.

감사합니다.
