### ISSUE TITLE
yona 사이트 관리자 계정 생성 페이지 skip하는 방법

### ISSUE THREAD

**Issue by CarpediemBDev** [yona-projects/yona#543]
안녕하세요..
맨처음에 yona를 설치형으로 설치하였다가
yona source 로 빌드하는 방법으로 요나를 설치했는데요
https://repo.yona.io/rtboss/Git_Yona_TortoiseGit/post/7

명령프롬프트로 run해서 시작한다음에 컨트롤 + D를 눌러 연결끊은다음에
다시 run명령어로 시작하면
관리자생성페이지로 나오게 됩니다. (이미 관리자는 생성되었고 다른계정도 만들어져있는데도 말이죠
run 명령어로 빌드 후에 관리자 생성페이지를 skip하는 방법이 있나요?

**Comment by doortts** [comment]
관리자 생성 페이지가 표시되는 이유는 application.conf 파일을 찾지 못해서입니다 application.conf 설정은 어느 위치의 파일로 수정하셨나요?

**Comment by CarpediemBDev** [comment]
C:\act\activator\yona\conf\application.conf 파일을 수정하였습니다.

**Comment by doortts** [comment]
개발환경에서도 환경변수로  YONA_DATA를 C:\act\activator\yona 로 지정해 주시지 않으면 yona 를 실행한 위치가 YONA_DATA 로 인식할 겁니다. 
 
즉,
환경변수 YONA_DATA를 지정하거나 (추천)
C:\act\activator\yona 에서 activator 를 실행하시면 될것 같습니다.

**Comment by CarpediemBDev** [comment]
감사합니다. 해당 방법으로는 실행해보지 않았는데 오늘 명령프롬프트를 켜고 다시 하니 관리자 계정 페이지가 안뜨고 skip되고 로그인하도록 되어있네요.. 음 변경한게 없는데 말이죠.. 희안하네요
