### ISSUE TITLE
yona data 폴더

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#544]
이직 후 간만에 yona를 시작 하려구 설치를 했는데...

흠... h2데이터 베이스 파일도 `YONA_DATA`로 생겨야 하지 않나 싶어서 문의 드립니다.

<- yona 1.12.0　　　　　　　　　　　　　　　　||　　　　yona-data ->
![yona_data](https://user-images.githubusercontent.com/5427199/62594356-569b9780-b915-11e9-8916-66f686b89c18.png)

**Comment by doortts** [comment]
네 환경설정은 동일하게 YONA_DATA 지정해야 합니다

**Comment by Terrorboy** [comment]
@doortts 

`application.conf` 파일의 
db.default.url를 

>  db.default.url="jdbc:h2:file:../yona-data/yona;MODE=PostgreSQL;MV_STORE=FALSE;MVCC=FALSE;CACHE_SIZE=131072;AUTO_SERVER=TRUE"

처럼 바꾸니 되네요.

감사합니다.

**Comment by doortts** [comment]
그러고보니 H2 버전의 경우 DB파일 자체도 YONA_DATA로 지정될 수 있으면 좋긴할것 같은데 application.conf 에서 말씀해 주신 default.url 을 수정해야 하는 상황이라 그 부분까지는 쉽게 지원은 안될것 같아요. H2 DB 버전은 지원 중단직전까지 갔다가 여력되는데까지 우선 지원하고 있는 상황이라 추가적인 H2 버전만의 기능에 시간을 투자하긴 어려울것 같습니다.

**Comment by Terrorboy** [comment]
@doortts 네네 어차피 맨처음에 1회만 수정 하는 부분이라 해당 부분을 안내(메뉴얼)만 해주면 되지 않을까 싶습니다.
