### ISSUE TITLE
데이터 Export 콘솔에서 가능할까요?

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#55]
근래에 좌충우돌 하면서 Yobi -> Yona를 무사히 마이그레이션 했습니다.
이번에 마이그레이션 하면서 보니까, 설정 -> 데이터 -> Export 한 내용을
그대로 Import 했을 때 매우 간결하게 진행되서 감동을 먹었습니다.

현재 백업을 구성하려는 도중, 이 부분을 Console 상에서 실행이 가능한지 여부를 알고 싶어서 이슈를 띄웠습니다. 

만일 가능하다면, 추출한 json과 uploads, repo 디렉토리만 백업하면 될 것 같습니다

**Comment by doortts** [comment]
yona 는 Maria DB를 사용하기 때문에 data backup은 MariaDB의 기능을 사용하시면 좋을 것 같습니다.

https://mariadb.com/kb/en/mariadb/mysqldump/

**Comment by minishanell** [comment]
해결된 내용 같아서.. 이슈를 닫습니다.
