### ISSUE TITLE
nginx + yona를 설치했습니다.

### ISSUE THREAD

**Issue by CarpediemBDev** [yona-projects/yona#558]
web 1대 :  nginx
was 1대 :  yona 를 설치하였습니다.
둘다 방화벽은 뚫어놓았는데

/etc/nginx/conf.d/nginx.conf 설정으로 아래와 같이 설정했는데
WEB서버 호출하면 YONA 이미지가 다 깨지던데 저 설정말고도 다른 설정이 더 필요한가요?

server {
  listen 80;
  server_name IP주소;
  server_tokens off;
  access_log /var/log/nginx/web_access.log;
  error_log /var/log/nginx/web_error.log;
  client_max_body_size 1024M;

  error_page 500 501 502 503 504 505 /pageError.html;
  error_page 400 403 404 422 /pageError.html;

  location = /pageError.html {
    root /etc/nginx/error_page;
    internal;
    charset utf-8;
  }

  location = /sb_error_icon.gif {
    root /etc/nginx/error_page/img;
  }

  location / {
    return 301 http://IP주소/yona;

    error_page 500 501 502 503 504 505 /pageError.html;
    error_page 400 403 404 422 /pageError.html;
  }

  location /yona/ {
    proxy_pass http://IP주소:9000/;
    proxy_http_version 1.1;
    proxy_set_header Accept-Encoding "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    error_page 500 501 502 503 504 505 /pageError.html;
    error_page 400 403 404 422 /pageError.html;

**Comment by yongseokleecom** [comment]
요나가 path 대응이 안되어있는거 같은데
최상위 경로 (/) 설정하시면 문제 없을듯합니다. 
저도 nginx + yona 조합으로 사용중입니다.

**Comment by CarpediemBDev** [comment]
저랑 같은 케이스였나요?
대단합니다 전 mime파일이 잘못되어 잉ㅣ지 파일을 못 읽는줄 알았어요 
그런데 혹시
최상위 경로 (/) 설정은  위에 설정부분에서 어디에  어떻게 해주면 되나요?
이해가 부족해서 죄송합니다 
미리 감사합니다

**Comment by yongseokleecom** [comment]
일반적으로 웹앱에서 URL 또는 Context 대응이 안되면 비슷한 현상이 발생합니다.

요나설정에서 Context 설정하시고 그래도 안되면 최상위로 변경하세요~
아래 방법중 하나로 하시면됩니다.

* 방법1. application.conf 의 context 설정변경 
application.conf 에 `application.context = /yona` 변경후 재기동하세요.
참고: https://github.com/yona-projects/yona/blob/master/docs/ko/application-conf-desc.md

* 방법2. 최상위 경로변경 

```
  location / {
    proxy_pass http://IP주소:9000/;
    proxy_http_version 1.1;
    proxy_set_header Accept-Encoding "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    error_page 500 501 502 503 504 505 /pageError.html;
    error_page 400 403 404 422 /pageError.html;
  }
```

**Comment by CarpediemBDev** [comment]
방법2. 최상위 경로변경

  location / {
    proxy_pass http://IP주소:9000/;
    proxy_http_version 1.1;
    proxy_set_header Accept-Encoding "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    error_page 500 501 502 503 504 505 /pageError.html;
    error_page 400 403 404 422 /pageError.html;
  }
이부분에서 뭐가 달라진건지 모르겠어요

--제 설정파일
location /yona/ {
proxy_pass http://IP주소:9000/;
proxy_http_version 1.1;
proxy_set_header Accept-Encoding "";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

error_page 500 501 502 503 504 505 /pageError.html;
error_page 400 403 404 422 /pageError.html;

**Comment by yongseokleecom** [comment]
location에서 yona가 빠집니다.

**Comment by CarpediemBDev** [comment]
너무나 감사합니다 
혹시 제 설정파일에서 변경된 부분이 yona뒤에 /붙이는  건가요?
변경전
location / {
return 301 http://IP주소/yona;
변경후
location / {
return 301 http://IP주소/yona/;

**Comment by yongseokleecom** [comment]
아니요~
location / 301 리다이렉한 설정이 빠지고
location /yona/ -> location / 이렇게 변경된겁니다.

**Comment by yongseokleecom** [comment]
## 변경전
```
location / {
  return 301 http://IP주소/yona;

  error_page 500 501 502 503 504 505 /pageError.html;
  error_page 400 403 404 422 /pageError.html;
}

location /yona/ {
  proxy_pass http://IP주소:9000/;
  proxy_http_version 1.1;
  proxy_set_header Accept-Encoding "";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  error_page 500 501 502 503 504 505 /pageError.html;
  error_page 400 403 404 422 /pageError.html;
}
```

## 변경후
```
location / {
  proxy_pass http://IP주소:9000/;
  proxy_http_version 1.1;
  proxy_set_header Accept-Encoding "";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  error_page 500 501 502 503 504 505 /pageError.html;
  error_page 400 403 404 422 /pageError.html;
}
```

**Comment by CarpediemBDev** [comment]
아 감사합니다 
교육 끝나고 적용해봐야겠습니다
정말  감사합니다

**Comment by CarpediemBDev** [comment]
해결되었습니다 
감사합니다
