### ISSUE TITLE
음 서버에 구성해보는것이 처음이라 질문드립니다.

### ISSUE THREAD

**Issue by CarpediemBDev** [yona-projects/yona#559]
putty로 요나가 설치된 서버로 들어가서
activator run을 하든 dev.sh 파일을 실행을 시키든 정상적으로 잘 동작합니다.

그런데 리눅스 putty 연결을 끊기면 실행된 yona도 같이 종료되는데 어떻게 해야하나요?
설치한 경로는 /srv/act/activator/yona 입니다.

일반 설치형이 아닌 배포형으로 소스받아서 설치하였습니다.

**Comment by doortts** [comment]
activator run 은 개발모드입니다
production mode에 비해 성능도 많이 낮고 중단시 바로 접속이 끊기게 됩니다.
`activator start` 로 실행 후 ctrl-D 로 끊으시면 중단되지 않으실거에요

https://www.playframework.com/documentation/2.3.x/Production

소스 기반으로 운영하실 예정이시라면 위 링크에서 참고할 내용을 발견하실 수 있을것 같습니다.

**Comment by CarpediemBDev** [comment]
감사합니다.
activator run 했을때에는 관리자 생성하라는 화면이 안보였는데
activator start 하니 보이네요
그런데 서버 재시작하라고 나오는데 어찌 해야하는지 가이드 홈페이지가도 Ctrl + d누르면 백그라운드로 간다는 말만있고 재시작, 중지가 안보이네요

**Comment by doortts** [comment]
관리자 생성하라고 보이는 이유는 YONA_DATA 환경변수가 지정이 되지 않아서 입니다.
보통 업로드 파일이과 코드저장소 파일들 설정들을 특정 폴더/디렉터리에 유지시키고 백업 및 복구, 버전업은 해당 컨텐츠 내용들과 무관하게 동작하도록 만들기 위해 YONA_DATA 를 따로 관리하고 있습니다.

repo.yona.io 라던가 내부 운영은 소스 기반으로 운영중인데요 이때 아래와 같은 간단한 스크립트를 만들어서 이용하고 있습니다

예제 설정은 제 로컬 노트북 기준으로 표시했습니다

```
# User this restart shell just for example
#
PORT=9000
YONA_DATA=/Users/doortts/repos/yona-data;export YONA_DATA
act=/Users/doortts/apps/activator-1.2.10-minimal/activator

pid=`ps -ef | grep java | grep activator-launch | awk '{print $2}'`
kill $pid
_JAVA_OPTIONS="-Xmx2048m -Xms1024m -Dyona.data=$YONA_DATA -DapplyEvolutions.default=true -Dhttp.port=$PORT" $act start
```

서비스 중단은 리눅스 계열에서는 kill 로 죽입니다. force kill 이 아닌 normal kill 을 사용해서 중지시키고 있습니다

:)

**Comment by CarpediemBDev** [comment]
감사합니다.
예제 설정대로 해보니 /yona/yoa-data 디렉토리에 conf, logs파일이 생성되었는데요..

기존에 /yona/conf 파일에 있는것을 다 여기로 옮기면 될까요?

**Comment by doortts** [comment]
네 옮기시면 해당 설정대로 동작합니다

**Comment by CarpediemBDev** [comment]
확인해보니 소스를 받아서 배포하게 두면 /yona/conf/application.conf 파일이 실행될때
/yona/yona-data폴더를 생성해두었으면 자동으로 만들어지도록 되어있던데 옮겨도 되고 안옮겨도 되는건가요? 정상동작은 합니다.

**Comment by doortts** [comment]
아직 특별히 따로 설정하신 부분이 없다면 따로 안 옮기셔도 됩니다.

**Comment by CarpediemBDev** [comment]
감사합니다.
그리고 위에 올려주신 쉘스크립트 감사합니다.
입맛에 맞게 수정하였습니다.
# User this restart shell just for example
#
PORT=9000
YONA_DATA=/srv/act/activator/yona/yona-data;export YONA_DATA
act=../activator

rm -rf /srv/act/activator/yona/target/universal/stage/RUNNING_PID
pid=`ps -ef | grep java | awk '{print $2}'`
echo $pid
kill -9 $pid
_JAVA_OPTIONS="-Xmx2048m -Xms1024m -Dyona.data=$YONA_DATA -DapplyEvolutions.default=true -Dhttp.port=$PORT" $act start

pid 가져오는 부분은 말씀해주신것처럼 했더니 정상적으로 못가지고와 수정하였습니다.
