### ISSUE TITLE
마일스톤 만들때 오류

### ISSUE THREAD

**Issue by h0ngz** [yona-projects/yona#56]
![image](https://cloud.githubusercontent.com/assets/5969709/15537928/0dd2d66c-22b4-11e6-980e-f79f3f79254a.png)

마일스톤 잘 만들어지다가

어느 순간 

![image](https://cloud.githubusercontent.com/assets/5969709/15537936/17b7bf3a-22b4-11e6-8aa1-c4964469c39d.png)

이렇게 오류 뜨더니
그다음부턴 계속 마일스톤 안만들어집니다.

ㅜㅜ

맨 처음 만든 프로젝트는 잘됐는데
두번째 프로젝트부터 이런현상 발생합니다
프로젝트 새로만들어도 계속 같구요.

**Comment by doortts** [comment]
버전이 어떻게 되세요?
최신 버전이 아니시라면 업데이트 해보세요.

그리고 admin으로 로그인 하시면 새 버전이 있을 경우 사이트 설정 페이지에서 알려주기도 합니다.

**Comment by h0ngz** [comment]
1.0.2 최신버전입니다. admin으로 사이트 관리가도 최신버전이라고 하고

프로젝트 위임 기능을 테스트해본 이후부터 그러던데..
(프로젝트 위임 시 프로젝트 주인에게 동의 메일이 와야하는데 안오더군요. ㅜㅜ)

**Comment by doortts** [comment]
혹시 프로젝트 이관작업을 admin 계정으로 하신건 아니시죠?
그리고 다른 프로젝트에서는 문제없이 잘 만들어 지나요?

**Comment by h0ngz** [comment]
네 일단 해당 문제가 한번 발생하면 계속 발생하는데

'서버 재부팅 (요나 재시작) ' 후 정상작동하네요 다시.

문제 있을때마다 재시작하면 해결되는것 같습니다.

**Comment by doortts** [comment]
불편을 드려 죄송한데요 환경문제인지 코드문제인지 확인이 조금 필요해서요.

repo.yona.io 에서 한 번 동일하게 작업해봐 주실수 있으세요?

#57 도 마찬가지로요.

**Comment by h0ngz** [comment]
https://repo.yona.io/h0ngz/TEST-PROJECT

#57 은 여기서도 마찬가지로 안되구요.

**Comment by h0ngz** [comment]
엇 오류를 내는 루틴을 찾았습니다. 제가 서버 처음만들어가지고 이것저것 해볼때 그대로의 행위를 재현해봤는데요

![image](https://cloud.githubusercontent.com/assets/5969709/15564009/d1e1166a-2348-11e6-8cc9-66b6bd80ee8f.png)

마일스톤 만들때 위와 같이 사진을 첨부하면서 생성한뒤

![image](https://cloud.githubusercontent.com/assets/5969709/15564029/e9f92ac6-2348-11e6-9cf9-458a158fa0c0.png)

수정을 통해 첨부사진을 삭제하고나면

![image](https://cloud.githubusercontent.com/assets/5969709/15564043/fcd7f140-2348-11e6-8b58-4f4b488eea17.png)


그다음 마일스톤을 만들대 위와 같이 에러가 납니다.

**Comment by doortts** [comment]
와우! 테스트해 고맙습니다.
https://repo.yona.io/h0ngz/TEST-PROJECT 에 관리자로 저를 추가해 주시겠어요?
재현하면서 문제원인을 찾아보겠습니다.

**Comment by h0ngz** [comment]
추가 테스트결과, https://repo.yona.io/h0ngz/TEST-PROJECT  프로젝트에
제가 다른계정으로 들어와서 마일스톤을 만드니 잘만들어집니다.

그후 다시 프로젝트를 만들었던 계정으로 들어와서 테스트해보니
또 서버오류메시지 뜹니다.

**Comment by h0ngz** [comment]
저 행위의 작업을 해서 오류가 발생하면 해당 오류를 낸 계정만 저 현상이 일어나며

그 계정으로 추가 프로젝트를 생성해도 다 막혀버립니다.

**Comment by doortts** [comment]
@h0ngz 여전히 문제가 남아있다면 다시 열어주세요.
