### ISSUE TITLE
https 적용관련 문의드립니다. 

### ISSUE THREAD

**Issue by bethleekor** [yona-projects/yona#561]
안녕하세요. 

기존에 linux에서 playframework 단독, http로 yona를 사용하고 있는데요.

nginx와 연동하여 yona 요청 시 
http-> https로 적용하려고 합니다.
(nginx에는 https를 적용한 상태입니다.)

혹시 가이드가 있는 지 궁금합니다.

**Comment by doortts** [comment]
nginx 에서도 reverse proxy 로 구성하시면 될 것 같습니다

apache 서버의 경우에는 아래 링크가 도움되실지 모르겠습니다.

[repo.yona.io 서버 구성](https://repo.yona.io/yona-projects/yona-help/post/5)

**Comment by bethleekor** [comment]
도움주셔서 감사합니다. 

말씀해주신 대로 nginx reverse proxy 설정에 proxy_pass http://서버ip:9000를 바라보도록 
구성하여 정상 동작 확인하였습니다.

하지만, yona 서버가 외부에서 접속 가능하여 http://서버ip:9000를 입력하여 
바로 접속하는 경우에는 https로 어떻게 처리할 수 있는 지 문의드립니다.

**Comment by localvoodoo** [comment]
- http로 요청하면 https로 redirect하는 설정 예입니다.
  - 80 포트를 위한 server block을 하나 만듭니다.
  - 80 포트로 요청이 유입되면 http status code 301를 반환하고 클라이언트가 https로 재요청합니다.  
```
server {
  listen 80;
  listen [::]:80;
  return 301 https://$host$request_uri;
}
```

**Comment by bethleekor** [comment]
늦은 시간까지 답변 주셔서 감사합니다.

제 설명이 부족했나봅니다.
nginx에  80, 443 관련 설정 및  말씀해주신 return 301도 하였으나
http://서버ip (default 80)로 접속하는 경우에는 https로 적용이 되지만

http://서버ip:9000으로 접속하는 경우에는
적용이 되지 않아 문의드렸습니다.
(9000포트의 경우 playframework에서 사용중)

**Comment by bethleekor** [comment]
-  다음에 연동하시는 분이 계실까 하여 설정한 정보 공유드립니다.
nginx에 설정을 아래와 같이 진행하시면 됩니다.

```
        server { 
                listen 80; 
                server_name 서버ip; 

                return 301 $scheme://서버domain$request_uri; 

        } 

        server { 
                listen 443; 
                server_name 서버domain; 

                ssl     on; 
                ssl_certificate         /root/security/ssl/cert.pem; 
                ssl_certificate_key     /root/security/ssl/key.pem; 
                ssl_session_timeout     20m; 
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers  HIGH:!aNULL:!MD5; 
                ssl_prefer_server_ciphers   on; 

                location / { 
                        proxy_buffering off; 
                        proxy_set_header Host $host; 
                        proxy_set_header X-Real-IP $remote_addr; 
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                        proxy_set_header X-Forwarded-Proto $scheme; 

                        proxy_pass http://서버ip:9000/; 
                        proxy_http_version 1.1; 
                 } 


        }
```

- 추가적으로 9000번 포트로 바로 접속 관련해서는 방화벽에서 처리 진행하였습니다.

**Comment by localvoodoo** [comment]
- yona는 외부에서 직접 접근 안되게 가급적 0.0.0.0이 아닌 127.0.0.1로 바인딩하는 것이 보안상 좋습니다.
- 보안을 위해서 nginx 설정은 아래와 같이 수정하셔야 합니다.
  - ssl_protocols  SSLv2 SSLv3 TLSv1; --> ssl_protocols TLSv1.2 TLSv1.3; 
  - nginx 설정을 위해서 두 사이트 참고 부탁드립니다 https://nginxconfig.io/  https://ssl-config.mozilla.org/

**Comment by bethleekor** [comment]
오호~ 정말 감사합니다. (_ _)

---- 확인----
헛.. 알려주신 값으로 설정 했을 경우에는 서버가 재구동 되지 않아서
ssl_protocols TLSv1 TLSv1.1 TLSv1.2; 로 설정하였습니다.

**Comment by localvoodoo** [comment]
취약점이 발견되어 조만간 TLSv1 TLSv1.1는 major browser 제조사(google, apple, microsoft)에서 지원을 중단할 예정입니다.
nginx에서 TLSv1.3을 사용하기 위해서 nginx (1.13+)빌드시 openssl 1.1.1 이상 버전의 소스를 이용해야합니다. 아래 url 참고 하셔서 미리 미리 준비하시기 바랍니다.
https://blog.naver.com/timberx/221543338758

**Comment by bethleekor** [comment]
와~ 정말 감사합니다. (_ _)
적용 후 설정 값 업데이트 하도록 하겠습니다.

---- 확인 ---
openssl 1.1.1 / nginx 1.16으로 업데이트 후 적용
