### ISSUE TITLE
yona의 계정이 잠겼습니다.

### ISSUE THREAD

**Issue by qkrxodud** [yona-projects/yona#566]
계정이 잠겨서 신규가입 할때 메일 url을 확인 하라는 alter가 뜨고 있는데, 가입 당시 메일을 찾아서 url을 눌러도 Invalid verification 이뜨면서 인증이 안되고 있습니다. 
참고로
아이디 : qkrxodud00
메일 : qkrxodud00@gmail.com 입니다.

**Comment by doortts** [comment]
다시 시도해보시겠어요?
