### ISSUE TITLE
혹시 계정 찾는 방법은 알 수 없을가요?

### ISSUE THREAD

**Issue by qkrxodud** [yona-projects/yona#567]
이메일 : typark@FreeCap.co.kr로 등록되있는 아이디는 찾을 수 없을가요 ?

**Comment by doortts** [comment]
coby 인것 같습니다

**Comment by qkrxodud** [comment]
이메일 :  typark@FreeCap.co.kr
으로 오늘말고 이전에 등록된 아이디는 못찾을가요 ?
