### ISSUE TITLE
프로젝트 정보 , 삭제 수정 안되나요?

### ISSUE THREAD

**Issue by h0ngz** [yona-projects/yona#57]
![image](https://cloud.githubusercontent.com/assets/5969709/15562045/a6abf5c6-2336-11e6-817e-68a1e63318cf.png)

프로젝트 정보를 테스트삼아 추가해보았는데 삭제가 안됩니다.
x 버튼 눌러도 반응이 없고.

j 라는 섹션자체를 삭제하는 것도 안되보이고

아직 미구현 상태인 부분인지, 저만 안되는것인지 모르겠습니다.

**Comment by minishanell** [comment]
프로젝트 정보~~ 저도 안되긴 해요. 아마 버그인가봐요!!

**Comment by minishanell** [comment]
현재(1.2.0) 수정이 된 것으로 보여 해당 이슈를 닫습니다. ^^
