### ISSUE TITLE
[문의] 요나 최초 로그인 확인메일이 안옵니다.

### ISSUE THREAD

**Issue by tidycatnero** [yona-projects/yona#578]
요나 최초 로그인 확인메일이 오지 않아 더 이상 진행이 되지 않습니다.

**Comment by doortts** [comment]
repo.yona.io 를 말하시는거라면 
![image](https://user-images.githubusercontent.com/520523/66282530-b228d800-e8fa-11e9-8862-880f0b11aa33.png)
 으로 사용하시는 메일 주소 보내주세요.
