### ISSUE TITLE
DB를 다른곳으로 옮길때 백업 방법

### ISSUE THREAD

**Issue by irinakim12** [yona-projects/yona#58]
Yona를 백업한 후  다른 PC에 옮기려고 하면 어떻게 하나요?
이전에 Yobi에서 질문을 보니 *.db파일/upload폴더/repo폴더를 복사해서 
overwrite하면 된다고 하긴하던데...
Yona에서는 repo폴더는 찾았는데, 다른 폴더와 파일들은 찾지 못해서...
정확한 위치를 알려주시면 감사하겠습니다.
빠른 답변  부탁드립니다^^

**Comment by doortts** [comment]
Yona를 MariaDB로 사용하신다면 .db 파일은 따로 존재하지 않습니다.
데이터는 마리아 DB의 백업을 이용하시는걸 권장드립니다.

https://mariadb.com/kb/en/mariadb/backup-and-restore-overview/

그래서 upload와 repo 폴더를 옮기시면 됩니다.
upload폴더는 파일을 업로드 하셨다면 생기셨을겁니다.
