### ISSUE TITLE
시놀로지 도커로 여기 설명대로 설치했는데 한글프로젝트명이 안되요

### ISSUE THREAD

**Issue by syseop** [yona-projects/yona#589]
한글 프로젝트명을 사용하면 에러가 나요
설치 가이드(https://repo.yona.io/yona-projects/yona/issue/26
 시놀로지 도커에 yona설치하기)를 따라 그대로 했구요. 
yona는 최신번전을 썼어요

**Comment by syseop** [comment]
[error] play - Cannot invoke the action, eventually got an error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /root/yona_data/repo/git/admin/???.git/config
[error] application -

에러 내용은 이렇구요. CentOS버전까지  아래 안내서에 나온 대로 설정을 했는데 동일한 증상입니다.
https://repo.yona.io/yona-projects/yona/issue/26

**Comment by doortts** [comment]
@pokev25 혹이 생각나시는부분 있으세요?

@syseop https://github.com/pokev25/docker-yona 에도 이슈 남겨보시겠어요?

**Comment by pokev25** [comment]
설치 방법 문서를 읽어보니 한글이 지원되지 않아서 발생 하는것 같습니다.

같은 이미지 받아서 locale 확인해보니 posix로 되어 있네요.
