### ISSUE TITLE
클립보드 이미지 붙여넣기 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#59]
크롬에서는 잘 됩니다.

IE 11, Firefox 에서는 동작 하지 않습니다.

**Comment by doortts** [comment]
네. 마지막으로 구현한 시점기준으로는 크롬에서만 동작하게 만들었고 (IE8시절이라)
그 이후로 새롭게 리뉴얼을 하진 않아서 그렇습니다. 
좀 아쉬운 부분이죠.

**Comment by pokev25** [comment]
구현방법이 브라우저마다 많이 다른가요?

티스토리에서 포스팅 하다가 파이어폭스에서 붙여넣기 해보니 잘 들어가더라구요.
