### ISSUE TITLE
비밀번호를 찾을 수 있는 다른 방법이 없을까요?

### ISSUE THREAD

**Issue by happyrich96** [yona-projects/yona#590]
가입할 때 이메일에 오타를 냈던건지.. 
제가 가진 모든 이메일 주소를 써봐도 틀렸다고 나와서요 ㅠㅠ
여기에 아이디랑 예측된 메일주소 모두를 쓰기는 조금 위험한듯 한데.. 1:1 비공개 문의로 해결할 수 있는 방법같은게 있을지요?

**Comment by happyrich96** [comment]
부탁드리기전에 혹시 몰라 최초 로그인 메일이라도 확인해보려 했는데, 웬만한 메일함 모두에 없는걸 봐서.. 지운건지 ㅜㅜ 찾을 수가 없네요.

**Comment by doortts** [comment]
혹시 가입한 곳이 어디신가요?

**Comment by doortts** [comment]
오랜기간 답이 없으셔서 닫음처리합니다
