### ISSUE TITLE
프로젝트 닫기기능

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#591]
프로젝트를 더이상 사용하지 않아, 종료하고 싶습니다.

데이터가 사라지는것은 원하지 않기 때문에 프로젝트 삭제 기능말고 이슈 닫기 같은 개념으로 가고 싶은데요.

프로젝트 소유자만 데이터에 접근을 하고 다른 인원들은 프로젝트 list에서 제거 할수 있는 방법이 있을까요?

**Comment by hongwonjun** [comment]
저는 아카이브 그룹을 만들어서 그 쪽으로 이동 시키는 방법을 사용하고 있습니다.

실제로 멤버를 삭제 한 후 별도의 그룹으로 옮기는 것으로는 해결할 수 없을까요?

**Comment by iowtis** [comment]
괜찮은 방법 같아요~ 답변 감사합니다!
