### ISSUE TITLE
이슈 작성자 이미지 삭제

### ISSUE THREAD

**Issue by hongwonjun** [yona-projects/yona#598]
현재 Issue 리스트의 각 아이템의 경우 작성자의 이미지와 이름이 모두 표시되고 있습니다.

담당자의 경우 이미지를 통해서만 그 정보를 확인할 수 있는데요,
전반적으로 작성자의 정보 너무 부각되는 부분이 있어서 그 이미지를 삭제하도록 건의를 해봅니다.

삭제 후에는 작성자는 텍스트로 그 이름이 표현되고 담당자는 이미지로 표현되는 형식으로 현재 github 도 같은 정책을 취하고 있습니다.

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/70864378-942fc180-1f94-11ea-83b7-567b874506f5.png)

위 이미지는 https://repo.yona.io/yona-projects/yona 의 이슈 목록 화면인데 아바타가 적절하게 되어 있지 않은 경우에는 작성자 이미지가 적절한 구분자가 되고 있지 않는것이 문제이긴 합니다.

아예 없애 버릴지, 작성자 아바타 이미지 표시 여부를 옵션으로 남겨둘지 조금 고민이 필요한 것 같습니다.
Github 이 잘 동작하고 있기 때문에 사실상 제거해도 크게 불편함은 없을 것 같긴하네요.
