### ISSUE TITLE
서버 관련 문의사항

### ISSUE THREAD

**Issue by 4aries17** [yona-projects/yona#6]
안녕하세요. 오늘 처음 요나를 사용해보았습니다.

gitlab이나 redmine같은경우 서버 컴을 두어 설치해서 사용테스트해보았는데,

요나의 경우에는 어떤방식으로 서버가 형성되어있는건가요 ?

회원가입하고 프로젝트를만드니 서버설치없이 바로 사용이 가능하던데 웹호스팅형태인가요 ?

그러기에는 업로드도 몇십메가자리 영상이 훅훅 올라가는거보면 .. 유료여야하지않을까싶은데

그런것도없고, 심지어 비공개관리도 되니

궁금하네요! 다른 라이센스가 있는건가요 ?

답변부탁드려요 :D

**Comment by doortts** [comment]
안녕하세요? 반갑습니다. : )
요나(yona)는 기본적으로 내려받아서 사용하는 설치형 SW입니다.
혹시 repo.yona.io 를 말씀하시는거라면 repo.yona.io는 현재 최신 버전의 Yona가 어떤 모습인지 볼 수 있도록 운영하는 일종의 데모서버입니다.
다만 데이터를 지우거나 할 계획은 현재로는 없기 때문에 원하시면 프로젝트 생성해서 동료분들과 함께 사용하셔도 무방합니다.

**Comment by 4aries17** [comment]
답변 감사합니다 :D
데모서버에서 사용해본 뒤 설치해서 사용해야겠네요 ~
번창하셔요 !
