### ISSUE TITLE
yona 접속을 https로 하게할려면 어떻게 해야합니까?

### ISSUE THREAD

**Issue by bulchor** [yona-projects/yona#60]
CentOS7에 요나를 설치했는데 접속이 http://127.0.0.1:9000 이런 식으로 됩니다.
https://http://127.0.0.1로 접속하게 할려면 어떤 설정을 해야합니까?

너무 초보적인 질문인가요?
리눅스 초보라 설치방법 따라서 설치만 한 상태입니다.

**Comment by doortts** [comment]
안녕하세요?  우선 설치에 성공하셨다면 축하드립니다! ㅎ

https로 운영하고 싶으신데 어떻게 하면 좋을지에 대한 질문이시죠?

Yona의 기반 프레임워크인 play 만으로 https 운영을 하고 싶으시면
https://www.playframework.com/documentation/2.3.x/ConfiguringHttps

혹시 apache 같은 web server 와 함께 사용해서 https 로 운영하실예정이라면
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-centos-7

nginx 를 쓰실예정이시면
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-centos-7

를 참고해 주세요.
repo.yona.io 도 비슷하게 작업했습니다.

**Comment by bulchor** [comment]
먼저 감사합니다.
첩첩산중입니다.

https 시작은 https://www.playframework.com/documentation/2.3.x/ConfiguringHttps을 참조해서 시작을 했는데 인증서 오류가 발생하네요...

인증서 생성을 따라하는데 잘 안되네요..
혹시 설치하실 때 사용한 파일이나 그런거 없을까요.
너무 어렵습니다.ㅜㅜ

**Comment by doortts** [comment]
인증서 오류라는게 어떤 오류세요?
기본적으로 SSL인증서는 구매하지 않고 개인이 서명을 만들면 오류?경고?가 뜨게 되어 있습니다.

그런 경우라면 SSL인증서를 무료로 발급해주는
https://letsencrypt.org/
를 한 번 이용해 보세요.

**Comment by bulchor** [comment]
https://letsencrypt.org/ 사이트의 certbot로는 진행하다가 중단됩니다. 
"The server could not connect to the client to verify the domain :: Failed to connect to 127.0.0.1:443 for TLS-SNI-01 challenge ...."

요나는 -Dhttps.port=9443으로 실행했습니다.
-Dhttps.port=443으로 실행해도 마찬가지고요..

**Comment by doortts** [comment]
아. 혹시 운영하시려는 서버가 127.0.01 즉 개인 localhost 라면 공인 SSL 인증을 받으실 수 없으세요. SSL을 브라우저에서 오류없이 운영하시려면 공인 IP가 있으셔야 합니다. 

비 공인상태로 브라우저의 경고와 거부를 강제무시해가면서 SSL을 private network 즉 127.0.0.1이나 192.xx~ 10.xx ~등에서 https를 사용하시는건 의미가 없지 않나 싶습니다.

localhost에서 https를 사용하시려는 이유가 어떻게 되세요?

**Comment by bulchor** [comment]
죄송합니다.
로컬 호스트에서 사용하는 것은 아니고 공인IP라서 표시를 127.0.0.1로 한 것입니다.
실 사용은 사무실 등 특정 존에서만 접속하도록 구성할 예정입니다.

**Comment by doortts** [comment]
@bulchor 따로 웹서버는 사용하지 않고 계신거죠?

**Comment by bulchor** [comment]
네
웹서버는 따로 없습니다.
웹서버를 설치해도 상관은 없습니다, 
보시고 간단하게 할 수 있는 방법을 알려주셔도 됩니다.

**Comment by doortts** [comment]
링크 보고 따라하셨으면 특별히 문제가 될 부분은 없으실것 같은데요 혹시 도메인도 구매하셨나요?

**Comment by bulchor** [comment]
회사에서 사용하는 도메인은 있습니다.
https://letsencrypt.org/ 사이트의 certbot로 인증서 생성을 진행하면 certbot이 443포트로 접속을 하면서 체크하는 것 같은데 yona는 9443으로 포트지정(-Dhttps.port=9443)이 되어있어 443접속에 대응하지 못하는 것 같습니다.
yona 포트를 443으로 지정(-Dhttps.prt=443)해서 실행해도 마찬가지고요.

certbot없이 인증서를 발급받으려고 하니( Generating X.509 Certificates Section 참조) 뭔 말인지도 잘 모르겠고, 너무 복잡해서 엄두가 안나네요...

**Comment by pokev25** [comment]
요나만 사용해서는 인증서 발급이 어려울것입니다. 나중에 인증서 적용도 어렵구요.
인증서 관련 설정은 아파치 혹은 nginx에서 하시고 요나 서버는 proxypass로 연결하세요. 

개인적으로는 startssl의 무료 인증서 발급을 추천합니다. 
저도 letsencrypt로 몇번 하다가 실패하고 startssl에서 발급 받아 적용했구요.

https://blog.outsider.ne.kr/1178
이거 보구 수작업으로 해서 발급 받는데 성공했지만..그냥 startssl사용하기로 했습니다.

그리고 요나의 application.conf에서 다음 두줄을 설정하세요.

application.scheme="https"
application.hostmane="mydomain"

발급 받은 SSL 인증서 적용은
서버에 설치된 정확한 버전을 확인하시고 다음의 링크에서 추천하는대로 설정하세요.
https://mozilla.github.io/server-side-tls/ssl-config-generator/

저는 Modern으로 설정해서
제가 설정한대로 셋팅하면 IE6에서는 아마 접속이 안될껍니다.
IE6를 접근대상으로 생각하시면 Old설정으로 하세요.

제가 사용하는 설정입니다 - 우분투 14.04 아파치에서 사용합니다.
https://gist.github.com/pokev25/fba0d6ec89d112fcf56e3977dc38ea98


ssl설정 관련 제가 참고한 링크입니다. 
https://www.xpressengine.com/tip/23021383

**Comment by bulchor** [comment]
요나만으로는 어려운거군요...

꼭 https가 필요한 것인지 다시 한번 고민해본 후 설명해주신대로 작업을 해보겠습니다.

도움주신 분들 모두 감사드립니다.

**Comment by doortts** [comment]
@pokev25 고맙습니다!!!
@bulchor repo.yona.io 같은 경우에는 앞에 아파치 웹서버를 두고 내부는 virtual host로 연결했습니다.

httpd.conf 파일은 우선 http로 들어오면 다 redirect 시켜버리게 만들었고요
```sh
...
...
<VirtualHost *:80>
  ServerName repo.yona.io
  Redirect permanent / https://repo.yona.io/
</VirtualHost>
...
...
```

yona는 그냥 내부 ip 와 9000번 포트로 띄워놓고 VirtualHost로 연결시켰습니다.

ssl.conf 에는 
```sh
...
...
<VirtualHost _default_:443>
ProxyPreserveHost On
ServerName repo.yona.io:443
ProxyPass  /excluded !
ProxyPass  /robots.txt !
ProxyPass / http://127.0.0.1:9000/
ProxyPassReverse / http://127.0.0.1:9000/
ErrorDocument 503 "/home/doortts/home-yona/503.html"

<Proxy "https://repo.yona.io">
  ProxySet connectiontimeout=5 timeout=5
  ErrorDocument 503 "/home/doortts/home-yona/error/503.html"
</Proxy>

#   SSL Engine Switch:
#   Enable/Disable SSL for this virtual host.
SSLEngine on

#   SSL Protocol support:
# List the enable protocol levels with which clients will be able to
# connect.  Disable SSLv2 access by default:
SSLProtocol all -SSLv2 -SSLv3

#   SSL Cipher Suite:
# List the ciphers that the client is permitted to negotiate.
# See the mod_ssl documentation for a complete list.
SSLCipherSuite DEFAULT:!RC4:!EXP:!SSLv2:!DES:!IDEA:!SEED:+3DES

#   Server Certificate:
# Point SSLCertificateFile at a PEM encoded certificate.  If
# the certificate is encrypted, then you will be prompted for a
# pass phrase.  Note that a kill -HUP will prompt again.  A new
# certificate can be generated using the genkey(1) command.
#
# SSLCertificateFile /etc/pki/tls/certs/localhost.crt
SSLCertificateFile /etc/ssl/certs/repo.yona.io.crt

#   Server Private Key:
#   If the key is not combined with the certificate, use this
#   directive to point at the key file.  Keep in mind that if
#   you've both a RSA and a DSA private key you can configure
#   both in parallel (to also allow the use of DSA ciphers, etc.)
#
# SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
SSLCertificateKeyFile /etc/ssl/certs/yona.io.key

#   Server Certificate Chain:
#   Point SSLCertificateChainFile at a file containing the
#   concatenation of PEM encoded CA certificates which form the
#   certificate chain for the server certificate. Alternatively
#   the referenced file can be the same as SSLCertificateFile
#   when the CA certificates are directly appended to the server
#   certificate for convinience.
#SSLCertificateChainFile /etc/pki/tls/certs/server-chain.crt

#   Certificate Authority (CA):
#   Set the CA certificate verification path where to find CA
#   certificates for client authentication or alternatively one
#   huge file containing all of them (file must be PEM encoded)
# SSLCACertificateFile /etc/pki/tls/certs/ca-bundle.crt
SSLCACertificateFile /etc/ssl/certs/repo.yona.io.ca-bundle.crt
...
...
```

**Comment by pokev25** [comment]
```
<VirtualHost *:80>
    ServerName domain

    RewriteEngine on
    RewriteCond %{HTTPS} !on
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R,L]
</VirtualHost>
```
참고로 저는 이렇게 설정해놨습니다.
