### ISSUE TITLE
특정 언어 Syntax highlighting 안되는 문제..?

### ISSUE THREAD

**Issue by smsroql12** [yona-projects/yona#601]
안녕하세요.
요나를 서버에 구축해서 사용중인데요
신택스 하이라이팅이 뭔가 잘 안되는 것 같아요.
html 이랑 c++ 같은 경우는 되긴 되는데 뭔가 약한 것 같고
c# 파일인 cs 파일은 아예 하이라이팅이 되지 않네요.
혹시 제가 수정해야 할 부분이 있는건가요?
아니면 아예 c# 코드는 지원을 안하는건가요?

설치만 했고 따로 뭘 건드린건 하나도 없습니다.
프로젝트 만들고 푸쉬만 몇번 했고 yona를 시스템적으로 건든 건 없습니다.
yona 버전은 현재 최신버전인 1.12.0 입니다.

위 이미지를 확인 해 보시면 c# 코드의 경우 하이라이팅이 전혀 되지 않고 있네요..ㅠㅠ
해결 방법좀 부탁드리겠습니다..

**Comment by doortts** [comment]
안녕하세요?

C# 은 문법 하일라이팅 지원 언어입니다

https://repo.yona.io 에서 테스트 한 번 가능하실까요?

**Comment by doortts** [comment]
```
```C# 
```
같은 식으로 시작하셔야 할 것 같습니다.

**Comment by smsroql12** [comment]
> ```
> ```C# 
> ```
> 
> 같은 식으로 시작하셔야 할 것 같습니다.

https://repo.yona.io/smsroql12/c-sharp-test/code/master/hello.cs
여기 푸쉬 해서 올렸습니다! 그런데 마찬가지로 하이라이팅이 안되네요

```
```C#
//code
   ```  ```
부분을 추가하는건  푸쉬하고나서 코드 들어가서 Edit 버튼 누른다음에 코드 맨 윗줄에   ```C#    쓰고
맨 아랫줄에   ```   써준뒤 다시 수정(커밋)해야 하는건가요? 그렇게 해도 안되는데..
커밋 내역 한번 확인 해 주세요

된다 하더라도 자동 하이라이트 기능이 안되고 코드 올릴때마다 cs파일 하나하나 다 저런 작업을 해줘야 하는건 좀 힘들지 않을까 싶습니다.

제가 잘 이해를 못해서요 자세한 방법을 알려주시면 감사하겠습니다.

**Comment by hongwonjun** [comment]
해당 이슈 수정하여 PR 올렸습니다.
