### ISSUE TITLE
syntax highlighting 재문의 드립니다.

### ISSUE THREAD

**Issue by smsroql12** [yona-projects/yona#604]
![image](https://user-images.githubusercontent.com/30662770/72323495-3a81fa80-36ec-11ea-95d9-6df73e594455.png)

C++

![image](https://user-images.githubusercontent.com/30662770/72323673-98aedd80-36ec-11ea-94b5-2d373cda1da1.png)

HTML

![image](https://user-images.githubusercontent.com/30662770/72329264-c77e8100-36f7-11ea-904e-b2314b997d89.png)
JavaScript

![image](https://user-images.githubusercontent.com/30662770/72329299-d6653380-36f7-11ea-8975-fc9c3f9ba871.png)
CSS

![image](https://user-images.githubusercontent.com/30662770/72323716-b1b78e80-36ec-11ea-9163-f8d60271c713.png)
C#

위 사진에 보시는 바와 같이 C++과 HTML은 syntax highlighting이 되는 반면 C#은 안되네요.
저번에
```C#
//C# Code
```
이걸 말씀 해주셨는데 이 얘기는 C# 코드 자체에 마크다운 문법을 집어넣을 수는 없으니 마크다운파일을 하나 만들고 그 안에다가
```C#
Console.WriteLine("Hello World!");
```

이렇게 하나하나 따로 집어넣으라는 말씀이신건가요? 만약 그렇다면 그거랑은 별개의 문제인 것 같습니다.
그건 마크다운 코드 태그로 c# 소스를 하이라이팅 되어 볼 수 있게 하는 말씀이신 것 같구요
요나에 올려진 cs 파일을 클릭했을때 자동으로 하이라이팅 되어 보여지는 건 어떻게 해결해야
하는 건가요? 
찾아보니 highlight.js  를 사용한다고 들었는데 도데체 이유가 뭘까요
도움 부탁드립니다!!

**Comment by hongwonjun** [comment]
#601 이슈와 중복 이슈 같은데 한 이슈는 닫는게 좋을 것 같습니다.

**Comment by smsroql12** [comment]
네 이슈 닫았습니다!

**Comment by smsroql12** [comment]
> #601 이슈와 중복 이슈 같은데 한 이슈는 닫는게 좋을 것 같습니다.
@hongwonjun  

자꾸 부탁드리게 되어 죄송합니다. 이번 pull request 에 올리신    "csharp": ["cs"],    이 부분을
설치되어있는 요나 폴더의 lib/yona.yona-1.12.0-assets.jar 압축 파일에서
public/javascripts/service/yobi.code.Browser.js 파일에 한줄 추가 하였습니다.
pull request에 올리신 부분하고 똑같이요.
그 후 다시 서버를 재부팅 하였고 다시 c# 파일을 푸쉬 해봤는데 볼때 여전히 같은 증상이네요.

이 외에도 수정할 부분이 더 있는데 아직 확인중이신건가요??

**Comment by hongwonjun** [comment]
> > #601 이슈와 중복 이슈 같은데 한 이슈는 닫는게 좋을 것 같습니다.
> > @hongwonjun
> 
> 자꾸 부탁드리게 되어 죄송합니다. 이번 pull request 에 올리신 "csharp": ["cs"], 이 부분을
> 설치되어있는 요나 폴더의 lib/yona.yona-1.12.0-assets.jar 압축 파일에서
> public/javascripts/service/yobi.code.Browser.js 파일에 한줄 추가 하였습니다.
> pull request에 올리신 부분하고 똑같이요.
> 그 후 다시 서버를 재부팅 하였고 다시 c# 파일을 푸쉬 해봤는데 볼때 여전히 같은 증상이네요.
> 
> 이 외에도 수정할 부분이 더 있는데 아직 확인중이신건가요??

말씀하신 방법으로는 진행해본 적이 없어서 뭐라고 답변을 드려야 할지 모르겠습니다.
수정할 부분이 더 있지는 않습니다.

[위키 내 배포버전 만들기](https://repo.yona.io/yona-projects/yona/post/5#yb-header-%EB%B0%B0%ED%8F%AC%EB%B2%84%EC%A0%84-%EB%A7%8C%EB%93%A4%EA%B8%B0) 를 통해서 배포 버전을 만들 수에 다시 설치해보시면 될 것 같습니다.
