### ISSUE TITLE
Ace Editor C# 첫줄 앞 빨간 점 생기는 이슈

### ISSUE THREAD

**Issue by smsroql12** [yona-projects/yona#606]
자꾸 질문드려 죄송합니다 ㅎㅎ..
![image](https://user-images.githubusercontent.com/30662770/72706259-eb7f0e00-3ba0-11ea-9d97-4ce818de0662.png)

다른 코드는 괜찮은 것 같은데 유독 C# 에만 맨 첫줄 첫 부분에 저렇게 빨간색 배경의 점이 하나 생깁니다. 사실 사용하는데 크게 지장은 없습니다만 원인을 찾아보니 ace 라는 에디터에서 소스코드가 보여지는데 그 에디터의 원인 같습니다.

![image](https://user-images.githubusercontent.com/30662770/72706361-34cf5d80-3ba1-11ea-8279-18a5f89870bb.png)
위 사진에 있는 태그가 빨간 점이 삽입되는 태그인데 추적을 해보니 ace.js 라는 파일이 있었고 이 파일에서 삽입되는 위 부분을 찾아 전부 없앤 뒤 js파일 교체 후 다시 재구축 하기도 했습니다만 이 부분이 아닌지 역시 안되네요.

https://repo.yona.io/ 사이트에 제가 C# 테스트 파일을 올린 적이 있는데 여기서는 저런 점이 생기지 않고 잘 되네요.
제가 구축한 버전은 요나 깃허브 release에 있는 최신버전인 1.12.0 h2 버전을 받아서 했구요
요나 공식사이트와 무슨 차이가 있어서 저런 빨간 점이 뜨는지 궁금합니다.
말씀드렸다시피 공식사이트에서는 안그러는데 제가 구축한 요나의 c#에서만 저런 현상이 발생해서..

```html
public\javascripts\lib\ace\ace.js
public\javascripts\lib\ace\theme-clouds_midnight.js
public\javascripts\lib\ace\theme-ambiance.js
public\javascripts\lib\ace\theme-chaos.js
public\javascripts\lib\ace\theme-chrome.js
public\javascripts\lib\ace\theme-clouds.js
public\javascripts\lib\ace\theme-cobalt.js
public\javascripts\lib\ace\theme-crimson_editor.js
public\javascripts\lib\ace\theme-dawn.js
public\javascripts\lib\ace\theme-eclipse.js
public\javascripts\lib\ace\theme-idle_fingers.js
public\javascripts\lib\ace\theme-kr.js
public\javascripts\lib\ace\theme-merbivore.js
public\javascripts\lib\ace\theme-merbivore_soft.js
public\javascripts\lib\ace\theme-monokai.js
public\javascripts\lib\ace\theme-mono_industrial.js
public\javascripts\lib\ace\theme-pastel_on_dark.js
public\javascripts\lib\ace\theme-solarized_light.js
public\javascripts\lib\ace\theme-terminal.js
public\javascripts\lib\ace\theme-textmate.js
public\javascripts\lib\ace\theme-tomorrow.js
public\javascripts\lib\ace\theme-tomorrow_night.js
public\javascripts\lib\ace\theme-tomorrow_night_blue.js
public\javascripts\lib\ace\theme-tomorrow_night_bright.js
public\javascripts\lib\ace\theme-tomorrow_night_eighties.js
public\javascripts\lib\ace\theme-twilight.js
public\javascripts\lib\ace\theme-vibrant_ink.js
public\javascripts\lib\ace\theme-xcode.js
```
위 태그의 내용이 들어간 파일은 위와 같이 많아서 위 파일들을 일일히 다 찾아 수정하는건
너무 비효율적일 것 같아 혹시 해결 방법이 있는지, 원인은 무엇인지 궁금해서 여쭈어봅니다.

**Comment by doortts** [comment]
뭔가 별것 아닌듯하면서도 빨간게 계속 보이면 굉장히 신경쓰일것 같은 느낌이네요. https://repo.yona.io 에서는 재현이 안된다는 이야기이신거죠?

**Comment by smsroql12** [comment]
@doortts 
네 그렇습니다 ㅠㅠ 별거 아닌데 신경써주셔서 감사합니다.

**Comment by doortts** [comment]
한 번 에이스 에디터를 버전업 해보겠습니다.

**Comment by smsroql12** [comment]
@doortts 
감사합니다!!

**Comment by smsroql12** [comment]
@doortts 
해당 이슈에 대해서는 해결 되었습니다.
저도 doortts 님 말씀 듣고 ace 깃 프로젝트에 가서 최신버전으로 다운받은 뒤 요나에 있는 ace 관련 js 파일을 모두 최신버전 다운받은걸로 교체해봤는데 역시 해결되지 않습니다.

버전의 문제는 아닌 것 같아 계속 검색을 해본 결과 문제는 인코딩이었습니다.
C++, HTML, PHP 다 되는데 C# 만 안되길래 이상하다 이상하다 했는데 제가 사용하는 visual studio 2017에서 C# 프로젝트를 만들때 C#의 확장자인 cs 파일의 인코딩이 "'서명있는' UTF-8" 로 되있었습니다. 이걸 "'서명 없는' UTF-8" 로 인코딩을 변경 해 보라는 글을 보고 서명 없는 UTF-8 인코딩으로 변경하여 새로 저장한 뒤 푸쉬하였더니 정상적으로 빨간 점이 나타나지 않게 되었습니다.
서명있는 utf-8 은 BOM 이 들어가고 서명 없는 utf-8은 BOM이 들어가지 않아 BOM 때문에 빨간 점이 생겼다고 하더라구요.

인코딩 문제로 해당 부분에 빨간 점이 들어간 것 같습니다.
세세한 원인은 재대로 파악하지 못했지만 크게 보면 인코딩 문제인게 결론입니다.
요나 외에도 다른 ace.js 사용자들도 빨간 점이 생기는 현상으로 질문글을 올린게 있어서 찾았네요 ㅋㅋ

다만 궁금한점은 rona io 에 제가 c# 소스를 올렸을 때 분명 제 서버에서는 문제가 되었던 서명있는 utf-8로 되있는 c# 파일을 올렸는데 무슨 이유에서인지 빨간 점이 생기지 않던데 혹시 이에 대해서는 아시는 점이 있나요??

일단 이슈 내리겠습니다 같이 찾아봐주셔서 감사합니다 ㅎㅎ
