### ISSUE TITLE
yona는 LDAP 를 지원하나요?

### ISSUE THREAD

**Issue by yudonguk** [yona-projects/yona#61]
안녕하세요.

yona를 한번 사용해 볼까해서, docker 로 설치해서 실행해 보았습니다.

헌데 사이트 관리 항목에서 LDAP 설정 관련된것이 없더라구요.

yona는 LDAP를 지원하지 않나요?

**Comment by doortts** [comment]
아쉽지만 Yona는 아직 LDAP을 지원하지 않습니다. : (

**Comment by yudonguk** [comment]
답변 갑사합니다.
