### ISSUE TITLE
요나와 젠킨스 연동 방법??

### ISSUE THREAD

**Issue by JungYongWook** [yona-projects/yona#612]
안녕하세요
요나를 사용중인데 젠킨스와 연동하는 방법이 궁금합니다
참고할만한것이 있을까요??

**Comment by hongwonjun** [comment]
안녕하세요,
아직 공식 가이드는 없는 것으로 알고 있습니다.

검색해보니 몇 가지 포스팅이 있어서 공유 드립니다.

- https://kouzie.github.io/%EC%9E%A1%EB%8B%B4/jenkins,-yona/#%EA%B8%B0%EB%B3%B8-%EC%84%A4%EC%A0%95---%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EA%B4%80%EB%A6%AC
- https://www.hind.pe.kr/1250

#401 
- 위와 같은 문제가 있으나 현재는 develop 브랜치로 빌드시 문제가 해결될 것으로 예상합니다.

**Comment by hongwonjun** [comment]
https://hongwonjun.github.io/2020-03-13/Yona-Jenkins-%EC%97%B0%EB%8F%99%EB%B0%A9%EB%B2%95

위 포스트가 참고가 될지 모르겠습니다.

**Comment by hongwonjun** [comment]
@JungYongWook 
위 포스트에서 부족한 부분을 알려주시고, 필요한 내용이 정리 되었으면 이슈 Close 부탁드립니다.

**Comment by JungYongWook** [comment]
요나와 젠킨스 IP 구성을 어떻게할지 고민해봐야겠네요.. 감사합니다!

**Comment by finnbell** [comment]
Jenkins 에서 maven 프로젝트로 만들면 되던데요. 
https://www.youtube.com/watch?v=m0tky1jyP-0    참고 했습니다.
