### ISSUE TITLE
요나 프로젝트 commit&push 시에 자동 빌드

### ISSUE THREAD

**Issue by JungYongWook** [yona-projects/yona#613]
제목대로 하려고 프로젝트에 yona 프로젝트 및 계정 연동해놨고,
이클립스에서 커밋&푸시하고서 젠킨스에서 빌드하면 빌드 반영이됩니다.
그런데 자동으로 하려고 하는데,
제가 해놓은 것은 yona 프로젝트의 웹후크 - 전송할 주소에
http://젠킨스URL:9090/job/jenkins-test/build?token=TOKEN_NAME
으로 하고, Authorization Token 값은 push 라고 해놓은 상태입니다.
just the push event 에도 체크를 해놓았습니다.

빌드 유발은 원격으로 유발 설정 후 push 라고 입력해놓은 상태인데

해당 설정 만으로는 프로젝트 푸시 발생시 자동 빌드가 되지는 않는건가요?
지식이 없어 질문이 좀 막 쓴거같은데 이해 안되는 부분은 말해주시면
더 자세히 말씀드리겠습니다..

**Comment by doortts** [comment]
젠킨스쪽 서버 로그는 어떻게 표시되나요?

**Comment by JungYongWook** [comment]
답변감사합니다. 일단 전부를 붙여봤습니다.
특별한 동작을 한건없고
그냥 직접 빌드 눌러서 빌드해보고,
이클립스에서 프로젝트 커밋&푸시 후 빌드 자동으로 안되는거 확인 후
직접 눌러서 빌드해보고.. 정도가 전부입니다.

2월 24, 2020 6:10:42 오후 정보 hudson.WebAppMain contextInitialized
Jenkins home directory: C:\Program Files (x86)\Jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2월 24, 2020 6:10:43 오후 정보 org.eclipse.jetty.server.handler.ContextHandler doStart
Started w.@9a1df5{Jenkins v2.204.2,/,file:///C:/Program%20Files%20(x86)/Jenkins/war/,AVAILABLE}{C:\Program Files (x86)\Jenkins\war}
2월 24, 2020 6:10:43 오후 정보 org.eclipse.jetty.server.AbstractConnector doStart
Started ServerConnector@19b4d0f{HTTP/1.1,[http/1.1]}{0.0.0.0:9090}
2월 24, 2020 6:10:43 오후 정보 org.eclipse.jetty.server.Server doStart
Started @14431ms
2월 24, 2020 6:10:43 오후 정보 winstone.Logger logInternal
Winstone Servlet Engine v4.0 running: controlPort=disabled
2월 24, 2020 6:10:44 오후 정보 jenkins.InitReactorRunner$1 onAttained
Started initialization
2월 24, 2020 6:10:51 오후 정보 jenkins.InitReactorRunner$1 onAttained
Listed all plugins
2월 24, 2020 6:10:58 오후 정보 jenkins.InitReactorRunner$1 onAttained
Prepared all plugins
2월 24, 2020 6:10:58 오후 정보 jenkins.InitReactorRunner$1 onAttained
Started all plugins
2월 24, 2020 6:10:59 오후 정보 hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
2월 24, 2020 6:11:00 오후 정보 jenkins.InitReactorRunner$1 onAttained
Augmented all extensions
2월 24, 2020 6:11:00 오후 정보 jenkins.InitReactorRunner$1 onAttained
Loaded all jobs
2월 24, 2020 6:11:00 오후 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Started Download metadata
2월 24, 2020 6:11:00 오후 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Finished Download metadata. 39 ms
2월 24, 2020 6:11:00 오후 정보 org.springframework.context.support.AbstractApplicationContext prepareRefresh
Refreshing org.springframework.web.context.support.StaticWebApplicationContext@125540a: display name [Root WebApplicationContext]; startup date [Mon Feb 24 18:11:00 KST 2020]; root of context hierarchy
2월 24, 2020 6:11:00 오후 정보 org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@125540a]: org.springframework.beans.factory.support.DefaultListableBeanFactory@1c609c3
2월 24, 2020 6:11:01 오후 정보 org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1c609c3: defining beans [authenticationManager]; root of factory hierarchy
2월 24, 2020 6:11:01 오후 정보 org.springframework.context.support.AbstractApplicationContext prepareRefresh
Refreshing org.springframework.web.context.support.StaticWebApplicationContext@f33dfd: display name [Root WebApplicationContext]; startup date [Mon Feb 24 18:11:01 KST 2020]; root of context hierarchy
2월 24, 2020 6:11:01 오후 정보 org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@f33dfd]: org.springframework.beans.factory.support.DefaultListableBeanFactory@d8f33a
2월 24, 2020 6:11:01 오후 정보 org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@d8f33a: defining beans [filter,legacy]; root of factory hierarchy
2월 24, 2020 6:11:01 오후 정보 jenkins.InitReactorRunner$1 onAttained
Completed initialization
2월 24, 2020 6:11:01 오후 정보 hudson.WebAppMain$3 run
Jenkins is fully up and running
2월 24, 2020 9:30:36 오후 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Started Workspace clean-up
2월 24, 2020 9:30:36 오후 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Finished Workspace clean-up. 24 ms
2월 25, 2020 9:26:49 오전 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Started Fingerprint cleanup
2월 25, 2020 9:26:49 오전 정보 hudson.model.AsyncPeriodicWork lambda$doRun$0
Finished Fingerprint cleanup. 73 ms
2월 25, 2020 9:40:03 오전 정보 jenkins.slaves.JnlpSlaveAgentProtocol3$Impl allows
Inbound TCP Agent Protocol/3 has been forcibly disabled for additional security reasons. To enable it yet again set the system property jenkins.slaves.JnlpSlaveAgentProtocol3.ALLOW_UNSAFE
2월 25, 2020 9:40:11 오전 정보 hudson.model.Run execute
jenkins-test #6 main build action completed: SUCCESS
2월 25, 2020 9:43:06 오전 정보 hudson.model.Run execute
jenkins-test #7 main build action completed: SUCCESS

**Comment by doortts** [comment]
별다른 오류도 받은 내용도 보이지가 않는데요, 그럼 hook을 보내는 Yona 쪽 root.log 에는 요청과 응답로그가 어떻게 남았는지 알 수 있을까요?

**Comment by JungYongWook** [comment]
죄송하지만 말씀하신 Yona 로그를 어디서 확인할 수 있을까요..?

**Comment by doortts** [comment]
YONA_DATA 로 환경변수 지정하신 곳 아래에 logs 디렉터리에 보시면 보이실거에요.
h2 버전을 실행하셨다면 실행하신 곳 하위로 생겼을 거구요.

**Comment by JungYongWook** [comment]
2020-02-25 13:53:24,726 - [INFO] - from access./계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-upload-pack in play-akka.actor.default-dispatcher-11673
사용중인 Yona IP - - [25/Feb/2020:13:53:24 +0900] "GET /계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-upload-pack HTTP/1.1" 401 - - "JGit/4.6.1.201703071140-r" 1ms

2020-02-25 13:53:24,750 - [INFO] - from access./계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-upload-pack in play-akka.actor.default-dispatcher-11666
사용중인 Yona IP - 계정ID [25/Feb/2020:13:53:24 +0900] "GET /계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-upload-pack HTTP/1.1" 200 - - "JGit/4.6.1.201703071140-r" 6ms

2020-02-25 13:53:30,400 - [INFO] - from access./계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-receive-pack in play-akka.actor.default-dispatcher-11666
사용중인 Yona IP - - [25/Feb/2020:13:53:30 +0900] "GET /계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-receive-pack HTTP/1.1" 401 - - "JGit/4.6.1.201703071140-r" 1ms

2020-02-25 13:53:30,418 - [INFO] - from access./계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-receive-pack in play-akka.actor.default-dispatcher-11673
사용중인 Yona IP - 계정ID [25/Feb/2020:13:53:30 +0900] "GET /계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/info/refs?service=git-receive-pack HTTP/1.1" 200 - - "JGit/4.6.1.201703071140-r" 3ms

2020-02-25 13:53:30,462 - [INFO] - from access./계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/git-receive-pack in play-akka.actor.default-dispatcher-11666
사용중인 Yona IP - 계정ID [25/Feb/2020:13:53:30 +0900] "POST /계정ID/Jenkins_%EC%A0%95%EC%9A%A9%EC%9A%B1/git-receive-pack HTTP/1.1" 200 - - "JGit/4.6.1.201703071140-r" 3ms

2020-02-25 13:53:36,788 - [INFO] - from access./계정ID/프로젝트명/info/refs?service=git-upload-pack in play-akka.actor.default-dispatcher-11666
사용중인 Yona IP - - [25/Feb/2020:13:53:36 +0900] "GET /계정ID/프로젝트명/info/refs?service=git-upload-pack HTTP/1.1" 401 - - "git/2.25.0.windows.1" 2ms

2020-02-25 13:53:36,793 - [INFO] - from access./계정ID/프로젝트명/info/refs?service=git-upload-pack in play-akka.actor.default-dispatcher-11672
사용중인 Yona IP - - [25/Feb/2020:13:53:36 +0900] "GET /계정ID/프로젝트명/info/refs?service=git-upload-pack HTTP/1.1" 401 - - "git/2.25.0.windows.1" 2ms

2020-02-25 13:53:37,062 - [INFO] - from access./계정ID/프로젝트명/info/refs?service=git-upload-pack in play-akka.actor.default-dispatcher-11672
사용중인 Yona IP - 계정ID [25/Feb/2020:13:53:37 +0900] "GET /계정ID/프로젝트명/info/refs?service=git-upload-pack HTTP/1.1" 200 - - "git/2.25.0.windows.1" 4ms

2020-02-25 13:53:37,371 - [INFO] - from access./계정ID/프로젝트명/git-upload-pack in play-akka.actor.default-dispatcher-11666
사용중인 Yona IP - 계정ID [25/Feb/2020:13:53:37 +0900] "POST /계정ID/프로젝트명/git-upload-pack HTTP/1.1" 200 - - "git/2.25.0.windows.1" 4ms


이게 root.log 파일입니다.
이클립스에서 커밋&푸시 후 젠킨스에서 직접 빌드한 내용입니다.
그냥 제가 뭔가 설정을 안해놔서 그런건지..
위에 말한부분들 말고 확인해봐야 할 부분이 있을까요?

**Comment by JungYongWook** [comment]
빌드하면 푸시에 변경된 내용이 젠킨스 프로젝트 빌드때도 해당 내용이 반영되는걸 보면 연결은 되어있는데.. 뭔가 자동으로 빌드나 배포를 위한 설정이 빠져있는것 같은데 갈피를 못잡겠네요

**Comment by doortts** [comment]
음. 이거 조금 파악하기가 어렵네요. 보내주신 서버 로그에서는 hook 을 보낸 로그가 안보이는데 받는 젠킨스는 받는것 같다고 하시니까 영문을 잘 모르겠어요. 음.

**Comment by JungYongWook** [comment]
요나 프로젝트의 웹후크 설정이

전송할 주소 : http://젠킨스주소/job/jenkins-test/build?token=TOKEN_NAME
Authorization Token : push
Type of message : SIMPLE
Just the push event  체크상태

이렇게 해놓은 상태이고,

젠킨스에서 프로젝트 구성은
Github project 체크 후 Project URL 은 yona 프로젝트 경로로 설정해놓은 상태고
소스코드 관리 - git 체크 - Repositoty URL 및 credential 도 yona 프로젝트 URL 및 제 계정으로 등록해놓았습니다.

빌드유발은 다음과 같고,

![image](https://user-images.githubusercontent.com/24910138/75405141-1737a580-5950-11ea-9d88-955f80a7cf5d.png)

나머지 설정은

![image](https://user-images.githubusercontent.com/24910138/75405181-346c7400-5950-11ea-8b90-4bc85faef469.png)


이렇게 되어있는데 무슨 설정을 해놔야 할지.. 웹 후크가 동작은 하는건지 모르겠네요ㅠㅠ

**Comment by hongwonjun** [comment]
@JungYongWook 님
Github Project 체크를 해제하시고 This project is parameterized 를 사용해보시겠어요?

**Comment by JungYongWook** [comment]
![tempsnip](https://user-images.githubusercontent.com/24910138/75415702-b61fca00-596f-11ea-84db-e45112aa1885.png)

위쪽에 GitHub project 를 Yona 프로젝트 경로로 잡아놓은것을 체크 해제는 했는데, 말씀하신 설정 부분이 보이지가 않습니다..

**Comment by hongwonjun** [comment]
@JungYongWook 
curl 명령어로 일단 테스트 해보시겠어요?

**Comment by JungYongWook** [comment]
![image](https://user-images.githubusercontent.com/24910138/75504579-31d75080-5a1c-11ea-9e3c-41bd0ad99b8a.png)


이런식으로 쭉 html 코드가 나오는데.. 어떻게 확인해야하나요?

**Comment by JungYongWook** [comment]
curl 명령어로 진행해보니 젠킨스에서 빌드가 일어납니다.

**Comment by doortts** [comment]
혹시 젠킨스 서버가 외부(인터넷망)에서 접속 가능한가요?

**Comment by JungYongWook** [comment]
제가 윈도우 환경에서 명령 프롬프트에서 curl 명령어를 실행해 본것이었는데요,
외부 접속이라하면 어떻게 해야하나요?..
현재 젠킨스 URL은 제 자리 로컬 IP로 설정되어있습니다.

**Comment by hongwonjun** [comment]
@JungYongWook 

문제를 나눠서 봐야 할 것 같습니다.

1. 우선 Yona 서버에서 구동되는 webhook 이 jenkins 서버에 도착하는지를 확인해주셔야 할 것 같습니다.
- Python 구동이 가능하시다면 [간단한 Repo](https://github.com/hongwonjun/legendary-succotash) 로 만들어두었으니 사용하시는 것도 방법입니다.

2. webhook 으로 인한 콜이 잘 도착하는데 jenkins 구동이 되지 않는 것이라면 사실 Yona 가 아니라 jenkins 와 관련된 설정문제일텐데요. 이 부분은 curl 로 테스트 해보셨을 때 구동이 된다고 하셨으니 큰 문제는 없을 것 같습니다.

결론적으로 위의 1번 사항을 확인해주시고 Comment 주시면 같이 해결책을 확인해볼 수 있을 것 같습니다.

**Comment by JungYongWook** [comment]
webhook 이 잘 동작하는건지도 잘 모르겠네요..
파이썬을 설치를 했는데, 알려주신 링크에 있는 명령어
python run.py 를 치면 실행이 되지 않는데 별도로 설정이나 뭔가 설치를 해야할까요?

**Comment by hongwonjun** [comment]
@JungYongWook 

실행이 어떻게 되지 않나요?

실행 전에 아래 명령어로 flask 는 설치하셔야 합니다.

`pip install -r requirements.txt`

**Comment by JungYongWook** [comment]
파이썬 설치 후, power shell 에서 python 입력 후 
방금 알려주신 명령어 입력하면
install 쪽에서 invalid syntax가 나옵니다.

**Comment by JungYongWook** [comment]
해당 프로젝트 다운받고, 
git bash 에서 경로 접근 후 방금 알려주신 명령어 실행하였는데
아래와 같이 결과가 나옵니다.

![image](https://user-images.githubusercontent.com/24910138/75657499-b559a180-5ca9-11ea-965c-7bd3b40ddfa1.png)

**Comment by JungYongWook** [comment]
우선 말씀하신 프로젝트를 다운받아서 D드라이브에 넣어놓은 상태입니다.
그리고 cmd 에서 pip 설치하고, 해당 프로젝트 경로에 들어가서
requirements.txt가 있는 패스까지 들어가고나서
위에 말해주신 명령어를 입력해보니

![image](https://user-images.githubusercontent.com/24910138/75658617-fce12d00-5cab-11ea-8a0f-cd2918a93b4a.png)

이렇게 결과가 나옵니다ㅠ

**Comment by hongwonjun** [comment]
@JungYongWook 

제가 금주 내에 로컬 환경에서 작업하고 가이드 문서를 작성해서 공유드리도록 하겠습니다.

**Comment by JungYongWook** [comment]
아 그렇게까지.. 감사합니다ㅠㅠ

**Comment by hongwonjun** [comment]
@JungYongWook 

생각보다 늦어졌습니다.

아래 링크를 참고해보시고,
궁금하신 부분은 다시 Comment 주시면 될 것 같습니다.

아마 Jenkins 계정 관련 부분이 누락되지 않았나 싶습니다.

https://hongwonjun.github.io/2020-03-13/Yona-Jenkins-%EC%97%B0%EB%8F%99%EB%B0%A9%EB%B2%95

**Comment by JungYongWook** [comment]
안녕하세요 작성해주신 것 보고 쭉 진행을 해봤습니다.
젠킨스 설정에서 빌드 후 조치를 안하것 빼고는 똑같이 하고,

웹후크 설정을 아래처럼

![image](https://user-images.githubusercontent.com/24910138/77127923-a2104980-6a91-11ea-8354-d8ec0cb4818d.png)

해놓았는데 이클립스에서 소스 수정후 commit and push 진행을 하고 지켜봐도 자동으로 저는 젠킨스 빌드가 되지않는데.. 웹후크 설정 확인 부탁드립니다ㅠㅠ
젠킨스는 localhost:9090 으로 접속하고 있고 admin계정 사용중입니다.

**Comment by hongwonjun** [comment]
git push hook 에 check 를 해야 할 것 같습니다.
yona 도 localhost 에서 돌고 있는거죠?

**Comment by JungYongWook** [comment]
요나는 클라우드 서버에서 돌고있습니다.
그럼 git push hook 에 체크하고,
전송할 주소 끝쪽에 {token} 그대로 쓰는거는 맞을까요?

**Comment by hongwonjun** [comment]
localhost 는 자기 자신을 뜻하기 때문에 아마 @JungYongWook 의 localhost 가 아니라 클라우드 서버의 자기 자신을 호출하고 있을 것 같습니다.

지금 상황에서 가능한 방법은 아래 3가지 정도가 있을 것 같습니다.

1. 클라우드에서 현재 작업하시는 PC 에 접속이 가능하게 하고 현재 작업하시는 PC 의 외부에서 접속 가능한 IP 를 입력한다.

2. 같은 클라우드 환경 내 젠킨스 서버를 구축하고 그 IP 를 입력한다.

3. Yona 가 설치된 서버에 젠킨스 서버를 구축하고 localhost 주소를 사용한다.

**Comment by JungYongWook** [comment]
쉽지 않네요..
yona 서버로 접속 후 젠킨스를 명령어로 설치하고,
웹에서 Yona IP 로 Yona 접속하여 사용하는것처럼..
사용을하게 되는건가요?

**Comment by hongwonjun** [comment]
네 localhost 주소를 쓰시려면 같은 서버에 설치하시면 됩니다.

**Comment by hongwonjun** [comment]
@JungYongWook 
문제가 어떻게 해결되었는지 궁금합니다.

일단 Yona 의 이슈는 아닌 것으로 보이는데,
확인이 되었으면 이슈를 Close 처리 하는 것이 좋을 것 같네요.

**Comment by JungYongWook** [comment]
안녕하세요.
대답이 많이 늦었습니다.
말씀하신대로 진행 예정으로만 잡혀있고
현재 다른부분 작업을 진행중이라
우선 Close 해놓겠습니다.
감사합니다.
