### ISSUE TITLE
git Push 시 WEBHOOK이 작동하지 않습니다.

### ISSUE THREAD

**Issue by gmgmgm13** [yona-projects/yona#614]
안녕하세요~

사내에(폐쇄망-인터넷 불가) 요나를 설치하고자 h2버전으로 Test 중에 있습니다.
사내에서는 "오픈소스 설치형 슬랙" 이라고 불리는 Mattermost라는 메신저를 사용중이며,
Mattermost는 incoming web hook을 지원하고 있는데요~

git Push에만 웹훅이 동작하지 않아 이슈 등록하게 되었습니다.

1) just git push 체크 안한 경우
 - 이슈등록/코드 주고받기 요청/리뷰 등록 등 웹훅이 잘 동작함
 - **git push 또는 코드 병합하기 시에 웹훅이 동작하지 않음**
   ※ log상에도 webhook을 호출하지 않는듯 보입니다.

2) just git push 체크 한 경우
 - **git push 또는 코드 병합하기 시에 웹훅이 동작하지 않음**
  ※ 에러로그
    `[Webhook] Request responded cod 400: Bad Request`
    `[Webhook] Request payload: ..............json형식 파라미터 생략(한글 포함).........`

**Comment by gmgmgm13** [comment]
> 사용버전은 h2의 yona-1.12.0 (최신 버전입니다...^^)

**Comment by doortts** [comment]
Mattermost의 incoming web hook 요건은 어떻게 되나요? 참고하신 관련 URL도 괜찮습니다.

**Comment by gmgmgm13** [comment]
- mattermost의 incomming webhook도 슬랙과 마찬가지로 채널 단위로 생성이 됩니다(웹훅 생성 기능 제공)

- git push 시에 오류난 payload 데이터를 curl로 호출하면 동일하게 400에러가 나지만 단순한 json data(curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "Hello, this is some text\nThis is more text. :tada:"}' http://{your-mattermost-site}/hooks/xxx-generatedkey-xxx) 로 호출하면 200 ok로 정상등록되는 것을 확인했습니다!

- https://docs.mattermost.com/developer/webhooks-incoming.html

**Comment by gmgmgm13** [comment]
@doortts 님,

- mattermost 문서를 좀 더 확인해보니 payload 에 "text" 또는 "attachments" key가 필수라는 것을 확인했습니다.
1) https://developers.mattermost.com/integrate/incoming-webhooks/
2) https://docs.mattermost.com/developer/message-attachments.html


- **cURL로 "text"키와 "attachments"을 추가하여 호출시 200 정상 호출됩니다.**
 예) `curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "gmgmgm13님이 [ref/feature/main] 소스를 push하였습니다. http://요나IP:9000/그룹명/프로젝트명/commit/커밋ID", "attachments" : [{"text" : "커밋한 메시지" }] }' https://매터모스트 도메인/hooks/토큰키`


-  **[Webhook.java](https://github.com/yona-projects/yona/blob/0f497276f5049591f7a18fcb19f282954e8ae119/app/models/Webhook.java#L665
) 소스를 확인해보니 commit의 경우 "text"와 "attachments" key가 request 생성시 포함되지 않아 오류가 나는 것으로 확인됩니다.** 


신입 교육 때, doortts님께서 강의를 해주셨던 기억이 있는데, Yona를 만드셨다는 걸 알게됬네요. 
이렇게 뵙게되어 반갑습니다..^^

**Comment by gmgmgm13** [comment]
- Mattermost가 어느정도 Slack과 호환성을 보장하려고 하기 때문에,
  webhookType은 SIMPLE, DETAIL_SLACK 두 케이스 모두 테스트 하였으며, 모두 git Push 이외 테스트에서 정상동작합니다^^

**Comment by doortts** [comment]
@hongwonjun 혹시 추측가능한 부분 있으세요?

**Comment by hongwonjun** [comment]
확인해보도록 하겠습니다.

해당 이슈는 git push 시에 mattermost 로 메세지를 받고자 하는건가요?

**Comment by gmgmgm13** [comment]
@hongwonjun 
네, git push나 코드 병합시 mattermost로 메세지를 받고자 합니다.
이슈등록 및 수정, 담당자 변경 등의 다른 Case에서는 mattermost로 메세지가 전달 되고 있습니다.

**Comment by hongwonjun** [comment]
@gmgmgm13 
코드 병합이라는 것이 PR Merge 가 아니라 git 자체에서 사용하는 branch merge 를 말씀하시는 것이죠?
추가적으로 git push 는 현재 발송은 되고 있으나 mattermost 에 맞추어져있지 않다는 말씀이신거죠?

메신저향 (just git push 체크 안한 경우) 의 경우 git push 를 지원하게 되면 양이 너무 많아질거 같긴 하네요.
just git push 체크시는 메신저보다는 jenkins 등에 연동을 하고자 맞추어져있습니다.

기능을 추가하면서 새로운 옵션을 만들어야 할 것 같네요. @doortts 
일단 고민을 해보도록 하겠습니다.

**Comment by gmgmgm13** [comment]
@hongwonjun 

우선 답변해주셔서 먼저 감사인사 드립니다.

- 현재 아래 2케이스에서  just git push 체크 안한 경우 웹훅이 동작하지 않으며(에러로그가 없음),
   **just git push 체크 한 경우, 웹훅 발송은 되나 mattermost payload에 맞지 않아 400 에러가 나고 있습니다.**
 1) "코드 병합"은 요나에서 코드 주고받기 및 리뷰승인 후 코드 병합 버튼을 통해 PR Merge하는 경우를 의미합니다.
    ex) dev브랜치 → master 브랜치
 2) git 명령어를 통해 로컬 저장소에 commit된 소스를 YONA Git 원격 저장소 브랜치에  push하는 경우
 **※ 메신저향 (just git push 체크 안한 경우)의 경우는, 
PR Merge 및 git push 시에 웹훅 동작을 안하는 것이 현재 기준 정상 동작이란 말씀인지.. 궁금합니다.^^**

- just git push 체크되어 있음에도 400에러가 나는 이유는 mattermost는 payload내 "text"또는 "attachments"가 포함되어 있어야하는데, https://github.com/yona-projects/yona/blob/0f497276f5049591f7a18fcb19f282954e8ae119/app/models/Webhook.java#L665%EC%99%80%EB%8A%94 
```
 private String buildRequestBody(List<RevCommit> commits, List<String> refNames, User sender, String title) {
        ObjectNode requestBody = Json.newObject();
        ObjectMapper mapper = new ObjectMapper();
        ArrayNode refNamesNodes = mapper.createArrayNode();
        ArrayNode commitsNodes = mapper.createArrayNode();

        for (String refName : refNames) {
            refNamesNodes.add(refName);
        }

        requestBody.put("ref", refNamesNodes);

        for (RevCommit commit : commits) {
            commitsNodes.add(buildJSONFromCommit(project, commit));
        }

        requestBody.put("commits", commitsNodes);
        requestBody.put("head_commit", commitsNodes.get(0));
        requestBody.put("sender", buildSenderJSON(sender));
        requestBody.put("pusher", buildPusherJSON(sender));
        requestBody.put("repository", buildRepositoryJSON());

        return Json.stringify(requestBody);
    }
```
와 같이 json에 "text"와 "attachments"가 없이 아래의 예시와 같은 payload를 생성하여 호출하기 때문인 것으로 보입니다.
```
{
    "ref":[
        "refs/heads/master"
    ],
    "commits":[
        {
            "id":"c2f9f27ea16004020d1f4e846217c2825d217a12",
            "message":"test\n",
            "timestamp":"2015-06-12T04:41:21+0900",
            "url":"http://localhost:9000/dddeeee/commit/c2f9f27ea16004020d1f4e846217c2825d217a12",
            "author":{
                "name":"hello",
                "email":"hello@hello.com"
            },
            "committer":{
                "name":"hello",
                "email":"hello@hello.com"
            }
        }
    ],
    "head_commit":{
        "id":"c2f9f27ea16004020d1f4e846217c2825d217a12",
        "message":"test\n",
        "timestamp":"2015-06-12T04:41:21+0900",
        "url":"http://localhost:9000/dddeeee/commit/c2f9f27ea16004020d1f4e846217c2825d217a12",
        "author":{
            "name":"hello",
            "email":"hello@hello.com"
        },
        "committer":{
            "name":"hello",
            "email":"hello@hello.com"
        }
    },
    "sender":{
        "login":"hello",
        "id":2,
        "avatar_url":"/assets/images/default-avatar-128.png",
        "type":"User",
        "site_admin":false
    },
    "pusher":{
        "name":"hello",
        "email":"hello@hello.com"
    },
    "repository":{
        "id":33,
        "name":"dddeeee",
        "owner":"hello",
        "html_url":"/hello/dddeeee",
        "overview":"eee",
        "private":false
    }
} 
```
-  commit(git push)시의 발송을 위한 payload json 생성 코드인 Webhook.java#L665
와 달리 issue 나 comment 등록 등의 Case에서는Webhook.java#L522(아래 코드)와 같이 "text"와 "attachments"를 포함하여 payload를 생성하고 있어 정상동작하고 있습니다.
```
 private String buildRequestJsonWithAttachments(String requestMessage, ArrayNode attachments) {
        ObjectNode requestBody = Json.newObject();
        requestBody.put("text", requestMessage);
        requestBody.put("attachments", attachments);
        return Json.stringify(requestBody);
    }
```

-   모바일 개발이라 jenkins를 연동을 현재 안하고 있어서..ㅠㅠㅠ
    just git push 체크시 메신저에서 알림을 주면 개발자/현업들이 협업하기 더 좋을 듯 싶습니다. 
   감사합니다~^^

**Comment by hongwonjun** [comment]
@gmgmgm13 

상황을 정확하게 판단하고 계시네요.

```
현재 아래 2케이스에서 just git push 체크 안한 경우 웹훅이 동작하지 않으며(에러로그가 없음),
just git push 체크 한 경우, 웹훅 발송은 되나 mattermost payload에 맞지 않아 400 에러가 나고 있습니다.
```

- just git push 를 한 경우 발송되는 message 와 mattermost payload 이 맞지 않습니다. (그렇게 설계되어 있습니다.)
-> 이 케이스는 mattermost payload 에 맞추어 추가적으로 개발을 해야 하는 상황입니다.
개발 자체는 어렵지 않으나 현재 webhook 과 관련된 UI 복잡도가 올라가고 있어서 해당 부분을 어떻게 풀어야 할지 고민을 좀 해보고 지원하도록 하겠습니다.

```
    "코드 병합"은 요나에서 코드 주고받기 및 리뷰승인 후 코드 병합 버튼을 통해 PR Merge하는 경우를 의미합니다.
    ex) dev브랜치 → master 브랜치
    git 명령어를 통해 로컬 저장소에 commit된 소스를 YONA Git 원격 저장소 브랜치에 push하는 경우
    ※ 메신저향 (just git push 체크 안한 경우)의 경우는,
    PR Merge 및 git push 시에 웹훅 동작을 안하는 것이 현재 기준 정상 동작이란 말씀인지.. 궁금합니다.^^
```

- 위에서 말씀드린 것처럼 메신저향 케이스의 경우는 git push 의 경우 webhook 이 발생하지 않습니다. (그렇기 때문에 에러가 발생하지 않는 것으로 생각하시면 됩니다.)
- 다만 PR Merge 의 경우는 webhook 이 동작을 하는 것이 맞습니다. -> 이 부분은 제가 확인한 바로는 잘 동작하고 있기 때문에 에러 로그를 확인할 수 있을지 확인을 요청 드립니다.

**Comment by gmgmgm13** [comment]
@hongwonjun 

- 코드 병합시 흐르는 로직이 git 원격저장소 push와 다른 로직으로 흐르는 건가요??

- 현재 기준, 코드 병합 버튼을 통해 PR Merge 하는 경우에 
 just git push 체크면 git push의 경우와 마찬가지로 webhook 발송이 오류나는 것이 정상이고,
 메신저향에서는 git push의 경우와 다르게 webhook이 동작을 하는 것이 현재 기준 정상 동작이다라는 말씀으로 이해하면 될런지요? 
→ 맞다면, 메신저향에서 코드 병합 버튼 클릭 후 PR Merge 실행하면 아무런 에러로그가 남지 않습니다 ㅠㅠ (git push 케이스와 동일) + mail 로는 발송되것을 확인했습니다.

---------------------------------------------------------------------------------------------
추가글입니다..
- Yona v1.13 에서 "PR Merge 시 webhook 이 발송되지 않음" 에 대한 bug fix 진행하셨는데, 
버전을 올려야 하는걸까요?

**Comment by hongwonjun** [comment]
> 코드 병합시 흐르는 로직이 git 원격저장소 push와 다른 로직으로 흐르는 건가요??

- 네 맞습니다.

> 현재 기준, 코드 병합 버튼을 통해 PR Merge 하는 경우에
> just git push 체크면 git push의 경우와 마찬가지로 webhook 발송이 오류나는 것이 정상이고,

- webhook 발송이 오류가 아니라 webhook 을 받는 mattermost 에서 오류가 나는 것이 맞습니다. (설계가 mattermost 의 payload 와 다르게 되어 있기 때문입니다.)

> 메신저향에서는 git push의 경우와 다르게 webhook이 동작을 하는 것이 현재 기준 정상 동작이다라는 말씀으로 > 이해하면 될런지요?
> → 맞다면, 메신저향에서 코드 병합 버튼 클릭 후 PR Merge 실행하면 아무런 에러로그가 남지 않습니다 ㅠㅠ (git push 케이스와 동일) + mail 로는 발송되것을 확인했습니다.

> 추가글입니다..
> Yona v1.13 에서 "PR Merge 시 webhook 이 발송되지 않음" 에 대한 bug fix 진행하셨는데,
    버전을 올려야 하는걸까요?

- 네 버전을 올리셔야 합니다 ㅠ

**Comment by gmgmgm13** [comment]
@hongwonjun  @doortts 


코드 병합시 webhook 로직이 git push와 webhook 로직이 다르다고 하셔서 재테스트해보았습니다.
** 코드병합시 테스트와 git push 테스트 결과가 혼선이 있었습니다. 죄송합니다 ㅠㅠ**

just git push 체크 한 경우, "코드 병합" PR Merge 시에 웹훅 호출을 하지 않습니다.
**_→코드 병합시 webhook 호출 로직이 git push와 webhook 호출 로직이 다르니...
 just git push 체크시에는 git push 이벤트에만 웹훅 호출하고, PR Merge 시에 웹훅 호출 안하는 것이 정상동작 같습니다._**

다른 분들을 위해 v.1.1.12의 Mattermost 연동 테스트 결과 다시 정리합니다^^
--------------------------------------------------
1) just git push 미체크 (메신저향)
   * 이슈 등록, 코드보내기, 리뷰 승인등 정상 동작
   * 코드 병합(PR Merge)시 웹훅 발송 하지 않음 → v.1.1.13 에서 수정됨.
   * git push 시 webhook 호출하지 않는 것이 정상 동작
2) just git push 체크 
   * git push 시에만 webhook  호출 함 ※ 단, Mattermost payload에 맞지 않아 400 에러 발생
--------------------------------------------------

결과적으로는 v1.1.13버전의 메신저향에서 PR Merge시 웹훅이 잘동작하는지 테스트해보면 될 것 같습니다..^^

h2 설치형으로 테스트 중이어서, 당장은 v1.13를 테스트 할 수는 없겠지만 ㅠㅠ 
이슈 클로즈 후,  v.1.1.13 테스트에 문제 있을시 재 오픈 하도록 하겠습니다.


친절한 답변 정말 감사드립니다.

**Comment by hongwonjun** [comment]
@gmgmgm13 

네 다음 버전에서 관련 부분을 대응해보도록 하겠습니다.
