### ISSUE TITLE
특정 폴더명 오류

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#62]
요나 코드 트리에서 특정 문구가 들어간 폴더의 하위 리스트가 뜨지 않네요.
파악된 특수 기호는 `[`나`]`로 확인 되었습니다.

ps. windows 7, 크롬(최신), 서버-window(mariaDB)
ps2. 백그라운드 처리로 로그가 쌓이지 않고 있어 첨부를 못했습니다.
ps3. 간만에 버그 이슈 하나 올렸네요 ㅎㅎ

![1](https://cloud.githubusercontent.com/assets/5427199/16399894/624bc998-3d11-11e6-97c2-4e4535a845b4.png)

**Comment by doortts** [comment]
아마 개인 일정상 빠르게 해결하진 못할것 같습니다. ㅜ

**Comment by Terrorboy** [comment]
@doortts 아! 그렇군요.
항상 좋은 소스 감사합니다!

**Comment by doortts** [comment]
@Terrorboy 현재기준 https://repo.yona.io 에서 재현되는지 확인한번 부탁드릴게요. 여전하다면 다시 이슈 열어주세요.

**Comment by Terrorboy** [comment]
![bug](https://cloud.githubusercontent.com/assets/5427199/22851430/b8ebf064-f064-11e6-8a77-948af61eab4b.png)

`&`, `(`, `)`, `^`, `'`, `기본한글외 조합`

**Comment by sjstyle** [comment]
특수문자가 있는 폴더들도 git add, commit는 하신건가요?

**Comment by Terrorboy** [comment]
@sjstyle 네네

**Comment by doortts** [comment]
@Terrorboy '리오픈이 안된다'고 하셨는데 그게 어떤 의미이신거에요?

**Comment by sjstyle** [comment]
포함 안된 폴더들만 git add - git commit - git push 해보시겠어요? 
git clone 해도 애초에 커밋을 안한것처럼 안받아지네요.
만약에 해당 커밋들이 서버에 올라가지 않으면 commit id 가 달라서 git repo가 꼬여야 할 것 같습니다.

**Comment by rtboss** [comment]
@Terrorboy 님 정상동작 하는것 같은데요
올려신 프로젝트를 포크하여 **&저장소, (1) 저장소, [1] 저장소** 폴더 3개 생성하여 테스트시 문제 없습니다.
아래 프로젝트에서 확인 가능합니다.
 https://rtboss@repo.yona.io/rtboss/bug

![image](https://cloud.githubusercontent.com/assets/4962243/22918926/54c3e510-f2d0-11e6-8b86-33e7028ded53.png)

혹시 폴드하위에 파일이 없을경우 git이 폴더를 추가하지 않습니다.
참고로 저는 윈도우10에 **tortoiseGIT**으로 작업 했습니다.

**Comment by sjstyle** [comment]
@rtboss 확인 감사합니다.

**Comment by Terrorboy** [comment]
@rtboss 거북이깃 버전좀 알수 있을까요? 어쩌면 거북이 문제 일수도 있겠네요.(업데이트 시도중입니다.)

window7 + tortoiseGIT 1.8.7.0

**Comment by Terrorboy** [comment]
@rtboss @sjstyle 확인 해보니 커밋이 안된 파일이 비어있었네요. 죄송합니다.! ㅠ.ㅠ

**Comment by Terrorboy** [comment]
@doortts 아 이이슈에 대하여 이슈 리오픈이 안됬던 상황입니다. 깃헙 업데이트로 잠시 안됬었나 봅니다.

**Comment by rtboss** [comment]
@Terrorboy 사용중인 버전 입니다.
git version 2.11.1.windows.1
TortoiseGit 2.4.0.0
window 10

**Comment by doortts** [comment]
@Terrorboy 다행이에요! @rtboss 확인 고맙습니다!! : )

**Comment by Terrorboy** [comment]
@rtboss 확인 및 테스트 감사합니다.!!!!
