### ISSUE TITLE
그룹명으로 회원 가입시 이미 존재하는 id

### ISSUE THREAD

**Issue by wittbox** [yona-projects/yona#620]
안녕하세요,

회원가입시 입력하는 id 가 이미 존재하는 그룹명일 경우 중복 id라 뜨고 가입이 안됩니다.

그룹명과 id 는 구분이 될 필요가 있지 않을까요?

감사합니다.

**Comment by doortts** [comment]
네 이야기 주신 내용이 맞습니다. 초기 설계시에 그룹명과 개인 계정의 이름의 중복을 허용하지 않는 방향으로 정했었습니다. 계층 체계를 만들다보니 논리적으로 충돌이 발생해서 우선 그렇게 정했었는데요 아마 많은 상황에서 문제되는 경우가 발생하지 않는다면 현재 기준에서는 변경은 어려울 것 같습니다.

예) 
yona.io/abc 가 그룹일때는 그룹으로 보이고 개인 아이디가 abc 였을때는 프로필페이지로 보이는데 둘 다 허용할 경우 yona.io/abc 는 어디로 가야 하는가? 라는 문제입니다.

**Comment by wittbox** [comment]
감사합니다.
