### ISSUE TITLE
시간 표시 문제

### ISSUE THREAD

**Issue by choiyh73** [yona-projects/yona#622]
안녕하세요?

1.13 pre DB 버전 사용중 입니다.

시간 표시가 9시간 전으로 표시되는군요.
몇 초전 몇 분전 이건 맞습니다.
표준시간 +0 시간대로 표시되는 것 같습니다.
이슈, 게시판, 내 파일 모두 동일합니다.

구글 크롬 브로우져와 네이버 웨일 브로우져로 확인 하였습니다.

서버의 시간 대역은 +9 KST 로 되어 있습니다.

가능하다면 클라이언트쪽 시스템에 설정된 시간 대역에 맞게 표시되면 좋겠군요 :)

감사합니다.

**Comment by doortts** [comment]
현재는 설치된 서버의 Yona 실행 유저가 따르는 시간대를 따르게 되어 있습니다. Yona를 설치하신 서버의 OS는 무엇인가요?

**Comment by choiyh73** [comment]
서버는 ubuntu 입니다. 아... 근데, docker 에서 실행하니까 docker 에서의 시간설정을 봐야 겠군요.
확인 해 보겠습니다.

**Comment by choiyh73** [comment]
java image 받아서 실행했는데, 확인해 보니 시간대역이 UTC 였군요.

**Comment by choiyh73** [comment]
java docker 에서 bin/yona 를 실행하는 스크립트에, ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime 을 추가했는데 안되네요...

#!/bin/bash
YONA_DATA=/yona/data; export YONA_DATA
cd /yona/yona-1.13.0
rm -f RUNNING_PID
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
bin/yona

음... 서버 리부팅하고, exec 로 들어가서 보면 KST 로 바뀌어 있는데 안되네요...
새 이슈 만들어도 UTC 시간으로 나오는군요. 음...

**Comment by choiyh73** [comment]
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
date > d.txt
bin/yona

d.txt 를 확인해 보면 KST 로 나오는데, 요나에 접속해 보면 UTC 시간으로 나오는 군요.

**Comment by doortts** [comment]
```
export TZ="Asia/Seoul"
```
실행파일 환경변수에 한 번 지정해 보시겠어요?
출처: https://www.baeldung.com/java-jvm-time-zone

**Comment by choiyh73** [comment]
오 시간이 바뀝니다.
다만, 과거 항목의 시간은 그대로 UTC 로 표시되네요.
새로 만든 항목만 바뀌는 군요.

**Comment by doortts** [comment]
그런데 사실 저 설정은 시스템의 설정을 무시하고 강제로 timezone을 override 하는 방법이라서 아마 yona가 실행되는 서버의 시스템 기본 timezone은 여전히 UTC 기준으로 되어 있을 수 있습니다.

**Comment by pokev25** [comment]
저는 docker-compose 사용하는데 환경변수에 설정 합니다.

도커 사용자가 전세계 누구든 될 수 있기 때문에 이미지는 UTC로 보통 만들어요.

```
    environment:
      - "TZ=Asia/Seoul"
```

env 파리미터로 주시면 될 것 같네요
https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by choiyh73** [comment]
시간 대역 표시가 나오지 않아서 옛날 시간은 약간 헷갈리는 군요.
시간 대역 표시가 나오거나 현재 사용하는 시간대역으로 통일하여 표시하는 방식도 좋을 듯 합니다.
감사합니다.
