### ISSUE TITLE
이슈 그룹담당자 지정

### ISSUE THREAD

**Issue by bykoo-code** [yona-projects/yona#627]
이슈를 등록시 담당자 지정은 개인별로 되어지는것 같은데 담당자 그룹을 만들고 이슈를 등록시
담당자 그룹 전체에게 할당 되어지게 할 수는 없는지요?

**Comment by doortts** [comment]
한 이슈에 '복수의 담당자 지정' 기능을 이야기 하시는건가요? 
기본적으로 하나의 이슈가 공동의 책임을 갖게 할 경우
지정한 사람의 의도와는 별개로 담당된 일련의 사람들은

- 책임의식이 약해지거나
- 소극적으로 묻어 가거나 

하기 쉽다는 경험을 얻게 되었습니다. 그래서 최종적으로는 여러명 지정 대신에 '서브태스크' 기능을 도입했습니다. 어려명이 함께 진행해야 하는 이슈라면 '서브태스크'로 나누어 할당하시는걸 권장드리고 싶습니다.

![image](https://user-images.githubusercontent.com/520523/77287872-ef065100-6d19-11ea-9eb2-c55645340dda.png)

**Comment by bykoo-code** [comment]
네, 감사합니다.
