### ISSUE TITLE
이슈 수정권한 

### ISSUE THREAD

**Issue by bykoo-code** [yona-projects/yona#628]
오픈된 프로젝트에서 관리자, 사용자 등록 후 이슈를 등록 하였는데 등록자 이외의 사용자도 이슈 본문의 수정권한이 있는 듯 합니다. 이슈 수정의 권한을 프로젝트 관리자만 갖도록 하고 싶은데 이에 대한 기능이 있는지 알고 싶습니다.
yona version은 1.12.0 입니다.

감사합니다.

**Comment by doortts** [comment]
이슈 수정은 작성자 혹은 해당 프로젝트 멤버가 가능하도록 되어 있는데요
아쉬울 수 있으시겠지만 프로젝트 관리자만 수정권한을 같도록 조정하는 기능은 제공하지 않습니다.

일정 상황에서 해당 기능이 필요하다 생각드실 수 있으실텐데요 여기에는 약간의 제품 철학이 담긴 부분이기도 합니다. 

'그 팀의 도구는 그 팀 문화를 반영한다.'

자율과 책임을 기반으로 효율을 지향하는 제품이다 보니 프로젝트 멤버라면 본문도 수정가능하도록 초반부터 설계되어 있습니다. 대신 일종의 보조장치로 타 멤버의 이슈 수정시 변경 사항이 '변경이력' 에 기록되고 메일로도 발송됩니다.

![image](https://user-images.githubusercontent.com/520523/77287442-eeb98600-6d18-11ea-987b-e149433bb090.png)

**Comment by bykoo-code** [comment]
네, 감사합니다.
