### ISSUE TITLE
프로젝트 다운로드

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#63]
https://github.com/naver/yobi/issues/499
예전 요비에 올렸던 이슈인데 혹시 앞으로 계획이 잡혀 있으신지요?

**Comment by doortts** [comment]
프로젝트별 export 기능을 만들고 있습니다. (@Terrorboy 반가워요~~)

**Comment by Terrorboy** [comment]
@doortts 아! 제가 찾지못했나보네요. 감사합니다!
1년 반정도 안쓰다 보니 메뉴가 헛갈리네요 ㅎㅎ

**Comment by Terrorboy** [comment]
실수로 닫았네요  ㅎㅎㅎ

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.2.0 에서 지원하기 시작했습니다.

**Comment by Terrorboy** [comment]
@doortts 수고하셨습니다!
