### ISSUE TITLE
[TIP] windows에서 yona 백그라운드 처리

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#64]
http://www.ntwind.com/software/hstart.html
를 다운받아 적당한 위치에 풀어 줍니다.

### yona_auto_start.bat
```
@echo off
d:
cd D:\yona
del RUNNING_PID
bin\yona.bat
```
아래 내용중 경로를 yona설치 폴더로 잡아 줍니다.
```
d:
cd D:\yona
```

윈도우 시작 프로그램에 `yona_auto_start.bat`를 생성하고 다음과 같이 내용을 채워 줍니다.
```
"D:\Hstart\hstart.exe" /NOCONSOLE "D:\yona\yona_auto_start.bat"
```
내용중 경로는 각 설치 경로로 변경 해주세요.

이제 시작 프로그램에 넣어 두었기 때문에 윈도우가 부팅 되면서 백그라운드 실행이 됩니다.

ps. 윈도우에서 yona종료 시키는 방법은..... 모르겠네요 ㅎㅎㅎ

**Comment by Terrorboy** [comment]
2016-07-07 내용추가 (간혹 config를 못읽는 현상 수정)
```
SET JAVA_OPTS=-Dyona.home=d:/yona -Dconfig.file=d:/yona/conf/application.conf -Dlogger.file=d:/yona/conf/application-logger.xml
```

**Comment by hyunseogi** [comment]
상기 방식으로 시작 프로그램에 등록해서 실행 하는 것은 사용자가 로그인을 해야만 실행이 된다는 맹점이 있습니다.  도움이 되실까 해서 repo.yona.io 에 글을 올려 두었습니다.
https://repo.yona.io/hyunseogi/JHS_TEST/post/2
