### ISSUE TITLE
MariaDB 접속 IP를 변경해도 localhost로 접속을 시도합니다

### ISSUE THREAD

**Issue by yjj8353** [yona-projects/yona#640]
application.conf 파일

```
# MariaDB
db.default.driver=org.mariadb.jdbc.Driver
db.default.url="jdbc:mariadb://192.168.99.100:3306/yona?useServerPrepStmts=true"
db.default.user=yona
db.default.password="yonadan"
```

에러로그

`[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused: connect.Message:Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused: connect`

제목 그대로 application.conf 파일에서 MariaDB IP 정보를 변경해도, yona.bat 파일을 실행하면 localhost로 접속을 시도합니다.
MariaDB는 Docker에 설치한건데, 일단 HeidiSQL로 동작하는걸 확인했습니다.

OS                      : Windows 10 Home
YONA Version    : v1.13.0 Pre-release
MariaDB Version: 10.4.12

**Comment by doortts** [comment]
처음부터 접속이 안되시는건가요? 아니면 중간에 연결이 끊기는 건가요?

그리고 설정파일이 제대로 반영이 안되는 경우의 문제는 대개 YONA_DATA 환경변수 지정에 문제가 있는 경우였습니다.

참고: https://github.com/yona-projects/yona/blob/next/docs/ko/yona-run-and-restart.md

**Comment by yjj8353** [comment]
확인 완료했습니다, 환경변수가 제대로 추가가 안돼서 conf가 엉뚱한데 생성되고 있었네요...
혹시 그리고 예전 이슈중에 openjdk를 이용한 yona 설치가 제대로 안된다는 이슈가 있었던거 같은데, 이 부분은 아직 해결이 안된건가요?

**Comment by doortts** [comment]
현재는 Openjdk 로 실행가능합니다.

**Comment by yjj8353** [comment]
그런가요?
윈도우에서 YONA 13 프리뷰 버전으로 설치할때 openjdk로 에러가 나길래요.
https://wiki.openjdk.java.net/display/jdk8u
jdk는 위 사이트걸로 썼습니다.
일단, 답변 달아주시면 이슈는 클로징 하겠습니다.

**Comment by doortts** [comment]
openjdk 9 이상으로 테스트 해보시겠어요? 저는 예전에는 openjdk 9로, 최근에는 openjdk 13으로 테스트 했었습니다.

그런데 8 도 되는걸로 알고 있습니다. 
Pokev 님의 Yona official Docker 도 8로 알고 있습니다.
https://github.com/pokev25/docker-yona/blob/master/Dockerfile

**Comment by yjj8353** [comment]
어제 테스트 하던 컴퓨터가 죽어서 재포맷하고 새로 설치해봤습니다.

일단 아래 에러 로그입니다.

```
A Java JDK is not installed or can't be found.
JAVA_HOME = "C:\Program Files\OpenJDK\openjdk-8u252-b09"

Please go to
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
and download a valid Java JDK and install before running yona.

If you think this message is in error, please check
your environment variables to see if "java.exe" and "javac.exe" are
available via JAVA_HOME or PATH.
```

OpenJDK는 Chocolatey를 통해 인스톨 했습니다.

**Comment by doortts** [comment]
커맨드창에서

```
java --version
```

결과가 어떻게 표시되나요?

**Comment by yjj8353** [comment]
```
C:\Users\yona>java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

이렇게 뜹니다.
PATH랑 JAVA_HOME은 전부 설정 된 상태에서도 똑같이 에러가 뜹니다.

**Comment by yjj8353** [comment]
혹시나 필요할지도 몰라서 적어 둡니다.

OpenJDK8 설치과정 (PowerShell에서)
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
```
choco install openjdk8
```

이후, JAVA_HOME은 설정되어 있고 PATH만 별도로 수정해 주었습니다.

**Comment by yjj8353** [comment]
일단 혹시나해서 exe로 openjdk 설치하고 설정해봤는데도 문제가 여전하네요.

#436 처럼일단 ```set JAVAOK=true```로 변경해서 임시방편으로 성공하긴 했습니다.
