### ISSUE TITLE
요나 서버가 재시작이 안됩니다.

### ISSUE THREAD

**Issue by interstander** [yona-projects/yona#645]
요나를 이제 갓 설치해서 테스트 해보려고 합니다.
환경은 윈도우이고 
요나는 1.15버전입니다.
디비는 maria 10.3.10버전을 사용중이고
JDK는 1.8.0_241을 사용중입니다.

처음 mariaDB에서 
set global innodb_file_format = BARRACUDA;
set global innodb_file_format_max = BARRACUDA;
set global innodb_large_prefix = ON;

이 부분 셋팅 빼곤 잘 되었습니다.( 10.3버전에서 innodb_file_format이런 변수가 삭제되었다고 하더군요)

요나를 실행하기 위한 배치 파일은
------------------------------------------------------------------------------------------------------
@echo off

SET YONA_DATA=C:\Yona\data
SET JAVA_OPTS=-DapplyEvolutions.default=true -Dhttp.port=9500 -Xmx2048m -Xms2048m
yona-1.13.0\bin\yona.bat
pause
------------------------------------------------------------------------------------------------------
형태로 작성했습니다.

첫 실행은 잘 되었고 관리자 계정까지 만들었습니다.
관리자 계정을 만들고 나니 재시작을 하라고 해서
배치파일이 실행중인 명령프롬프트를 그냥 껐습니다.   ctrl+c가 아닌 그냥 창을 껐습니다.

그러고 배치파일을 다시 실행하니
This application is already running (Or delete C:\Yona\yona-1.13.0\bin\..\RUNNING_PID file).
라는 메시지가 나오면서 요나가 실행되지 않습니다.
아니 요나에 접속이 되지 않습니다.

컴퓨터를 재부팅을 여러번 해봤습니다만 같은 현상이 반복됩니다.

혹시나 해결방법이 없다면 요나를 제거하려면 폴더만 삭제하면 될까요?

**Comment by rtboss** [comment]
yona가 정상적인 종료가 되지 않아 발생한 문제로 추정됩니다
yona 설치 폴드의 "RUNNING_PID" 파일을 삭제하고 실행하시면 정상 동작 될 겁니다.

**Comment by interstander** [comment]
yona를 통채로 지우고 다시 했습니다.
미리 확인했으면 좋았을텐데..감사합니다.

**Comment by interstander** [comment]
yona를 통채로 지우고 다시 했습니다.
미리 확인했으면 좋았을텐데..감사합니다.
