### ISSUE TITLE
사이트 설정방법

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#65]
`application.siteName`과 `signup.require.confirm` 를 수정 하고자 합니다.
수정 해본 사항들은 다음과 같습니다.
1. yona/bin/conf/application.conf - 실패
2. yona/conf/application.conf - 실패
3. yona/conf/application.conf.default - 실패

어디를 수정 해야 하나요? yobi의 경우 `yona/conf/application.conf `를 수정 하면 되었는데..

ps. 비가 많이 오내요 출퇴근길 조심 하세요~

**Comment by pokev25** [comment]
2번으로 되어야 하는게 정상인데요..

**Comment by Terrorboy** [comment]
@pokev25 그러게요 yobi에서 사용 하던데로 2번처럼 해서 변하지 않기에 1번, 3번도 수정 했는데 안되더라구요. 윈도우 서버라 그런가....

**Comment by doortts** [comment]
2번으로 되어야 하는게 정상맞아요. 음...
한번 
https://github.com/yona-projects/yona#windows의-경우
를 보고 직접 conf 파일을 지정해서 실행해봐 주시겠어요?

**Comment by Terrorboy** [comment]
@doortts 
이상하군요
```
SET JAVA_OPTS=-Dyona.home=/home/user/.yona -Dconfig.file=/home/user/.yona/conf/application.conf -Dlogger.file=/home/user/.yona/conf/application-logger.xml
```
를 환경에 맞게 똑같이 세번 타이핑 하고 나서야 정상적으로 뜨네요.
윈도우 환경 문제 였나봅니다.(워낙 깔린게 많다보니 충돌이 있었을지도...)
