### ISSUE TITLE
[Conflict] Already modified by someone.

### ISSUE THREAD

**Issue by lamia100** [yona-projects/yona#653]
원인은 알기 어려우나 체크리스트 작성후 체크박스를 변경하려고 하는경우
[Conflict] Already modified by someone.
이라는 에러 팝업이 표시되고 체크 상태가 저장되지 않습니다.
왠지 제가 작성한 체크리스트에 예약어가 포함되어 있는건가 하는 생각은 들긴 합니다.

![image](https://user-images.githubusercontent.com/1259992/85348510-d1be6a00-b536-11ea-9d64-0483e21052c1.png)

오류발생함
https://repo.yona.io/lamia100/테스트/issue/1

정상
https://repo.yona.io/lamia100/테스트/issue/2

**Comment by doortts** [comment]
Fixed v1.14.0
