### ISSUE TITLE
페이지 수 표기 오류

### ISSUE THREAD

**Issue by h0ngz** [yona-projects/yona#66]
<img width="1067" alt="2016-07-06 3 33 52" src="https://cloud.githubusercontent.com/assets/5969709/16609485/76bb10bc-438f-11e6-9b0f-5b9882102299.png">

프로젝트가 몇개안됨에도 불구하고 페이지수 저렇게 됩니다.

다음페이지가도 아무것도 안나오구요.

이게 아마 만들었다가 삭제한 프로젝트들을 포함해서 토탈수를 잡기 때문인것 같아요.

**Comment by doortts** [comment]
이건 알려진 버그인데요 페이징 계산할때 private 프로젝트까지 포함해서 계산하고 실제 보려면 private은 감춰져버려서 그렇습니다. 수정해야 해요

**Comment by doortts** [comment]
의외로 이게 꽤 해결이 간단하지가 않다는 걸 알게 되었습니다.

**Comment by doortts** [comment]
v1.4에서 우선 공개 프로젝트만 보여주는 방식으로 변경해서 이 문제는 해결했습니다.
