### ISSUE TITLE
CPU 과점유 현상

### ISSUE THREAD

**Issue by yoosejin** [yona-projects/yona#668]
일단 현상은 사용량이 많지 않음에도 CPU 전체 코어를 사용하는 현상입니다.

검색해보니 과거 이슈에서 쓰레드 값을 조정하여 해결했다는 내용을 확인하였고 수정했으나 해소가 되지 않았습니다.

설정-------------------------
parallelism-min = 30
parallelism-max = 100
------------------------------

다른 방법으로 문제를 해결하긴 했는데 그 방법은 JDK 다운그레이드 입니다.

openjdk-1.8.0.265 버전에서 CPU 과점유 현상이 발생하였고,
openjdk-1.8.0.252 버전으로 다운그레이드 이후 정상으로 동작하고 있습니다.

사용중인 yona 버전은 1.12.0입니다.

같은 문제를 겪고 계신 다른 분들을 위해 공유 차원에서 글을 남깁니다.

**Comment by doortts** [comment]
내용 공유 고맙습니다! 유사한 상황 발생시 다른 분들에게도 도움이 될 것 같아요!! :)
