### ISSUE TITLE
인텔리j 개발/디버깅 환경 어떻게 만드나요?

### ISSUE THREAD

**Issue by jaedo-good** [yona-projects/yona#670]
인텔리j 개발/디버깅 환경 어떻게 만드나요?

**Comment by doortts** [comment]
위키 페이지에서 https://github.com/yona-projects/yona/wiki

![image](https://user-images.githubusercontent.com/520523/98350584-e3745a00-205e-11eb-998b-10a90e236bab.png)

위 링크를 참고해주세요
outdated 로 만약 문제가 생기시면 댓글로 남겨주시면 추가로 살펴보겠습니다.

**Comment by jaedo-good** [comment]
![image](https://user-images.githubusercontent.com/7520861/98528857-3a2c9e80-22c0-11eb-8263-fc4c80d34e3e.png)



"com.typesafe.activator#activator-launcher;1.2.10: not found" -> 오류가 나는데 어떻게 실행하는건가요???

**Comment by jaedo-good** [comment]
> 위키 페이지에서 https://github.com/yona-projects/yona/wiki
> 
> ![image](https://user-images.githubusercontent.com/520523/98350584-e3745a00-205e-11eb-998b-10a90e236bab.png)
> 
> 위 링크를 참고해주세요
> outdated 로 만약 문제가 생기시면 댓글로 남겨주시면 추가로 살펴보겠습니다.

maven 라이브러리 파일들 받을수 있을까요? 먼가 라이브러리 링크가 다운로드 안되는것이 많은것은데......

**Comment by doortts** [comment]
참고: https://github.com/yona-projects/yona/issues/673#issuecomment-725338644
