### ISSUE TITLE
소스실행에 필요한 .ivy 폴더 전체 파일을 받을수 없을까요?

### ISSUE THREAD

**Issue by jaedo-good** [yona-projects/yona#673]
소스실행에 필요한 .ivy 폴더 전체 파일을 받을수 없을까요?
라이브러리 다운로드도 안되고, 소스로 실행을 도저히할수가 없네요

**Comment by doortts** [comment]
https://github.com/yona-projects/yona-dev-env
가 도움이 될지 확인 부탁드릴게요

**Comment by jaedo-good** [comment]
> https://github.com/yona-projects/yona-dev-env
> 가 도움이 될지 확인 부탁드릴게요

감사합니다.

**Comment by jaedo-good** [comment]
라이브러리 다운받아서 사용하니 잘되네요 감사합니다.
