### ISSUE TITLE
git working directory 확인 방법 문의

### ISSUE THREAD

**Issue by jonglee823** [yona-projects/yona#676]
os : linux 

git version : 2.22.0

git reset --hard[브런치] 를 실행하면 다음과 같은 문구가 출력됩니다.

git fatal 이 작업은 작업 폴더에서 실행해야 합니다.

git log 명령어를 실행했을때는 잘나옵니다..

혹시 yona를 통해 설치, 설정된 git에서 reset hard하려면 working directory를 어떻게 확인 해야할까요..?

제가 설정한 사람이 아니라서 설정한 사람한테는 물어보기 어려울것 같습니다 ㅠㅠ
기본적인거라 죄송합니다.

**Comment by doortts** [comment]
안녕하세요 git 관련 명령어 오류처럼 보이는데요 스샷이 있으면 좀 더 이야기 드리기 편할것 같습니다... 라고 타이핑 치는 도중에 closed 하셨네요.. (...) 잘 해결 되셨길 기원합니다.

**Comment by jonglee823** [comment]
앗 정말 감사합니다.

공공사업중이라.. 스샷은 어려울것 같아요.

제 질문이 개발환경에 종속된 질문같아서 제가 열심히 찾아보려고 내렸습니다.

정말 감사합니다. 

즐거운 하루 보내세요:)
