### ISSUE TITLE
그룹공개 프로젝트의 코드 주고받기 문의

### ISSUE THREAD

**Issue by asklsd** [yona-projects/yona#686]
1.14 버전 사용중입니다.
그룹공개 프로젝트에서 
그룹멤버로는 등록되어있고, 프로젝트 멤버로는 등록 안된 사용자가 
새 코드주고받기를 생성하려고 할 때
아래와 같이 프로젝트를 선택 할 수 없어 코드 주고받기를 생성할 수 없습니다.
![image](https://user-images.githubusercontent.com/6562368/112267160-6289c800-8cb8-11eb-86c3-02cd268ce2c4.png)

이 상황은 의도된건가요? 버그인가요?

**Comment by doortts** [comment]
코드 주고받기 관련 기능은 현재는 해당 프로젝트 멤버만 가능하게 되어 있습니다. 이외의 사용자는 `코드 저장소 복사하기`를 이용해서 저장소 복제 후 주고받기를 해야 합니다.

**Comment by asklsd** [comment]
답변 감사합니다
