### ISSUE TITLE
Yona 비밀번호 재설정 페이지 오류 (이메일 미발송 및 확인불가)

### ISSUE THREAD

**Issue by devlunch4** [yona-projects/yona#692]
소셜로그인 유저입니다. (구글)
소셜로그인 이후 Yona 계정의 로그인을 위해 비밀번호 재설정시 
재설정을 위한 이메일이 발송되지 않는 것인지, 해당 메일 수신이 되지 않습니다. (스팸함에도 수신된 메일 없음)
확인 부탁드립니다.

**Comment by doortts** [comment]
소셜로그인을 하고 나면 Yona 에서 계정 재설정이 저장소 push/pull 에서만 영향을 주고 나머지는 소셜 로그인 상태를 따라갑니다.

**Comment by devlunch4** [comment]
답변 감사합니다.
