### ISSUE TITLE
pycham 에서 get from version control 에서의 연동 및 로그인/비밀번호 관련 문의 드립니다.

### ISSUE THREAD

**Issue by devlunch4** [yona-projects/yona#694]
pycham 에서 get from version control 에서의 연동 및 로그인/비밀번호 관련 문의 드립니다.
로그인을 위해 해당 프로젝트의 주소 입력후 
로그인 및 비밀번호 입력을 하여 연동을 하려하는데.
현재 계정이 소셜로그인 상태입니다. 이에 아이디는 있으나 비밀번호를 소셜로그인 계정의 비밀번호로 입력시 로그인이 되지 않습니다. 
해결방법이 어떻게 될지 문의드립니다.

https://repo.yona.io

**Comment by doortts** [comment]
소셜로그인의 경우 인증을 소셜사이트로부터 받아오며 패스워드를 자체 저장하지 않습니다. 소셜로그인이 아닌 계정로그인 형식으로 로그인하셔야 하며 이경우 repo.yona.io 에서 패스워드 리셋작업이 필요합니다. 
소셜사이트 패스워드가 바뀌는 것이 아니라 repo.yona.io 의 로그인용 패스워드만 바뀐다는 점을 유의해 주시고
이때 사용하게되는 아이디는 사용자 프로필 페이지 https://repo.yona.io/user/editform 에서 확인가능합니다.
