### ISSUE TITLE
회원가입 인증메일이 오지 않아요...

### ISSUE THREAD

**Issue by cyPark9510** [yona-projects/yona#696]
저번주에 회원가입을 하고

네이버 이메일을 입력했는데 아직까지 인증메일이 오지 않아요....

저는 https://repo.yona.io/users/signupform 여기서 가입했습니다.

아이디 : cas15987
이메일 : cas15987@naver.com 입니다.

**Comment by doortts** [comment]
잠기해제 되었습니다. 확인해보세요.
