### ISSUE TITLE
Yona 가입 메일 문의

### ISSUE THREAD

**Issue by hee513** [yona-projects/yona#698]
안녕하세요 Yona 가입을 했는데, 가입 메일이 오지 않습니다.
https://repo.yona.io/
여기서 멤버 가입을 눌러서 진행했습니다. 혹시 오류인가 싶어서 다른 이메일로도 만들었는데 (총 2개 생성) 이메일은 오지 않습니다,
재가입 하려고 하면 존재하는 이메일이라고만 뜨네요

**Comment by doortts** [comment]
여전히 동일한 문제를 겪고 계시면 알려주세요
