### ISSUE TITLE
Yona 가입 확인 메일이 오지 않습니다. 

### ISSUE THREAD

**Issue by DukhaengLee** [yona-projects/yona#705]
Yona 가입 확인 메일이 오지 않습니다. 

ID: dh_lee

**Comment by doortts** [comment]
repo.yona.io 를 말하시는건가요?

**Comment by Ukheon** [comment]
저도 가입확인 메일이 오질 않습니다.

**Comment by doortts** [comment]
> 저도 가입확인 메일이 오질 않습니다.

확인해보시고 안되시면 메일주소 남겨주세요
