### ISSUE TITLE
Multiple Assignees 을 지원할 계획이 있나요?

### ISSUE THREAD

**Issue by DaeHyeoNi** [yona-projects/yona#708]
코드를 살펴보니 준비하려고 하신거 같은데 계획된 일정이 있나요?

**Comment by doortts** [comment]
Multiple Assignees 에 대한 계획이 예전엔 있었는데 두 가지 이유로 더이상 진행하지 않았습니다.
- 서브태스크 기능을 도입
- 한가지 일을 두 사람 이상이 맡게 되었을때 책임의 분산 (주 이유)

두 번째 이유로 인해 메인 담당자는 한 사람이 좋다는걸 경험을 통해 결정하게 되었습니다. 필요하다면 서브태스크를 만들어서 부분을 나누는 식으로 하는 쪽으로요.

**Comment by DaeHyeoNi** [comment]
그렇군요 답변 감사합니다.
