### ISSUE TITLE
Yona 가입 메일 문의

### ISSUE THREAD

**Issue by sys3316** [yona-projects/yona#709]
https://repo.yona.io/

yona 사용을 위한 가입을 진행하였는데 가입 인증 메일이 오지 않습니다.
sys3316 / sys3316@emoney.co.kr

**Comment by doortts** [comment]
안녕하세요? repo.yona.io 에는 해당 이메일이나 계정으로 가입신청된 내용이 존재하지 않습니다.

**Comment by sys3316** [comment]
로그인시, "잠긴 사용자 계정입니다. 이메일함에서 가입 확인메일을 찾이 확인 링크를 누르세요. 만약 메일이 없다면 어드민에게 연락하세요"라는 문구가 뜹니다. 한번 더 확인부탁드립니다.

**Comment by sys3316** [comment]
> 안녕하세요? repo.yona.io 에는 해당 이메일이나 계정으로 가입신청된 내용이 존재하지 않습니다.

로그인시, "잠긴 사용자 계정입니다. 이메일함에서 가입 확인메일을 찾이 확인 링크를 누르세요. 만약 메일이 없다면 어드민에게 연락하세요"라는 문구가 뜹니다. 한번 더 확인부탁드립니다.

**Comment by doortts** [comment]
처리되었습니다! 문제시 다시 열어주세요 :)
