### ISSUE TITLE
application.allowsAnonymousAccess 이 동작하지 않습니다.

### ISSUE THREAD

**Issue by Gloriashield** [yona-projects/yona#71]
안녕하세요?

일반 회원 가입을 막고자 옵션을 true 에서 false 로 변경했습니다만,

application.allowsAnonymousAccess=false

재시작을 했음에도 불구하고 여전히 회원 가입이 가능합니다 (ㅠㅠ)
혹시 옵션을 잘못 찾은 것 일까요?

감사합니다 ///ㅂ//

**Comment by doortts** [comment]
저 옵션은 로그인하지 않은 유저들이 공개 프로젝트를 볼 수 있게 할 것인지를 정하는 옵션입니다.

#if you want to use sign-up confirm, uncomment below
signup.require.confirm = true

이 부분을 추가하시면
이제 가입해도 어드민이 해당 유저를 사용상태로 바꿔주지 않으면 사용불가 상태가 됩니다.

설명이 부족해서 오해가 된 것 같습니다.
수정해야 겠어요.

**Comment by sjstyle** [comment]
@doortts  이것도 해결된 이슈로 보입니다.

**Comment by doortts** [comment]
@sjstyle 네. 핑계김에 팀 멤버 권한 드렸습니다. 혹시 지나다가 처리할 일 있으면 자유롭게 닫거나 열어주세요. 마찬가지로 저도 필요하다면 다시 열거나 닫거나 할게요. : )
