### ISSUE TITLE
yona 잠김 사용자 계정

### ISSUE THREAD

**Issue by sys3316** [yona-projects/yona#711]
http://yona.x1.co.kr/users/loginform

sys3316 / "잠긴 사용자 계정입니다. 이메일함에서 가입 확인메일을 찾거나 어드민에게 연락하세요" 안내창이 뜹니다.
확인부탁드립니다.

**Comment by doortts** [comment]
현재 활성화사용자로 표시되고 있습니다.

**Comment by doortts** [comment]
알려주신 사이트는 설치하신 엔지니어에게 문의해주세요.
