### ISSUE TITLE
프로젝트가 중복생성되어 삭제가 되지 않음.

### ISSUE THREAD

**Issue by jangyk27** [yona-projects/yona#712]
![image](https://user-images.githubusercontent.com/47581511/129827309-4fd69308-1dfe-4d8d-807f-1aa9e925a746.png)

![image](https://user-images.githubusercontent.com/47581511/129827428-155822aa-d6ca-42d5-98c7-189c41b81bba.png)

프로젝트 생성 시 반응이 없어서 생성버튼을 두 번 클릭했더니 동일프로젝트가 두 개 생성되었고,
삭제 시 위와같은 오류메시지와 함께 삭제가 되지 않습니다.
이름변경도 되지않아 난감한 상황인데, 어떻게 해야하나요?

**Comment by doortts** [comment]
둘 다 어느쪽도 삭제가 되지 않는 상태인가요?

**Comment by jangyk27** [comment]
> 둘 다 어느쪽도 삭제가 되지 않는 상태인가요?

네, 둘 다 삭제 및 이름변경이 되지 않습니다.

**Comment by doortts** [comment]
시스템 어드민으로 사이트 관리자 메뉴에서 삭제진행해보시겠어요?

**Comment by jangyk27** [comment]
> 시스템 어드민으로 사이트 관리자 메뉴에서 삭제진행해보시겠어요?

시스템어드민으로 삭제해도 동일하게 오류가발생되네요..ㅠ

**Comment by jangyk27** [comment]
음. 일단 서버에서 데이터베이스 테이블에서 삭제를 통해 지웠습니다. 혹시 문제가 생기면 다시 이슈를 올려 여쭙겠습니다.

**Comment by doortts** [comment]
고생하셨어요. 큰 도움 못드려 부끄럽네요.
