### ISSUE TITLE
Wiki에 있는 Telegram 사용자채널 링크가 접속이 안되네요.

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#713]
안녕하세요~~
몇년째 요나를 잘 이용하고 있는 유저입니다. ^^ 감사드립니다.
어째.. 하다보니 저는 개발용 쪼끔하고 BBS 용도로 많이 이용하고 있네요.

이번에 Wiki쪽을 살펴보는데.. 텔레그램 접속 링크가 시효가 다 되었다하여...
혹시 계속 운영하고 계시면, 접속링크를 알려주십사하고 적어봅니다.

Wiki 수정권한은 여전히 가지고 있으니, 나름 최신화해서.. 수정도 해보겠습니다.

**Comment by doortts** [comment]
안녕하세요? 오랜만이에요.
https://t.me/joinchat/PJ-mzFAOPmLYjNHa
텔레그램 그룹 링크입니다.

홈페이지쪽도 링크 업데이트 해 놓았습니다.

**Comment by minishanell** [comment]
![image](https://user-images.githubusercontent.com/13401664/130010270-4346c443-26b6-44b1-8051-dedaa46ba9e2.png)
이렇게 나오고 들어가지지가 않네요..
새로알려주신 주소도, 이전 주소도 그러네요.

**Comment by doortts** [comment]
아 그러네요. 저도 링크 새로만든건데 초대가 안되는거였군요. 이번기회에 슬랙으로 옮겨야 하나 싶기도 하네요.

**Comment by doortts** [comment]
https://t.me/joinchat/KRvrSlNmt91mMzY6
우선 이걸로 해보시겠어요?
