### ISSUE TITLE
v1.15.0 업그레이드 후 자동 링크 풀림 현상

### ISSUE THREAD

**Issue by leroro** [yona-projects/yona#714]
안녕하세요?
요나로 거의 대부분의 프로젝트를 진행하며 항상 감사히 쓰고 있는 기업입니다 :)

v1.15.0 업그레이드 후 일부 링크 텍스트에서 링크 풀림 이슈가 발견 됩니다.

특정 링크 형식의 문제인가 싶어 이리저리 테스트 해 보았는데,
한 페이지 내에서 일부 단락을 지우고 등록하면 링크가 걸리고,
일부 단락이 포함되면 링크가 풀리는 등 텍스트 패턴이 원인은 아닌 것 같습니다.

오류를 유발하는 마크다운 예제 및 스크린샷 첨부드립니다.

```
### test
- [test](https://docs.google.com/spreadsheets/d/10uvVzTfJYRHBuDuSGLkJdPoNJgOd6XG45iS5DY961rI/edit?usp=sharing)
- [test](https://docs.google.com/spreadsheets/d/10uvVzTfJYRHBuDuSGLkJdPoNJgOd6XG45iS5DY961rI/edit?usp=sharing)
- https://docs.google.com/spreadsheets/d/10uvVzTfJYRHBuDuSGLkJdPoNJgOd6XG45iS5DY961rI/edit?usp=sharing

### test
- https://docs.google.com/spreadsheets/d/10uvVzTfJYRHBuDuSGLkJdPoNJgOd6XG45iS5DY961rI/edit?usp=sharing
- https://docs.google.com/spreadsheets/d/10uvVzTfJYRHBuDuSGLkJdPoNJgOd6XG45iS5DY961rI/edit?usp=sharing
```

### 마크다운 링크 이후에 오는 링크 풀림 (스크린샷)
![image](https://user-images.githubusercontent.com/4100017/130371723-fdd7df4d-a22e-4a30-a7ef-d69fa9434107.png)

### 마크다운 링크 제거시 링크 정상적으로 걸림 (스크린샷)
![image](https://user-images.githubusercontent.com/4100017/130371733-7f800a2c-aad5-4a0d-80e5-42ce95bdc55f.png)

**Comment by doortts** [comment]
이슈제보 고맙습니다. https://github.com/yona-projects/yona/releases/download/v1.15.0/yona-v1.15.1-bin.zip 를 다시 내려받아주세요. 관련 의존 모듈을 다운그레이드 하였습니다.

**Comment by leroro** [comment]
@doortts 해결되었습니다. 감사합니다 :)
