### ISSUE TITLE
주소복사 기능에 포트번호도 같이 나오게 부탁드립니다.~

### ISSUE THREAD

**Issue by hanbada79** [yona-projects/yona#715]
안녕하세요 yona를 설치하고 잘 쓰고 있습니다

한가지 버그가 있어서 문의드립니다.

프로젝트를 만들고 프로젝트에 대한 svn, git 주소를 복사 하는데

port번호가 없어서 출력이 됩니다. 뭐 port번호야 그냥 붙이면 상관없긴한데.

추후에 업데이트시에 포트번호까지 붙어지게 수정좀 부탁드립니다.

**Comment by doortts** [comment]
application.conf 에서 port 번호를 지정하시고 재시작 하시면 되어요.

참고: https://github.com/yona-projects/yona/blob/next/conf/application.conf.default#L171

만약 의도한대로 되지 않으시면 다시 이슈 열어주세요

**Comment by hanbada79** [comment]
감사합니다. 해결 되었습니다.
