### ISSUE TITLE
[Git 연동] Repository 변경

### ISSUE THREAD

**Issue by HeungrokOh** [yona-projects/yona#717]
Yona 초보자입니다.

기존에 Git을 사용하고 있었습니다(서버에 Repository 존재).
Yona를 설치하였는데, 코드 repository를 기존에 사용하던 repository로 변경하고 싶습니다.
어떻게 변경하면 될까요?

**Comment by pokev25** [comment]
https://git-scm.com/book/ko/v2/Git%EC%9D%98-%EA%B8%B0%EC%B4%88-%EB%A6%AC%EB%AA%A8%ED%8A%B8-%EC%A0%80%EC%9E%A5%EC%86%8C

git remote add 로 yona의 저장소를 추가 하시면 둘다 사용 가능 합니다.
