### ISSUE TITLE
1.15.0 h2 버전은 언제 배포나요...

### ISSUE THREAD

**Issue by tabago** [yona-projects/yona#720]
언제나 잘 사용하고 있습니다...
이번에도 업데이트 감사합니다..
궁금한 점은 1.15.0 h2 버전은 언제 배포되는지 알고 싶습니다..

**Comment by doortts** [comment]
h2 버전은 추석 연휴 이후 혹은 월말이 될 것 같습니다.

**Comment by lindolsang** [comment]
안녕하세요. 감사히 잘 쓰고 있습니다. :)
1.15.0 h2 버전 배포일정은 아직 확정 안되었을까요?

**Comment by lindolsang** [comment]
> h2 버전은 추석 연휴 이후 혹은 월말이 될 것 같습니다.

안녕하세요. 감사히 잘 쓰고 있습니다. :)
1.15.0 h2 버전 배포일정은 아직 확정 안되었을까요?

**Comment by doortts** [comment]
1.16버전이 배포되었습니다.
