### ISSUE TITLE
아이디를 찾고싶습니다.

### ISSUE THREAD

**Issue by ssujinchoi** [yona-projects/yona#727]
몇년전에 가입해서 아이디를 찾고싶은데 아이디를 찾을방법이 없네요.그리고 탈퇴기능도 없구요

**Comment by minishanell** [comment]
그러고보니.. 탈퇴기능은 없군요. ^^:;;
관리자가 삭제는 가능해요.

어디에 가입하신건지... 해당 사이트의 관리자에게 요청해보심은 어떨지요?
