### ISSUE TITLE
요나 첫 페이지의 그림을 바꾸고 싶어요.

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#729]
평소에 로그인해서 쓸때는 별로 못느끼지만..
처음 켜지는 요나 메인페이지의 뒤 배경그림을 다른 걸로 교체할 수 있을까요?

한 서버에 요나를 여러개 설치해두고 쓰니. ^^:;; (H2버전 나머지 2개는 일반 BBS처럼 쓰고 있습니다.)
하나는 DB연동, 나머지 두개는 H2버전을 구동했어요. 작동포트를 서로 다르게 설정하고..
아파치에서 리버스 프록시로 서브도메인 부여해서 이용중입니다.

셋 다 똑같은 그림이 나오다보니.. 주소를 보고 찾는 것이 헷갈려서.. 서로 다른 그림이 나오면 좋을 것 같아서요..
에셋을 뒤져보니.. 여러 배경 그림이 들어있던데요... 혹시 내부 설정에서 바꿀 수 있는 방법이 있을까요?

매번 잘 이용하고 있어서 감사드립니다.

**Comment by doortts** [comment]
명시적으로 바꾸는 기능은 현재는 없습니다만
배포판 lib 폴더를 살펴보면 yona.yona-1.15.0-assets.jar 와 같은 배포 버전이 붙은 파일이 있습니다.
```
jar xf yona.yona-1.15.0-assets.jar 
``` 
압축을 해제해보면 project_default.jpg 파일이 기본 헤더 배경 이미지 입니다.
해당 이름으로 다른 이미지를 넣으시고 다시 압축을 하시면
기본 배경이미지가 변경됩니다.

관련코드 https://github.com/yona-projects/yona/blob/next/app/utils/TemplateHelper.scala#L188

**Comment by minishanell** [comment]
감사합니다~~ 이 방법으로 바꾸어보겠습니다.
