### ISSUE TITLE
Yona 에서 Github 프로젝트 이관 이슈

### ISSUE THREAD

**Issue by kairos0** [yona-projects/yona#731]
안녕하세요.

Yona 에서 Github 프로젝트 이관 중 발생한 이슈 해결방법에 대하여 조언을 구하고자 합니다.

현재 https://repo.yona.io/yona-projects/yona-help/post/4 글을 기준으로 프로젝트 이관을 시도하였습니다만..

OAuth Authorization callback URL는 개인 URL로 지정 했음에도 repo.yona.io/migration으로 리다이렉팅 되는 오류가 발생합니다.

* Setting/Applications/Authorized OAuth Apps 에는 연동 된것을 확인하였습니다.

해당 포스트 아래 "redirect url 은 github 설정 변경" 에 대하여 설명이 있지만 해당 방법을 찾을수 없습니다..ㅜㅜ

재확인 결과 github.allow.migration = true 설정 시 client.id에 상관없이 진행됩니다.

버전 1.12.0, 1.15.0 입니다..

도움 부탁드립니다.

**Comment by kairos0** [comment]
자문 자답입니다.

* 1.15.0 기준

원본 소스코드 \public\javascripts\service\yona.Migration.js 위치에 CLIENT_ID 가 하드코딩 되어 있으며, 해당 위치를 수정하거나 URL 요청시 clientID URL 을 수정하시면 됩니다.

다만.. 이슈 및 게시판만 마이그레이션 되는것이 아쉽네요.. 커밋 내역과 소스코드 마이그레이션은 지원하지 않는 듯 합니다.. ㅠㅠ

해당 이슈는 24시간 뒤 close 하겠습니다.

**Comment by doortts** [comment]
네. 아쉽지만 소스코드는 직접 git push 형식으로 github 해당 저장소로 이동해주어야 합니다. 고생하셨어요.
