### ISSUE TITLE
[문의] Yona 내 git 프로젝트를 "Git 저장소에서 코드 가져오기"를 하는 방법이 어떻게 되나요?

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#735]
팀 프로젝트들이 대부분 SVN이 되어 있던 것을 하나씩 바꿔가고 있습니다.
그 일환 중 중요한 기능인 Root 프로젝트를 만들어 fork 해볼려고 하는데요.

Yona 내 생성된 git 프로젝트를 fork 하려고,
 "Git 저장소에서 코드 가져오기" 라는 방법으로 프로젝트를 생성하려고 했습니다.
그런데, "Git 저장소 접근에 실패했습니다(cannot)" 이라는 메시지가 뜹니다.
일단, 원본이 되는 git 프로젝트에서 "주소복사"를 통해 URL을 가져오고
접근권한이 필요한 저장소에 체크한 뒤, 제 아이디와 암호를 넣기 까지는 했는데...
물론 아이디와 암호를 빼보기도 했지만요.
아니면 저 URL이 아닌 다른 형태의 URL로 넣어야 하는지...
한번 성공하면 대략 방법이 어떻게 될지 알겠는데,
계속 위와 같이 실패를 해서요.

방법을 알려주시면 고맙겠습니다.

**Comment by neohind** [comment]
제가 Git을 잘 몰라서 여러가지로 검색은 하는데, github에서 UI 상으로하는 것이 제일 많이 보이더라구요. 그 외에는 git remote 방법인거 같은데요. 직접 git command로 해야 하는지... 일단 yona에서 처리가 가능한지 여부를 확인하고 싶어서 issue Open 해봤습니다.

**Comment by pokev25** [comment]
테스트 하신 서버에서 git 저장소 접근이 안되는것 같습니다.

reop.yona.io 에서 테스트 진행 했습니다.

![image](https://user-images.githubusercontent.com/4251972/145933465-3e7bb0a6-4f4e-4ef1-a5bb-2eded86c6537.png)

github 의  yona 저장소를 가져 오는 테스트 입니다.

![image](https://user-images.githubusercontent.com/4251972/145933530-8b26d511-b1ed-49af-b95a-18f78f079560.png)

github의 주소를 git 저장소 url 로 설정 하고 
공개 저장소라 접근 권한은 체크 하지 않습니다.

비공개 저장소라면 접근권한 체크 하고 계정 정보를 입력 합니다.

![image](https://user-images.githubusercontent.com/4251972/145933596-30eb9b55-03c5-4d88-895d-f22146c1e076.png)


프로젝트 이름과 설명을 입력하고
하단 프로젝트 생성을 누르면 저장소가 생성되어야 합니다.

**Comment by pokev25** [comment]
이미 yona에 생성된 프로젝트라면 '코드 저장소 복사' 버튼을 누르시면 됩니다.

![image](https://user-images.githubusercontent.com/4251972/145934278-cdb10c3f-9f79-4a4c-ab90-b3dea36655db.png)

**Comment by neohind** [comment]
> 

일단, 빈 프로젝트를 만든 뒤, 코드 저장소 복사라는 방법을 취하는건가요?

**Comment by neohind** [comment]
일반적으로는 동작하는데, 제 쪽에서 안되는 것을 봐서는
제 쪽의 yona 서버의 문제일거 같긴한데요.
흠... 로그를 뒤져봐야 될 것 같습니다.

![image](https://user-images.githubusercontent.com/8743784/145938566-7850b618-27d0-423b-9dd5-dd6729bdc4bf.png)

**Comment by neohind** [comment]
시스템 관리자의 실수였던것 같네요;;;;
보니까, Yona 서버의 DNS가 동작하지 않아, 해당 URL로 데이터를 가져오지 못해서 발생한 것 이였습니다.;;;;;;

제쪽 문제이긴 했지만, 관심주셔서 좋은 참고되었습니다;;;

감사합니다.
