### ISSUE TITLE
요나를 새버전으로 이전하려고 합니다.

### ISSUE THREAD

**Issue by zidol** [yona-projects/yona#738]
안녕하세요..
요나를 제공 해주셔서 항상 감사하게 사용하고 있습니다.
다름이 아니라 이번에 사용하던 1.5.1요나를 서버를 이전하면서 1.15.0으로 업그레드 하려고 합니다.
처음 세팅하신분이 퇴사하셔서 우여곡절 끝에 이전하고 웹첫 화면을 띄웠는데 어드민 계정을 만드라고 하네요;;DB까지 이전 했는데 왜 만드라고 하는걸까요? 일단 테스트로 어드민 계정을 새로 만들었더니 서버를 재시작하라는 문구가 떴습니다.
기존에 있던 계정으로 로그인을 했더니 로그인은 잘 되는듯합니다..그럼 기존에 사용하던 admin계정은 어떻게 되는건가요? 아직 테스트라서 괜찮지만 운영중인 yona를 완전 이전 시 어떻게 해야할까요?

**Comment by doortts** [comment]
admin 계정의 id/pw 를 리셋하는 과정이라서 그렇습니다.
다른 문제는 없을 거에요.

**Comment by zidol** [comment]
application.conf의 application.secret 값을 그대로 사용하니 기존의 어드민 계정으로 사용가능한데 이대로 사용 해도 될런지요?

**Comment by doortts** [comment]
@zidol 네 그대로 사용하셔도 되어요. 그 서버 비밀키값을 공개하지만 않으신다면요.

**Comment by zidol** [comment]
답변 감사합니다
