### ISSUE TITLE
요나 버그

### ISSUE THREAD

**Issue by ssong-kg** [yona-projects/yona#744]
version : yona-1.15.0 (구축)
issue : git 사용 중 생긴 버그입니다.
 아이디 ---> nono123
yona 작성자 칸에 보이는 정보 --->  나의 passwod ( 1******) 가 보여짐 
마우스 hover시 href 링크로 안 뜨고 text형태로 보여짐.
참고로 제 프로필 사진도 다른 사람들과 구분하기 위해 windows 배경화면으로 바꿔놨는데 기본 프로필로 보여짐.
(특정 유저만 발생)

이럴 경우에는 어떻게 처리를 해야하는지 알려주시면 감사하겠습니다.

![KakaoTalk_20220118_184445233](https://user-images.githubusercontent.com/41041279/149912520-b98ec9eb-cd7e-48f9-b28d-9b3fbee8fedc.png)

**Comment by Ssong94** [comment]
> 버전 : 요나-1.15.0 (디지엄) 이슈 : git @e.git a, da. [nono23 --->@ --->] [] 주한자 스내, 스위즈, 윈도우, 스위즈,
> 
> 이럴 경우에는 어떻게 처리를 해야하는지...?
> 
> ![KakaoTalk_20220118_184445233](https://user-images.githubusercontent.com/41041279/149912520-b98ec9eb-cd7e-48f9-b28d-9b3fbee8fedc.png)

**Comment by doortts** [comment]
사용하시는 OS와 Web browser, JAVA 버전이 어떻게 되세요?

**Comment by ssong-kg** [comment]
> 
1. 서버 환경 
---> Centos7 / java8 / mariadb 10.3.32 / yona 1.15.0 /

2. 클라이언트 환경
---> windows 10, 11 / 자바 11 / browser - 엣지,크롬, 브레이브 브라우저 등등... 

다른 유저로 로그인 or 비로그인 상태로 프로필에 마우스를 올려도 다른 사람에게 제 비밀번호가 보여집니다.
(생판 모르는 유저가 or 로그인되어 있지 않은 사용자가 제 비밀번호를 볼 수 있음.)

제 컴퓨터 캐시의 문제도 아닙니다.
시크릿모드 or 다른 유저의 컴퓨터 or 모바일에서도 똑같은 현상입니다.

**Comment by doortts** [comment]
저곳은 커밋 작성자의 이메일 혹은 아이디가 표시되는 곳입니다.
저장소에서 커맨드 git 명령으로 git log 했을때 혹시 동일한 메시지가 표시되는지 확인 한번 해주시겠어요?
그리고 가입에 사용한 이메일과 커밋 author 의 email 도 한번 확인부탁드려요.

예시)
![image](https://user-images.githubusercontent.com/520523/150283414-e8a94d44-832c-474a-adea-44316714d45f.png)

**Comment by ssong-kg** [comment]
![yona](https://user-images.githubusercontent.com/41041279/150441061-8214b658-ed1f-44c4-a7b0-3cef56a4b77b.png)

이메일이 들어가야 할 곳에 패스워드가 들어가네요..?
가린곳이 패스워드입니다.

**Comment by doortts** [comment]
조심스런 추측으로는 git user name 지정하실때 email 부분에 password 를 지정해서 설정하신것이 아닌가 싶습니다.

```
git config user.email
```

```
vi ~/.gitconfig
```

실행하셔서 확인해 보시고 필요하다면 변경하셔야 할듯합니다.

확인하셨을때 만약 이메일대신 password 를 지정하신거라면
git commit 은 한번 기록되면 다시 커밋을 수정하기전까지 계속 유지되기 때문에 
커밋 히스토리 전체에 걸쳐서 email 을 수정하시는 작업을 진행하셔야 할 것 같습니다.

이경우 https://stackoverflow.com/a/750182 를 참고해주세요.

**Comment by ssong-kg** [comment]
> 
도움주셔서 정말 감사합니다.
