### ISSUE TITLE
최초 로그인 이메일 이슈

### ISSUE THREAD

**Issue by jinseo-James-Cha** [yona-projects/yona#745]
가입 후, 최초 로그인이라 이메일 인증을 기다리고있습니다.
시간이 지나도 이메일이 도착하지않네요?

보통 얼마나 소요되나요?

**Comment by doortts** [comment]
repo.yona.io 를 말하시는거라면 보통 바로 메일 발송됩니다. 만약 못 받으셨다면 아이디 알려주시면 unlock 해드릴게요

**Comment by LEEJEHEON** [comment]
저도 메일이 오지 않아서 unlock 하고 싶습니다. 혹시 어디로 아이디 말하면 될까요??

**Comment by doortts** [comment]
project.yona@gmail.com 으로 보내주시면 돼요

**Comment by 8breeze** [comment]
저도 메일이 오지 않아서 unlock를 하고 싶어 [project.yona@gmail.com](mailto:project.yona@gmail.com) 로 메일을 보냈는데  처리 부탁합니다.

**Comment by wowddok99** [comment]
메일이 안와서 project.yona로 메일 보냈습니다! 
제 아이디는 wowddok99 입니다. unlock 해제 처리 부탁드려요!!
