### ISSUE TITLE
프로젝트 삭제 후 재생성시 오류

### ISSUE THREAD

**Issue by alzkdpf** [yona-projects/yona#75]
버전 : 1.0.2
운영체제 : 우분투
이슈 : 
서버 이전할때 repo 안에 폴더 일부가 누락되서 옮겨졌는데 누락된 repo에 해당하는 프로젝트 삭제 후 동일한 명(삭제했던 프로젝트명)으로 재생성하니 ‘권한이 없거나 없는 파일’ 라는 에러가 발생하내요. 
계정을 바꿔 생성하면 또 생성이 되고 원래 최초 만들었던 소유 계정에서 생성하면 다시 ‘권한이 없거나 없는 파일’ 에러가 발생합니다.
그리고 추가로 admin 페이지에서 프로젝트 리스트 뷰에 다음, 이전 반복 페이징할때 리스트가 제대로 안나오는 경우가 있는 것 같습니다.

p.s 
잘 사용하고 있습니다. ^^
항상 감사드립니다.~

**Comment by doortts** [comment]
Yona가 설치된 디렉터리(폴더) 하위인 `repo/git` 폴더에 들어가 보시면
계정별로 디렉터리가 보이실거에요. 
문제가 생긴 계정 디렉터리로 들어가셔서 삭제하셨다는 프로젝트가 디렉터리명으로 보이는지 확인해 보시고 삭제해보세요.

순서는

```
Yona에서 해당 프로젝트 삭제 -> 설치디렉터리로 이동해서 저장소 디렉터리내에서도 해당 프로젝트가 삭제되었는지 확인 -> 혹은 권한이 꼬여있지는 않은지 확인 -> 보이면 디렉터리 삭제
```

p.s
@alzkdpf 잘 사용해주셔서 고맙습니다. : )

**Comment by alzkdpf** [comment]
저도 콘솔에서 보면 조금 다를까 싶어서 확인해봤는데 폴더는 정상적으로 생성이 되는데 접근이 안되내요.

그래서 다시 테스트 해봤습니다. ㅋㅋ

**Comment by doortts** [comment]
@alzkdpf  https://github.com/yona-projects/yona/releases/tag/v1.0.3 수정했습니다. 확인부탁드려요
