### ISSUE TITLE
로그인 잠긴사용자 계정입니다

### ISSUE THREAD

**Issue by the-mascot** [yona-projects/yona#750]
안녕하세요 로그인하려는데 계속 잠긴사용자 계정이라고 나옵니다.
이메일에서 가입확인메일을 찾으라는데 메일에 아무것도 안와있네요
이상한건 요나 프로젝트 주소로 들어가면 로그인이 되어있는상태로 들어가지는데
요나 프로젝트 홈페이지에서 로그인할때 계속 안되네욤..
아이디는 dmstn1812 입니다 확인부탁드립니다

**Comment by doortts** [comment]
처리되었습니다
