### ISSUE TITLE
요나에서 사용하는 Play Framework 버전 관련 문의입니다.

### ISSUE THREAD

**Issue by mbh77** [yona-projects/yona#751]
설치 가이드에서 소스코드로 직접 빌드하여 설치할 경우
다운받을 Play Framework 사용 버전이 1.2대 버전입니다.
Play Framework 최신 버전이 2.8 이던데 요나가 최신 프레임워크에도 대응이 되는 것인지 궁금합니다.

2.8 버전 프레임워크는 자바도 동일하게 동작한다고 하지만 스칼라를 위주로 지원하는 것 같은데
향후 스칼라 관련 개발 계획도 있는 지도 같이 알려주세요.

**Comment by doortts** [comment]
플레이프레임워크가 아니라 activator 버전이 1.2 대일거에요.
Yona 의 Play 버전은 2.3 입니다.

**Comment by mbh77** [comment]
네 다시 살펴보기 activator 버전이 1.2군요.
그러나 여전히 Play Framework는 더 이상 activator를 사용하지 않는다고 하는 것 같은데
향후 최신 버전 대응 계획이 있는 것인지 궁금합니다.

제가 Scala나 Play등 사용 경험이 없는 상태입니다.
윈도우에서 가이드 문서에 있는 방법데로 빌드 후 실행을 하려고 하는데
뭔가 제대로 빌드되지 않고 Play Framework 공식 사이트에서도 이에 대해 딱히 지원하지 않는 것 같습니다.

**Comment by mbh77** [comment]
Play와 Activator 사용은 처음인데 뭔가 처음부터 빌드부터 잘 되지 않습니다.

일단 가이드에 있는 repositories 파일 설정도 하고 이미 저장해 놓은 환경 파일을 user/ 및에 있는 폴더에 복사해 봐도
빌드 중에 http://repo1.maven.org/, http://repo.typesafe.com/ 접근하면서 계속 에러가 납니다.

Play 자체도 이제는 activator를 사용하지 않아서 앞으로도 지원이 원할하지 않을 것 같은데
향후 프레임워크 지원 계획은 어떻게 되는지 궁금합니다.
