### ISSUE TITLE
git 다운로드 속도 변경 문의

### ISSUE THREAD

**Issue by tonghyun** [yona-projects/yona#753]
안녕하세요.
yona 프로젝트 관리 시스템을 만드시느라 수고하십니다.

문의드릴 내용은
git clone으로 yona에 등록된 소스를 다운로드하면 초당 5MB 정도의 속도가 나오는데
이 속도를 높이고 싶은데요. 속도를 변경할 수 있는 방법이 있는지요?
application.conf에는 이와 관련된 설정은 없는 것 같네요.

감사합니다.

**Comment by doortts** [comment]
아쉽지만 특별히 속도 관련된 기능은 현재 없습니다.

**Comment by tonghyun** [comment]
답변 감사합니다.
내용을 찾아 봤을 땐 git의 http는 curl을 기반으로 한다고 하는데 그게 영향인지 play frameworks내에서의 기능 제한인지 알 수가 없어 문의드렸었습니다.
수고하세요.
