### ISSUE TITLE
git server hook 질문입니다

### ISSUE THREAD

**Issue by otk2625** [yona-projects/yona#754]
특정 브랜치에 push하는걸 막고 싶어서 git server side hook을 사용하려고 합니다

yona 서버에  프로젝트이름.git 폴더 hooks에 pre-receive를 만들었는데 동작이 안되는데 어떻게 해야 동작하는지 알 수 있을까요?

프로그램적으로 master에 push하는걸 막는 방법이 있는지 알고 싶습니다!

**Comment by doortts** [comment]
아쉽게도 현재 server side git hook 기능은 제공하고 있지 않습니다. 대신 특정 브랜치에 PR을 거치지 않은 push 를 막는 기능 추가를 고려해 보려고 하는데 그 기능이 생긴다면 원하시는 부분이 해결될까요?

**Comment by otk2625** [comment]
@doortts  아 그렇군요~!  그런 기능이 추가된다면 브랜치 관리가 더 잘돼서 제가 원하는 부분이 해결될 것 같네요~! 답변 감사합니다
