### ISSUE TITLE
yona에서 사용 되는 마크다운 에디터가 무엇인가요?

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#76]
커밋 비교 쪽은 에이스에디터인데 마크다운에디터(코멘트, 게시판)은 어떤건가요?
너무 탐나서 ㅎㅎㅎ

**Comment by doortts** [comment]
[marked](https://github.com/chjj/marked) 기반으로 커스텀 CSS를 입힌 형태입니다.
멘션은 [at.js](http://ichord.github.io/At.js/)를 이용해서 만들었고요.

에디터만 따로 떼어내볼까 늘 생각만 하고 있습니다만 
늘 밀리네요.  (Yearly plan에는 들어가 있어요)

**Comment by Terrorboy** [comment]
@doortts 오호 감사합니다. 개인적으로 작업 중인곳에 적용 해보겠습니다 ㅎㅎㅎㅎ
