### ISSUE TITLE
이슈 및 댓글 알림 메일이 오지 않습니다.

### ISSUE THREAD

**Issue by Indra-Yun** [yona-projects/yona#761]
안녕하세요. 

21년 12월에 1.15버전 설치 후 잘 사용하고 있었는데, 지난달 중순즈음부터 이슈 등록 및 댓글 등록시 알림 메일이 오지 않고 있습니다.
관지자 계정을 통한 메일 1건 메일발송은 정상적으로 발송됩니다.

이슈 등록시 로그는 확인 못했으나, 댓글 등록시 로그는 다음과 같습니다. (댓글 대상자는 1명입니다)

```
2022-10-04 19:52:44,179 - [DEBUG] - from play in play-akka.actor.default-dispatcher-43437
Unable to parse part of media range header 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
```

설치된 서버 스펙
CentOS 6.8
MariaDB 10.3
java 1.8(open jdk)

applcation.conf파일에서 별도의 이메일설정은 하지 않았습니다.
```
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gmail smtp
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = yourGmailId
# Be careful!!! Not to leak password
smtp.password = yourGmailPassword
smtp.domain = gmail.com
#true to use mock mailer for testing, false for using real mail server
smtp.mock = true
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5
```

**Comment by doortts** [comment]
안녕하세요? 그동안 메일 서버는 어떤걸 사용하고 계셨는지 확인이 필요한것 같습니다.

**Comment by Indra-Yun** [comment]
sendmail 사용하고 있습니다.

**Comment by Indra-Yun** [comment]
관리자 계정에서 메일전송하기는 정상적으로 되는것으로 보아, 메일 보내는것 자체는 문제가 없는것으로 생각됩니다.

**Comment by doortts** [comment]
발송이 되다가 갑자기 안되는 이런 경우에는 sendmail 계정 자체에서 오류가 있는 경우가 많은데요 관리자 계정은 메일이 전송된다는 점이 특이하네요. 받는 서버에서 스팸으로 분류되어서 거절처리하는 경우도 있지만 동일 유저에게 관리자가 발송하면 메일이 간다는 말씀이시죠?

Yona 설치시 정한 위치 하위의 log 폴더의 application.log 에서 혹시 다른 오류가 있는지 확인 한 번 부탁드릴게요.

**Comment by Indra-Yun** [comment]
별다른 로그는 남지 않습니다.

관리자에서 메일 보낼때 로그입니다.

```
2022-10-05 14:59:02,545 - [INFO] - from application in play-akka.actor.default-dispatcher-43473
>>><1799699794.1418.1664949538739.JavaMail.lotusport@localhost.localdomain>
```

**Comment by Indra-Yun** [comment]
혹시 이게 정상인 상황인가요?
예전에 정상적으로 메일 올때 스샷인데요.

보내는사람과 받는사람의 이메일 주소가 일단 같고, 보내는 사람의 이름은 이슈 등록자(혹은 댓글 작성자)로 표시되며, 실제 제 이메일 주소는 숨김cc처리되어 표시가 되지 않네요.

![image](https://user-images.githubusercontent.com/55868766/193993638-b14ac049-b0a9-4cb7-9a38-b7c94999b74f.png)

**Comment by doortts** [comment]
혹신 수신 대상자들이 gmail.com 메일 유저들인가요?

**Comment by Indra-Yun** [comment]
전부는 아니구요.
gmail, naver, hanmail, 거래처 도메인(실제 메일서버는 뭘 쓰는지 모름) 이렇게 골고루 있습니다.

제 메일은 hanmail이고, 기업메일과 혼용해서 사용합니다.
허나 기업메일 도메인이던, gmail이던, 관리자에서 메일 전송시에는 정상 수신 됩니다.

**Comment by doortts** [comment]
sendmail 발송의 경우 발송서버가 수신 이메일서버로부터 접근이 안되는 경우, 혹은 발송자 이메일과 표시 이메일등이 다른 경우 쉽게 스팸으로 빠지는 경우가 있습니다. 

수신자의 스팸메일함을 확인해 볼 수 있으면 좋을 것 같습니다.

그리고 senmail 발송에 대해서는 발송 로그를 확인해 봐 주시면 좋을 것 같습니다.
https://kslovee.tistory.com/entry/Sendmail-%EB%A1%9C%EA%B7%B8%EB%B6%84%EC%84%9D-%EA%B8%B0%EB%B3%B8

**Comment by Indra-Yun** [comment]
스팸메일로도 수신되지 않아요

그리고 정상 발송, 미발송 모두 로그가 남지 않네요.. 
메일 로그가 왜 안남는지 확인중이긴한데...

**Comment by doortts** [comment]
어떻게 해결되셨어요?

**Comment by Indra-Yun** [comment]
> 어떻게 해결되셨어요?

gmail 설정으로 변경했어요.
예제에도 있는 설정이라 별다른 코멘을 안달았습니다 ㅎㅎ
