### ISSUE TITLE
설치 후 localhost:9000의 메인페이지 css 깨짐

### ISSUE THREAD

**Issue by graylobo** [yona-projects/yona#764]
![image](https://user-images.githubusercontent.com/37823841/197816204-5195bf51-8ba3-4d3b-b2cf-c6bc2ff3a796.png)

요나설치후 localhost:9000에 접근하면 첨부이미지처럼 css가 깨지는데 원인을 알수있을까요?

**Comment by doortts** [comment]
여전히 발생하시면 댓글 남겨주세요.

**Comment by graylobo** [comment]
https://user-images.githubusercontent.com/37823841/199508797-b4cde33b-f0bb-46b5-a97d-2a4268a4d1b0.mp4

여전히 css, js 파일을 로드하지못해서 깨지는 현상이 발생하여 진행과정 영상 첨부드립니다

추가적으로 설정해야되는 부분이 있는지 알려주시면 감사하겠습니다 
(maria db를 사용한 방법, h2 db를 사용한 방법 둘다 시도해보았으나 동일한 현상이며
녹화영상은 h2 db (14버전) 를 사용한 영상입니다)

**Comment by doortts** [comment]
윈도우에서 실행시에 bat 파일을 탐색기로 실행해서는 정상 실행이 되지 않습니다. 😢
https://github.com/yona-projects/yona/blob/next/docs/ko/yona-run-options.md#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0 를 참고하셔서 커맨드 라인으로 home 폴더에서 bin\yona.bat 식으로 실행해 주셔야 정상 실행이 되실거에요.

**Comment by graylobo** [comment]
그래도 동일현상이 발생됩니다 ㅜ 저와 비슷한 케이스인데 해결했던 사례가 없을까요?

https://user-images.githubusercontent.com/37823841/199662272-4bde5a81-974a-48c5-84f8-0da18c4850b5.mp4

**Comment by doortts** [comment]
사용한 java 버전이 어떻게 될까요?
