### ISSUE TITLE
회원가입 후 인증메일이 오지 않습니다

### ISSUE THREAD

**Issue by donghakang** [yona-projects/yona#765]
ID: dkang
EMAIL: dkang@adenasoft.com

확인 부탁드립니다.

**Comment by doortts** [comment]
가입한 사이트를 확인해 보시면 좋겠습니다. https://repo.yona.io 에서는 해당 이메일로 가입 시도한 내용이 없습니다

**Comment by donghakang** [comment]
![스크린샷 2022-11-01 오후 3 07 06](https://user-images.githubusercontent.com/50029346/199169863-b7805afe-5dd4-4dad-b086-71ed9983d9f7.png)

아직도 메일이 오지 않았습니다.
확인해주세요

**Comment by doortts** [comment]
언락처리하였습니다 :)
