### ISSUE TITLE
yona를 aws에서 사용하는경우

### ISSUE THREAD

**Issue by graylobo** [yona-projects/yona#767]
이전회사에서 yona를 굉장히 편리하게 잘사용했어서 현재 이직한 사내에도 yona를 적용해서 사용하고싶어서 
aws에 설치를 완료하였는데요, 몇가지 문의사항을 여쭙습니다

1. 이전회사에서 yona를 사내서버(NAS같은)에 설치했는지 aws에서 설치했는지 모르겠는데 yona를 활용하는 회사에서는 보통
사내서버, aws 둘중 어디에 설치를 하는지, 혹은 둘중에 권장되는 쪽이 있는지 궁금합니다

2. 처음엔 window에 설치하려다 css깨짐문제때문에 실패해서( https://github.com/yona-projects/yona/issues/764 <- 해당 링크에 실패영상올렸는데 시간되실때 답변주시면 감사하겠습니다) 일단 kenu님의 영상을 통해 aws에 설치하는것을 성공했습니다.
업무특성상 10mb~1gb 사이 용량의 zip파일(많은 이미지파일이 담긴 압축파일) 을 이슈등록시 첨부할일이 
많을것 같은데 이런경우 첨부파일이 포함된 이슈가 쌓임에따라서 용량이 누적돼서 aws과금도 점점 많이 나오게 될까요? 
사내에 yona를 제안해서 꼭 사용하고싶은데 aws를 이번에 yona를 설치하면서 처음 다뤄봐서 aws를 통해 yona를 사용할 경우 과금폭탄이 우려되어 차후 책임을 지게 될까봐 걱정이 되네요 ㅜ  

바쁘시겠지만 답변주시면 감사드리겠습니다~!

**Comment by doortts** [comment]
> 1. 사내서버, aws 둘중 어디에 설치를 하는지, 혹은 둘중에 권장되는 쪽이 있는지 궁금합니다

특별히 권장되는 쪽은 없고 편하신 쪽을 사용하시면 됩니다.
저희도 양쪽 모두 사용하고 있습니다.

> 처음엔 window에 설치하려다 css깨짐문제때문에 실패해서( https://github.com/yona-projects/yona/issues/764 <- 해당 링크에 실패영상올렸는데 시간되실때 답변주시면 감사하겠습니다

전에 보고된 적이 없는 사례라 추가적인 확인이나 방법 제안이 조금 어려운 상황입니다. 전체 재 설치 이후에도 동일 문제가 발생한다면 OS 를 변경해 보시면 좋겠습니다. 

> 업무특성상 10mb~1gb 사이 용량의 zip파일(많은 이미지파일이 담긴 압축파일) 을 이슈등록시 첨부할일이
많을것 같은데 이런경우 첨부파일이 포함된 이슈가 쌓임에따라서 용량이 누적돼서 aws과금도 점점 많이 나오게 될까요?

네트워크 사용량과 disk 사용량 양쪽으로 과금이 될 가능성이 있습니다. 관련되서 AWS 요금제를 살펴보셔야 할 것 같습니다. 참고로 비용은 https://www.ncloud.com 와도 비교해 보시면 좋을 것 같습니다.

사내 서버를 이용하시면 이 부분은 훨씬 나으실거라 생각됩니다. 사내망에서 데스크탑 리눅스를 이용하는 방법도 있습니다.
