### ISSUE TITLE
이슈 엑셀 다운로드 시 이슈번호가 아닌..

### ISSUE THREAD

**Issue by h0ngz** [yona-projects/yona#77]
요나 매우 잘 쓰고 있습니다.
### 문제

회사에서 이슈사항으로 토의를 하기 위해 이슈 엑셀 다운로드 시  이슈번호가 나왔으면 좋겠는데 그냥 테이블 id 값이 나옵니다. 하나하나 찾아서 이슈번호 적어줘야되는 이중작업을 하고있습니다.
이슈번호나오도록 수정되었으면 좋겠습니다. 라벨도 엑셀에 나왔으면 좋겠습니다.

> 직접 수정하여 도움을 드려야되는데, 일단은 이슈로 올리고 추후에 시간이 허락되면 열심히 저도 보겠습니다.

**Comment by doortts** [comment]
@h0ngz 최근 #90 이슈를 해결하면서 같이 처리했습니다. 혹시 여유가 되신다면 repo.yona.io 에서 한 번 테스트 진행해 주실수 있을까요?

**Comment by doortts** [comment]
@h0ngz v1.3에서 처리되었습니다. 만약 재현된다면 다시 열어주세요.
