### ISSUE TITLE
로그인 팝업에서 social login 을 숨기는 설정값이 있을까요?

### ISSUE THREAD

**Issue by ezsimple** [yona-projects/yona#772]
yona/conf/application.conf 파일에서, 아래와 같이 설정해 보았습니다.
소셜로그인 버튼을 숨기고 싶습니다. 어떻게 설정하면 숨길 수 있을까요?
```
# choice: github, google
# application.social.login.support = "github, google"
application.social.login.support = ""
```

**Comment by doortts** [comment]
설정하신대로 하면 동작해야 합니다. 의도한대로 동작하지 않는다면 YONA_DATA 설정이 잘 되었는지 확인해보세요.
참고: [Yona 설치](https://github.com/yona-projects/yona/blob/next/docs/ko/install-yona-server.md#%EB%B3%B8%EA%B2%A9%EC%A0%81%EC%9D%B8-%EC%B2%AB-%ED%99%94%EB%A9%B4-%EB%B3%B4%EA%B8%B0-%EC%9C%84%ED%95%9C-%EC%8B%A4%ED%96%89)
