### ISSUE TITLE
사이트 접속이 안됩니다.

### ISSUE THREAD

**Issue by KimWebDev** [yona-projects/yona#774]
http://repo.yona.io/

http://yona.io/

둘 다 안되고 있습니다.

**Comment by doortts** [comment]
확인중입니다. domain 쪽에 문제가 생긴것으로 판단됩니다.

**Comment by doortts** [comment]
domain 제공업체와 컨택중입니다만 해결에 시간이 다소 소요될 것 같습니다. 불편을 끼쳐드려 죄송합니다.

**Comment by KimWebDev** [comment]
확인 감사드립니다.
