### ISSUE TITLE
비밀번호 초기화 링크 접속 불가

### ISSUE THREAD

**Issue by jwcom1995** [yona-projects/yona#776]
비밀번호 초기화를 위해 이메일로 받은 url 접속이 정상적으로 이루어지고 있지 않습니다.

**Comment by doortts** [comment]
처음부터 다시 한 번 시도해 보시겠어요?

**Comment by jwcom1995** [comment]
여러차례 시도해봤는데 계속 접속이 안되네요

메일을 통해 받은 URL 은
 http://13.124.156.175:9000/resetPassword?
로 시작하고 ERR_CONNECTION_TIMED_OUT 뜨면서 접속이 안됩니다.

**Comment by doortts** [comment]
설치하신 서버 주소(ip)가 13.124.156.175 맞으신가요?

**Comment by jwcom1995** [comment]
아 메일로 온 주소 그대로 사용하는걸로 이해했네요.
서버 실사용 주소로 변경후 접속하여 해결했습니다.
감사합니다
