### ISSUE TITLE
가입 메일 인증 문의

### ISSUE THREAD

**Issue by rlatl852** [yona-projects/yona#778]
아이디 : yhkim1220
이메일 : yhkim@sppartners.co.kr

가입 인증 메일이 오지 않았습니다.

**Comment by doortts** [comment]
잠금해제하였습니다

**Comment by rlatl852** [comment]
> 잠금 해제했습니다

본문에 적힌 메일로도 가입시도를 했습니다. 총 두번의 가입 시도였는데요
첫번째 아이디는 잠금해제되었지만 
두번째 가입시도에서의 아이디는 잊어버려 로그인이 불가능합니다. 
아이디 찾기 기능은 없습니까? 아마 본문의 아이디는 처음 시도한 아이디고 이메일은 두번째 시도한 계정의 이메일 입니다.

**Comment by rlatl852** [comment]
> 잠금해제하였습니다
본문에 적힌 아이디와 이메일이 다르네요
yhkim@sppartners.co.kr 로 연결된 아이디를 잠금 해제 하고싶습니다.
아이디를 잊어버려서 생긴 문제입니다.
추가적으로 메일로 아이디를 보내주실 수 있으신가요

**Comment by doortts** [comment]
메일드렸습니다.
