### ISSUE TITLE
기존 형상관리(SVN)이용 가능한가요?

### ISSUE THREAD

**Issue by leesunho0909** [yona-projects/yona#78]

**Comment by rtboss** [comment]
### 기존 SVN을 GIT으로 이전 하는 것을 추천 드립니다. 
   SVN에서 GIT으로 이전은 "git svn"으로 편리하게 이전 할수 있습니다.

### 기존 SVN에서 신규 yona SVN 서버이전 가능합니다.
synsync를 사용하시면 됩니다.
아래는 TEST한 내용입니다.

* TEST 조건 입니다.
 - Windows 10
 - yona 디렉토리 : C:\yona-1.0.2
 - yona 사용자 ID : userid
 - yona 신규 저장소 이름 : Test_SVN_DEST

 - 기존 SVN_ORG 저장소  : https://repo.yona.io/svn/rtboss/Test_SVN_ORG
 - 신규 SVN_DEST 저장소 : C:\yona-1.0.2\repo\svn\userid\Test_SVN_DEST
 
1. yona를 실행하여 신규 SVN 프로젝트 "Test_SVN_DEST"를 생성합니다.
   (userid로 "Test_SVN_DEST"프로젝트를 생성하면 "C:\yona-1.0.2\repo\svn\userid\Test_SVN_DEST"에 신규 저장소가 생성됩니다.)

1. 초기화 "svnsync init"
 C:\yona-1.0.2\repo\svn>svnsync init file:///C:\yona-1.0.2\repo\svn\userid\Test_SVN_DEST https://repo.yona.io/svn/rtboss/Test_SVN_ORG

1. 저장소 복사 "svnsync sync"
 svnsync sync file:///C:\yona-1.0.2\repo\svn\userid\Test_SVN_DEST

참고 : http://www.pyrasis.com/main/Subversion-HOWTO#svnsync
 SVN 다운로드 : https://sliksvn.com/download/

**Comment by doortts** [comment]
@rtboss 친절히 팁 올려주셔서 고맙습니다.
@leesunho0909 Yona가 현재 SVN을 지원하고 있긴 하지만 SVN은 하루빨리 벗어나시는걸 추천드리고 싶어요.

**Comment by rtboss** [comment]
@doortts 직접 코멘트까지 주시고 "Yona" 잘 사용하겠습니다.
