### ISSUE TITLE
인증 메일이 오지 않습니다

### ISSUE THREAD

**Issue by MinJu-A** [yona-projects/yona#781]
회원 가입을 완료하였는데 인증 메일이 오지 않아 로그인을 진행할 수 없습니다. 
메일은 pinokioandmj@jkds.kr로 기입하였습니다 확인 부탁드립니다.

**Comment by MinJu-A** [comment]
관련해서 다른 계정으로 추가 가입을 시도하였지만 여전히 메일이 오지 않습니다 
이번 가입에 사용한 계정은 pinokoandmj@naver.com입니다. 

확인이 되신다면 추가 가입 시도한 계정은 삭제 요청 드립니다. 
번거롭게 해 죄송합니다 확인 부탁드립니다.

**Comment by doortts** [comment]
잠김해제되었습니다! :)
