### ISSUE TITLE
소셜로그인 비밀번호 변경

### ISSUE THREAD

**Issue by PaakTwe** [yona-projects/yona#784]
소셜로그인으로 사용 시 비밀번호를 몰라 사용에 불편이 있습니다.,.

 비밀번호 변경 인증메일도 계속 보내봤지만 반응이 없고 메일이 안옵니다...

 혹시 몰라서
 id oh7934 / e-mail oh7934@naver.com
 id paaktwe / e-mail oh7934@geolabs.co.kr
 으로 가입했는데도 가입인증 메일이 안와서 사용이 불가능합니다.
 
빠른 해결부탁드리겠습니다..

**Comment by doortts** [comment]
잠김해제되었습니다.
