### ISSUE TITLE
비밀번호 재설정 문의드립니다.

### ISSUE THREAD

**Issue by minyingg** [yona-projects/yona#787]
비밀번호 재설정 할때
'메일 발송에 실패했습니다. 잘못된 비밀번호 재 설정 요청입니다.' 
이렇게만 뜨는데 방법은 없나요..? 이메일이랑 아이디 정확하게 적었습니다.

**Comment by doortts** [comment]
소셜로그인(gmail)을 이용해서 로그인해보시겠어요?

**Comment by minyingg** [comment]
> 소셜로그인(gmail)을 이용해서 로그인해보시겠어요?

그렇게 해도 로그인이 안됩니다.ㅠ

**Comment by doortts** [comment]
그렇다면 접근하시려는 서버가 yona demo 서버인 repo.yona.io 가 맞으실까요?

**Comment by minyingg** [comment]
아뇨 사내에서 따로 설치 한 것 같습니다. 주소가 다르네요

**Comment by doortts** [comment]
그 경우에는 설치하신 분에게 문의하셔야 할 것 같습니다 :)
