### ISSUE TITLE
가입 인증 메일이 오지 않고 원래 있던 계정은 로그인이 안 됩니다

### ISSUE THREAD

**Issue by hr960730** [yona-projects/yona#791]
deeperdiving@naver.com (deeperdiving)으로 확인 부탁드립니다.

**Comment by hr960730** [comment]
hr960730@naver,com(hrseo) 확인 부탁드립니다. 또한 how_0102@naver.com(how_0102) 계정이 프로젝트 추가 시 없는 계정이라고 나오는데 같이 확인 부탁드립니다.

**Comment by doortts** [comment]
처리하였습니다. 확인해주세요.

**Comment by hr960730** [comment]
인증 메일 미발송 및 로그인 안 되는 문제, 계정 프로젝트 추가 시 없는 계정이라고 뜨는 이슈 여전하게 지속되고 있습니다.

**Comment by doortts** [comment]
<img width="650" alt="image" src="https://github.com/yona-projects/yona/assets/520523/4fdc249c-cea5-41c7-a910-c3c6503143d4">


두 계정 모두 활성화 상태로 표기되고 있습니다. 원하시면 임시 패스워드를 해당 메일들로 보내드릴게요.
