### ISSUE TITLE
어제 요나 가입시 인증이 안돼서 계정을 풀어주셨는데 다시안됩니다.

### ISSUE THREAD

**Issue by baxksy** [yona-projects/yona#796]
어제 가입한 같은 이메일 계정으로 로그인하려니 없는 계정으로 떠서 다시 가입했는데 인증메일이 안옵니다.

아이디 qorbaxk
이메일 qorbaxk@nextinnovation.kr 입니다.

**Comment by baxksy** [comment]
전 아이디로 로그인이 잘 됩니다. 죄송합니다. 
혹시 같은 이메일로 중복된 것은 아닌지 확인 부탁드립니다. 다른아이디로 가입할때 같은 이메일을 사용했는데 가입이 되었습니다.

**Comment by doortts** [comment]
데모서버 운영이 종료되었습니다.
