### ISSUE TITLE
BOS "지불수단별 정산서(정기결제)" 관련 개선 요청

### ISSUE THREAD

**Issue by 182520** [yona-projects/yona#798]
BOS "지불수단별 정산서(정기결제)" 관련 개선 요청

1. <정산내역> 탭
- <일별 정산서 현황> 탭에서 일자별 당사/PG사의 매출 불일치 대사건에 대해 조회되는 화면
- 예시: 매출일자 7월 2일, 3일에서 +/- 차이나는 3만원에 해당되는 주문 건이 조회 필요
            ※ 참고화면: 최초 BOS "지불수단별 정산서" 와 동일하게 구성 요청하였음 

2. <정산내역>, <상세내역> 탭 
- 본 2개 화면에 조회기준이 되는 <회원번호>가 <신세계유니버스클럽번호>로 변경 필요

**Comment by doortts** [comment]
잘못 작성하신것으로 판단됩니다.
