### ISSUE TITLE
소스 컴파일시 입력줄이 너무 깁니다. 오류 발생

### ISSUE THREAD

**Issue by tabago** [yona-projects/yona#8]
안녕하세요 
소스를 git를 이용해서 컴앤드명령어로 컴파일 및 실행을 하면 
"입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다. "
오류가 나오고 있습니다.
환경은 원도우 환경입니다.
어디를 수정하면 되는지요..
아.. intellij연결해서 실행하면 잘되는데.. 툴이 없는곳에서 사용할라고...
그리고 설치설명이 너무 틀리는군요.. 업데이트가 필요해보입니다.
배포 방법좀 알려주세요..

**Comment by doortts** [comment]
안녕하세요?
windows의 경우 경로깊이가 길 경우 해당 문제가 발생하는 것으로 보고 되어 있습니다.

아래 링크를 참고해 주세요.
https://github.com/naver/yobi/issues/976

**Comment by tabago** [comment]
네네 감사합니다.. 확인해보겠습니다.

**Comment by tabago** [comment]
안녕하세요 소스를 다시 c루트 최상쪽으로 다운받고
play framework까지 풀더안쪽에 복사하여 실행했습니다.
하지만 마찮가지로 계속 같은 오류가 나고 있습니다.

C:\yona>activator
[info] Loading project definition from C:\yona\project
[info] Set current project to yona (in build file:/C:/yona/)
[yona] $ start
[info] Updating {file:/C:/yona/}yobi...
[info] Wrote C:\yona\target\scala-2.10\yona_2.10-1.0.0.pom
[info] Resolving com.google.code.findbugs#jsr305;3.0.0 ...
[info] Done updating.
[info] Packaging C:\yona\target\scala-2.10\yona_2.10-1.0.0.jar ...
[info] Done packaging.

(Starting server. Type Ctrl+D to exit logs, the server will remain in background)

입력 줄이 너무 깁니다.
명령 구문이 올바르지 않습니다.

C:\yona>

**Comment by doortts** [comment]
안녕하세요? 
어제밤에 테스트 해 보았는데요 
제가 테스트 했던 환경에서는 가이드대로 따라했을 때 정상 설치 및 실행 되었습니다.

다만 혹시 activator가 다른 경로에 긴 path로 설치되어 있는건 아닌지 의심됩니다.

저는 c:\act <- activator가 설치된 곳
c:\act\yona <- 요나가 설치된 곳
실행
요나 폴더에서
```
..\activator
```
로 실행했습니다.

**Comment by tabago** [comment]
path가 길다고 해서 동일한 풀더에서 함께복사해서 실행했는데 동일할 결과가 나와서 
고민하다가  play 실행할때 start 대신에 run으로 실행하니 잘동작합니다..
저만 그런지 osx에서도 소스로 실행하면 오류가 나오는데 run명령어로 하면 잘 동작하고 마찮가지로 intellij로 소스받아서 실행해도 잘 동작합니다...제가 머가 잘못하고 있어서 나오는 문제인데..어디가 문제일까요,,ㅠ.ㅠ.
여튼 run명령어로 잘 실행하고 있습니다..
답변 감사합니다.

**Comment by doortts** [comment]
흠.. 이상하네요. 
run으로 실행할때와 start로 실행할때의 차이점은 
start는 배포라이브러리(dist 명령과 동일)를 만들어 내고 그걸 기반으로 실행합니다.
경로는 target\universal\staged 아래쪽에 생기는데 그 경로가 길어져서 인가 싶기도 하고...

그리고 run 으로 실행하면 사실 개발모드라 성능저하가 어느정도 있습니다. 
직접 path를 지정해서 실행해 보는 방법이 있는데 한 번 테스트 해 보겠습니다. (밤에 ㅎ)

그리고 OSX 에서 소스로 실행했을때는 어떤 에러가 나오나요?

**Comment by tabago** [comment]
osx에서 playframework 개발할때 start실행하면conf파일 읽기못하는 경우가 있어서 혹씨나 해서 
activator "start -Dconfig.file=./conf/application.conf" 실행하니 동작합니다.
하지만 관리자정보 입력화면나 계속...저장이후 진행이 안되는군요..
다시 소스를 받아서 확인해보겠습니다.. 또 어디서가 실수로 해서 진행이 안되는것죠..ㅠ.ㅠ

**Comment by doortts** [comment]
osx/unix 에서는 root 에 있는 restart.sh 을 참고해서 한번 실행해 보시겠어요?

**Comment by tabago** [comment]
osx에서 restart.sh 경로패스 수정해서 실행했습니다.
역시 conf를 파일을 못찾는 같습니다..
전에도 동일한 오류가 나와서 플잭할때 한참고생해던기억이 너무 답답해서 구글번역기를 통해서
play framework쪽에 문의했더니 메일준답변이 activator "start -Dconfig.file=./conf/application.conf" 이런씩으로
진행하라는 답변을 받아서 맥에서는 항상 이런씩으로 진행하고 있습니다.....소스를 다시 받아서는 실행을 안했는데 조만간 진행해보겠습니다.
나머지는 오류 메시지 입니다..
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms1024m -Dyobi.home=/Users/.../Documents/yona -Dconfig.file=/Users/.../Documents/yona/conf/application.conf -Dlogger.file=/Users/.../Documents/yona/conf/application-logger.xml
[info] Loading project definition from /Users/.../Documents/yona/project
[info] Set current project to yona (in build file:/Users/.../Documents/yona/)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:114)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:113)

**Comment by doortts** [comment]
@tabago mac 이나 linux 에서는 아래와 같은 쉘을 보통 사용해서 종료와 실행을 하고 있습니다. 
```
#
# User this restart shell just for example
#
PORT=9000
YONA_HOME=/data/yona;export YONA_HOME
PLAY2_HOME=/home/doortts/apps/play2

pid=`fuser $PORT/tcp`
kill $pid
_JAVA_OPTIONS="-Xmx2048m -Xms1024m -Dyobi.home=$YONA_HOME -Dconfig.file=$YONA_HOME/conf/application.conf -Dlogger.file=$YONA_HOME/conf/application-logger.xml -DapplyEvolutions.default=true -Dhttp.port=$PORT"  $PLAY2_HOME/bin/yona
```
한번 해보시겠어요? mac에서는 문제없이 실행되어야 하는데 말입니다.

**Comment by doortts** [comment]
v1.0.1 에서는 windows에서도 YONA_HOME을 인식하도록 변경되었습니다. 만약 v1.0.1에서도 동일 문제가 발생한다면 다시 이슈를 열어주세요.

**Comment by rtboss** [comment]
이문제 해결 되었나요?
저도 start로 실행하면 아래와 같이 "입력 줄이 너무 깁니다." 에러가 발생합니다.
run으로 실행시 정상동작 합니다.
환경은 "윈도우10", yona 1.3.0 입니다.

![yona_start_error](https://cloud.githubusercontent.com/assets/4962243/22724459/9a8a8200-ee09-11e6-9f54-459065aa5e46.png)

설치 폴드는  위에서 말씀하신  
c:\act <- activator
c:\act\yona <- 요나
로 하였습니다.

시스템환경변수는 따로 정의하지 않았습니다.

**Comment by doortts** [comment]
파일을 한 번 새로 다시 다운로드받아보시겠어요?

**Comment by rtboss** [comment]
@doortts 윈도우 재부팅후 activator및 yona 다시 다운로드 하여 실행해도
동일하게 발생됩니다.

java 설정하고 관련이 있을까요.
JDK는 C:\java\jdk1.8 에 설치하고
java 관련 시스템 환경 변수는 아래처럼 추가 하였습니다.
            * C:\java\jdk1.8\bin path에 추가.
            * JAVA_HOME C:\java\jdk1.8 시스템 변수에 추가.
            * CLASSPATH %classpath%; 시스템 변수에 추가
java 및 javac 버전은 v1.8.0_121 입니다

**Comment by doortts** [comment]
@rtboss bin\yona.bat 파일을 여서 155번째 줄 정도가 아래 링크처럼 * 로 줄여져 있는지 확인 부탁드릴게요.
https://github.com/yona-projects/yona/issues/130#issuecomment-276650179

**Comment by rtboss** [comment]
@doortts 님 bin\yona.bat 파일이 *로 줄여져 있지않습니다.
"C:\act\yona\target\universal\stage\bin\yona.bat" 파일 입니다.

릴리즈된 bin\yona.bat 파일과 다릅니다.
아래 이미지가 릴리즈된 파일과 비교한 내용 입니다.
좌측이 생성된 파일이고 우측이 릴리즈 파일입니다.
![yona_bat_diff](https://cloud.githubusercontent.com/assets/4962243/22728578/0a962672-ee22-11e6-8e0b-4b93aa7ee1e5.png)

릴리즈된 bin\yona.bat 파일로 교체 후 Command창에서 실행시 정상 동작됩니다.
![yona_start](https://cloud.githubusercontent.com/assets/4962243/22728597/34dc4e34-ee22-11e6-863b-2a9b9b4a5c40.png)

**Comment by rtboss** [comment]
@doortts 
next 브랜치도 동일한 문제가 발생합니다.
(build.sbt: Fix for Windows OS long path problem" 커밋)

master 브랜치와 next 브랜치에서 생성된 bin\yona.bat 파일이 다르네요.
도움이 되실지 모르겠지만 yona.bat 파일 비교해서 올립니다.

좌측이 next 브랜치 우측이 master 브랜치 입니다.
![next_master](https://cloud.githubusercontent.com/assets/4962243/22732551/e6d3c0b8-ee31-11e6-9073-499dd218e996.png)

**Comment by doortts** [comment]
@rtboss 확인해주셔서 고맙습니다. 소스코드 빌드로 운영중이신걸 알았으면 제가 일찍 이야기드렸을텐데 죄송해요.

현재 개발코드에서 프로그래밍적으로 해당 부분을 수정할 방법을 아직 찾지 못해 우선 불편함 줄이는 차원에서 릴리즈 파일에는 제가 직접 손으로 수정해서 묶어서 올려놓았습니다.

소스 코드에서도 수정해서 적용할 수 있는 방법을 찾을 수 있을거라 믿고(는) 있습니다.

**Comment by rtboss** [comment]
@doortts 별말씀을요.!!
일단 컴파일 후 실행하는 방법을 알았으니 필요할때 컴파일 하는 것은 문제 없을것 같습니다.
yona  감사히 잘 사용하고 있습니다.
