### ISSUE TITLE
ubuntu 설치 

### ISSUE THREAD

**Issue by universe9999** [yona-projects/yona#802]
![image](https://github.com/yona-projects/yona/assets/74581812/0559b314-47df-4042-ace1-2574fe625d84)

리눅스-우분투 가상머신에서 설치 및 테스트중입니다.
(ubuntu22.04 / java8(1.8.0_382) / mariadb 10.6.12)

실행 시 해당 문구를 나타내며 error를 내고 있는데 어떤 문제일까요?

**Comment by doortts** [comment]
에러 메시지가 잘렸는데 아래쪽도 같이 스샷으로 붙여 주시겠어요?

**Comment by universe9999** [comment]
> 에러 메시지가 잘렸는데 아래쪽도 같이 스샷으로 붙여 주시겠어요?

![image](https://github.com/yona-projects/yona/assets/74581812/d40de027-5f00-4c9d-a40c-8ff63555dfb0)
![image](https://github.com/yona-projects/yona/assets/74581812/30256afc-732f-4704-bf11-c62c63df84a9)
![image](https://github.com/yona-projects/yona/assets/74581812/19b542cc-525b-47ba-8879-d2d3e3a8c99d)
 이렇게 나오네요.
