### ISSUE TITLE
언어 변경 방법 알려주세요.

### ISSUE THREAD

**Issue by klrodel** [yona-projects/yona#806]
한글로 언어 변경하고 싶은데 아무리 찾아봐도 변경하는 메뉴가 없네요.. 
어떻게 바꿔야 하나요?  한글 패치 같은것이 있나요?
크롬에서 한글로 번역 사용하니 내용이 이상합니다.

![image](https://github.com/yona-projects/yona/assets/13342140/42d4e74f-3650-46bc-8b44-b7487ae5c30b)

**Comment by doortts** [comment]
현재 사용하시는 브라우저의 기본언어를 따라 가도록 되어 있습니다. 
브라우저의 언어를 한국어로 변경해보세요.

**Comment by klrodel** [comment]
> 현재 사용하시는 브라우저의 기본언어를 따라 가도록 되어 있습니다. 브라우저의 언어를 한국어로 변경해보세요.

감사합니다. 크롬 기본 언어가 영어로 되어 있었네요. ^^

**Comment by ckocho5oh** [comment]
저 크롬 기본언어가 한국어인데도 안되던데요
