### ISSUE TITLE
프로젝트 복사 오류

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#81]
1. 프로젝트를 '코드 저장소 복사' 메뉴로 복사를 합니다.
2. 사용합니다.  코드 주고받기도 합니다.
3. 코드가 꼬인것 같아 원본 저장소에서 다시 받을 생각으로 내 저장소를 삭제 합니다.
4. 다시 '코드 저장소 복사'를 합니다.
5. '권한이 없거나 존재하지 않는 프로젝트입니다.'  라고 나오고
   코드 저장소를 다시 복사하려고 하면 '동일한 원본 프로젝트를 복사한 프로젝트가 있습니다.'  
   라고 나옵니다.

6. repo경로에서 저장소를 삭제해봤는데 DB에서 처리가 안되는 모양입니다.

 수동으로 DB에서 삭제하려면 뭘 삭제 해야 하나요?

**Comment by pokev25** [comment]
DB에서 문제가 되는 프로젝트 id를 찾아서

project_menu_setting
project_user
project

순서대로 삭제 하고 다시 저장소 복사를 해도 ...권한이 없다고 나오네요..

**Comment by pokev25** [comment]
DB비교해보려고 project1으로 복사 후 삭제 해보고
다시 project1으로 하려니 안되네요.. DB어디에도 정보가 남아있지 않은데 
어디 다른데 보관하는데가 있나요?

**Comment by doortts** [comment]
@pokev25 동일한 이름으로 프로젝트를 만드시는건 되시나요?

**Comment by doortts** [comment]
repos 폴더 아래에 git 아래에 계정이름 아래에 프로젝트 이름으로 된 폴더가 있습니다. 해당 폴더를 폴더채로 한 번 지워봐보세요.

**Comment by pokev25** [comment]
동일한 이름으로 프로젝트 생성해봤는데 같은 결과 입니다.
해당 경로는 삭제후 테스트 진행했습니다.

**Comment by pokev25** [comment]
아..어이 없는 결과가 나왔어요.....

재시작 했더니 정상적으로 보입니다...  어딘가 메모리상에 캐시가 문제인가 보네요.

**Comment by doortts** [comment]
@pokev25 v1.0.3 에서 확인부탁드려요

**Comment by pokev25** [comment]
테스트 해봤는데 잘 동작 합니다. 
문제 생기면 다시 이슈 올리겠습니다.
