### ISSUE TITLE
yona webook

### ISSUE THREAD

**Issue by veinfx** [yona-projects/yona#810]
안녕하세요 최근 yona webhook 메신저에서 받으려고 셋팅하였는데요.

![image](https://github.com/yona-projects/yona/assets/55982173/abb92408-807b-4550-94c2-b62f6bc70bba)

위와 같이 새로운 글이나 주요 타이틀은 잘 오는데

수정된 내용이나 미리보기로 필터링할수 있는지 궁금합니다.

**Comment by doortts** [comment]
webhook 관련되어서 적절한 답변을 드리지 못해 죄송합니다.

**Comment by veinfx** [comment]
아닙니다. 메신저 변경으로 slcak 으로받으니 미리보기와 내용 잘옵니다.
