### ISSUE TITLE
프로젝트 생성후

### ISSUE THREAD

**Issue by banykim** [yona-projects/yona#82]
먼저 좋은 프로그램 만들어주셔서 감사합니다.^^
다름이 아니오라
앱테나 에디터에서 만들어진 코드를
요나프로젝트에 커밋하려고 하는데
방법을 모르겠습니다.
죄송하지만 커밋하는 방법에 대하여
가르침 부탁드립니다.

**Comment by rtboss** [comment]
### 프로젝트 홈에 가서 저장소 URL(주소)로 clone후 하시면 됩니다.
![image](https://cloud.githubusercontent.com/assets/4962243/17795360/af070810-65f2-11e6-890a-84024e76bfcd.png)

### 프로젝트 생성후 "코드"탭에 가시면 Git remote 사용법 간단히 설명되어 있습니다.
![image](https://cloud.githubusercontent.com/assets/4962243/17795427/422cbf5e-65f3-11e6-993e-c09cb3bb4ce9.png)

### Git 사용법은 아래 링크들 참고하세요.
git-book : [https://git-scm.com/book/ko/v2](https://git-scm.com/book/ko/v2)
Git 기본개념과 사용법 : [http://www.slideshare.net/andabi/git-16126636?next_slideshow=1](http://www.slideshare.net/andabi/git-16126636?next_slideshow=1)
svn 능력자를 위한 git 개념 가이드 : [http://www.slideshare.net/einsub/svn-git-17386752](http://www.slideshare.net/einsub/svn-git-17386752)
tortoiseGIT 사용법 : [https://opentutorials.org/course/303/category/85/395](https://opentutorials.org/course/303/category/85/395)
Git-생활코딩: [https://www.opentutorials.org/course/1492](https://www.opentutorials.org/course/1492)
