### ISSUE TITLE
라즈베리 파이3에서 구동시 게시판 권한 문제

### ISSUE THREAD

**Issue by minishanell** [yona-projects/yona#86]
안녕하세요.
요나 프로젝트가 너무 맘에 들어 활용을 열심히 해보려고 합니다. ^^

라즈베리3에 오라클 자바 1.8과 마리아DB를 설치하고.. 요나를 구동하고 있는데요..
오늘 팀으로 이것저것 해보다 보니 문제가 생겨 어떻게 해볼까 고민을 하고 있답니다.

발견한 문제점은 3가지.
1. 이슈를 글쓴이나 담당자가 아닌 사람이 수정이 가능하더라구요.. (다른 인원은 참가자입니다)
2. 게시판의 글도 글쓴이 외에 참가자가 수정이 가능해요. 
   (원래 게시판은... 수정이 안되어야 하지 않나요?)
3. 프로젝트 메인에, 언어와 라이센스를 한번 쓰면 지울수가 없네요.

의도적으로 이렇게 되어있는 것은 아니죠?

어떤 것을 수정해야할지 궁금해서 여쭤봅니다.

[테스트환경]
머신 : 라즈베리파이 3 라즈비안 제시
서버 : 마리아DB, 아파치2, PHP, 오라클 자바 ARM 1.8, Yona 1.0.4
브라우저 : 윈도우10, 엣지, 익스플로러11

ps. 일반 x86서버에서 문제가 없다면... YonaPI로 프로젝트 Fork해서 수정진행해도 괜찮을까요?

**Comment by doortts** [comment]
@minishanell 안녕하세요? 

발견하신 문제점은 3가지에 대한 답변입니다.

> 1. 이슈를 글쓴이나 담당자가 아닌 사람이 수정이 가능하더라구요.. (다른 인원은 참가자입니다)
> 2. 게시판의 글도 글쓴이 외에 참가자가 수정이 가능해요. (원래 게시판은... 수정이 안되어야 하지 않나요?)

이 부분은 의도적으로 같은 프로젝트 멤버들은 해당 권한을 가지고 수정할 수 있게 만들었습니다. 다만 본인 작성글이 아닌경우 수정시에 항상 메일이 발송되도록 만들어져 있습니다. 특히 게시판은 위키처럼 사용할 수 있도록 그렇게 만들어 놓았습니다. 일반적인 게시판 사용법과 달라 처음엔 조금 고민했었는데 막상 생각보다 거의 문제가 없었습니다.

> 3. 프로젝트 메인에, 언어와 라이센스를 한번 쓰면 지울수가 없네요.

버그인가봐요..;;; 

> 일반 x86서버에서 문제가 없다면... YonaPI로 프로젝트 Fork해서 수정진행해도 괜찮을까요?

이건 물어보실 필요도 없이 당연히 가능합니다! 저야말로 포크하셔서 @minishanell 님의 커스텀이 들어가시면 알려주시면 다른 분들께도 소개해도 괜찮죠? : )

ps.
그나저나 라즈베리3에서 저런 환경 구동이 가능하다니 놀랍네요. 그냥 작은 보드 정도로 생각했었는데 ㄷㄷㄷ;;

**Comment by minishanell** [comment]
아하.... 위키 형식이었네요 ^^
혹시 라즈베리라서 잘못된 건가 걱정했었어요~~
언어와 라이센스는 지금은 고칠 것은 phpmyadmin으로 수동으로 수정만 하고 있긴 해요.
버그 부분을 찾아봐야 할 것 같아요.

Fork는 일단 해 보겠습니다. ^^:;
사실 자바를 배우지를 않아서... (책 보다가...  두고 그냥 PHP만 쓰고 있네요..)
조금 수정할 것이 생기면 공부해다 조금씩 수정해볼께요~~
라즈베리3에서의 문제점은 연속적인 램 사용밖에 없었는데...  캐쉬로 의도하신 내용이겠지요?
Git서버와 요나는 정상적으로 잘~ 돌아갑니다.  데모 서버처럼 매끄럽게 돌아가네요. 
램을 약 900메가 넘게 먹고 있긴 한데... 특별한 문제점도 없고, 서버에 과부하도 없답니다.
라즈베리용으로는 메모리 사용량만 조금 줄이면 될 것 같아요. 
지금도 좋지만.. 일단.. 한달쯤 구동해보고 내부 자원 활용도를 체크해봐야겠지요~~
가용 메모리가 적어서 요나 이외의 작업이 어려울 듯해 보이거든요~~
