### ISSUE TITLE
[제안] 마일스톤 검색기능

### ISSUE THREAD

**Issue by Terrorboy** [yona-projects/yona#87]
게시판의 경우
"[버그][공통] 리스트 중복출력"
이런식으로 남기면
[버그], [공통]을 선택시 자동 검색기능이 작동되는데 이게 마일스톤에도 적용 되면 좋을 것 같습니다.

---
# 마일스톤
## ![4](https://cloud.githubusercontent.com/assets/5427199/19140897/ece05dae-8bcb-11e6-8017-a65aad1e283a.png)
# 게시판

![5](https://cloud.githubusercontent.com/assets/5427199/19140912/155bb3d2-8bcc-11e6-931b-f35e2f749a72.png)

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.2.0 에서 해결되었습니다.

**Comment by Terrorboy** [comment]
@doirtts 감사합니다. 은근필요하던 참인데!
항상 감사합니다.
