### ISSUE TITLE
linux에서 background 실행방법좀 알려주세요

### ISSUE THREAD

**Issue by tabago** [yona-projects/yona#88]
안녕하세요
linux에서 background 실행방법좀 알려주시면 감사하겠습니다..
원도우에서 설치하다가 서버를 linux로 변경했는데 
background로 실행을 못하고 있습니다..
start & 또는 nohup start실행하면 바로 죽는데.
다른방법이 있는지요..
답변좀 부탁드리겠습니다.

**Comment by doortts** [comment]
콘솔에 아마 ctrl+d 로 중단하라고 메시지가 나올거에요.
혹시 ctrl+c 로 중단하신건 아니세요? 

ctrl+c 는 사실 kill signal 이거든요. 
https://www.google.co.kr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&safe=off&q=What+signal+is+sent+by+CTRL+C%3F

그리고 unix/linux 용 재시작 스크립트 예제는 아래를 참고해주세요.
https://github.com/yona-projects/yona/blob/next/restart.sh

**Comment by tabago** [comment]
아...잘못봤습니다..하하하...
날씨가 참춥죠...
