### ISSUE TITLE
업그레이드에 대한 질문입니다.

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#9]
릴리즈 파일을 보면

yobi-data-export.zip 과 yona-1.0-h2.zip 둘다 H2상태에서 운용이 가능한 것으로 보입니다.

그렇다면 [Yobi에서 Yona 마이그레이션하는 방법](https://repo.yona.io/yona-projects/yona/post/1) 

에서 설명한 것 처럼 yobi-data-export.zip를 사용하지 않고

yona-1.0-h2.zip 으로 사용해서 업그레이드는 안되는것인가요?

**Comment by doortts** [comment]
안녕하세요?
이야기 주신 내용을 보니 설명이 조금 부족했다는 생각이 들었습니다.

yobi-data-export.zip 은 yobi 0.8.2 기준으로 export 기능만 넣은 버전입니다.
현재 pre-release 로 되어 있는 yona-1.0-h2.zip 는 h2 기준의 1.0 버전이 맞습니다. 다만 앞으로 h2 버전은 업그레이드 계획이 없습니다. 

1.0 버전을 조만간 release 할 예정인데요 h2 버전으로의 업그레이드는 정식 릴리즈 때까지 잠시 기다려 주시면 좋을 것 같습니다. 여러가지 더 나은 기능으로 h2 버전을 제공해 드릴 수 있을 것 같습니다.

**Comment by doortts** [comment]
Yona v1.0.0 버전이 릴리즈 되었습니다. 
예고드린대로 yona-h2-v1.0.0-bin.zip 파일도 함께 배포합니다.
https://github.com/yona-projects/yona/releases/tag/v1.0.0

다만 기존에 Yobi 0.8.x 버전을 사용중이시고, 여러 프로젝트를 여러 팀이 같이 사용하는 경우라면 안정성을 위해서 MariaDB로의 이전을 추천드리고 싶습니다. 

그럼에도 yona-h2 v1.0.0 버전으로 업그레이드를 하신다면 기존 운영중이던 인스턴스를 잘 종료하시고 db 파일을 백업받으신 다음 업그레이드 진행하시길 권장드립니다.
