### ISSUE TITLE
리뷰 탭에도 excel 다운 받는 바턴이 있었으면...

### ISSUE THREAD

**Issue by buka-a4** [yona-projects/yona#90]
안녕하세요. 
요나라는 좋은 웹을 만들고 수고했습니다. 감사합니다.
그런데 한 가지 부탁이 있는데요.  
Issue 탭을 이용해서 이슈의 목록을 볼 수 있는고 여기 Excel로 더운 받을 수 있는 바턴이 있어요.
이 바턴과 비슷하게 Review 탭에도 목록을 excel로 다운 받을 수 있는 바턴을 만들어 줄 수 있는지요?
어떤 리뷰 댓글들이 나왔는지 몇 개를 닫았는지를 파일로 이와 비슷하게 다운 받았으면 하고 있어요.

**Comment by doortts** [comment]
목록을 이용해서 어떤 작업을 하고 싶으시고 항목으로는 어떤 것들이 들어가 있길 바라시나요?

**Comment by buka-a4** [comment]
코드의 commit id가 리뷰란 연결돼 있다고 생각합니다. 그래서 다음과 비슷한 항목으로 나올 수 있을까요?
commit id, review id, review title, reviewer, review state, review inserted date

혹시 리뷰가 리뷰에 답한 답변과 연결될 수 있을까요?
다른 말로 한 리뷰에 누군가가 답을 했다면 그들이 서로 연결됄 수 있지요?
만약에 가능한다면 다음과 같으 항목을 만들면 됄까요?
commit id, review id, review title, reviewer, review state, review inserted date + response id, response text, response date, response user

안된다고 하시면 외에 있는 항목으로 목록이 나오면 충분합니다 :)

**Comment by buka-a4** [comment]
[Code review excel example.xlsx](https://github.com/yona-projects/yona/files/692984/Code.review.excel.example.xlsx)
Review Template - Example excel

**Comment by doortts** [comment]
@buka-a4 요청하신대로 동작하는지 repo.yona.io 에서 한 번 테스트 해 봐 주시겠어요? 
Could you test it if it works as you requested?

**Comment by buka-a4** [comment]
@doortts 안녕하세요.
테스트 해 봤어요. 엑셀 다운로드가 잘 되고 서료도 잘 나와요. 이렇게 써도 될 것 같아요 :+1: 
감사합니다 :)
