### ISSUE TITLE
프로젝트 정보 > 카테고리에 공백을 넣으면 랜더링이 깨집니다

### ISSUE THREAD

**Issue by sjstyle** [yona-projects/yona#93]
![image](https://cloud.githubusercontent.com/assets/4811664/19881837/6cd49842-a04c-11e6-9207-276d85bfdc19.png)

프로젝트 홈 > 정보 > 카테고리에 공백이 포함된 것을 입력해 둘 경우, 카테고리 랜더링이 깨져 수정버튼을 누르지 않아도 수정 상태처럼 표시되고 있습니다.

https://repo.yona.io/sjstyle/test 에서 확인이 가능합니다.

**Comment by doortts** [comment]
프로젝트 정보 부분을 다 지워버리고 싶네요. (음냐.. 버그들...)

**Comment by doortts** [comment]
> 프로젝트 정보 부분을 다 지워버리고 싶네요. (음냐.. 버그들...)

...라고 위에 썼던 댓글 내용을 다음 버전에서 실행할 예정입니다.

즉, 다음 릴리즈때 프로젝트 라벨기능을 제거해버릴 예정입니다. 프로젝트 설명은 프로젝트 설명영역(프로젝트 검색시 포함되는 영역)
![image](https://cloud.githubusercontent.com/assets/520523/22205485/674f4b24-e1ba-11e6-8140-7a759011208b.png)

이나 README 를 이용하는 걸로 변경합니다.

**Comment by minishanell** [comment]
프로젝트 정보부분이 삭제되었기에, 이 이슈를 닫습니다.
