### ISSUE TITLE
한글 폴더명 문제

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#94]
코드-파일 에서 한글 폴더명을 클릭하면 동작 하지 않습니다.

![hangul01](https://cloud.githubusercontent.com/assets/4251972/20044091/05ad6e96-a4d9-11e6-9e2e-1e319d6b250f.png)

이때 URL 경로
```
code/master#한글명
```
%ED로 깨진 부분을 클릭하면 정상적으로 한글이 표시됩니다.

![hangul02](https://cloud.githubusercontent.com/assets/4251972/20044092/05b558f4-a4d9-11e6-8bb3-4872b02d3b12.png)

이때 URL경로
```
code/master/한글명
```

**Comment by doortts** [comment]
@pokev25 혹시 repo.yona.io에서도 동일한지 테스트한번 해주실수 있을까요?

**Comment by pokev25** [comment]
@doortts 네 동일한 증상 보입니다.

https://repo.yona.io/postimg/test/code/master

**Comment by sjstyle** [comment]
@pokev25 혹시 사용환경이 어떻게 되시나요?

해당 주소를 테스트해봤는데, 대부분의 환경에서 이상이 없었습니다.
Mac + Chrome : 이상 없음
Mac + Safari : 문제 있음. (두번 눌러야 들어가지는 문제)
Windows 10 + Chrome, Edge, IE 11 : 이상 없음.

**Comment by pokev25** [comment]
@sjstyle 
firefox 입니다.  파폭은 어디가나 문제가 살짝 있군요  ^^

**Comment by doortts** [comment]
@pokev25 크흑~ 왠지 파폭일것 같았습니다. 저도 한 몇년 파폭유저였는데 다시 크롬으로 갈아탄지 또 몇년 (3년쯤?) 되었네요. 요즘 파폭은 맥OS기준(저의 개발머쉰) 콘솔에서 한글도 제대로 잘 타이핑이 안되요. (이 녀석들!!!)

죄송합니다..

**Comment by doortts** [comment]
윗 글에서 => 제대로(x) 때때로(o)

**Comment by doortts** [comment]
@pokev25 님 repo.yona.io 를 대상으로 테스트 한 번 부탁드릴게요.

**Comment by pokev25** [comment]
@doortts 파이어폭스에서 이상 없이 잘 나옵니다.

**Comment by pokev25** [comment]
아..이건..좀 미묘한 차이라서..한번 확인만 해봐주세요.  크롬, 파이어폭스 둘다 그럽니다.

화살표한 부분의 클릭에 따라서 박스안에 공백이 하나 들어갔다 나갔다 합니다.

![clk1](https://cloud.githubusercontent.com/assets/4251972/22235429/02afc23c-e243-11e6-8ab2-3c386543c109.png)

![clk2](https://cloud.githubusercontent.com/assets/4251972/22235430/047dfad4-e243-11e6-934d-cfec8bafedeb.png)

**Comment by doortts** [comment]
@pokev25 우선 이걸 발견하셨다는 사실에 놀라움과 감탄을 보냅니다. 이 미묘한 동작을 '매의 눈'으로 잡아내셨네요. 꼼꼼하십니다!! 마찬가지로 다시 한 번 테스트 부탁드립니다.

**Comment by pokev25** [comment]
동작 확인 했습니다!.
