### ISSUE TITLE
관리자 계정 생성 페이지가 계속 뜨는 현상

### ISSUE THREAD

**Issue by naninyang** [yona-projects/yona#95]
OS: macOS 10.12
git repository version
-
application.conf 파일을 불러오지 않는 것 같아서 start -Dconfig.file=./conf/application.conf 명령으로 강제로 환경설정 파일 불러오게 처리하고 접속했습니다.

이후 브라우저로 접속하면 관리자 생성 페이지가 뜨는데 여기서 관리자 계정을 생성하고 서버 재시동을 하라는 메시지가 떠서 서버 재시동을 하는 방법을 몰라 macOS 재부팅을 했습니다.

다시 서버를 띄우고 위와 똑같이 실행시켰습니다. (할 때마다 Dconfig.file 써야 하는 것 같습니다. 생략하면 db 에러떠요) 이미 재부팅을 하기 전에 관리자 생성을 했기 때문에 로그인 페이지가 뜰 거라고 기대를 했습니다만, 또 생성 페이지가 뜹니다. 또 반복했는데 역시 또 생성 페이지가 뜹니다.

정상적으로 서버 재시동 또는 스톱을 시키지 않아서일까요?

근데 이메일은 이미 등록되어 있는 것 같습니다. 이미 등록된 이메일이라고 경고가 뜨네요.
디비에 저장이 안되고 있는 건 아닌 것 같은데 로그인 화면으로 넘어가지 않으니 답답하네요.

**Comment by doortts** [comment]
@naninyang 안녕하세요
혹시 YONA_HOME을 지정 안하신것은 아니세요?
https://github.com/yona-projects/yona#linux-osx의-경우

그리고 YONA_HOME 지정으로 안되신다면
https://github.com/yona-projects/yona/blob/next/restart.sh

참고하셔서 시작 스크립트를 하나 만드셔서 사용하시는 걸 권장드려요. 

그럼 해보시고 알려주세요!

ps
본의아니게 답답하게 해드려서 미안해요. ㅠ

**Comment by naninyang** [comment]
start 뒤에 다른 명렁어를 추가해야 하는 번거로움은 없어졌는데 sh restart.sh 는 여전히 먹지 않네요.
그래서 재부팅...을 하면 여전히 관리자 계정 생성 페이지가 뜹니다...

dev:yona/ (next✗) $ sh restart.sh                                                                                                                                 [18:20:43]
/usr/bin/fuser: '9000/tcp' does not exist
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

아무래도 PID kill 이 안되서 발생하는 듯 합니다.

**Comment by sjstyle** [comment]
@naninyang 

Mac 의 경우에는 https://github.com/yona-projects/yona/blob/next/restart.sh#L8 줄이 다음과 같이 바뀌어야 할 것 같습니다.

pid=`lsof -i :8080 | grep java | awk '{print $2}'`

**Comment by doortts** [comment]
lsof 가 정확히 잡아준다면 grep awk 조합대신 pgrep 하셔도 돼요

**Comment by doortts** [comment]
관리자 생성페이지가 계속뜨면 db 다시 만드시는걸로....;;; 이미 해당 관리자 유저아이디나 이메일로 DB 등록되서 그렇습니다..
