### ISSUE TITLE
자동 발송된 이메일에서 이미지가 보이지 않는 현상

### ISSUE THREAD

**Issue by SongPaul** [yona-projects/yona#96]
이슈를통해 자동적으로 발송된 이메일에서 이미지가 깨진형태로 출력됩니다.

**Comment by doortts** [comment]
conf/application.conf 파일 보시면

`application.hostname`을 설정하는 부분이 있습니다. 이 부분을 사용하시는 도메인으로 적어주시고 재시작 해주시면 될겁니다.

repo.yona.io 경우에는 아래처럼 되어 있습니다.
```
# Components used to construct the URL to this application.
application.scheme="https"
application.hostname="repo.yona.io"
```

https로 동작하기때문에 https인데 이 부분은 사용하시는 protocol 보시고 변경하시거나 그냥 http로 놔두시면 됩니다.
