### ISSUE TITLE
이슈의 본문을 수정해도 '알림' 에는 're:' 로 뜸

### ISSUE THREAD

**Issue by witbox** [yona-projects/yona#97]
안녕하세요?

제목 그대로 입니다.

이슈의 본문 내용을 수정하고 나서 뜨는 알림 내용에는 댓글이 달린것 처럼 re: 가 제목 앞에 붙습니다.

버그인지, 아니면 일부러 이렇게 처리하신건지요?

**Comment by doortts** [comment]
안녕하세요?

알림이라는게 알림 메일 말씀이신가요? 아니면 프로젝트 타임라인(timeline )을 의미하시는거에요?

**Comment by witbox** [comment]
메일 말고 타임라인 알림입니다.
