### ISSUE TITLE
프로젝트 간 이슈 이동 방법

### ISSUE THREAD

**Issue by SongPaul** [yona-projects/yona#98]
프로젝트를 분리 하게 되었습니다.

프로젝트에 라벨로 분류 되어있는 이슈를 이동할수 있을 까요. ?​

**Comment by sjstyle** [comment]
현재로서는 방법이 없는 것으로 알고 있습니다.

**Comment by doortts** [comment]
v1.4 에서 프로젝트간 이슈 이동이 가능하게 되었습니다.
